### ISSUE TITLE
Use different email 'from' depending on implementation

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1000]
## Context: 
Some e-mails we know we can send from an emailadress of an implementation.
For example we can send all vouchers requested from implementation Nijmgen from @nijmegen.nl

## Goal:
This issue is about adding a way to configure domain names and from names for each implementation. If an e-mail is send from an implementation, we will check if these variables are filled and chose to send mails from this domain and from name.

**Comment by jamalv** [comment]
Related: #261 

@maxvisser @aghimpu I see some work has been done on this, what is the current status?
