### ISSUE TITLE
UI/Design: Notification preferences

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1002]
## Context/goal: 
bootstrap page with functionality:
![Screenshot from 2019-09-12 12-25-58](https://user-images.githubusercontent.com/10818702/64776458-8a8f5b80-d558-11e9-95ec-9617d22b75d4.png)

**Comment by danrminds** [comment]
- https://www.dropbox.com/s/1smcvwi8n9f3wf1/Notification%20settings%20%28New%29.PSD?dl=0
- https://www.dropbox.com/s/fl1za15z8khrmgs/Notification%20settings%20%28Webshop%29.TIF?dl=0

**Comment by maxvisser** [comment]
change toggle to blue
