### ISSUE TITLE
Fund application form builder

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1006]
## Context:
For the application procedure we have developed an MVP for the fund configuration page. This issue is about extending that MVP to make it possible:
* For a sponsor to configure the application procedure 
* For the validator to set
  * What kind of records they validate
  * What kind of proofs (document uploads) they need
  * To give an explanation (text) about the proofs they require

The application form that will be configured with the dashboards is shown here: https://www.figma.com/file/nyH6OawYjZonHEFocQ4q4o/Webshop-%2B-Dashboard-(Alpha-Version)?node-id=255%3A2747

<details><summary>Show updates to the sponsor fund page:</summary>

![image](https://user-images.githubusercontent.com/30194799/65249445-4cfc7680-daf4-11e9-9886-8c9a68b41afa.png)

</details>

<details><summary>Show new validator eigenschappen (records) page </summary>

![image](https://user-images.githubusercontent.com/30194799/65248698-e2970680-daf2-11e9-996c-426c167e0de5.png)
</details>

**Comment by maxvisser** [comment]
I think this is already getting pretty difficult to configure and needs a IT guy to do it. Also I wonder if the sponsor should even configure the form or if the validator should do that.

**Comment by jamalv** [comment]
Hi Dan, could you check this issue out with Alex and update / make the designs from the wireframes? Then when Valentin is done with the MVP, he can start working on this issue 👨‍💻 

Let me know if you have any questions

**Comment by danrminds** [comment]
@jamalv Will plan it for tomorrow and weekend.

**Comment by jamalv** [comment]
that was a very quick response, I would almost think you have some kind of crazy system for these kind of things 😛

**Comment by danrminds** [comment]
https://www.dropbox.com/sh/m5fut0eybno3q5i/AAAV6SnUWIaBse_0l6oRhRuNa?dl=0
