### ISSUE TITLE
Hide volgende button on last step of sign-up form

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1008]
Some shopkeepers klik "volgende" instead of aanmelden. Simply hiding the "volgende" button on the next step would solve this problem.

**Comment by maxvisser** [comment]
![laststep](https://user-images.githubusercontent.com/10818702/65253891-afa54080-dafb-11e9-9112-6093e6a6935c.png)

**Comment by maxvisser** [comment]
text to 'Overslaan' (skip)

**Comment by jamalv** [comment]
and would not make it a button, just underlined grey text:

> Sla over en ga naar dashboard >

**Comment by maxvisser** [comment]
Good suggestion
