### ISSUE TITLE
Image does not load because of starting slash in Media path - release v0.2.13

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1018]

**Comment by GerbenBosschieter** [comment]
https://s3.eu-west-1.amazonaws.com/staging.media.forus.io//media/7e6558fdf4c60fce2ca8503c350986c7a5a71195b020ca84345b06ba2aa34a.jpg

should be:
https://s3.eu-west-1.amazonaws.com/staging.media.forus.io/media/7e6558fdf4c60fce2ca8503c350986c7a5a71195b020ca84345b06ba2aa34a.jpg
