### ISSUE TITLE
Blockchain integration

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#102]
- [ ] Create fund token
- [ ] Create fund wallet
- [ ] Blockchain transactions to shopkeeper and back
- [ ] Vouchers mean access to x tokens from the fund wallet

**Comment by maxvisser** [comment]
We should aim to have this in before 1 jan - westerkwartier

**Comment by danrminds** [comment]
I think this has to be partly implemented before 1 nov 2018 as well (to comply at least with a bit of blockchain)

**Comment by maxvisser** [comment]
I will close this now for the same reason I gave in https://github.com/teamforus/forus/issues/85

**Comment by jamalv** [comment]
As I see this is the first step to creating an issuer backed token in the platform.

Indeed regarding current privacy issues in ethereum this is currently not feasible. Should re-open when there is a reasonable zk implementation we can use.
