### ISSUE TITLE
Epic. Signup-flow. Requester - Questions about "In Progress"

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1031]
## Context/goal: 
Some things need more clarifications:

What if a group of records is "In progress / Assigned to somebody"

1. Should somebody see the values before he "starts" validating the group?
2. Should somebody else who does not work on that group see the values of the records and proofs?
3. Maybe for future would be nice to plan a possibility to "unassign yourself" and how to handle that part, or forward this group to somebody else.
4. Maybe add a filter to see opened requests in general / yours (assigned to you already).

**Comment by jamalv** [comment]
I need a bit more context around this new scope. But with the idea of doing the simple thing first and avoiding adding to much complexity in the first iteration, I would say the following;

1. Yes
2. Yes
3. Good idea, out of scope for now
4. Haha “assigned to me” I know that from somewhere ;) good idea, but let’s also keep it out of scope for now.

Please assign me again if you have more questions.

**Comment by maxvisser** [comment]
Well we are going to implement multiple people working together on the same validation requests (requests done to the organization)

So this is basically something to help people work together. I also don't know yet if this is a big enough problem that we have to tackle it this sprint yet.

**Comment by danrminds** [comment]
You mean the complete "In progress" functionality?
