### ISSUE TITLE
Epic. Signup-flow. Requester - Ask for more information

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1032]
## Context/goal: 
This part also needs a bit more discussions and clarifications.

Okay, you as a validator ask for more information from the Requester. He will get an email with a confirmation and the message from the validator. But what is the best workflow after this?

1. Send him to a custom form with only the requested questions? 
2. How should we handle this if he opens this on mobile

etc.

**Comment by jamalv** [comment]
Yes, I think he should be linked to a page that is similar to the signup form, but is specifically for the parts that require extra information. The page can be something like:
![image](https://user-images.githubusercontent.com/30194799/66292233-1ab88a80-e8e4-11e9-82e1-59ac74eb45a4.png)

The form also has a mobile design:
![image](https://user-images.githubusercontent.com/30194799/66292295-40459400-e8e4-11e9-9927-ba39397bdf35.png)

**Comment by danrminds** [comment]
How should it display the steps where you don't need to do anything?
Should the form process his records again? to see which ones are already processed? 

I think it should be processed as a separate form (as an entity), not the same form. It can look the same though.

**Comment by jamalv** [comment]
If there is a step where you don't need to do anything, can we simply hide that step? That should probably be the case for the form in general.

In the overview, you see the status of all records: 
* If the record is green, there doesn't need to be a step for it, you already have it and it complies with the criteria.
* If the record is orange, you already have a record but it doesn't comply with the criteria of the fund, so in the step you will add a new (additional) record.
* If the record is blue, there are no records yet, and you will add one in a step.

![image](https://user-images.githubusercontent.com/30194799/66334314-1ec2c780-e939-11e9-81b6-8e772b2f624a.png)
