### ISSUE TITLE
Epic. Signup-flow. Requester - Sponsor actions.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1034]
## Context/goal: 
Sponsor will create the fund and for the fund will specify the criterias. 
Based on this criteria we will have to build the application form for the requesters. 

When specifying the criterias - we have 2 optional fields:

1. File attachment required or not. Depending on this field - show the file attachment or hide it
2. We will have an additional textarea field, in a modal, with Markdown formatting. He you can add additional description of the requirement. It will be displayed above the File attachment (if applicable)

**Comment by danrminds** [comment]
How should the automatisation do we want in the creation of the application based on the criteria set of the fund? 

Maybe some usecases descriptions could clarify this. I am open for a call later today to discuss it.

**Comment by jamalv** [comment]
Yea, we have some ideas about that. I think a call tomorrow would probably be good. In the video that we're planning to record in the morning we might also be able to share those ideas.

**Comment by danrminds** [comment]
I think a call can still be planned.

**Comment by jamalv** [comment]
Sure, we can just stay in the call 👍
