### ISSUE TITLE
Epic. Signup-flow. Requester - Send email notification when a group is validated

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1037]
## Context/goal: 
When all requests from the group are approved or rejected - we send an email notification with the status of the Group to the requester. 

What type of emails would be those? What content should they have?

**Comment by jamalv** [comment]
Most important is to share what is expected of the requester:
* If they are eligible for a new voucher; we can send the voucher, maybe with a login url that redirects to the webshop.
* If they are missing information, we should explain how they can provide this information
* If they are rejected, we should also explain this, and if there is anything they can do

Let's keep this assigned to max and me to come up with the emails.
