### ISSUE TITLE
Map view on the General webshop. Adjust headers

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1040]
## Context/goal: 
On the general webshop the map view does not look good because the header is not delimited as on Nijmegen for example.

Please see the screenshots.

![Screenshot 2019-10-07 11 04 01](https://user-images.githubusercontent.com/33207036/66320565-591f6b00-e91f-11e9-95dd-5c61e2d4a996.png)
![Screenshot 2019-10-07 11 04 15](https://user-images.githubusercontent.com/33207036/66320567-59b80180-e91f-11e9-89f5-917029c5f3e7.png)
![Screenshot 2019-10-07 11 04 29](https://user-images.githubusercontent.com/33207036/66320568-59b80180-e91f-11e9-978d-e921eb7fcfe3.png)

**Comment by maxvisser** [comment]
I would maybe suggest to just make all headers full width.

**Comment by danrminds** [comment]
That would be the easiest.

**Comment by maxvisser** [comment]
all webshop currently online have full width header
zuidhorn.forus.io
westerkwartier.forus.io
nijmegen.forus.io

**Comment by maxvisser** [comment]
@danrminds can you give an update on this issue?

**Comment by danrminds** [comment]
We did the front-end of these pages, but without mobile compatibility, and without the fix of the header. Mainly because it is decided now to redesign it (by Lena) in the new generic style.

**Comment by maxvisser** [comment]
@jamalv I don't like to waste time with a new map; if the markup is almost done. i propose to finish it anyway; I don't see coming sprint that a new generic style is implemented.

**Comment by jamalv** [comment]
We discussed to implement the new map with at least the filters on the old design:

* Search
* Fund
* Category

Regarding the header, it is not a priority now as we're not using the generic webshop, later we can update it to the style of the site: 

<img width="921" alt="Screenshot 2019-12-02 at 07 21 50" src="https://user-images.githubusercontent.com/30194799/69935194-6e0a1c00-14d4-11ea-87f3-08392690a07b.png">

**Comment by jamalv** [comment]
Not a priority as we're not using the general webshop. Will need to check everything when using it becomes a possibility.

**Comment by dev-rminds** [comment]
> Not a priority as we're not using the general webshop. Will need to check everything when using it becomes a possibility.

The header styles for general webshop was already fixed (now the header is full width).
