### ISSUE TITLE
Epic. Signup-flow. Requester - Pre-validations and application form. (DigiD)

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1044]
## Context/goal: 
In most cases - we will have a prevalidated list of BSN numbers with records.

On this model: 

|BSN|Record_type|Record_value|
|---	|---	|---	|
|44675433|amount_kids|2|
|44675433|income|688,35|

After the requester logged in via DigiD - we validate his BSN number and check it with the prevalidated list. #1035 
If found in the prevalidated list - we create the records and validate them accordingly
If not found in the prevalidated list - send him to fill in the complete application form. #1033

**Comment by maxvisser** [comment]
closed https://github.com/teamforus/forus/issues/875 this issue superseded
