### ISSUE TITLE
Toggle notification preferences should directly submit

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1052]
## Context/goal: 
On notification preferences when toggling a notification the form should be submitted directly.
Currently the user still need to submit the form manually.

If implemented, the submit button can be removed.

**Comment by danrminds** [comment]
@maxvisser 

Here is one aspect that bothers me. (We had same issue on OnePlan)
When on some pages you need to press Save and on some you don't - it confuses the user. 
We need consistency in it.

**Comment by maxvisser** [comment]
Well there are no other on/off switches yet. But I would say if you use those it should not need a submit button. It does not feel like a form.

Some screens give an informational popup after pressing a button. I think could maybe make less intrusive notifications in right bottom corner
