### ISSUE TITLE
no text by tooltips

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1055]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/66512483-59636600-ead9-11e9-9055-66aadd7e3668.png)
the text are already there:
https://github.com/teamforus/forus-frontend/blob/85e65e673282577419423dd80ab8b216899d53a7/src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js#L993

**Comment by jamalv** [comment]
@maxvisser what can each role do?

**Comment by maxvisser** [comment]
edited the issue; there is no need to refine as it is just some texts that is disconnected. permalink shows the i18n translations
