### ISSUE TITLE
E-mail: FundStartedMails.php sends new_fund_created.php e-mail

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1058]
## Context/goal: 
wrong mail is being send. Should send fund_started.php

**Comment by aghimpu** [comment]
I cant see any fund_started.php on the develop branch, how can I find it (perhaps its on a different branch) ?

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-notification/blob/master/web/app/templates/templated_email/nl/vouchers/fund_started.tpl

As discussed earlier should be ported on the php backend (we don't have it right now)
https://github.com/teamforus/forus-notification/blob/master/web/app/templates/templated_email/nl/vouchers/fund_started.tpl
