### ISSUE TITLE
Token expired js alert should be changed to login modal with warning

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1061]
## Context/goal: 

Current flow:
User sends login link to email (login_via_mail)
User forgets he wanted to login
After sometime possible next day he clicks on link in email
He opens webshop/dashboard gets a message his token is expired

Happy flow:
User sends login link to email (login_via_mail)
User forgets he wanted to login
After sometime possible next day he clicks on link in email
A modal opens with a message saying the token is expired but also give user a way to login by filling in his email again or using QR-code.

**Comment by jamalv** [comment]
Open a modal: Your token expired (can use the text of the javascript error)

open existing login modal again

**Comment by GerbenBosschieter** [comment]
erro text:
Helaas, het is niet gelukt om in te loggen. De link is reeds gebruikt of niet meer geldig. Probeer het opnieuw met een andere link.
