### ISSUE TITLE
Opening time fields Research

### ISSUE THREAD

**Issue by Myshelova** [teamforus/forus#1062]
**1 var. Opening hours (group checkbox setting)**
![image](https://user-images.githubusercontent.com/22478043/66821283-787f4f00-ef42-11e9-9626-4dca1f98b1b7.png)
![image](https://user-images.githubusercontent.com/22478043/66821296-7ddc9980-ef42-11e9-8fec-138d0400658d.png)
![image](https://user-images.githubusercontent.com/22478043/66821303-82a14d80-ef42-11e9-8b3d-2b9e1399939b.png)
https://github.com/FLEXIcontent/flexicontent-cck/issues/358
———
**￼2 var**
![image](https://user-images.githubusercontent.com/22478043/66821350-951b8700-ef42-11e9-9773-c305baaf4c4c.png)
_____________
**Set of hours**
https://support.postmates.com/merchant/articles/115003374367-article-Updating-your-store-hours
![image](https://user-images.githubusercontent.com/22478043/66821410-abc1de00-ef42-11e9-9999-d78af69d7692.png)
![image](https://user-images.githubusercontent.com/22478043/66821424-afedfb80-ef42-11e9-82b1-fa096b22063a.png)
________
![image](https://user-images.githubusercontent.com/22478043/66821453-bb412700-ef42-11e9-90b2-eee6dbcf8d80.png)
_________
￼
![image](https://user-images.githubusercontent.com/22478043/66821476-c4ca8f00-ef42-11e9-881c-40fd6e97dce3.png)
![image](https://user-images.githubusercontent.com/22478043/66821610-ffccc280-ef42-11e9-9be7-4c010f4afb62.png)
![image](https://user-images.githubusercontent.com/22478043/66821576-f3e10080-ef42-11e9-86ce-3a095a9f6ef1.png)

![image](https://user-images.githubusercontent.com/22478043/66821635-0a875780-ef43-11e9-8311-267f4eac2b22.png)
https://ilyabirman.net/meanwhile/all/group-checkbox-setting/

_________
￼
**Opening hours google**
![image](https://user-images.githubusercontent.com/22478043/66821739-3c98b980-ef43-11e9-8fae-7754062acb28.png)
![image](https://user-images.githubusercontent.com/22478043/66821757-43bfc780-ef43-11e9-8853-8dc47481a7f9.png)

￼
￼
￼
￼

**Comment by maxvisser** [comment]
Nice! I think oneplan also has a better office hours picker @danrminds

**Comment by danrminds** [comment]
@maxvisser you mean the one that was until now?

**Comment by danrminds** [comment]
We have 2 options done (for 2 projects):

![Screenshot 2019-10-17 at 09 25 22](https://user-images.githubusercontent.com/33207036/66987090-5dd2e480-f0c0-11e9-95c2-4f4fe38b899a.png)
![Screenshot 2019-10-17 at 09 26 46](https://user-images.githubusercontent.com/33207036/66987091-5dd2e480-f0c0-11e9-845a-cfbbe71e563f.png)
