### ISSUE TITLE
E-mail confirmations

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#107]
- [x] Provider approved
- [x] Provider applied
- [x] Validator added
- [x] New validation request
- [x] New fund created
- [x] New fund that is eligible for your provider organisation (to apply)
- [x] New product added

**Comment by GerbenBosschieter** [comment]
So I've wrote some e-mails. I've also added English translations so you guys can see what I wrote. 
right now I have the feeling that the e-mails are really short compared with the design. So pleas take a look at them, and give feedback if needed.

All of you can find them here:
https://drive.google.com/drive/folders/15bxa7_DydOOTvY6rOqjkKO4CWUEtsHdt?usp=sharing

**Comment by danrminds** [comment]
@GerbenBosschieter - all email that contain in them "name_requester", "user_name", "name_validator" and so on in the start (ex: Dear name_requester) should be changed. We can not use such variable, as 

- [ ] name not required field
- [ ] you can have more records of type name
- [ ] privacy issues

@jknnr these changes will have to be reflected in the mail service after Gerben fixes it

**Comment by GerbenBosschieter** [comment]
On it!

**Comment by danrminds** [comment]
New emails (to transfer from normal sending to using the mailing service). Need texts for them:

1. Login via email
2. Send voucher to email

**Comment by GerbenBosschieter** [comment]
@danrminds how about a provider rejected mail ? We are so positive, we think everybody gets accepted :D

**Comment by maxvisser** [comment]
Also the product voucher is disabled because sponsor deactivated provider mail
