### ISSUE TITLE
Epic. Sprint 2. Webshop Fund / Vouchers pages

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1071]
## Context/goal: 
Prepare the UI Kit / Design elements of these pages, based on the wireframes. 

Jamal made a video to explain the mockup and concepts behind it: https://drive.google.com/a/forus.io/file/d/1r8wgM5fzQ24V-cOUyY7DD7_WkQvbTVac/view?usp=sharing

The figma prototype can be accessed here: https://www.figma.com/proto/vHUKdbZ7pR4q07g7NRrQ75/Webshop---Prototype?node-id=172%3A6979&viewport=131%2C153%2C0.058287493884563446&scaling=scale-down-width

The figma project here: https://www.figma.com/file/vHUKdbZ7pR4q07g7NRrQ75/Webshop-Prototype?node-id=172%3A5167

**Comment by jamalv** [comment]
Created an updated prototype in figma with some suggestions:
<img width="344" alt="Screenshot 2019-11-20 at 08 06 34" src="https://user-images.githubusercontent.com/30194799/69216503-ad4b7b00-0b6c-11ea-9a1b-9c1e81640098.png">

I created a video with an explanation: https://drive.google.com/drive/u/0/folders/1tPeMvEEFTnJALxf3WRHP42mer2m-STHw

**Comment by jamalv** [comment]
After converting the current webshop to figma: https://github.com/teamforus/development/issues/270 and creating the common webshop, this will become relevant again. Will create new issue(s) then.
