### ISSUE TITLE
Epic. Sprint 2. Provider signup. Test transaction implementation

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1073]
## Context/goal: 
In the design we have a step for a test transaction to happen at the end. 
Easiest to implement it is with a new "qrcode_type" in the QRcode itself. When the app will scan this qrcode and sees the new type - will perform different actions than usually, by simulating a transaction.

**Comment by aghimpu** [comment]
For now I've added a hardcoded QR Code there.
@ will have to clarify the implementation details with @danieltcacenco .
