### ISSUE TITLE
Epic. Sprint 2. Approval of products.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1075]
## Context/goal: 
To me, Max and Jamal. We need to define the complete scope of this issue on Monday.

**Comment by maxvisser** [comment]
Few things I see here.

MVP is a provider details page on sponsor dashboard. You click a provider request to aplly for fund and see products, offices (opening times).

This way you can deny or accept the products on an organizational level.

Another option is to make a fund setting called 'spending level'. There will be two levels: budget level, product level. When sponsor selects product level. Budget vouchers will not have a QR-code. People can only use the budget to spend on product vouchers in the shop.

Provider can apply with products to the fund (on product level) and sponsor can select products to add to the active fund
