### ISSUE TITLE
Epic. Sprint 2. Application form vs Criterias

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1076]
## Context/goal: 
We need to define the complete scope of this issue. How the application form should rely on the criteria.

**Comment by maxvisser** [comment]
enhancement:
Criteria grouping (more criteria on one page of the application form) 

A hierarchy in criteria. 

A way to set different fixed formulas based on base_salary criteria if below 1100 fixed amount 400 euro if between 1100 and 1200 fixed amount is 300 euros etc.
