### ISSUE TITLE
Epic. Research Angular for potential new front-ends of the webshops (based on the new design)

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1077]
## Context/goal: 
As we will make a unified UI Kit and design for the webshops - it means we will have to rewrite mostly the frontend. In this case - we have a good opportunity to research the possibility to switch from AngularJS to Angular (2-7). (Valentin proposed)

**Comment by maxvisser** [comment]
Good idea to research this. Also because long term support and of angularjs ends in 2021. Maybe start with only the webshop first.

Different possibilities are vue or react

**Comment by jamalv** [comment]
Good issue, I also heard some good things about react. Will be good to update this in any way. I think this issue is best left to the developers.

**Comment by GerbenBosschieter** [comment]
In my opinion it's best to use the framework that our god developer can work best with. I don't really care if it's React, Vue or Angular. I will go with the flow and try to learn as much as possible about the chosen framework.

**Comment by danrminds** [comment]
Discussed with Valentin. We will look into "Angular"

**Comment by jamalv** [comment]
For me this decision is up to the developers. This issue doesn't seem actionable now. When upgrading the frontends becomes relevant again, we will open an issue for the update.
