### ISSUE TITLE
Webshop Map: No provider count like it used to be

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1089]
## Context/goal: 
Before the implementation of the new category system we had a provider count in the title of the map. Nowadays its gone, would be nice to have it back.

<img width="605" alt="Screen Shot 2019-10-30 at 13 01 56" src="https://user-images.githubusercontent.com/38419514/67856732-7eb22580-fb15-11e9-9a99-662859cc67ab.png">

**Comment by maxvisser** [comment]
It was a bit confusing cause it was the amount of locations instead of the amount organizations

**Comment by danrminds** [comment]
@maxvisser Should it be the number of Organisations or Offices?

**Comment by maxvisser** [comment]
organizations

**Comment by maxvisser** [comment]
Overzcith van alle locaties van {{ organization.amount }} aanbieders
