### ISSUE TITLE
Voucher overview needs more context.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1091]
## Context/goal: 
For some users it's not clear they can open the card at the my voucher overview to see the QR-code.

Pleas add a sentence: Open your voucher or click here for more information.
**English:** 
- Option 1: "Click here for more information".
- Option 2: "Click here to open your voucher".

**Dutch:**
- Option 1: "Klik hier voor meer informatie"
- Option 2: "Klik hier om uw voucher te openen"

This should be added to the all voucher cards (so also the product vouchers)

Not sure what option is best. 
<img width="1386" alt="Screen Shot 2019-10-30 at 13 06 57" src="https://user-images.githubusercontent.com/38419514/67857348-d9984c80-fb16-11e9-8e85-b25562eb7a10.png">

**Comment by GerbenBosschieter** [comment]
Option 2 is the most clear.

**Comment by jamalv** [comment]
This is part of the new design, closing in favour of: https://github.com/teamforus/forus/issues/1071
