### ISSUE TITLE
Expired vouchers. 

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1103]
## Context/goal: 
We need a new filter on the voucher list page. We need to see active and "Expired / Archived" vouchers.
Also relevant is issue #1082 . In same category will go vouchers with "0" euros on it.

**Comment by maxvisser** [comment]
Would be nice to remove buttons on voucher card and also hide qr code

**Comment by jamalv** [comment]
This is part of the new designs; closing this issue in favour of https://github.com/teamforus/forus/issues/1071
