### ISSUE TITLE
Small styling adjustments to the dashboard

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1108]
## Context/goal: 

- [ ] Wider content block
- [ ] White background

**Comment by maxvisser** [comment]
Maybe we can see which differences there are between crm and our dashboards and align.

We talked about making the style, the cards etc one code base / module so it can be more easily be reused also for different projects.

**Comment by danrminds** [comment]
We will finish it soon (the template) and I will demo it to you.

**Comment by maxvisser** [comment]
Decided with Dan to wait on the template and merge Forus dashboard stuff upstream to the template. Alex will make a sketch project for this template. This will give us options for a range of buttons/blocks the CRM uses.
