### ISSUE TITLE
add button (to dashboard) in new product added mail

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1114]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/68128302-c838b100-ff17-11e9-84fb-c4eb82aa56ac.png)

**Comment by maxvisser** [comment]
Er is een nieuw aanbod toegevoegd aan de webshop


Beste [Naam gemeente]
Er is een nieuw aanbod geplaatst op de webshop. Bekijk de webshop om te controleren of het voldoet aan de voorwaarden om vanuit [Fonds naam] aangeboden te worden.
Button: Ga naar het dashboard

**Comment by maxvisser** [comment]
can be added on this branch
https://github.com/teamforus/forus-backend/pull/385/files

**Comment by aghimpu** [comment]
There's a condition there before emails are being sent - product emails are sent only if the product category matches the fund product categories. @dev-rminds said it should be discussed later.
