### ISSUE TITLE
Release v0.0.4: (signup flow and dashboards) Font type is changed to montserrat

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1119]
## Context/goal: 
Font type of dashboard and sign up flow is changed to montserrat.

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-frontend/pull/698/files#diff-6f61565275fdec512b4def533c1b7290  we have per dashboard implementation now the choice to change font family; we can decide per implementation if we want to change the font from montserrat to different fonts
