### ISSUE TITLE
Webshop: Multiple fund titles

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1128]
<img width="1073" alt="Screenshot 2019-11-07 at 15 42 05" src="https://user-images.githubusercontent.com/30194799/68398877-bf451b00-0175-11ea-9037-9c21c2a64d58.png">

# Winterswijk:
## Kindregeling gemeente Winterswijk
Welkom op de website van de Kindregeling van de gemeente Winterswijk. Heeft u via de Sociale Dienst Oost Achterhoek een toekenning voor de Kindregeling gekregen? Dan kunt u hier het aanbod zien en het geld dat u kunt besteden.

Klik op ‘Start’ en vul uw activatiecode in. Deze code staat in de brief over de Kindregeling die u heeft ontvangen.

# Oost Gelre:
## Kindregeling gemeente Oost Gelre
Welkom op de website van de Kindregeling van de gemeente Oost Gelre. Heeft u via de Sociale Dienst Oost Achterhoek een toekenning voor de Kindregeling gekregen? Dan kunt u hier het aanbod zien en het geld dat u kunt besteden.

Klik op ‘Start’ en vul uw activatiecode in. Deze code staat in de brief over de Kindregeling die u heeft ontvangen.

# Kindregeling gemeente Berkelland
Welkom op de website van de Kindregeling van de gemeente Berkelland. Heeft u via de Sociale Dienst Oost Achterhoek een toekenning voor de Kindregeling gekregen? Dan kunt u hier het aanbod zien en het geld dat u kunt besteden.

Klik op ‘Start’ en vul uw activatiecode in. Deze code staat in de brief over de Kindregeling die u heeft ontvangen.

**Comment by maxvisser** [comment]
"Sociale dienst oost achterhoek" and "de Kindregeling" are no known variables in the system. Currently these kind of text are composed of variables like fund name or sponsor organisation name. To make the system scalable we should decide if we allow for each webshop custom texts this way; It will be higher maintanance; espacially if you change these blocks or want to translate texts using i18n in the future.

**Comment by maxvisser** [comment]
We could something called implementation name in the database which is not used. We could use it here and set it as 'de Kindregeling'. But this needs te be developed.

**Comment by maxvisser** [comment]
I will make a pr in  bit

**Comment by maxvisser** [comment]
Done. In v0.5.0 release
