### ISSUE TITLE
Update voucher page on: winterswijk, oostgelre, berkelland:

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1132]
Winterswijk, oostgelre, berkelland: move shopkeeper map above offers on budget voucher page:

![demo winterswijk forus io_](https://user-images.githubusercontent.com/30194799/68401245-b2c2c180-0179-11ea-8fad-3ebe640ac252.png)

**Comment by maxvisser** [comment]
lets fixed it for all webshops? or don't do it just yet but after the test sessions;
