### ISSUE TITLE
Revert: Hide logo on generic dashboard

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1133]
Yes, it will make the design look bad, i know. We need to quickfix it anyway.

Later it would be nice to replace it with: https://github.com/teamforus/forus/issues/674

<img width="1365" alt="Screenshot 2019-11-07 at 16 18 06" src="https://user-images.githubusercontent.com/30194799/68401575-4ac0ab00-017a-11ea-9a57-135c995391ca.png">

**Comment by GerbenBosschieter** [comment]
This "fix" has resulted in very bad UX IMO.
The logo could be used as an organisation switcher. Clicking on the logo gave a overview of all the organisations of that specific profile.

We should rethink this

**Comment by jamalv** [comment]
Yes, we decided to add the logo back to the generic dashboard to enable going back to the organisation view. We would like to add a (high quality) Forus logo.
