### ISSUE TITLE
Activate all funds automatically after filling activation code

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1135]
## Context:
After filling the activation code, the user gets redirected to the "funds" page. They now have to manually activate each fund and then go to the vouchers page.

## Goal
Automatically activate all vouchers and redirect to vouchers page instead of the funds page. To avoid confusion, we can hide the funds page after doing this. Then the user flow is much simpler:

* User activates code
* Funds get activated in the background
* User gets redirected to vouchers page

**Note:** we should also add an "open voucher" button to the voucher overview, still the voucher should _also_ open when you click the card:

<img width="1317" alt="Screenshot 2019-11-07 at 16 44 06" src="https://user-images.githubusercontent.com/30194799/68404056-40081500-017e-11ea-8cfd-f34d3bf0451d.png">

**Comment by maxvisser** [comment]
I would merge vouchers and funds page as one. Basically funds are vouchers that needs te be requested or activated. This way you have one overview but you need more filters on the page to see.

Automatically applying would mean adding more fund_id's to prevalidations; sponsor should select each fund he uploads a CSV for. currently he only selects one.

**Comment by jamalv** [comment]
@maxvisser yea, but in this case, since all vouchers will be automatically activated, we wouldn't even need to show funds at all, right?
