### ISSUE TITLE
Turn off reserve/buy product button based on frontend flag in flag.js 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1136]
## Context/goal: 
Westerkwartier provider are starting to use the product voucher system but experience some troubles:

- Products are located at different offices; A bike can only be picked off at location X but not at location Y
- User can buy a product but pick it up after X weeks. Provider needs to keep product on hold
- Provider does not get any contact details from requester to ask about when he is going to pick up order.

These problems were not identified while we used this system in Nijmegen as the way they use product voucher is for services only (not products)

We are now in a phase where we still can disable buying products all together.

## task definition

We want to disable the button that creates / buys a product only. We will do this for only this municipality and enable it again when we fixed their problems.

Userflow:
User can view and read product description but can't create product vouchers / reservations.

## task

- [ ] Create frontend flag per implementation that disables the product purchase button

**Comment by jamalv** [comment]
Is there still an intention to turn off this feature?

**Comment by jamalv** [comment]
let's refine what are the motivations of turning it off as well, and see how much of those things can be fixed

**Comment by maxvisser** [comment]
motivations are in issue... task is small. I would just develop the option even if we decide not to use it.

**Comment by jamalv** [comment]
Should probably on API level
