### ISSUE TITLE
Fix: kerstpakket footer

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#1139]
probably footer background should be white?

https://kerstpakket.forus.io

<img width="1680" alt="Screenshot 2019-11-12 at 08 44 15" src="https://user-images.githubusercontent.com/30194799/68651890-a0090d80-0528-11ea-8a89-e655b68139de.png">

**Comment by jamalv** [comment]
Needs changes: https://github.com/teamforus/forus-frontend/pull/776#issuecomment-555099915
