### ISSUE TITLE
Fix contact form 

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#114]
## all
- [ ] make organisation field not required

## nijmegen
- [ ] remove splash, sprite, girl
- [ ] recolor title to black and center
- [ ] use logo from nijmegen https://dev.nijmegen.forus.io/sponsor/assets/img/logos/logo-nijmegen.png
- [ ] send mail to meedoen@nijmegen.nl (organisation mail of implementation)
- [ ] hide social media

![image](https://user-images.githubusercontent.com/10818702/50692998-ff0f1380-1035-11e9-86f7-bf7250123319.png)

## zuidhorn

- [ ] use splash/logo from psd:
https://www.dropbox.com/sh/8sn54h6qeaixapg/AAAvaX4kPGFwhIrU6udB5ubfa?dl=0&preview=Funds.psd

- [ ] hide social media
- [ ] send mail to kindpakket@zuidhorn.nl (organisation mail of implementation)

**Comment by maxvisser** [comment]
I think we can remove the contact form from the webshop. It's probably better to have it only on the landings pages and link it to support@forus.io

**Comment by danrminds** [comment]
no-reply@forus.io - sending from

**Comment by maxvisser** [comment]
@GerbenBosschieter could you add a mail for this to the mail service?
