### ISSUE TITLE
Providers. Page where I see what access I have to each fund.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1144]
## Context/goal: 
We need to elaborate and give the provider more insights on what funds they are accepted at, what access they have, etc.

This will touch the following pages:

- [ ] Funds applications 
- [ ] Products / product page

fund application and products page need this information:
- [x] approved for 'budget' scanning
- [x] approved for 'product' scanning
- [x] approved for 'product' for specific products scanning
- [ ] show in modal which specific products are allowed (needs-design)
- [x] show closed funds (from previous years)
- [ ] Make three lists: Invited (needs-design), Approved, Opportunities, Closed/Archived 
- [ ] show dismissed -> show dismissed status

## Improve status showing
Currently two options are missing:
Budget but no products -> this one is edge case
Budget with some products -> confusing
https://github.com/teamforus/forus/issues/1319

**Comment by maxvisser** [comment]
@danrminds is this done?

**Comment by maxvisser** [comment]
fund page should have multiple subpages
- [ ] approved for 'budget' scanning
- [ ] approved for 'product' scanning
- [ ] approved for 'product' for specific scanning
- [ ] show closed funds (from previous years)
- [ ] show upcoming funds (about to start)
- [ ] show opportunities for funds which are active but not applied to yet.
