### ISSUE TITLE
CSS: voucher card top is too wide

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1157]
On voucher card top space is too wide. It should be aligned to bottom (where buttons are)

**URL tested:** https://staging.nijmegen.forus.io/voucher/0x110cc308443f656359ba479a5461b165920b9655

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=18.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.nijmegen.forus.io%2Fvoucher%2F0x110cc308443f656359ba479a5461b165920b9655&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.nijmegen.forus.io/voucher/0x110cc308443f656359ba479a5461b165920b9655&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Edge 18.0 |
| Operating System | Windows 10 |
| Resolution | 2560x1310 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/c6f1c2b87c9b1fc86ae80a320fd64d2f50904ce6/win10_edge_18.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/c6f1c2b87c9b1fc86ae80a320fd64d2f50904ce6/win10_edge_18.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=18.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.nijmegen.forus.io%2Fvoucher%2F0x110cc308443f656359ba479a5461b165920b9655&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.nijmegen.forus.io/voucher/0x110cc308443f656359ba479a5461b165920b9655&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by aghimpu** [comment]
I cant check out those screenshots.

**Comment by maxvisser** [comment]
Weird. Probably you will find the issue if you open the page on edge

**Comment by maxvisser** [comment]
Can't reproduce on the newest version of edge. Pretty hard to get this specific version for reproducing
