### ISSUE TITLE
Pagination Products webshop, responsiveness

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#116]
1. The navbar says "PRODUCTEN"
2. The "Bekijk Meer" call to action doesn't work. 3. If there are alot of products added the text below the products is not alligned with the background anymore.

--------------------------------

1. Change it to "AANBIEDINGEN"
2. Set a maximum amount of products shown on the page so the the "Bekijk meer" buttons can have a functionality.
3. see example
![screen shot 2018-09-12 at 15 01 07](https://user-images.githubusercontent.com/38419514/45426689-3d568080-b69d-11e8-95fa-ff9e74669440.png)

**Comment by danrminds** [comment]
Done
