### ISSUE TITLE
website does not load on iPhone 5s

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1161]
**URL tested:** https://nijmegen.forus.io/

Open [URL](https://live.browserstack.com/#os=iOS&os_version=7.0&device=iPhone+5S&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fnijmegen.forus.io%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://nijmegen.forus.io/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 5S |
| Browser | Mobile_safari |
| Operating System | iOS 7.0 |
| Resolution | 640 x 1136 px |
| Screen size | 4.0 in - 2.0 x 3.5 in |
| Viewport | 320 x 568 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/67776c12ff4a23fa14ade324eca25bce969716f4/realios_iPhone_5S.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/67776c12ff4a23fa14ade324eca25bce969716f4/realios_iPhone_5S.jpg)

**[Click here](https://live.browserstack.com/#os=iOS&os_version=7.0&device=iPhone+5S&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fnijmegen.forus.io%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://nijmegen.forus.io/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
Seems to be iOS 7. Should decide how old of a platform we support and maybe have some nice messages to these users that they should upgrade.

**Comment by jamalv** [comment]
I think we support from ios 10 and up. I'm okay with dropping support for ios 7.
