### ISSUE TITLE
IE: Demo environment doesnt support IE (production does work)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1163]
## Description
The demo environment is not supporting IE at all.
Some problems with Apache, Ie and Google Maps.
It doesn't work on production so there are no real users influenced by this problem.

### Should we fix this ?
We should fix this If we are going to use the demo environment to let our clients play with the application. A lot of our clients still use IE and it gives negative impressions if we want to showcase or test something on demo without the front end working on IE.

**Comment by maxvisser** [comment]
valentin would need to dive into this abit to make it work; should check if it is really valuable to have this working. as it is something with google maps we could also decide to disable maps on IE on these environments

**Comment by GerbenBosschieter** [comment]
is disabling Maps something thats easy to do for specifically the demo environment? I understand that it's currently being used by stakeholders

**Comment by maxvisser** [comment]
yes its easy but all map functionality stops working.

**Comment by maxvisser** [comment]
disabled map on demo (only on oostgelre, berkelland and winterswijk)

**Comment by maxvisser** [comment]
Found solution for this issue; in scripts.pug I included google maps after other libraries and this fixed the issue.

https://github.com/zloirock/core-js/issues/567 (maybe something like this happened)

**Comment by maxvisser** [comment]
still needs to be applied to develop and tested

**Comment by linda-90** [comment]
@maxvisser Fixed?

**Comment by maxvisser** [comment]
No did this manually; needs to be added to the code.
