### ISSUE TITLE
Sponsor dashboard: Double title looks weird if there is only one fund

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1165]
## Main asssignee: @

We've processed some feedback for our client thats is going to use multiple funds.
This processed feedback has some negative influence on our client that only use one fund.
We should think of a good solution.

## Context/goal: 
<img width="1026" alt="Screen Shot 2019-11-18 at 10 35 32" src="https://user-images.githubusercontent.com/38419514/69048745-8bcc8100-09fe-11ea-8387-a80ab7e544f4.png">

## Task
- [ ] first "aanbieder per fonds" can be hidden when there is only one fund.

**Comment by maxvisser** [comment]
for one fund the selector is hidden.

**Comment by aghimpu** [comment]
@GerbenBosschieter , @maxvisser , I think this is fixed already https://github.com/teamforus/forus-frontend/blob/6d8282954d3ef037048b52168fe09b710db829e3/src/sources/forus-platform/pug/tpl/pages/organization-providers.pug#L4

![Screenshot from 2019-11-28 22-56-49](https://user-images.githubusercontent.com/16317411/69831603-bd312200-1232-11ea-94a1-285d42764f2f.png)

I checked it on the develop branch.

**Comment by maxvisser** [comment]
Yes. With the new approve flow its fixed!
