### ISSUE TITLE
As a provider I would like to know how I can apply for a the fund of next year

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1166]
## Context/goal: 
I already got a couple of support questions about applying to a fund for next year.
We should think about this user scenario.

- Automatically apply all organisations of last year to the new fund (by the sponsor)
- Inform the organizations about the new fund and let them apply loggin into the provider dashboard. (by e-mail)

**Comment by danrminds** [comment]
Inform the organizations about the new fund and let them apply loggin into the provider dashboard. (by e-mail) - I think this should already be there (in case a new fund is available for them). At least we had it some time ago.

**Comment by maxvisser** [comment]
#1192
