### ISSUE TITLE
KVK should check input ?q= is a valid KVK number

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1167]
## Context/goal: 
currently you can fill in a name of organisation or just A on production. This means we don't check what people fill in on KVK, not even if it is a number

## Tasks
- [ ] only allow number characters in KVK field (0-9)
- [ ] check if response send KVK in array (if KVK is somewhere in ARRAY; kvk is valid)

**Comment by danrminds** [comment]
Checking if it is a number is clear. Might need a bit more clarification on the second. 
And is this regarding production or dev/staging as well?

**Comment by maxvisser** [comment]
production
