### ISSUE TITLE
implement Footer Zuidhorn content

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#117]
- [x] Link "Algemen voorwaarden" is not working 
- [x] Link "Privacy statement" is not working
- [x] Should be clear that openingstimes are from gemeente zuidhorn
- [x] add contact information from Gemeente

--------------------------------
# Solution proposal
1. Write term of agreements or copy them from last year
2. Write a privacy statement or copy them from last year

I think it's best to write some good content instead of copying it from last year.

------------------------
![image](https://user-images.githubusercontent.com/10818702/47020323-687b3680-d159-11e8-9334-5ac49fd1940e.png)

**Comment by maxvisser** [comment]
privacy statement is geupdate sinds vorig jaar zei Louise Pillon

**Comment by maxvisser** [comment]
I will fix 1 & 2, @GerbenBosschieter could you fix 3 & 4

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/160
should also fix navigation 
![image](https://user-images.githubusercontent.com/10818702/47067108-7b891780-d1e8-11e8-8d2c-dadfbf5554cf.png)

**Comment by maxvisser** [comment]
fixed 3 &4
