### ISSUE TITLE
Translate error message: Token Expired or unknown

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1174]
## Context/goal: 
Dutch text: Deze link is reeds gebruikt of of ongeldig

This text can be found in the frontend - > router.js

https://github.com/teamforus/forus-frontend/blob/622f471e44e06beca4a832059312ea4e283effe2/src/sources/forus-webshop/js/angular-1/routers/router.js

**Comment by maxvisser** [comment]
I like this quickfix but I also made an issue about this error message:
https://github.com/teamforus/forus/issues/1061

**Comment by maxvisser** [comment]
I think issues need to be merged and be put higher on the backlog.

**Comment by jamalv** [comment]
https://github.com/teamforus/forus-frontend/blob/622f471e44e06beca4a832059312ea4e283effe2/src/sources/forus-webshop/js/angular-1/routers/router.js#L378

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-frontend/pull/808
