### ISSUE TITLE
Add fund description to fund page

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1176]
## Context:
We will use the fund description in a couple places. e.g. in the provider signup form, and in the updated webshop pages. The sponsor should be able to write 130 characters at the fund page.

<img width="1066" alt="Screenshot 2019-11-20 at 07 12 47" src="https://user-images.githubusercontent.com/30194799/69213801-72921480-0b65-11ea-8939-3adda676c449.png">

**Comment by danrminds** [comment]
@jamalv Can you please write here an example of Fund description?

**Comment by maxvisser** [comment]
Who asked for a text btw? cause it can be confusing where it is displayed.. should be made clear here aswell.

**Comment by danrminds** [comment]
It will be displayed first of all on funds page for the requester (on webshop).
That's why I need an example as well - to see if it fits under the space allocated there. 

![Screenshot 2019-11-20 at 09 07 08](https://user-images.githubusercontent.com/33207036/69220384-264ed080-0b75-11ea-9344-7f7f60525c37.png)

**Comment by maxvisser** [comment]
example:
Gaat uw kind naar de peuterspeelzaal? Of naar de basisschool of het voortgezet onderwijs? En maakt u kosten voor de peuterspeelzaal, voor een schoolreisje of voor aanschaf schoolspullen? En heeft u een inkomen op of rond bijstandsniveau? En heeft u weinig vermogen (maximaal € 12.240,00 voor een meerpersoonshuishouden)? Dan komt u mogelijk in aanmerking voor een tegemoetkoming in de kosten peuterspeelzaal en schoolgaande kinderen.

**Comment by danrminds** [comment]
@maxvisser Does not look like 130 characters :D

**Comment by maxvisser** [comment]
Indeed! This is an example description I found from kindpakket from the municipalities website.

**Comment by Myshelova** [comment]
Can we use a fund description like this one? 🙂[199 characters]
_"If your child will go to the preschool or primary school you can order some of the supplies and compensate costs. For customers who have a little income (up to € 12.240 for a multi-person household)."_

As my opinion original text a little bit messy and massive for reading and understanding what information is important to a user for applying to the right fund

**Comment by jamalv** [comment]
The fund description should be pretty generic:

Kindpakket by the municipality of Westerkwartier supports children in low-income families by awarding a budget of €300 per child.

[129 characters ] ;)

We will also show it at the fund-apply page for shopkeepers.

**Comment by jamalv** [comment]
Probably we should add an example text below or above

**Comment by jamalv** [comment]
And maybe add previews to explain where the text will be shown?
