### ISSUE TITLE
Loading notifications on webshop and dashboards

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1179]
## Context
Sometimes the system or the internet is slow, the user clicks a button and nothing happens. The user tries again leading to unexpected behaviour. 

## Goal
To show a visual indication that the system is loading. It should be subtle and probably not get the user stuck on the loading page. So the user should still be able to perform actions, but just be notified that the system is loading.

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1111

**Comment by jamalv** [comment]
Closing in favour of https://github.com/teamforus/forus/issues/1111
