### ISSUE TITLE
No kerstpakket logo on dashboard

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1180]
## Context/goal: 
Logo on dashboard 'kerstpakket' is missing.

**Comment by jamalv** [comment]
Why is this critical?

**Comment by jamalv** [comment]
they are already on the dashboards, have we gotten complaints about this?

**Comment by maxvisser** [comment]
well they Emmen is actively using this dashboard and its a small fix. login on kerstpakket.forus.io/sponsor with your own mail and see ;)

**Comment by jamalv** [comment]
Personally, I think for kerstpakket we should use the generic dashboards.

**Comment by jamalv** [comment]
That means the kerstpakket implementation dashboards can be removed.

**Comment by jamalv** [comment]
I don't know if they are being used though.

**Comment by jamalv** [comment]
Let's wait a couple months and take them down. I think this issue can be closed.
