### ISSUE TITLE
Sponsor voucher generator: Exclude QR-Codes that need to be confirmed by pincode (to successfully do a transaction)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1181]
## Context/goal: 
Export function of the voucher generator gives double QR-codes.
If I would upload a csv with 42 records it wil result in 84 QR Codes.
This has to do with the unique QR Code thats being generated for transaction by pin only.

Pleas exclude these QR Codes from the export. Especially if they are not assigned to an e-mailadres.

**Comment by maxvisser** [comment]
Even if assigned the qr codes needed for confirmation by pin should not be exported
