### ISSUE TITLE
When a Fund hits the end date (end date is the past) fund state should be closed.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1182]
## Context/goal: 
FUND_STATE should be closed when end date is in the past or today
example
end date is 01-01-2020 fund should be state closed when new year is starting at 31-12-2019 23:59

**Comment by aghimpu** [comment]
@maxvisser , we already have a cron to check the fund state and it calls a function from the Fund model which actually does what was asked here, but perhaps while testing some funds weren't configured (is_configured field from fund_configs table)?

https://github.com/teamforus/forus-backend/blob/master/app/Models/Fund.php#L631

**Comment by maxvisser** [comment]
Thanks for checking!

**Comment by maxvisser** [comment]
I think this was because the fund was set to 31st of Oct instead of 1st of November. All funds now are set to the correct end date (1st of the month)
