### ISSUE TITLE
QR-code, Map and product sample are hidden on expired vouchers.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1185]
## Context/goal: 
On expired vouchers all actionable content should be hidden. A QR-Code can't be used so why show it? The approved provider are not usefull anymore so these can be hidden. As well as the product samples.

on expired voucher details page
- [ ] placeholder image (expired)
- [ ] hide qr code
- [ ] hide approved providers
- [ ] hide product overview

**Comment by aghimpu** [comment]
>> placeholder image (expired)

@maxvisser , Can I have such a placeholder? There's nothing like this at the moment, right?

**Comment by maxvisser** [comment]
Only really usefull thing are the transactions.. I would maybe even just show only the transaction block. If we do this I would propose to also change the text on the button on voucher list to a text link  'Bekijk transacties' (show transactions)
