### ISSUE TITLE
Offices and organisation of closed funds should not be displayed on provider list / map

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1187]
## Context/goal: 
I am not sure if this is an issue but this needs to be checked. If a fund is closed all offices and organisations should be hidden from the provider list / map. As these providers are not a approved provider anymore for an active fund. People cannot spend their a voucher there.

- [ ] check current status (if a fund is closed, providers should not be displayed - only show providers of currently active funds)
- [ ] if still showing, hide it from the provider list / map

**Comment by jamalv** [comment]
@danrminds could you check if this is an issue?

**Comment by aghimpu** [comment]
@maxvisser, I checked and we aren't displaying such offices

https://github.com/teamforus/forus-frontend/blob/master/src/sources/forus-webshop/js/angular-1/components/Modals/ModalOfficesComponent.js#L32

https://github.com/teamforus/forus-backend/blob/master/app/Models/Office.php#L71

**Comment by maxvisser** [comment]
Ah I see the active funds query

**Comment by maxvisser** [comment]
Thought this was an issue system wide. Thanks for checking
