### ISSUE TITLE
Connecting me quick fixes

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1197]
# Update text:

## Current text:
Autoriseer apparaat
<img width="391" alt="Screenshot 2019-12-21 at 12 54 44" src="https://user-images.githubusercontent.com/30194799/71307650-48947200-23f1-11ea-903f-865c86596f85.png">

## New text:
Log in op de me app
<img width="349" alt="Screenshot 2019-12-21 at 12 55 19" src="https://user-images.githubusercontent.com/30194799/71307652-4f22e980-23f1-11ea-87b1-ecb6e95ba8ff.png">

# Update connect screen
https://www.figma.com/file/Cs7yXSgClrrBotoFCRryVi/Koppel-Me-app?node-id=0%3A1

## Current screen:
![image](https://user-images.githubusercontent.com/30194799/71307611-d6bc2880-23f0-11ea-9ebe-b5624bd5f6e2.png)

## New screen:

![image](https://user-images.githubusercontent.com/30194799/71307597-ba1ff080-23f0-11ea-97f2-3183a616a33e.png)

**Note:** The download me should open the popup that allows you to fill in your phone number to send a download link

Texts: 
Stap 1
Download en open de me app

Stap 2
Kies “Ik heb al een profiel”

Stap 3: Vul de code in
Vul de 6 cijfers die in uw app verschijnen hieronder in

Koppel de app

## Old notification:
![image](https://user-images.githubusercontent.com/30194799/71308933-6fa76f80-2402-11ea-99a7-b9ec046844ea.png)

## New notification
![image](https://user-images.githubusercontent.com/30194799/71308928-5a324580-2402-11ea-8e8e-a8c1ae192f87.png)

Texts:
De app wordt gekoppeld aan uw profiel

Na 5 tot 10 seconden wordt de app gekoppeld. Is het gelukt? Klik dan op volgende. 

Ziet u na 30 seconden nog steeds de 6 cijfers in de app? Probeer het dan opnieuw.

**Comment by maxvisser** [comment]
#868

**Comment by maxvisser** [comment]
Zou er gewoon ' Log in op de app '

**Comment by aghimpu** [comment]
I dont seem to have access to https://www.figma.com/file/Cs7yXSgClrrBotoFCRryVi/Koppel-Me-app?node-id=0%3A1

**Comment by jamalv** [comment]
@aghimpu i’ve updated the permissions
