### ISSUE TITLE
Voucher export, one pdf instead of multiple png images

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1198]
task:
- [ ] research option to do this on the frontend (including show loading screen if it takes long)
- [ ] implement choice modal when exporting [png / pdf]

**Comment by maxvisser** [comment]
https://pdfcandy.com/png-to-pdf.html

**Comment by maxvisser** [comment]
maybe there are other third party tools we could offer; I don't know for sure but this seems pretty server  intensive

**Comment by maartenfv** [comment]
This Issue was discussed and promised to the customer after discussing if it was possible with Jamal. Adding the label "Should have" is incorrect as there was an expectation which has not been met. Customer is not satisfied. 

@jamalv Can we reschedule this issue and place it in the backlog for the upcoming sprint?

**Comment by maartenfv** [comment]
When exporting the voucher the best situation would be:
- Being able to select with check boxen which vouchers to export
  - This needs filters
  - This needs a check all/ uncheck all option
- Being able to select in which format the voucher will be downloaded
 - In PNG or in PDF
- Being able to download in one big file
- Being able to download in individual files

**Comment by maxvisser** [comment]
> This Issue was discussed and promised to the customer after discussing if it was possible with Jamal.
> **Deadline was 2-12-2019.**
> 
> Adding the label "Should have" is incorrect as there was an expectation which has not been met. We have missed our deadline and the customer is not satisfied.
> 
> @jamalv Can we reschedule this issue and place it in the backlog for the upcoming sprint?
> 
> It would be good to be able to tell the customer they have been listened to and the functionality has been added, despite it being late.

Maybe you can open an issue about this in development? This has nothing to do with the feature request but with internal processes. Forus is just for development.

**Comment by maxvisser** [comment]
needs wireframe on how the selection of PDF/PNG needs to look. aswell of explanation of how PDF should be formated. How sponsor will know which QR-code is on which page of pdf etc.

**Comment by jamalv** [comment]
# MVP

## PDF / PNG selection (rough wireframe)
![image](https://user-images.githubusercontent.com/30194799/70091332-2ee6e280-161c-11ea-9041-857ab677d1e3.png)

The pdf can be very simply formatted. Just an empty page with a qr code on the top left. If possible using the printables would of course be even better. But this is the MVP (inner shadow should NOT be included, just a basic white page):

![image](https://user-images.githubusercontent.com/30194799/70092069-bed95c00-161d-11ea-8e4f-5eb4a1b0c342.png)


We will add the ID to the bottom and a CSV file with basic info:

Voucher ID | Amount
--- | ---

**Comment by jamalv** [comment]
@maxvisser @aghimpu I see some time was tracked on this, what is the status?
