### ISSUE TITLE
Webshop: Add menu item to open provide card

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1199]
## Context/goal: 
Pleas add $ctrl.showPopupOffices() to the navbar.
So people can open the provider card from the navbar.

There are already some ideas about the map and how to approach this. 
But I would like to see this small iteration in our current webshop to make it easier for our users.

See example below:
<img width="1153" alt="Screen Shot 2019-11-22 at 15 10 03" src="https://user-images.githubusercontent.com/38419514/69432598-51365180-0d3a-11ea-834d-7a324c102e16.png">

**Comment by jamalv** [comment]
this has been done
