### ISSUE TITLE
Missing content after activation process

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#120]
1. There is no notification or any guidelines what do user should do after the user activates his records by entering a valid e-mail address and activation code.
2. If the user wants to join a fund he/she has to click two times on “Doe Mee” before it can apply to the fund / kindpakket.

--------------------------------

1. Add a confirmation notification after entering a valid e-mail adress and activation code.
2. Add a guideline notification what to do after the activation. Something like "Congratulations, your activation code is approved, pleas go to the FUNDS section to join a fund.

**Comment by maxvisser** [comment]
this is fixed by automatically applying for fund, can you test this @GerbenBosschieter
