### ISSUE TITLE
Use another Media query for sign-up flow. It's currently not usable on tablets

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1201]
Use another Media query for sign-up flow. It's currently not usable on tablets

**URL tested:** https://kerstpakket.forus.io/provider/sign-up

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro+9.7+2016&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fkerstpakket.forus.io%2Fprovider%2Fsign-up&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://kerstpakket.forus.io/provider/sign-up&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPad Pro 9.7 2016 |
| Browser | Tablet_safari |
| Operating System | iOS 11.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/2f60b0def9cd824f15cde573ad22a6e70ad731b1/realios_iPad_Pro_9.7_2016.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/2f60b0def9cd824f15cde573ad22a6e70ad731b1/realios_iPad_Pro_9.7_2016.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro+9.7+2016&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fkerstpakket.forus.io%2Fprovider%2Fsign-up&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://kerstpakket.forus.io/provider/sign-up&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
the sign-up flow is not accesible from iPad pro but there are no issues there. Could we check if we could allow some tablets?
