### ISSUE TITLE
Voucher generator: use s3 to store .zip files instead of local when a config is set

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1207]
## Context/goal: 
Currently all .zip files are stored locally; on production environment we store all files on s3. These .zip files also need to be stored on AWS S3.

## Tasks
- [ ] add an option to upload .zip files to media bucket and download it from AWS S3

**Comment by maxvisser** [comment]
Discussed this with aghimpu; we will wait until this become a problem if even so.

**Comment by jamalv** [comment]
does that mean this issue can be closed?
