### ISSUE TITLE
Voucher generator: Move export example csv button to upload csv modal

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1212]
## Context/goal: 
Export button can be on modal (example):
![image](https://user-images.githubusercontent.com/10818702/69550659-b177fe00-0f9b-11ea-8ba1-233a0b845c8d.png)
I would use this style for the button and text
![image](https://user-images.githubusercontent.com/10818702/69552358-9bb80800-0f9e-11ea-993f-72d88d299f88.png)

Maybe place all these example input buttons on this location?
![image](https://user-images.githubusercontent.com/10818702/69552433-bb4f3080-0f9e-11ea-90d8-881a78dccd9a.png)

**Comment by jamalv** [comment]
please put it under the text
