### ISSUE TITLE
Both searching and filtering on amount does not work

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1215]
## Context/goal: 

Example of the problem:
![image](https://user-images.githubusercontent.com/10818702/69554025-6e208e00-0fa1-11ea-87a2-2478fe3f04c4.png)

Screenshot shows a filter set on 1 till 10 euro's and also keyword "Sociaal"
As you can see results show aswell transactions above 10 euro's

**Comment by aghimpu** [comment]
Weirdly I cant replicate this, tested on develop. The search function on the VoucherTransaction model looks fine too, uses callback function when a parameter requires multiple logical conditions (so I dont see how it can go wrong). It doesnt even matter in which order you apply the filters, they all seem to work together, tried your example.
Could this be rechecked?

**Comment by maxvisser** [comment]
Maybe it was because date filter was broken. I will try to reproduce tomorrow
