### ISSUE TITLE
Voucher generator: move button 'upload csv'

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1216]
## Context/goal: 
This button:
![image](https://user-images.githubusercontent.com/10818702/69554793-9957ad00-0fa2-11ea-872e-c7b96914d81d.png)

Should be an option here:
![image](https://user-images.githubusercontent.com/10818702/69554724-7f1dcf00-0fa2-11ea-97a9-bd5412ab57f3.png)

"create in bulk" / "Maak aan in bulk"

**Comment by jamalv** [comment]
I like it, I think "Download voorbeeld" should then also be moved to the resulting page.
