### ISSUE TITLE
Validator wants to see which emailadres used its activation code

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1219]
## Context: 
A validator currently has limited information of who has used a activation code. Sometimes a requester calls validator about the status of his activation code or to generate a new activation code.

## Goal
For problem solving the validator and requester should be able to handle problems related to already activated activation codes themselves.

## Task
- [ ] add which email address has used a specific activation code.

**Comment by jamalv** [comment]
To add this to the sponsor dashboard you mean? Or to the voucher generator? (i think it is there)

**Comment by maxvisser** [comment]
this is done
