### ISSUE TITLE
Voucher generator: uploading example csv gives unknown errors

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1223]
## Context/goal: 
A wild unknown error appears !

I can only upload csv's with amount header; the example csv can't be uploaded without errors. So this issue is basically fixing it and returning it to a state where it can be used as intended.

## task
 - [ ] we should check which variable is broken. seems that getOrMakeByEmail(); does not create identities or any other column is broken.

## Additional information
https://github.com/teamforus/forus-backend/blob/6eb15edc5e93b93c21d1e7b5337eda0b41aca81c/app/Http/Controllers/Api/Platform/Organizations/Sponsor/VouchersController.php#L70

**Comment by jamalv** [comment]
@maxvisser what do you expect out of this issue?

**Comment by maxvisser** [comment]
I can only upload csv's with amount header; the example csv can't be uploaded without errors. So basically fixing it and returning it to a state where it can be used as intended.

**Comment by aghimpu** [comment]
An error raises only when there's no actual data added to the csv, if you upload it just with the headers (which makes sense I think). 
There was an issue with the file size filter on minification, which produced a JS error as well, but it's not the one mentioned in the task (I fixed it though).
