### ISSUE TITLE
WK webshop fixes

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1231]
- [x] switch offers and providers order (first providers, then offers)

People have difficulty finding the providers. We should show providers above offers on the webshop and on the voucher page.

- [x] add providers to menu

Add an option "Aanbieders" to the top menu. Clicking it will open the map modal.

edit 12-04 @maxvisser :
rebase https://github.com/teamforus/forus-frontend/pull/818/files to stage new release (rebase to master); maybe code needs to be reimplmented sadly

**Comment by maxvisser** [comment]
This issue is needed sooner; https://github.com/teamforus/forus-frontend/pull/818/files is checked out from develop. I can't stage a seperate release for this issue.
