### ISSUE TITLE
Voucher generator fixes

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1232]
- [ ] automatically pre-create identity if no identity

**Comment by jamalv** [comment]
@danrminds could you help refine this issue?

**Comment by maxvisser** [comment]
I would fix the voucher generator first as it seems to not be working now. https://github.com/teamforus/forus/issues/1223

1 & 3 is already done; you can even test this by generating a voucher manually and assigning it. (3 as an mvp as it sends a generic mail)

**Comment by jamalv** [comment]
should test if this works on csv uploader
- consideration: a bunch of emails

**Comment by jamalv** [comment]
dependancy: worker for sending  emails asynchronously (todo: create issue)

**Comment by maxvisser** [comment]
I think we should also implement a fix for bounce mails; As we don't have alot of control over who people will send mails to (they can create a list of mails who are all faulty and bounce)

**Comment by jamalv** [comment]
should be implemented after email cronjob
should be split up in seperate issues

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1357
https://github.com/teamforus/forus/issues/1356
