### ISSUE TITLE
setting unlimited amount on product does not work

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1233]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/69936347-d27aaa80-14d7-11ea-874a-e60d5c19ba54.png)

Userflow:
create new product
set unlimited amount

result:
error that stock amount is too low

**Comment by jamalv** [comment]
needs testing, if cannot be reproduced, please close the issue

**Comment by maxvisser** [comment]
I tested again could not replicate this. Will close it for now
