### ISSUE TITLE
Add notes for transactions

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#124]
- [ ] Sponsor
- [ ] Provider

**Comment by danrminds** [comment]
provider wants to. have the option to fill in a note when doing a product voucher transaction or normal one

**Comment by maartenfv** [comment]
The exact case was that shopkeepers state wanting to be able add more info when a product was sold by adding a note in the description field. Later they want the system to add this note to the bunq payment. So the note can be seen in the transaction in the app and on the euro payment banktransfer.

**Comment by jknnr** [comment]
<img width="267" alt="screen shot 2018-10-24 at 13 53 00" src="https://user-images.githubusercontent.com/32199937/47429814-bd413180-d797-11e8-903b-739c3a4042e8.png">

**Comment by jknnr** [comment]
implemented
