### ISSUE TITLE
Possible bug, amount of medewerkers does not match with number at the top of page.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#1240]
Users tell us that the number of medewerkers does not match with the amount stated at the top. Could not recreate myself but needs to be checked.

![image](https://user-images.githubusercontent.com/30211022/69961031-2d79c500-150b-11ea-97f6-d08ec447b413.png)

## Task
- [ ] reproduce issue

**Comment by jamalv** [comment]
Can't work on this until we have steps to reproduce :(

**Comment by jamalv** [comment]
Can not be reproduced. Closing issue.
