### ISSUE TITLE
Update fund top up reminder email; 

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1247]
## Description

When a sponsor has multiple funds its sometimes hard to remember which topup code is for which of your funds. This task is about adding IBAN and reference code to the balance warning email send to sponsor to warn him that he needs to top up his fund.

## Task
- [ ] include bank account number and reference code

**Comment by maxvisser** [comment]
Current text: 

Het budget 'Kindpakket 2019' fonds heeft de ingestelde aanvulherinneringsgrens overschreden.
 
Beste {{ sponsor org name }}

U ontvangt deze aanvulherinneringsmail omdat u heeft aangeven te willen worden geïnformeerd wanneer het budget van het 'Kindpakket 2019' fonds lager is dan €{{BALANCE WARNING AMOUNT}}

Het budget op het 'Kindpakket 2019' fonds is momenteel €{{ BALANCE}}

Indien het budget niet toereikend is zullen er geen automatische betalingen meer kunnen worden verricht.

Wilt u een storting doen op het fonds om het budget te verhogen of wilt u de aanvulherinneringsgrens aanpassen dan kan dit door in te loggen op uw dashboard.
