### ISSUE TITLE
SDOA webshop; add FAQ:

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1248]
We have to add a Q and A to the FAQ of:
* Berkeland
* Winterswijk
* Oostgelre

These should **not** be added to the other webshops

**Question:** 
Welke organisaties kunnen mij ook ondersteuning bieden?

**Answer:** 
De kledingbank kan u ondersteunen u door het verstrekken van kleding, schoenen en textiel. Tweemaal per jaar kunt u bij hen terecht, hiervoor heeft u een doorverwijzing nodig. De informatie hierover vindt u op http://www.kledingbankwinterswijk.nl/home.aspx 

Stichting leergeld kan u ondersteunen op het vlak van schoolkosten of kosten voor sport, wanneer deze kosten niet vergoed worden door Sociale Dienst Oost Achterhoek, meer informatie hierover vindt u op https://leergeldoostachterhoek.nl/welkom 

Bij de speelgoedbank kunt u speelgoed lenen, hiervoor heeft u een doorverwijzing nodig. Meer informatie vindt u op http://www.speelgoedbankoostachterhoek.nl/speelgoed-doneren/ophalen/ 

De voedselbank kan u ondersteunen wanneer u niet voldoende inkomen hebt om boodschappen te doen, voor de voedselbank heeft u een doorverwijzing nodig. Meer informatie vindt u op https://voedselbankachterhoek.nl/ 

Voor extra financiële ondersteuning kunt u contact opnemen met het jeugdsportfonds voor de gemeente Berkelland en de gemeente Winterswijk. De voorwaarden vindt u op https://jeugdfondssportencultuur.nl/voor-wie/voor-ouders/ 

De stichting Jarige Job kan u ondersteunen op het vlak van kinderfeestjes. Kijkt u voor meer informatie op www.stichtingjarigejob.nl

**Comment by maxvisser** [comment]
must have issue with a private gdocs?:P

**Comment by maxvisser** [comment]
What are the questions for the FAQ? I only see some texts and links;
