### ISSUE TITLE
DigiD refinement. Login

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1254]
## Context/goal: 
First part with DigiD refinement is done. Do we need to implement also just simple login to the system via DigiD?
If yes, then we need to refine couple of things:

1. We need to revise the Login popup to include also DigiD
2. We need a screen where people go after login - if no record with this verified BSN number is in the system. It can be in 2 cases:
 - User has no identity
 - User has identity, but has not verified his BSN yet.
This screen needs wireframing. We need to show a message and the 2 options: to login and to create the identity. Here we also might want to automatically link the BSN record and validate

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1173

**Comment by jamalv** [comment]
What is the status of this? I see it is already on staging?
