### ISSUE TITLE
Inviting providers to a new created fund.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1258]
## Context/goal: 

- [ ] Design invitation on sponsor dashboard
- [ ] Design page to accept invitation   
- [ ] Design providers to see all active invitations

#### Design invitation on sponsor dashboard

When a sponsor creates a new fund he needs a step where he can:
- Invite new providers by e-mail
- Import providers from an old fund (selector from which fund)

####  Design page to accept invitation   

A provider will receive an email for this and will have a button to click. After the click he will land on a page with the styling of our new application / signup form.

We need:
- Page where they land. It will contain a title, subtitle and the fund details with a CTA to accept the invitation
- We need to give some feedback that invitation got accepted and show the login opportunity to the dashboard. 

####  Design providers to see all active invitations

A dashboard page to see all current and past invitations from funds. Maybe upgrade the current funds page of the provider dashboard.

**Comment by maxvisser** [comment]
First page dutch text:

H1: U bent uitgenodigd om deel te nemen aan Kindpakket 2020
Description: 
U was afgelopen jaar aangesloten als aanbieder, daarom sturen wij u deze uitnodiging. We hopen dat u weer meedoet.
Heeft u vragen of loopt u tegen problemen aan bij de aanmelding? Dan kunt u een mail sturen naar {{ sponsor mail address }} of bel naar telefoonnummer {{ sponsor telephonenumber}}.

max
max
Admin
11:51
Second page dutch text:
H1: U bent geaccepteerd en klaar om te scannen!
Description: Mocht u alvast een aanbod willen plaatsen voor het nieuwe jaar, log dan in op uw dashboard.
