### ISSUE TITLE
Double entry possible at CSV uploader 

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#127]
- As a validator it's possible to add a second CSV file with the same content in it.
So if you upload the same CSV file it wil generate new activation codes for the same BSN.

-----------

- Would be nice if it could recognise double entries to prevent confusion

**Comment by danrminds** [comment]
Everybody can be a validator, add a CSV file and create records for people. Also you can add for the same person multiple records of the same type - it does not matter here. 

So - not relevant at this point. Might come back to this after we establish some access level.
