### ISSUE TITLE
Payment: Scanning budgetvoucher for provider which is only allowed to scan productvouchers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1279]
A user can have bought a product with a budget voucher from a provider which is only applicable to scan product vouchers. (new approved provider flow functionality).
 
If citizen shows QR-code of budgetvoucher we should still show all tokens from productvouchers. As the citizen can get confused as he does not know if provider can only scan product voucher or any other reason why he shows the wrong QR-code.

## Task

- [ ] update api route
- [ ] check app -> button should be hidden to scan budget voucher

**Comment by jamalv** [comment]
@maxvisser could you clarify what you mean with the second task? "check app -> button should be hidden to scan budget voucher"

**Comment by maxvisser** [comment]
when you scan budgetvoucher you get a list of product voucher you reserved at that shopkeeper.
Below this list there is a button which allows you to fill in amount (go to next screen where you can do so). When a provider is approved for scanning products (or some products) they should still get the list of reservations (product vouchers) but not the blue button below this list,

**Comment by maxvisser** [comment]
approved provider for specific products
citizen has reservation and bring budgetvoucher
provider scans budgetvoucher and is not allowed to scan.

what should happen his the provider should get an option to press the reserved product voucher

**Comment by maxvisser** [comment]
migration strategy

**Comment by jamalv** [comment]
We will keep the old version working for about a month
We will monitor how many people have updated the app
