### ISSUE TITLE
Auto filter product list on budgetvoucher user has

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1282]
## Context/goal: 
Currently we show all products of implementation approved providers. This can be confusing for people who only have 3 of 5 fund vouchers on their account. Products they can't buy are not needed to be shown when logged in.

**Comment by maxvisser** [comment]
Must have if we can't implement new product list with filters before monday.

**Comment by jamalv** [comment]
"show me only what i can buy"
