### ISSUE TITLE
Productvoucher details: cancel, share button move / delete

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1283]
### Cancel reservation
![image](https://user-images.githubusercontent.com/10818702/70786697-82c89880-1d8d-11ea-9f44-196f5e60f5b5.png)

- [ ] move cancel reservation button to a right, give it less weight and give it underline

### Share with provider
![image](https://user-images.githubusercontent.com/10818702/70786266-89a2db80-1d8c-11ea-977a-30f94e14e755.png)
- [ ] Share with provider is on this page twice, The left button can be removed; Button texts can slightly bigger as there is more room from 10px to 12px;

## Details of provider
Make public function should work like this:
We dont want to put their information public on the internet. So people need to authenticate first before seeing any telephonenumbers/mailadresses. Currently on this page; no details are shown. This is pretty bad UX; we should display the details to citizen as they reserved a product by this provider.

### example of how it should look
![image](https://user-images.githubusercontent.com/10818702/70787290-a4764f80-1d8e-11ea-8a89-9513cc583a6c.png)

**Comment by aghimpu** [comment]
>> Make public function should work like this:
We dont want to put their information public on the internet. So people need to authenticate first before seeing any telephonenumbers/mailadresses. Currently on this page; no details are shown. This is pretty bad UX; we should display the details to citizen as they reserved a product by this provider.

I dont see any issues like this, couldnt replicate it either.
If you look the code on voucher page then you also wont see any condition related to the display of that information (and this is the case for budget vouchers as well)
https://github.com/teamforus/forus-frontend/blob/develop/src/sources/forus-webshop/pug/tpl/pages/voucher.pug#L113
https://github.com/teamforus/forus-frontend/blob/develop/src/sources/forus-webshop/pug/tpl/pages/voucher.pug#L116

**Comment by maxvisser** [comment]
Could it be that it is on api level?
https://github.com/teamforus/forus-backend/blob/master/app/Http/Resources/OrganizationBasicResource.php

**Comment by aghimpu** [comment]
That's right, probably while I was checking it didn't have the details as private. And that's right, its on the backend.

**Comment by aghimpu** [comment]
I guess the idea was to hide the details completely from everyone if set as private, because someone can still use the inspector and analyze the requests.
Should decide then how to show/hide it properly, but we have to do that on the API level.
