### ISSUE TITLE
Financial dashboard sponsor: Statistics of individual shopkeepers make no sense

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1289]
On the sponsor dashboard, finance, when looking at the statistics of individual shopkeepers there are a lot of numbers that make no sense. Please check each and make sure they work or are removed to prevent confusion.

![image](https://user-images.githubusercontent.com/10818702/71881997-d41d3b00-3133-11ea-80d9-ac084dd89a0c.png)

## task
- [ ] explain current statistics, how should 1, 2, 3, 4 work?
- [ ] redefine what it should be (if statistics dont make sense)

**Comment by maxvisser** [comment]
also the list does not have filters, on a dashboard like Meedoenregeling is it not usefull at all as you have to click through alot of provider until you know which is the biggest seller etc.

**Comment by jamalv** [comment]
@maxvisser @danrminds who should be able to explain these stats?

**Comment by maxvisser** [comment]
@aghimpu, @dev-rminds  or myself

**Comment by maxvisser** [comment]
done
