### ISSUE TITLE
Hardcoded message webshop  (Login Popup)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#129]
- There is a hardcoded timestamp at the bottom of the popup after you click on login. (see example below) would be nice if there would be added a realtime calculation of the current time + 15 minutes.

![screen shot 2018-09-27 at 09 24 35](https://user-images.githubusercontent.com/38419514/46129766-f8ebe880-c237-11e8-8ebe-defad354c355.jpg)

**Comment by maxvisser** [comment]
remove it for now @GerbenBosschieter, we can implement it later again

**Comment by GerbenBosschieter** [comment]
done
