### ISSUE TITLE
Voucher generator: Patch forbidden error 403 on assigning vouchers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1299]
## Main asssignee: @

start from release-v0.6.0

## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/71001510-b7b25380-20dd-11ea-9fd2-1b4e9466a76a.png)

**Comment by jamalv** [comment]
I assume this is a must have? What needs to be refined?

**Comment by maxvisser** [comment]
I discussed this with @aghimpu I probably was logged out while testing. Could not reproduce the issue.
