### ISSUE TITLE
Can't close 'aanmelden' pop-up

### ISSUE THREAD

**Issue by Jimmy390** [teamforus/forus#130]
**Bug:** When you click the login button and choose to login with an email, you'll enter your email and after that, it gives a pop-up which states that an authorization link will be sent to your email, only the cancel(?)/close button is not working.

**Note:** I encountered this bug on my own testing environment of the platform ([https://participatie.ddns.net](https://participatie.ddns.net))

**Comment by GerbenBosschieter** [comment]
I will try to reproduce this on our own environment also !

**Comment by GerbenBosschieter** [comment]
![screen shot 2018-10-05 at 12 18 04](https://user-images.githubusercontent.com/38419514/46530022-caee5000-c898-11e8-86ef-cdb1db8aa1a8.png)

Got the same, the Cancel (annuleren) button doesn't work and there is no cross button to cancel the pop up

**Comment by maxvisser** [comment]
This should be fixed on develop
