### ISSUE TITLE
Show chosen organisation instead of sponsor in auth-user-role

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1302]
## Context/goal:

![image](https://user-images.githubusercontent.com/10818702/71005328-c69c0480-20e3-11ea-8ef0-d37206369466.png)

Sponsor or provider is not really descriptive. Only to show on which dashboard you are.
I would suggest to add here the organization name on which you are logged in.

**Comment by jamalv** [comment]
Organisation name - role
