### ISSUE TITLE
IE: Staging environment doesn't work on IE (again

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1317]
IE: Staging environment doesn't work on IE (again)

Would be nice if we could prevent this happening over and over again

**URL tested:** https://staging.forus.io/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 924x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/edc8f7d14ab4a4e72325785bf530fe9ad208c336/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/edc8f7d14ab4a4e72325785bf530fe9ad208c336/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
the other issue is still open; I found a solution but it is not implemented yet.

**Comment by maxvisser** [comment]
could you check if its the same issue? (google maps)

**Comment by maxvisser** [comment]
fixed
