### ISSUE TITLE
IE: Can't click on he carrot or profile icon to open settings

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1327]
IE: Can't click on he carrot or profile icon to open settings

Can't open the red square to open profile settings. I can only  use the green circle to open the profile settings

**URL tested:** https://staging.berkelland.forus.io/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.berkelland.forus.io%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.berkelland.forus.io/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1440x632 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/c6d129bd2029ec97ee22704828c093c4396713b3/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/c6d129bd2029ec97ee22704828c093c4396713b3/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.berkelland.forus.io%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.berkelland.forus.io/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by aghimpu** [comment]
I checked it on IE11 (not on Browserstack though, cause I dont seem to have access for IE11 there).
I couldn't replicate it, even on the same version of IE. It works correctly no matter if I click the caret or profile icon.

![ie11](https://user-images.githubusercontent.com/16317411/71420731-9e7e4980-267f-11ea-971e-2f59d223314b.png)
