### ISSUE TITLE
make config for opening up sponsor and validatorroles

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#133]
## Main asssignee: @
@dev-rminds 
## Context/goal: 
As for the context of 1 november the roles of sponsor and validator will still be Zuidhorn. We should add to the config file an option to disable any organisation to be a sponsor or validator except Zuidhorn.

@danrminds maybe we can discuss this issue on monday

**Comment by danrminds** [comment]
Meaning that based on a configuration - we do not allow identities to create new funds.
Also - hide the CSV uploader if the identity not trusted for the fund having the CSV uploader.

**Comment by jamalv** [comment]
I think it should kind a whitelist, right? Nobody can become a sponsor / validator, unless you are on the whitelist, which will now just be a couple people in Zuidhorn (Marleen / Margrieta / Financial ladies) that we manually add. After nov. 1 we can extend this to be more flexible to also allow more complexity and configurability for cases like Nijmegen.

**Comment by maxvisser** [comment]
I agree! Good idea ;) Maybe a set up this whitelist on organisation level. I think we should add an ORG_MAPPING in env file with organisation ids that can add employees to add funds and csv's; if you are not part of the org in the mapping you cant use the sponsor/validator dashboards.

**Comment by maxvisser** [comment]
what is the status of this issue?

**Comment by danrminds** [comment]
Until now - postponed )

**Comment by maxvisser** [comment]
I almost implemented with access level will close this issue for now
