### ISSUE TITLE
Provider: Can't create an office

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1331]
## Context/goal: 
The signup flow doesn't force the provider to add an office. But it will give you the option to apply for a fund.

After finishing the sign-up flow and visiting the dashboard the provider can't add an office anymore. 
This results in the fact that the provider can't apply for a new fund.

### Additional information
This problems definitely occurs at the filtered signed up flow. Not sure if this also occurs at the regular sign-up flow.

See video below for visual explanation

https://drive.google.com/file/d/14k47jjYH5M-dCvDeot2vZr0BlgG4Vty3/view?usp=sharing

**Comment by maxvisser** [comment]
I think this is about the new breaks that a office can't be added? @aghimpu
