### ISSUE TITLE
Admin role can upload csv but activation code is not valid

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1333]
## Context/goal: 

Admin role is percivied to users as a role which can do everything owner can. If we refactor acccess level we should rethink current structure of roles and which roles there are.

This issue is about a confusing interaction as the Admin can upload CSV's but all activation codes are not valid. I would propose to disable the option to upload csv's for now.

**Comment by GerbenBosschieter** [comment]
@maxvisser On what environment did you test this?

This is correct for the the multiple funds implementation.

**Comment by jamalv** [comment]
On which branch did you test? @dev-rminds thinks it might work on develop

**Comment by maxvisser** [comment]
I tested this on release v0.6.0

**Comment by maxvisser** [comment]
gerben tested this aswell also found the issue
