### ISSUE TITLE
Sponsor: Filter functionality offer options that do not exist

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1334]
## Context/goal: 
The status: accepted or declined (geaccepteerd of afgewezen) do not exist anymore.

### Solution
We should think about this, removing these options is in my opinion not the way to go.
Before working on this issue we should refine the product validation functionality

<img width="342" alt="Screen Shot 2019-12-20 at 14 15 00" src="https://user-images.githubusercontent.com/38419514/71259174-183ccd00-2338-11ea-9c22-043dfb212ed1.png">

**Comment by maxvisser** [comment]
I would add two filters
Budget yes / no
Product yes / no

if anyone has a good way to make it one filter

**Comment by maxvisser** [comment]
I would remove it for now as it now a dropdown that does nothing
