### ISSUE TITLE
DigiD: Hide "volgende stap"

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1335]
"Volgende stap" on the screen below sends me to a blank page, I can't use the back button in the browser. "Volgende stap" Button should be hidden.

<img width="1792" alt="Screenshot 2019-12-23 at 08 18 28" src="https://user-images.githubusercontent.com/30194799/71342389-eeb0bb00-255c-11ea-94d4-37eb93b8e89c.png">

**Comment by maxvisser** [comment]
could you leave these on the PR on frontend?
