### ISSUE TITLE
Automatically accept aanbiedingen when accepting budget

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1336]
## Description
When allowing budget -> allowing product should automatically also be approved.

This will result in user only flicking a single toggle to approve a provider. If he has to do multiple provider in a batch he can now more easily do so.

**Comment by jamalv** [comment]
Add new button "Allow all" same behaviour as old button (both toggles go to right).

**Comment by jamalv** [comment]
@aghimpu please ask @dev-rminds if unclear :)

**Comment by jamalv** [comment]
In dutch "Accepteer alles"
