### ISSUE TITLE
Map: seperate page instead of modal

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1339]
## Goal
Right now the map is a modal:
<img width="1680" alt="Screenshot 2019-12-23 at 10 30 30" src="https://user-images.githubusercontent.com/30194799/71349391-3fc9aa80-256f-11ea-9f14-4269db3b2e7f.png">

The goal of this issue is to create a separate page to show the map full screen, similar to the aanbiedingen page:

<img width="1680" alt="Screenshot 2019-12-23 at 10 31 25" src="https://user-images.githubusercontent.com/30194799/71349458-60920000-256f-11ea-918b-bb61c71bd230.png">

## Result:
![image](https://user-images.githubusercontent.com/30194799/71350010-9c799500-2570-11ea-9f8b-e6f5ce769c4e.png)

**Comment by danrminds** [comment]
@jamalv Aren't we finishing the new designed map / products page?

**Comment by jamalv** [comment]
Yes we are, but we would like to do the simple thing first. We need the filter asap and we feel this issue became too big. Therefore the focus will first be on this issue and this one: https://github.com/teamforus/forus/issues/1340 

Then we can continue with implementing the new map.

**Comment by jamalv** [comment]
Yes, exactly, it is a temporary hot fix to enable us to add the filter: https://github.com/teamforus/forus/issues/1340

**Comment by jamalv** [comment]
Discussed: directly implement new map with filter instead

**Comment by maxvisser** [comment]
wll close this one as the provider map page is done
