### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#134]
### Regular vouchers
- [ ] activated voucher

EN: You used an activation code to receive a `{{fund_name}}` voucher.
NL: U hebt een activatiecode gebruikt om '{{fund_name' voucher te activeren.

### Product vouchers

- [ ] product bought 

EN: You bought a product in '{{implementation name}}' webshop
NL: U hebt een aanbieding gekocht in '{{implementation name}}' webshop.

### Offline regular transactions
- [ ] Payment

EN: There has just been payment of € {{amount}},- from your '{{fund_name}}' voucher.
NL: Er is zojuist een betaling plaats gevonden van € {{amount}},- van uw '{{fund_name}}' voucher

 
### Product voucher transactions

- [ ] pick up product

EN: A product voucher is used `{{product_name`
NL: Een aanbieding voucher is zojuist gebruikt om `{{product_name}}` af te nemen.

### BUNQ transactions
- [ ] bunq transaction from pending to done

to provider organisation owner
EN: Uw transactie van €{{amount}},- has been payed out.
NL: Uw transactie van €{{amount}},- is uitbetaald.

## Access levels
- [ ] added as employee

EN: You have been added tot {{org_name}} as {{role_name_list}}
example: You have been added to Gemeente Zuidhorn as Admin, Finance and Validation.
NL: U bent toegevoegd aan {{org_name}} as {{role_name_list}} 
example: U bent toegevoegd aan {{org_name}} as Beheerder, Financiën en Validator.

- [ ] removed as employee

EN: You have been removed as an employee from {org_name}
NL: U bent verwijderd als een medewerker van {{org_name}}

## fund application provider

- [ ] Accepted for fund

EN: You have been accepted for `fund_name`
NL: U bent goedgekeurd voor 'fund_name'

no decline message needed

**Comment by GerbenBosschieter** [comment]
Just saw this issue. Will worn on this today!

**Comment by maxvisser** [comment]
Zou ipv 'in jouw wallet' er 'aan jouw eigendommen' van maken

**Comment by maxvisser** [comment]
Validatieverzoek is 1 woord

**Comment by maxvisser** [comment]
Maybe notifications for the providers?

 Accepted as provider for [fund]. 

Your organisation is declined as a provider for [fund]

There is a new fund available for your organisation to apply for.

**Comment by maxvisser** [comment]
Dont know if this is needed as the notification dont lead towards any new items in the Me app
