### ISSUE TITLE
Give descriptive error when  a provider scans product vouchers where he was previously allowed

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1341]
## Context/goal: 

When a user scans a productvoucher which he was previously allowed to scan. (User bought product reservation when provider was allowed for products). Provider should see that he is denied for scanning products. (or this specific product)

**Comment by jamalv** [comment]
Could you make concrete tasks out of this?

**Comment by maxvisser** [comment]
added on hold as with groningen this whole workflow will change.
