### ISSUE TITLE
IE: Missing header images on provider landingpages

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1350]
Headers are missing on provider landingpages.
Only Internet Explorer has this problem.

**URL tested:** https://staging.berkelland.forus.io/provider/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.berkelland.forus.io%2Fprovider%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.berkelland.forus.io/provider/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1416x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/af615ef7c4d2a41bddad1993f57cb02128e15500/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/af615ef7c4d2a41bddad1993f57cb02128e15500/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.berkelland.forus.io%2Fprovider%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.berkelland.forus.io/provider/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/77739995-c8466400-7012-11ea-85a0-5b4824c357ec.png)

**Comment by maxvisser** [comment]
Webshop:
![image](https://user-images.githubusercontent.com/10818702/77740015-d3998f80-7012-11ea-8b66-105106de9828.png)
