### ISSUE TITLE
Create new e-mail specificly for assigning vouchers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1356]
## Context/goal: 
Currently the e-mail that is used to send email to your self is the same for when a voucher is assigned to you. We should differentiate these mails

## Task
- [x] write text for email
```
Title: Hierbij ontvangt u uw {{fund_name}}-voucher
Beste gebruiker,

Er is een {{ fund_name }} tegoed aan u toegekend. Hierbij ontvangt u uw {{fund_name}}-voucher. 

De voucher heeft een waarde van € {voucher_amount} en is geldig tot en met {{ expire_at - 1 day }}.
Onderstaande voucher laat u bij de organisatie van uw keuze zien. 

{{ QR-CODE }}

De organisatie scant deze code en de betaling gebeurt automatisch.

Let op! Als u een aanbieding afneemt met een geldbedrag lager dan € {{ voucher_amount }}, blijft het restantbedrag op de voucher staan.  Bewaar deze voucher dus goed.

Veel plezier met de door u gekozen aanbieding.
```
- [ ] implement new mail

**Comment by jamalv** [comment]
Figma reference: https://www.figma.com/file/9Pe1gS7QUCL7uD3SKoNsly/Groningen-Demo?node-id=1%3A1410

Should still be updated to be more generic

**Comment by jamalv** [comment]
<img width="1013" alt="Screenshot 2020-01-08 at 14 41 04" src="https://user-images.githubusercontent.com/30194799/71982557-065a9580-3225-11ea-8725-e47f872222d1.png">

**Comment by jamalv** [comment]
@maxvisser, could you add the text?

**Comment by GerbenBosschieter** [comment]
@jamalv 
I have received text from on our clients.
I am not going to create a new e-mail and not going to add the text into figma, pleas assign someone else to this.

I will only change what our clients requested me.
Feel free to use the text they send me.

**Text**
Beste heer/mevrouw,

U heeft zich aangemeld voor de meedoen-regeling 2020.​  

Uw aanvraag is goedgekeurd. Hierbij ontvangt u uw persoonlijke Meedoen-regeling voucher. 

De voucher heeft een waarde van € 150,00.
Onderstaande voucher laat u bij de organisatie van uw keuze zien. 
De organisatie scant deze code en de betaling gebeurt automatisch.
Let op ! Als u een activiteit afneemt met een geldbedrag lager dan € 150,00, blijft het restantbedrag op de voucher staan.  Bewaar deze voucher dus goed.
Veel plezier met de door u gekozen activiteit.

**Comment by maxvisser** [comment]
Thanks gerben. Ik heb hem toegevoegd aan de issue (iets aangepast zodat hij wat generieker is)
