### ISSUE TITLE
As a provider I can add a product while I am not accepted to a fund.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#136]
So what I did:
- I logged in on to the provider dashboard with a random identity. I can add a product to the webshop. You cannot buy the product if a provider isn't accepted so its secured.
But the problem is that the webshop can be cluttered.

see the picture below
![product](https://user-images.githubusercontent.com/38419514/46662469-c9d06200-cbbb-11e8-9f0b-5ced96c5bb40.jpg)

**Comment by danrminds** [comment]
done
