### ISSUE TITLE
Financial dashboard: No data is displayed at the first view if fund is closed

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1364]
## Main asssignee: @

**Tested branch: master**

## Context/goal: 
If a sponsor would open the financial dashboard and select a closed fund it will display the information of the current year. This could be confusing if the sponsor expects data about the year the fund was active.

- Could the information displayed at the chart be fixed at the year the fund was active after a fund is closed. This will result in a better first impression after opening the financial dashboard

![ui-control2](https://user-images.githubusercontent.com/38419514/72006511-19368f80-3250-11ea-8948-f5059d9a609f.jpg)

**Comment by aghimpu** [comment]
>> Could the information displayed at the chart be fixed at the year the fund was active after a fund is closed

How can we determine the date the fund was closed? Would it be accurate to do so by the end date?
We also have an updated_at field for the funds, but this really has a totally different purpose.
I suppose we might have to add a new field called 'closed_date' or so.
