### ISSUE TITLE
Navbar: Replace current logo's with higher quality

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1369]
## Context/goal: 
The logo's on the general landingpage and dashoards and westerkwartier webshop are low quality.
Pleas replace this with higher quality

Westerkwartier:
- Use the logo that is being used for the hover class and landing pages. This one is higher quality.
You can find it here:  _**./assets/img/landing/logo-normal.svg**_

Forus: 
- Use the logo that is being used on the website. 
You can find it here: **_resources/platform-general/assets/img/svg/forus-logo.svg_**

<img width="202" alt="Screen Shot 2020-01-10 at 11 24 37" src="https://user-images.githubusercontent.com/38419514/72146148-2bbddf80-339c-11ea-98a7-0b67e4e9e038.png">
<img width="319" alt="Screen Shot 2020-01-10 at 11 24 50" src="https://user-images.githubusercontent.com/38419514/72146150-2c567600-339c-11ea-92f0-e9ffcc944aac.png">

**Comment by maxvisser** [comment]
logo on forus.io/sponsor forus.io/provider are still not right
