### ISSUE TITLE
As a user I would like to cancel a product voucher if the expiration date is due

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1371]
## Context/goal: 
Currently when a product voucher is expirated the voucher details page is disabled (no open voucher button anymore) therefor the cancel button is also removed from UI. 

We should readd the cancel button; on voucher list

**Comment by maxvisser** [comment]
Don't show cancel button on list when:
- budget voucher is expired aswell
- a transaction is done on product voucher
- product voucher is not returnable
