### ISSUE TITLE
Design and wireframe Sessions list / screens

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1375]
## Main asssignee: @
Do we need it for dashboard and webshop? 1 common screen or separate screens/designs for both?

We might need wireframes in case we need sessions AND other settings on the same page as recovery options (similar to how Google has)

## Context/goal: 
```
[
    {

        [Client: Webshop, Browser: Chrome] [current]
        Last activity: 25min ago [ip: 192.168.0.1, Netherlands, Zuidhorn]
        
        Show details:
        [session: #xxx1]
            [ip: 192.168.0.1, Netherlands, Zuidhorn]
            [ip: 192.168.0.1, Netherlands, Zuidhorn]

        session started: 25 jan 2077
        
        X Terminate session
        
    }, 
    {

        [Client: Webshop, Browser: Chrome] [session: #xxx2] [online]
        Last activity: 25min ago
        
        Show details:
        [session: #xxx1]
            [ip: 192.168.0.1, Netherlands, Zuidhorn]
            [ip: 192.168.0.1, Netherlands, Zuidhorn]

        session started: 25 jan 2077
        
        X Terminate session
    
    }, 
    {

        [Client: Webshop, Browser: Chrome] [session: #xxx2]
        Last activity: 25 years ago
        
        Show details:
        [session: #xxx1]
            [ip: 192.168.0.1, Netherlands, Zuidhorn]
            [ip: 192.168.0.1, Netherlands, Zuidhorn]

        session started: 25 jan 2077
        
        X Terminate session
    
    }, 

    X Terminate all sessions
]
```

### Examples:

![screencapture-myaccount-google-security-checkup-2-2020-01-13-11_45_29](https://user-images.githubusercontent.com/33207036/72331580-b6fae600-36b8-11ea-98b1-d3e7e243e873.png)
![screencapture-myaccount-google-security-checkup-1-2020-01-13-11_42_01](https://user-images.githubusercontent.com/33207036/72331581-b7937c80-36b8-11ea-841c-f5bcbaa66704.png)

![screencapture-myaccount-google-security-checkup-4-2020-01-13-11_37_28](https://user-images.githubusercontent.com/33207036/72331582-b7937c80-36b8-11ea-9894-ce41ebe14448.png)

<img width="626" alt="Screenshot 2020-01-13 at 11 35 27" src="https://user-images.githubusercontent.com/33207036/72331583-b7937c80-36b8-11ea-8a74-fe092e20481a.png">

<img width="1158" alt="Screenshot 2020-01-13 at 11 33 30" src="https://user-images.githubusercontent.com/33207036/72331584-b7937c80-36b8-11ea-87dd-fee1cf71a292.png">

<img width="1022" alt="Screenshot 2020-01-13 at 11 29 42" src="https://user-images.githubusercontent.com/33207036/72331585-b7937c80-36b8-11ea-8260-f0dc9883f7c0.png">

**Comment by maxvisser** [comment]
made the json part together with valentin, design wise I like Github

active status color (grey not active, green active) icon of type device (desktop or mobile) and a details button.

**Comment by sashooa** [comment]
https://drive.google.com/open?id=151H4R41BRL4zWKs3zCrv8fCGcE2bGu8d

**Comment by maxvisser** [comment]
Terminate all sessions seems missing..

I would make details a seperate page like github has. I am OK with mostly copying their ui
