### ISSUE TITLE
Update DigiD error message

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1379]
Current error: "Er kon niet ingelogd worden met DigiD door een onbekend probleem."

Required error: "Er is een fout opgetreden in de communicatie met DigiD. Probeert u het later nogmaals. Indien deze fout blijft aanhouden, kijk dan op de website https://www.digid.nl voor de laatste informatie."

**Comment by jamalv** [comment]
@maxvisser please check if you can fix it and put it on staging, otherwise could you check if anybody can pick it up before Logius will test tomorrow?

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-frontend/pull/939

**Comment by maxvisser** [comment]
when will logius start testing? I fixed the texts but I could not really test if they work as aspected (dont really know how to get a weird error code back from DigiD)

**Comment by maxvisser** [comment]
done.
