### ISSUE TITLE
As a validator I would like to see all activation codes of a closed fund.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1390]
## Description (user experience)
One of our clients has a closed fund. The employee that generated the activation codes wants to have some statistics about how many activation codes they generated and how many people really used the activation code. So they can maybe change something in their communication to encourage or help the citizen to activate the voucher next time.

### Problem
The validator accounts can't see any activation codes right now.
I am not sure what causes the problem, didn't have time left to really reproduce it properly.
Possible causes:
- The fund is closed, and therefore there is nor information displayed
- There are multiple funds and the **Aanvrager** tab doesn't know what fund to select.
- After we did something for DigiD we change the way we use prevalidations, but this is unlikely cause this problem does not occur on active funds.

**Comment by jamalv** [comment]
upload block should be hidden

**Comment by jamalv** [comment]
on api level: reading codes should be possible, but not uploading

**Comment by GerbenBosschieter** [comment]
uploading shouldn't be possible, but using the filter options should be :D
