### ISSUE TITLE
provider_applied.blade.php is send to contact mailadres instead of the acces level "manager"

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1392]
## Main asssignee: @

# Description
Employee who process the applications of the providers don't receive any mails. If you have one owner with 3 organisations and 15 funds it's pretty unusable :D

## Solution
Please send this mail to user acces level: "Manager"

**Comment by jamalv** [comment]
should also list all emails that we are sending to the contact address of organisation
