### ISSUE TITLE
Change e-mails header (from) back before it gets merged into the release

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1398]
## Context/goal: 
For one of our projects we changed the FROM header to the name of our clients.
I am not sure how this is done, but before this gets merged into a release branch I would like to see his changed.

![Screen Shot 2020-01-24 at 14 52 40](https://user-images.githubusercontent.com/38419514/73074246-7588e880-3eb9-11ea-9ee1-a9a21cd5d095.jpg)

**Comment by maxvisser** [comment]
done
