### ISSUE TITLE
Hard cap products on api (max 25 products)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1399]
## Context/goal: 
*explain why this issue was opened*

**Comment by GerbenBosschieter** [comment]
Is this smart to do?
I know that frond end isn't the best place to assign the maxproductcount.
But it does provide us flexibility if we need to change it for specific implementations.

**Comment by maxvisser** [comment]
which cap would be the max do you think?

**Comment by GerbenBosschieter** [comment]
Well I think 25 is fine. But it's more about the flexibility.
But untill now we capped it on 2 and it was okay.

So capping it on 25 on api level would do the trick for now.
