### ISSUE TITLE
E-mail (voucher send by mail) text update for specific client

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1401]
## Context/goal: 
Voucher is being send after user activates it or by user reuquest.

Change text: 
Beste heer/mevrouw,

U heeft zich aangemeld voor de meedoen-regeling 2020.​  

Uw aanvraag is goedgekeurd. Hierbij ontvangt u uw persoonlijke Meedoen-regeling voucher. 

De voucher heeft een waarde van € 150,00.
Onderstaande voucher laat u bij de organisatie van uw keuze zien. 
De organisatie scant deze code en de betaling gebeurt automatisch.
Let op ! Als u een activiteit afneemt met een geldbedrag lager dan € 150,00, blijft het restantbedrag op de voucher staan.  Bewaar deze voucher dus goed.
Veel plezier met de door u gekozen activiteit.

**Comment by maxvisser** [comment]
I am not sure if this is an implementation based email and also the context is abit different then what currently the text is of the mail.
