### ISSUE TITLE
Make KVK not unique for organization who have a valid office number

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1406]
## Context/goal: 
Show bigass warning: This KVK is taken. Have you already signed up? try to log in. But there is a way to continue anyway if you really want to.

Condition:
Should enter office number. It should be unique. We will store it with the office.

**Comment by maxvisser** [comment]
lets add some nice popup modal and think of how we want to validate office number;

**Comment by maxvisser** [comment]
Discussed it with gerben allowing KVK not be unique is not an option; we should try to only allow unique offices. So a business with only one office should only be able to register once.

**Comment by jamalv** [comment]
Didn't read comments above and already made a modal so will share anyway :)

Figma: https://www.figma.com/file/aXi8c3EX5aHDYg4Xywb22G/Warningmodal?node-id=2%3A35

![image](https://user-images.githubusercontent.com/30194799/73444594-2c251700-4359-11ea-981c-535859ac3a7d.png)

**Comment by jamalv** [comment]
Added a second wireframe to ask for officenumber:

![image](https://user-images.githubusercontent.com/30194799/73445107-47dced00-435a-11ea-8b92-b8ff74dfb4d6.png)

**Comment by jamalv** [comment]
The first modal can open the second one. We could check if the number is unique. A single business with only one "office" would not have a vestigingsnummer I think.

**Comment by maxvisser** [comment]
thats not the case; we should ask for all organization their unique office number; maybe we can fetch it from kvk api and dont show it.

**Comment by jamalv** [comment]
## Proposal:

We first show the first modal: 

![image](https://user-images.githubusercontent.com/30194799/73445360-cb96d980-435a-11ea-947c-295eaa2e158b.png)

If people click "annuleer" we redirect them out of the signup flow (for example to forus.io) so people don't have an option to continue anyway.

If people do continue, we ask for a "vestigingsnummer" which has to be unique. So a company with one "vestigingsnummer" will not have one probably.

**Comment by maxvisser** [comment]
made a workaround for gerben; this is less urgent if workaround is working https://github.com/teamforus/implementation/issues/295
