### ISSUE TITLE
Error / validation messages backend

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#141]

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/47237429-56122e80-d3df-11e8-82dc-02562feb9cd9.png)

![image](https://user-images.githubusercontent.com/10818702/47237525-a6898c00-d3df-11e8-8d6d-fdb495515f06.png)

**Comment by maxvisser** [comment]
@gerben added https://github.com/teamforus/forus-backend/tree/develop/resources/lang/nl this folder, how to switch the backend from en to nl

**Comment by maxvisser** [comment]
Found it! 
![image](https://user-images.githubusercontent.com/10818702/47237941-d1281480-d3e0-11e8-9490-4df36ce7345d.png)
