### ISSUE TITLE
Sponsor dashboard: [Question] Generating individual activation code by a UI-control?

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1417]
# Is your feature request related to a problem? Please describe
One of our stakeholders isn't really skill-full with Excel or other text/data editors.
The process of creating activation codes is already really painfull for them because they have like 3 organisations with a lot of funds. To can't really use the systems the way they want to, so we offer them workarounds.

## Problem
1. Requests the funds. (nothing to do with the system)
2. The employee adjust their CSV template with client number and amount of kids.
3. The CSV file is not accepted. 

The CSV is not accepted because they made a mistake with entering the data of the CSV file.

### Impact
- Because these employees do not have the skills to adjust the CSV file properly it always results into me generating the activation code.
- To generate the activation codes for these people , they send me highly sensitive personal information.
- I have already explained them multiple times what the problems is. But it just doesnt help.

They requested me to change the way we create individual activation codes

**Describe the solution you'd like**

@aghimpu @dev-rminds 
I am not searching for a solution immediately.

I am just curious if we could easily change the frond end a bit to create individual activation codes by using a UI-control instead of uploading a CSV file while:
- We can still grant multiple funds by using one activation code.
- Export this data so they can process this information into a letter.

**Describe alternatives you've considered**
- Explaining how they should adjust the CSV file.

**Additional context**
I know the CSV uploader and using activation codes will be depreciated eventually.
But for this year we will still have multiple municipalities that are using this.

**Comment by maxvisser** [comment]
the csv can contain other record types than only which are set in the criteria; maybe we can help them if we have an example file of what they try to upload?

**Comment by GerbenBosschieter** [comment]
I've already tried. Just asking how feasible this is. Not asking for another work around.

**Comment by maxvisser** [comment]
Could you share such an example. maybe let them make a csv with dummy data so we can use it to reproduce the issue ourselves?

**Comment by GerbenBosschieter** [comment]
Not related to my question

**Comment by maxvisser** [comment]
well as you are adding records in a csv what we could do is make a popup modal which contains:

[fund key: BSN] [input field] 
[fund criteria 1: kindpakket_eligible]  [input field]
[+ add extra record]

[Submit: Create prevalidation]

a post api endpoint should be added to create a prevalidation token with just a json post request.

**Comment by GerbenBosschieter** [comment]
# Request after review:

## Add single prevalidation
**Must have**:
- Add the option to delete records to give the user the option to correct human mistakes (See image below)
![deleterecord](https://user-images.githubusercontent.com/38419514/75241105-cac05e80-57c5-11ea-9db8-347c52e2d734.jpg)

- Add a confirmation modal after clicking **Confirm** to give the user an option to correct their input. (see image below) 
This modal should contain the following:
1. Summary of the created records with the entered data
2. Button to confirm -> go to activation code 
3. Button to edit input -> go back to add single prevalidation record
4. Text with explanation:
**English:**
Title: "Verify data" 
Description: "Pleas check if you have entered the correct data before submitting"
**Dutch**
Title: "Gegevens controleren" 
Description: "Controleer of u de juiste gegevens hebt ingevoerd voordat u deze bevestigd."

Reasons to confirm before submitting:
1. Entering a word while a number is expected.
2. To check if entered BSN number is correct.

<img width="686" alt="Screen Shot 2020-02-25 at 11 53 43" src="https://user-images.githubusercontent.com/38419514/75241031-a5cbeb80-57c5-11ea-915a-999b11e8a86d.png">


**Could have**
- Also show BSN number after the modal thats shows activation code.
<img width="682" alt="Screen Shot 2020-02-25 at 12 11 30" src="https://user-images.githubusercontent.com/38419514/75242265-09efaf00-57c8-11ea-94d1-da782683ec26.png">
