### ISSUE TITLE
Change the button "open me app" on mobile. (Frontend)

### ISSUE THREAD

**Issue by jknnr** [teamforus/forus#1426]
When login with the me app, you receive the letter to your email, when it redirects back to the app you go to this page:
![2020-02-28 14 53 52](https://user-images.githubusercontent.com/32199937/75546679-272bb400-5a3a-11ea-9c68-21883fb4b1aa.jpg)

**So the task is to change this button to the new one:**

https://www.figma.com/file/sDB8jUy4fM4oIdlPTL90nf/Log-me-in?node-id=347%3A211

**Comment by maxvisser** [comment]
on safari on mobile the button is not completely centered
