### ISSUE TITLE
Connect real transactions in the provider and sponsor dashboard

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#143]

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/172

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/46972115-12a58080-d0be-11e8-9712-ad5e2e09e58b.png)

**Comment by maxvisser** [comment]
Quick fix: disable with config file and reimplement later

**Comment by danrminds** [comment]
done
