### ISSUE TITLE
Validator dashboard. Show funds they are added as validators. 

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1430]
## Context/goal: 
We will need to display in the validator dashboard - a page with a list of Funds the validator is added to as trusted. 

He will see the list of cards, (1 card per fund)
Each card will contain:
- Fund image and title
- Organisation of the sponsor
- Status
- List of criterias they are trusted to validate
- Accept each criteria (toggle or buttons)
- Accept / decline all criterias for this fund

![IMG_8470 copy](https://user-images.githubusercontent.com/33207036/76539118-9cf33f00-6480-11ea-8820-8fbc3da6e8c8.jpg)

**Comment by sashooa** [comment]
Leeftijd is kleiner dan 18
Maandloon is kleinder dan 1200
Uitkering (netto) is gelijk aan 200
Kindgebonden budget is gelijk aan Ja
Gemeente is gelijk aan Westerkwartier
