### ISSUE TITLE
Vouchers page. Search. [Sponsor dashboard]

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1436]
## Context/goal: 
Fix search through the assigned emails of the vouchers

![Screenshot 2020-03-17 at 18 57 20](https://user-images.githubusercontent.com/33207036/76943048-00f18980-68ff-11ea-9a80-2a13e4a3316d.png)
![Screenshot 2020-03-17 at 18 57 27](https://user-images.githubusercontent.com/33207036/76943054-03ec7a00-68ff-11ea-99cc-8a6166767569.png)

And fix the tooltip to display the complete email
![Screenshot 2020-03-18 at 09 59 30](https://user-images.githubusercontent.com/33207036/76943172-36967280-68ff-11ea-90d5-94030586fb81.png)

**Comment by maxvisser** [comment]
done
