### ISSUE TITLE
Email: New fund created

### ISSUE THREAD

**Issue by jknnr** [teamforus/forus#145]
Dutch

Onderwerp: Er is een nieuw fonds toegevoegd

Geachte [ name requester ],

Er is een nieuw fonds aangemaakt. Je voldoet aan de voorwaarden om mee te doen aan [ name fund ]. Ga naar https//:dev.forus.link, log in op de webshop om je aan te melden voor dit fonds.

English

Subject: A new fund is added

Dear [ name requester ],

A new fund has been created. You are eligible to participate in [name fund]. Go to https //: dev.forus.link, log in to the web-shop to sign up for this fund.

Приходит реквестору, когда создается фонд, к ваучеру которого он подходит по критериям.

**Comment by kremlinwarrior** [comment]
{lang}/sender/vouchers/new_fund
