### ISSUE TITLE
Can't create a new profile: Creating a profile will result in an error

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1454]
## Context/goal: 
**Branch** Release/v0.9.2 (backend)

Creating a new profile will 100% of the time result in an error: "E-mailadres already used"
.The error isn't correct. I've tested multiple mailadressen that are certainly not being used. But it Will stil give me an error.

**Console**

<img width="811" alt="Screen Shot 2020-03-29 at 12 18 41" src="https://user-images.githubusercontent.com/38419514/77846949-d1256a00-71b9-11ea-88a9-098f9a2f7ae2.png">

**Comment by maxvisser** [comment]
Seems like it  does create an account and gives back a access token but does not set it to local storage and logs the user in;
