### ISSUE TITLE
Potjswijzer. Choose organisation page. 

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1461]
## Context/goal: 
*explain why this issue was opened*

**Comment by maxvisser** [comment]
Will this be part of the website, webshop or landing pages?

**Comment by jamalv** [comment]
will initially be part of potjeswijzer website:

![image](https://user-images.githubusercontent.com/30194799/78540820-00109100-77f5-11ea-8550-971a12383663.png)

But should later be added to our own website as well: 

![image](https://user-images.githubusercontent.com/30194799/78540909-1d455f80-77f5-11ea-86b4-5e052fea34b1.png)

**Comment by maxvisser** [comment]
for me as a reviewer, i would need a design for each of the webshops (not only potjeswijzer) or no pr should be made to develop as it will not be merged until it is finished for all webshops.
