### ISSUE TITLE
Login mail does not contain  panel_type

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1463]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/78533016-7f4b9800-77e8-11ea-822e-eb33d8a7ec92.png)

I am not sure if it is a configuration issue but on dev we have this issue.

its does return me to the right dashboard.

**Comment by aghimpu** [comment]
@maxvisser, can't it be the database not being configured correctly (url_webshop, url_sponsor, url_provider etc fields in 'implementations' table)? I was able to replicate it just in that case.
