### ISSUE TITLE
Signupflows design: update popup modals

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1464]
## Context/goal: 
*explain why this issue was opened*

**Comment by dev-rminds** [comment]
### Image cropper (uploading organization logo or office photo):

![image](https://user-images.githubusercontent.com/25606248/78545659-cfd0ee80-7804-11ea-84f2-a48358cf10ce.png)
Texts:
- **Verplaats en wijzig grootte**
- U kunt de afbeelding naar uw voorkeur instellen, links ziet u de originele afbeelding en rechts een voorbeeld van hoe het op de webshop eruit komt te zien.
- **Verander afbeelding**
- UPLOAD AFBEELDING
- De afbeelding dient vierkant te zijn met een minimum afmeting van 400x400px.
   Toegestaande formaten: .JPG, .PNG
- ANNULEREN
- BEVESTIGEN

### Confirmation modal (confirm adding new employee):
![image](https://user-images.githubusercontent.com/25606248/78545752-ff7ff680-7804-11ea-9aa0-ff3a6f9ce756.png)
Texts:
- **Bevestig uitnodiging**
- Wil u de medewerker hcn2@rminds.io uitnodigen? Deze medewerker zal hier over een email ontvangen.
- Bevestig
- Annuleer

**Comment by Myshelova** [comment]
I saw a third modal window with dropdown. Can you add this one too? @dev-rminds

**Comment by maxvisser** [comment]
its not part of the signupflow but a modal that popup when an organization is chosen which does not have business type (to convert all organization to start using one)

**Comment by jamalv** [comment]
https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/prototype-signupflows?node-id=953%3A3953
