### ISSUE TITLE
Email: New product added

### ISSUE THREAD

**Issue by jknnr** [teamforus/forus#147]
Dutch:

Onderwerp: [ name product ] is toegevoegd aan de webshop

Er is een nieuw product of dienst toegevoegd aan de webshop door [ name provider ].
Bekijk de webshop om te controleren of [ name product ] voldoet aan de voorwaarden om vanuit het fonds aangeschaft te worden.

English:

Subject: [ name product ] has been added to the web-shop 

A new product or service has been added to the web-shop by [name provider].
View the web-shop to check if [name product] meets the requirements to be purchased from the fund.

Приходит (не знаю кому), чтобы сообщить, что в веб-шопе появился новый товар. 
Полагаю, что может прийти реквестору и как подтверждение самому магазину. Нужно уточнить

**Comment by kremlinwarrior** [comment]
/{lang}/sender/vouchers/new_product_added
