### ISSUE TITLE
Email: new validation request

### ISSUE THREAD

**Issue by jknnr** [teamforus/forus#148]
Dutch:

Onderwerp: Er staat een nieuw verzoek voor je klaar.

Geachte [ name validator ],

Er staat een verzoek voor je klaar om eigenschappen te valideren. Ga naar het validator dashboard om dit verzoek te behandelen.

English:

Subject: There is a new request waiting for you.

Dear [ name validator ]

There is a request for you to validate records. 
Go to the validator dashboard to process this request.

Запрос валидатору на валидацию рекордов.

**Comment by kremlinwarrior** [comment]
/{lang}/sender/validations/new_validation_request
