### ISSUE TITLE
IE: Some of our pages don't work at all on IE

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1484]
## Some of our pages don't work at all on Internet Explorer.

**List**
- https://dev.forus.io
- https://staging.forus.io
- https://forus.io
- https://staging.forus.io/provider/#!/sign-up-v2
- https://staging.forus.io/provider/#!/sign-up

**URL tested:** https://forus.io/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforus.io%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forus.io/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1438x820 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/d4a6e1896b09b1111b7d5d3a1dd4d426fdb645a6/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/d4a6e1896b09b1111b7d5d3a1dd4d426fdb645a6/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforus.io%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forus.io/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1109
