### ISSUE TITLE
Dashboard: Can't acces dashboard after logging in

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1487]
## Main asssignee: @

Tested on: https://staging.forus.io/provider/organizations
**Branch**: release/v0.10.0

## Context/goal: 
I have a profile with multiple organisations.
Tried to sign up for our dogfooding competition, I couldn't acces the dashboards any more after creating my organization on a profile that already had other organisations .

<img width="1313" alt="Screen Shot 2020-04-10 at 14 22 20" src="https://user-images.githubusercontent.com/38419514/78990622-2d33ab00-7b37-11ea-8e47-43261baad22d.png">
<img width="855" alt="Screen Shot 2020-04-10 at 14 27 09" src="https://user-images.githubusercontent.com/38419514/78990692-64a25780-7b37-11ea-90d5-df8dade1f1f0.png">

**Comment by maxvisser** [comment]
could this be a caching issue? As the logo should also be replaced with the organization switcher.

**Comment by GerbenBosschieter** [comment]
yes, think so
