### ISSUE TITLE
Email: Provider applied

### ISSUE THREAD

**Issue by jknnr** [teamforus/forus#149]
Dutch:

Onderwerp: [ provider name ] wil zich aanmelden voor [ name fund ]

Geachte [ name sponsor ],

Er is een aanmelding binnengekomen van [ name provider ] om deel te nemen aan [ fund name ]. Controleer of deze leverancier voldoet aan uw voorwaarden om deel te nemen. Meld je aan op het sponsor dashboard om deze aanvraag te behandelen.

English: 

Subject: [ name provider ] wants to register for [ name fund ]

Dear [ name sponsor ],

A registration has been received from [ name provider ] to participate in [ name fund ]. Check whether this provider meets your conditions to participate. Log in to the sponsor dashboard to process this registration.

Приходит спонсору (создателю фонда), если магазин сделал заявку на внедрения ваучера данного фонда

**Comment by kremlinwarrior** [comment]
/{lang}/sender/vouchers/provider_applied

**Comment by maxvisser** [comment]
Tested it works
