### ISSUE TITLE
PDF viewer on validator dashboard doesn't work on safari

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1493]
## Prerequisites

1. Safari on macos
2. Upload a document while applying trough application form

## Description

When viewing the pdf, it doesn't show on safari

**Reproduces how often:** 100%

**Comment by SjoerdHilhorst** [comment]
I cant find the pdf viewer, can you provide a screenshot

**Comment by jamalv** [comment]
<img width="1792" alt="Screenshot 2020-04-17 at 11 10 10" src="https://user-images.githubusercontent.com/30194799/79552985-1abbf300-809c-11ea-96b1-e23099ab7e3c.png">

Yes, is op het validator dashboard: https://drive.google.com/file/d/1cwqId0_zF5em4V0aoTUR2K_8i8N5kuQq/view

Dit is op de dev omgeving op het account; dev+leergeld@forus.io

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1126
