### ISSUE TITLE
Align figma deployement with production

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1499]
## Context/goal: 
To share the platform with stakeholders

- [ ] Check the current status
- [ ] Work with dan / alex to merge the new screens into the library
- [ ] Add screens from library to deployement and update texts

**Comment by maxvisser** [comment]
@danrminds where do you think my help is most needed?

**Comment by maxvisser** [comment]
@jamalv I think with Groningen using a test environment this is less important now? I also labeled this scope to big as I think this should be split up

**Comment by jamalv** [comment]
I'm now leaning more towards the direction of creating a good design system, and less towards having figma be perfectly aligned with production. This free e-book influenced me a lot: https://atomicdesign.bradfrost.com/table-of-contents/

This makes this issue no longer relevant.
