### ISSUE TITLE
Email: Provider approved

### ISSUE THREAD

**Issue by jknnr** [teamforus/forus#150]
Dutch:

Onderwerp: Je aanmelding voor [ name fund ]

Je aanmelding is geaccepteerd!

Geachte [ name provider ],
Je hebt op [ date ] een aanmelding gedaan voor [ name fund ].
[ name sponsor ] heeft je verzoek geaccepteerd.

Dit betekent dat je vanaf nu je producten en/of diensten kan leveren aan klanten die recht hebben op [ name fund ]

English:

Subject: your application for [ name fund ]

Your application is accepted!

Dear [ name provider ]
On [ date of application ] you’ve signed up for [ name fund ].
[ name sponsor ] has accepted your application.

From now on you can sell your products / services to customers who are eligible for [ name fund ]

Приходит магазину, когда его заявка на внедрение ваучера обработана и ответ - да

**Comment by maxvisser** [comment]
Is this one added yasha? If so, you may close

**Comment by jknnr** [comment]
done
