### ISSUE TITLE
Whitelabel master: add products pages

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1508]
@jamalv commented on [Mon Feb 10 2020](https://github.com/teamforus/development/issues/389)

- [x] https://winterswijk.forus.io/products 
- [x] https://winterswijk.forus.io/products?display_type=grid
- [ ] https://winterswijk.forus.io/products/354

**Comment by jamalv** [comment]
@danrminds could you pick this one up with @sashooa? since @Myshelova is now mainly focussed on components/guides and reviews, and less on the templates
