### ISSUE TITLE
Email: Validator added

### ISSUE THREAD

**Issue by jknnr** [teamforus/forus#151]
Dutch:

Onderwerp: [ name sponsor ] heeft je toegevoegd als validator

Geachte [ name validator ],

[ name sponsor ] heeft je toegevoegd als validator.
Dit betekent dat je vanaf nu persoonlijke eigenschappen kan valideren.
Indien je vooraf ingestelde eigenschappen wil toevoegen kan je gebruik maken van de .CSV uploader.

English:

Subject: [ name sponsor ] has assigned you as a validator

Dear [ name validator ],

[ name sponsor ] has assigned you as a validator.
From now on you can validate personal records. If you want to add a batch with pre validated records, you can use the CSV uploader.

Приходит валидатору, когда спонсор назначил его валидатором

**Comment by kremlinwarrior** [comment]
/{lang}/sender/sponsors/you_added_as_validator
