### ISSUE TITLE
Create list of all required action a provider / sponsor.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1510]
## Context/goal: 
We want to give more context on the dashboard what the minimum actions are a provider or sponsor need to preform before they can use the patform.

- [ ] Create list of all required action a provider or sponsor should preform before they can use the platform.

**Comment by maxvisser** [comment]
@GerbenBosschieter I will move this to a different repo.

**Comment by maxvisser** [comment]
Issue moved to [teamforus/general #839](https://github.com/teamforus/general/issues/839) via [**ZenHub**](https://www.zenhub.com/)
