### ISSUE TITLE
Sponsor dashboard: 500 sever error when inviting providers

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1514]
## Context/goal: 
**Tested on Branch**(you don't have to start from this branch): release v0.10.0

Inviting a group of providers will result into a 500 error.
I have seen it working locally.

<img width="1422" alt="Screen Shot 2020-04-20 at 15 27 27" src="https://user-images.githubusercontent.com/38419514/79756856-911a5880-831b-11ea-9d58-f41507882bb0.png">

**Comment by maxvisser** [comment]
```
 dev.ERROR: Call to a member function urlProviderDashboard() on null {"userId":"0xe536eee5c6fdb82828103925108a4fd5affa54f0","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function urlProviderDashboard() on null at /var/app/current/app/Models/FundProviderInvitation.php:132)
```
