### ISSUE TITLE
Hide discount if 0%

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1515]
Context/goal: 
Right now if there is no discount on an offer; we show 0% discount. This is weird. If there is no discount we should hide the discount card. This should be done on the cards and on the list, and generally everywhere we show the discount formulla.

Right now:
<img width="244" alt="Screenshot 2020-04-21 at 10 25 10" src="https://user-images.githubusercontent.com/30194799/79843357-7519c400-83ba-11ea-9b01-9edb5cd16a4f.png">

Should be:
<img width="243" alt="Screenshot 2020-04-21 at 10 25 31" src="https://user-images.githubusercontent.com/30194799/79861269-6cce8280-83d4-11ea-8998-2380a778969f.png">

**Note:** if there is a discount we should off course still show it.

**Comment by maxvisser** [comment]
Both images are the same

**Comment by maxvisser** [comment]
you only want to hide in on card view or everywhere? could you list all places
