### ISSUE TITLE
Change statistics about providers on sponsor dashboard

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1517]
## Context/goal: 
Sponsor dashboard: overview of funds wil wil give you some statistics.
The title or the number itself is incorrect below "Aanbieders (providers)".
The column "Aanbieders(providers)" shows all the provider employees instead of number of providers.

This is really confusing and misleading.

![Screen Shot 2020-04-21 at 11 49 22](https://user-images.githubusercontent.com/38419514/79852949-aea4fc00-83c7-11ea-9454-0588d3dcc87c.jpg)

### Task
- Add provider count to statistics (as main).
- Display provider employees next to it in parentheses. 
* Dutch word for employees is Medewerkers.

I have added a shame label because we already knew this and one of our sponsors really thinks this number represents the number of providers. In reality it's much lower.

**Comment by maxvisser** [comment]
Well all resemble user counts we could add another label 'Aan unieke gebruikers verbonden aan dit fonds:'

**Comment by maxvisser** [comment]
Aanbieder accounts

**Comment by maxvisser** [comment]
Other option is see is add organization count as well!

**Comment by maxvisser** [comment]
Aanbieders
180 (483 accounts)

**Comment by GerbenBosschieter** [comment]
I like the last one. It's te best
