### ISSUE TITLE
Hover icon financial dashboard is wrong

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1522]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/80200341-ca580e80-8622-11ea-9a6b-a73d08ddc848.png)

should replace with
[Financial dashboard (Active).zip](https://github.com/teamforus/forus/files/4528098/Financial.dashboard.Active.zip)

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1129
