### ISSUE TITLE
Change screenshots Log me in

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1523]
## Context/goal: 
 - [x] change screenshots on Authorize device modal webshop and platform
 - [x] change screenshots on old signupflow
 - [x] change texts
	- button to 'Koppel de app'
    - Stap 1 & stap 2 headers
    - description of step below header
    - Stap 3: Vul de code in
    - Stap 3 updated description

#### old
![image](https://user-images.githubusercontent.com/10818702/80200635-38043a80-8623-11ea-90c3-eeecba834e9f.png)

#### new
![image](https://user-images.githubusercontent.com/10818702/80200646-3cc8ee80-8623-11ea-9c0f-8c7067f22162.png)

## Figma prototype:
https://www.figma.com/file/sDB8jUy4fM4oIdlPTL90nf/prototype-Log-me-in?node-id=50%3A19

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1130
