### ISSUE TITLE
Financial dashboard: Provider statistics should also contain year and previous/next buttons

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1526]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/80202003-45222900-8625-11ea-84de-b6b0a86c9861.png)

should be like this: 
![image](https://user-images.githubusercontent.com/10818702/80202085-6256f780-8625-11ea-88d7-258787958008.png)

**Comment by SjoerdHilhorst** [comment]
i think they do, but you're on the "alles" section.

Or do you want to change the "alles" section to a year section?

**Comment by maxvisser** [comment]
'alles' should be year with previous and next buttons yes :)

**Comment by SjoerdHilhorst** [comment]
Response of fund statistics:
{"dates":[{"key":"Kwartaal 1","value":0 ...}

Response provider statistics 
{"dates":[{"key":"2020-04-26","value":47 ...}

unless the backend gets updated i dont think there is a completely easy way to implement this?
or i am missing something

**Comment by maxvisser** [comment]
Hmm seems more difficult indeed.
