### ISSUE TITLE
Access expired when open me link on desktop (on production and staging)

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1536]
## Prerequisites

1. Me app connected to production or staging
2. Existing account

## Description

Opening the email link from the me app results in a link expired error. It's a nice error, but it doesnt suit the situation :(

<details><summary>View error</summary>

<img width="815" alt="Screenshot 2020-05-01 at 18 14 06" src="https://user-images.githubusercontent.com/30194799/80820840-ef76ef00-8bd7-11ea-824f-42fc0080851f.png">

</details>

## Steps to Reproduce (bug report)

1. Open the me app
2. Fill your email adres
3. Open the link on desktop

**Expected behavior:** I expect to get the screen where I can take an action to log in (authorize)

**Actual behavior:** I get the error

**Reproduces how often:** Every time

## Additional Information (optional)
Tested on staging and production, not on dev.

I don't know the status of the new authorize device method on desktop, but this error is now incorrect (it says you should send another email but then you get the same result)

**Comment by maxvisser** [comment]
Reproduced it aswell.
