### ISSUE TITLE
Mobile: Hamburger menu doesn't work

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/forus#1551]
## Description

[staging.forus.io](staging.forus.io) and [forus.io](forus.io)
Hamburger menu button in top navbar doesn't work on mobile.

**Expected behavior:** 
Menu opens

**Actual behavior:** 
Nothing happens when pressed

**Reproduces how often:** 
Always

**Comment by GerbenBosschieter** [comment]
Nothing has changed related to the navbar. It still works on production and on de.forus.io.

@maxvisser coudl this be minify issue?

**Comment by maxvisser** [comment]
Yes looks like production bundle.min.js is not minified.

**Comment by GerbenBosschieter** [comment]
@maxvisser This issue is now a bug on production.
How can we solve this bug.
