### ISSUE TITLE
E-mail: Dutch translation missing (expiration date)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1552]
# E-mail: Change date format to dutch

## Context/goal: 
The e-mail that people receive after activation their voucher uses english day and month:

## Task
- Use dutch format for day and month
- Use lowercase letters for the day and month (thats normal in dutch)

<img width="549" alt="Screen Shot 2020-05-12 at 12 23 27" src="https://user-images.githubusercontent.com/38419514/81673159-7a16e400-944b-11ea-9b42-01450bce1eaa.png">

**Comment by GerbenBosschieter** [comment]
maandag, 31 mei 2021

**Comment by maxvisser** [comment]
dev is only english; should not be the case on production.

**Comment by GerbenBosschieter** [comment]
@maxvisser I can't reproduce on production. Can't send my expired voucher to myself ;)
But I did find a forwarded mail with a voucher from one of our  foundation supervisors (toezichthouders)
It's a bit outdated maybe. But it does have the same bug.

<img width="604" alt="Screen Shot 2020-06-18 at 10 37 19" src="https://user-images.githubusercontent.com/38419514/85014349-62c3c880-b166-11ea-8dce-e39656d793b7.png">

**Comment by jamalv** [comment]
only on dev
