### ISSUE TITLE
Template design for all implementations (new homepage)

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1554]
## Context/goal: 
https://www.figma.com/file/u8cUqcmaa4Ds8yeeg9UOjP/Menu-by-RMinds?node-id=16%3A326&viewport=-3831%2C-1111%2C0.5

These implementations:
https://demo.forus.io/nijmegen/#!/
https://demo.forus.io/westerkwartier/#!/
https://demo.forus.io/noordoostpolder/#!/
https://demo.forus.io/oostgelre/#!/
https://demo.forus.io/berkelland/#!/
https://demo.forus.io/winterswijk/#!/

**Comment by danrminds** [comment]
Work on comments
https://www.figma.com/file/sEenqvErGSaTEfwqhsGfmQ/%F0%9F%A7%AAWebshop-improvements?node-id=93%3A986&viewport=-2592%2C-1880%2C0.5

**Comment by maxvisser** [comment]
@danrminds whats the status of this one?

**Comment by danrminds** [comment]
Will close for now until we get back to it
