### ISSUE TITLE
Amount of Kindpakket voucher = fixed

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#156]
At this moment it doesn't matter how many children people have, if they use the activation-code it will give them a voucher of 300 euro. 

-----------------------------------

Add a formula that calculates the 300 x (children count).

Thought this was already in the backlog, couldn't find it. So if this is a double issue, just close it.

**Comment by maxvisser** [comment]
This one should be fixed on develop if you use record type key children_nth
