### ISSUE TITLE
Signup-v2 Translation: No matching feedback after clicking submit button

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1562]
## Context/goal: 
There is no matching explanation giving after entering your phone number and clicking sumbit to receive the sms.

**Current text:** "Heeft u geen link ontvangen? Ga dan op uw telefoon naar www.forus.io/DL".
**Proposed text:** "We hebben u een sms gestuurd! Heeft u geen link ontvangen? Ga dan op uw telefoon naar www.forus.io/DL"

@maxvisser aggreed?

*explain why this issue was opened*
<img width="660" alt="Screen Shot 2020-05-26 at 16 56 13" src="https://user-images.githubusercontent.com/38419514/82993916-a14fe280-a001-11ea-86d4-8ace0f7890eb.png">

**Comment by maxvisser** [comment]
gestuurd*
