### ISSUE TITLE
Sponsor dashboard: Display dismiss button only if all options are rejected

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1565]
## Context/goal: 
A sponsor can process an application of a provider. They can accept them for budget, all products or specific products.
The dismiss button (verberg) will appear if budget and all products are rejected but a specific product is accepted.

**Example**
<img width="811" alt="Screen Shot 2020-05-28 at 09 35 38" src="https://user-images.githubusercontent.com/38419514/83112818-ff92c900-a0c6-11ea-935d-6999efca8053.png">

If a sponsor would dismiss the application while a specific product is accepted it wil result in a weird overview for the provider.

**Example**
<img width="836" alt="Screen Shot 2020-05-28 at 09 36 11" src="https://user-images.githubusercontent.com/38419514/83112959-3d8fed00-a0c7-11ea-8549-32cfa2b6a6ff.png">

## Task
1. Would be nice if we only could display the dismiss button if all options are turned off.
2. Change the button text from: "Verberg" to "Weigeren en verberg"

**Comment by maxvisser** [comment]
If easier we could also always show the button but just deny the provider for everything when the button is pressed

**Comment by GerbenBosschieter** [comment]
@maxvisser even better
