### ISSUE TITLE
Signup-v2: Text improvement; things you need

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1567]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/83156608-e7409f80-a102-11ea-84f5-2885a1560c50.png)

Should be 

![image](https://user-images.githubusercontent.com/10818702/83156556-dabc4700-a102-11ea-8818-0f40f7af1c4e.png)

## Task

- [ ] change text for this step
- [ ] "app" can link to https://forus.io/me

note: tooltip can be skipped

**Comment by GerbenBosschieter** [comment]
@maxvisser Your image displays more than only textual changes. Just to bes sure, it's only about the textual changes. So the blue tooltip with: Waarom heb ik de Me-app nodig? should not be added right?

**Comment by maxvisser** [comment]
Yes needs a new screenshot

**Comment by maxvisser** [comment]
would also be nice to make it a clickable link to helpcenter @GerbenBosschieter maybe even better then a tooltip with alot of text

**Comment by GerbenBosschieter** [comment]
would be nice yea ;)

**Comment by maxvisser** [comment]
should be deployed on dev already;
