### ISSUE TITLE
Signup-v2: Textual change to close the Signup flow.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1568]
## Context/goal: 
We use the word: "Terug" to close the signup flow.

This can be really confusing, because it wil give an impression you got to the last page but you close the signup flow. This is not what you expect.

### Options
- Display a modal with a warning that they are leaving the signup flow.
- Change "**Terug**" to **"Verlaat het formulier"**

### Task
- Change "**Terug**" to **"Verlaat het formulier"**

**Example**
![backkkkk](https://user-images.githubusercontent.com/38419514/83169712-b9178b80-a113-11ea-8bc2-19a3d00515c0.jpg)

**Comment by maxvisser** [comment]
Just to give some context 'terug' means 'go back' which suggest you go back to the step before
