### ISSUE TITLE
Landing pages (general): Logo should be smaller

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1569]
## Context/goal: 
Some different height and padding does the job

**From**
<img width="1154" alt="Screen Shot 2020-05-29 at 10 59 30" src="https://user-images.githubusercontent.com/38419514/83241797-a5176c80-a19b-11ea-8959-df513daa5a07.png">

**To**
<img width="1643" alt="Screen Shot 2020-05-29 at 10 53 23" src="https://user-images.githubusercontent.com/38419514/83241821-ae083e00-a19b-11ea-9c87-898cbe1a9fea.png">

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1169

**Comment by GerbenBosschieter** [comment]
already released
