### ISSUE TITLE
From jquery navbar scroll and hide to angularjs

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1571]
## Context/goal: 
You created to angularjs plugin to hide the navbar when scrolling down.
https://github.com/teamforus/forus-frontend/pull/1156/commits/78eac239493a62d241c9406c08eef238ce28b338

I really like it and would like to see the same change on the website.
The website is currently using jquery to get this result.

### Task
- use angularjs instead of jquery to hide on scroll

**Comment by SjoerdHilhorst** [comment]
the website as in [forus.io](forus.io)? or every webshop like forus.nijmegen.io, forus.winterswijk.io, etc

**Comment by GerbenBosschieter** [comment]
no forus.io. The other webshops use the same JS so thats shouldn't be a problem

**Comment by SjoerdHilhorst** [comment]
while every webshop uses  [TopNavBarDirective](https://github.com/teamforus/forus-frontend/blob/25714ab49e819c5ff35de3dac74aa5d7be45e4fc/src/sources/forus-webshop/js/angular-1/directives/TopNavbarDirective.js). the [navbar](https://github.com/teamforus/forus-frontend/blob/7ade8d1446580aadd07a6d7455ce57f902df115f/src/sources/forus-platform/pug/tpl/directives/website/navbar.pug) from the general website does not, to my understanding, are you sure they use the same javascript?

**Comment by GerbenBosschieter** [comment]
@SjoerdHilhorst The are not using the same javacript. The website navbar shouldn't use the same Directive as the webshops. But it would be nice for the navbar of the website to have a similar Directive.
