### ISSUE TITLE
on identity_restore check if access token in local storage is still valid

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1572]
## Context/goal: 
I clicked on a used link in the mail. My account was still signed in but I got the popup. I think it would be nice to not show the popup if users access token is still valid.

![image](https://user-images.githubusercontent.com/10818702/83600364-b4693200-a56e-11ea-8d00-398cb0ce7ad7.png)

**Comment by GerbenBosschieter** [comment]
I like this one!
