### ISSUE TITLE
Single prevalidations: can't close record after chosen to add one.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1576]
## Context/goal: 
If a sponsor/validator clicks on add a record by mistake he can't cancel it.
He can only cancel it if he first submits the record itself.

Would be nice to make it possible to cancel earlier.

**Example where you cant cancel**
<img width="550" alt="Screen Shot 2020-06-05 at 10 08 23" src="https://user-images.githubusercontent.com/38419514/83852952-d8ff0e80-a714-11ea-95c4-224adc85c42c.png">

**Example where you can cancel, would be nice to add the close option to image one.**
<img width="493" alt="Screen Shot 2020-06-05 at 10 13 04" src="https://user-images.githubusercontent.com/38419514/83853379-807c4100-a715-11ea-8745-65b3bc08d8f4.png">

**Comment by maxvisser** [comment]
Optional fields should be able to removable.

**Comment by maxvisser** [comment]
Discussed this issue; All required fields are currently not deletable (as these are criteria for the fund selected)
