### ISSUE TITLE
Textual change: Kies voucher (choose voucher)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1577]
## Context/goal: 
If you have multiple vouchers and want to buy a product from a provider that is accepted for multiple funds you can choose which voucher you would like to use to do the payment.
The text you get is not really personal. 

**The current is:** "Kies voucher" (choose voucher)
**New text:** "Kies de voucher waarmee u de aanbieding wil reserveren"

<img width="1397" alt="Screen Shot 2020-06-05 at 10 24 34" src="https://user-images.githubusercontent.com/38419514/83854447-00ef7180-a717-11ea-8482-bcffc8107b9f.png">

**Comment by maxvisser** [comment]
I have not seen this page for a while; I see there is aswell last transaction and transaction amount on the card; which was removed on the voucher list haha :)

**Comment by SjoerdHilhorst** [comment]
![image](https://user-images.githubusercontent.com/48722300/84018573-75791900-a980-11ea-91e7-1fde3056643e.png)

perhaps also a bit smaller font?

**Comment by GerbenBosschieter** [comment]
And don't forget the LIDWOORD ;)

Kies DE voucher

**Comment by GerbenBosschieter** [comment]
I understand why you think that the font is to big. 
I would leave the font-size for what it is for now. font-sizes is being used on different places for different purposes. 

Besides the fact that we maybe should step up our font handling game. 
For now just leave it so that it stays aligned with the rest.

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1195
