### ISSUE TITLE
Provider dashboard: display how many offers are still available to buy on detail page (reserve)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1579]
## Context/goal: 
The provider can't see how many offer are still available if they click the offer itself.
It is displayed on the card of the offer itself, but would be nice to also add it to de details card. The other data about reservations and how many products are sold is also displayed at this card.

### Task
- Add the available offers to the product details card. It should also stay on the product card itself(see image 1)
**English**: available offers
**Dutch**: Resterend aanbod

- Add the border lines between the data (nice to have, looks a bit cleaner) (see image2)

**Image 1**
![image1](https://user-images.githubusercontent.com/38419514/83889561-960c5d80-a74b-11ea-9448-6d9e23eed662.jpg)

**Image2**
<img width="677" alt="Screen Shot 2020-06-05 at 16 30 32" src="https://user-images.githubusercontent.com/38419514/83890313-e7b4e800-a74b-11ea-9f69-920fa9e0a439.png">

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1175
