### ISSUE TITLE
Confirmation modal after login: Title is paraghraph

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1580]
## Context/goal: 
self explanatory (I assume so)

## Task
- Change style of the title to a title again

**From:**
<img width="528" alt="Screen Shot 2020-06-05 at 11 24 55" src="https://user-images.githubusercontent.com/38419514/83891012-d7e9d380-a74c-11ea-9ab9-8fef3a07bafc.png">

**To**
<img width="1162" alt="Screen Shot 2020-06-05 at 16 52 52" src="https://user-images.githubusercontent.com/38419514/83891324-43cc3c00-a74d-11ea-9205-cd4c26bd8a93.png">

**Comment by SjoerdHilhorst** [comment]
on which website? can't seem to reproduce it

**Comment by GerbenBosschieter** [comment]
- Landing pages sponsor and provider (checked most of them not all, assumption it's on al landing pages. So in the common file. a css selector missing or something)
