### ISSUE TITLE
Sign-up v2: Verify e-mailadress mail is the same as verify e-mail after activation

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1582]
Sign-up v2: Verify e-mailadress mail is the same as verify e-mail after activation

## Task
- [ ] Create new mail for verifying mail by sign up flow

or

- [ ] Make verify mail generic so it fits different user  flow

**URL tested:** http://asdasd.nl/email/tester577/26235157

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2Fasdasd.nl%2Femail%2Ftester577%2F26235157&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://asdasd.nl/email/tester577/26235157&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1904x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/79ddc57fb1f2d40934120b37d156efd78919b9f0/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/79ddc57fb1f2d40934120b37d156efd78919b9f0/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2Fasdasd.nl%2Femail%2Ftester577%2F26235157&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://asdasd.nl/email/tester577/26235157&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
- needs a new text

**Comment by GerbenBosschieter** [comment]
@maxvisser it depends. From what I understood from the refinement we wanted to use the same mail for all verify email flows.
If this is the case we should also reconsider the user flow of activating a voucher by sing a activation code.

Otherwise we are just moving the issue to a new user flow.

**Comment by maxvisser** [comment]
yes so the second option you proposed seems the more scalable one right?

**Comment by maxvisser** [comment]
Superseded by https://github.com/teamforus/forus/issues/1620
