### ISSUE TITLE
Sign-up v2: Login with ME from desktop (connect/koppelcode) 

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1583]
The order of the steps to follow is a bit weird. The first step is on bottom right corner. While you expect it on the top left just like "Vul koppelcode in".

Proposal:
- add the folowing bullet points (steps)
    - 1.  Open de Me-app en druk op *Koppelen*
    - 2. Vul de koppelcode in
    - 3. Druk op *koppelen*

**URL tested:** https://dev.api.forus.io/api/v1/identity/proxy/confirmation/redirect/7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22?client_type=me_app-ios&implementation_key=general&is_mobile=1

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.api.forus.io%2Fapi%2Fv1%2Fidentity%2Fproxy%2Fconfirmation%2Fredirect%2F7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22%3Fclient_type%3Dme_app-ios%26implementation_key%3Dgeneral%26is_mobile%3D1&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.api.forus.io/api/v1/identity/proxy/confirmation/redirect/7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22?client_type=me_app-ios&implementation_key=general&is_mobile=1&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1904x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/a579a6df00d6fda7f8003319abbaf867fee22a17/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/a579a6df00d6fda7f8003319abbaf867fee22a17/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.api.forus.io%2Fapi%2Fv1%2Fidentity%2Fproxy%2Fconfirmation%2Fredirect%2F7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22%3Fclient_type%3Dme_app-ios%26implementation_key%3Dgeneral%26is_mobile%3D1&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.api.forus.io/api/v1/identity/proxy/confirmation/redirect/7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22?client_type=me_app-ios&implementation_key=general&is_mobile=1&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
I think figma should be updated for this page aswell. I think its a good suggestion @jamalv

**Comment by jamalv** [comment]
Yea, good suggestion. Maybe do it like you did with the provider screen:
1. Kies in de app voor Koppelen
2. Vul de koppelcode in

Figma: https://www.figma.com/file/VxSHozMsxo563vbKWK4aLZ/Connect-me-switch-order?node-id=1%3A2
