### ISSUE TITLE
Sign-up v2: Add your company logo is almost a hidden feature because of the design

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1587]
It's really unclear that organizations can upload their company logo. IT doesn't out and if you don't you know you will probably skip it. 

We should rethink this design. No solutions yet.

**URL tested:** https://dev.forus.io/provider/#!/sign-up-v2

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1904x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/4623355b38dab4540c2373c44f5ef283cdad60eb/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/4623355b38dab4540c2373c44f5ef283cdad60eb/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
a clear button would help. Like UPLOAD below  the placeholder image

**Comment by danrminds** [comment]
Created another task for the implementation
