### ISSUE TITLE
Sign-up v2: Hide breaks because tit's useless

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1588]
We should hide the option to add breaks. The webshop and the dashboards don't do anything with breaks. As long this is the case we should hide it.

**URL tested:** https://dev.forus.io/provider/#!/sign-up-v2

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1904x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/cbd430879655fbb96ea6b577e8fcd96009dd423d/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/cbd430879655fbb96ea6b577e8fcd96009dd423d/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by danrminds** [comment]
I think @aghimpu implemented the breaks to be shown on the Webshop.

**Comment by maxvisser** [comment]
Yes these are added already on dev.

**Comment by maxvisser** [comment]
Also the title is hilarious. Tits are never useless gerben :joy:

**Comment by GerbenBosschieter** [comment]
@maxvisser you are right max.
Id it's already on the webshop on dev than it's nice. 
@danrminds Is it also added to the dashboard.
Cause adding your break times but not able to change them afterwards is still a reason for e to not show at all.

**Comment by maxvisser** [comment]
You can also edit them on the dashboard on dev
