### ISSUE TITLE
Automatic selection on downpress in organisation creation

### ISSUE THREAD

**Issue by martijndoornik** [teamforus/forus#159]
## Prerequisites

1. Go to Create organisation;
2. Click on "Telefoonnummer";
3. Press tab to continue to select the next input ("Product categorieën");
4. Press down (usually to open dropdown), and it automatically selects a catagory.

**Expected behavior:** [What you expect to happen]

To open the dropdown, and press down. Scroll through through them and press space to select of deselect the category

**Actual behavior:** [What actually happens]

Pressing down automatically selects the first unselected category

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

**Comment by danrminds** [comment]
Checked it out. This is the default behaviour of dropdowns. After TAB to the dropdown - you have to press enter to open it and then up or down to select something. 

Will look for a workaround if it will still be relevant later - using a custom dropdown. 

For now will close it.
