### ISSUE TITLE
Sign-up v2: Last stap: go to dashbaord doesn't redirect to dashbaord but landingspage

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1599]
## Context/goal: 
- Last step: go to dashboard doesn't redirect to dashboard but landingspage**

**Comment by maxvisser** [comment]
If you are logged it should redirect you from the landing page to the dashboard; Maybe an IE bug?

**Comment by GerbenBosschieter** [comment]
I will try to reproduce this. Not sure anymore
