### ISSUE TITLE
Home text spelling issue

### ISSUE THREAD

**Issue by TomForus** [teamforus/forus#160]
## Description

I found a few spelling and style mistake on the dev.zuidhorn.forus

I have added two pictures. One is the front-page. Here are a few spelling mistake regarding how 'het Kindpakket' is written without a capital. 

## Additional Information (optional)

![screen shot 2018-10-15 at 15 00 01](https://user-images.githubusercontent.com/36765624/46952675-d22d0f00-d08b-11e8-9f6b-bb3b259d525b.png)

**Comment by GerbenBosschieter** [comment]
I will fix the text. Could you @dev-rminds something about the second part of the question

**Comment by maxvisser** [comment]
@TomForus the text was copied from https://zuidhorn.forus.io/kindpakket/

its also wrong on the current version lol
