### ISSUE TITLE
Sign-up v2: Step to create office Is unclear what you should do if you already have 

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1600]
This step will ask you to create an office. But if you already have an office it doesn't tell you to create a new or select a excisting office.

It's also no clear you can click on the already created office.

## Task
- Add the following office if there is already an office: "Kies een vestiging om door te gaan of voeg een vestiging toe"

**URL tested:** https://dev.forus.io/provider/#!/sign-up-v2?tag=sdoa

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2%3Ftag%3Dsdoa&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2?tag=sdoa&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/744cde782c7ec69f9123cdd312b0cdd1a998cd98/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/744cde782c7ec69f9123cdd312b0cdd1a998cd98/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2%3Ftag%3Dsdoa&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2?tag=sdoa&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
@jamalv could you adjust this in figma

**Comment by jamalv** [comment]
I see this was already done :)

https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=1%3A3751

**Comment by maxvisser** [comment]
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/da3e259c-1826-436d-9426-78eaa4be7869)

```
Kies een bestaande organisatie of voeg een nieuwe organisatie toe.

```
