### ISSUE TITLE
Sign-up v2: step indicator on mobile is broken

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1601]
## Context/goal: 
The step indicator on the mobile version of the signupflow doesn't make any sense.
We could try to let make it sense. But we could also hide the step indicator on mobile.

See images for examples:

**Example**
![IMG_0069](https://user-images.githubusercontent.com/38419514/84029948-84b59200-a993-11ea-954c-edcfa609649a.PNG)
![IMG_0357](https://user-images.githubusercontent.com/38419514/84029970-8bdca000-a993-11ea-8926-e9b3170e070d.PNG)
![IMG_0358](https://user-images.githubusercontent.com/38419514/84029973-8c753680-a993-11ea-87c2-85abd4a4708c.PNG)

**Comment by maxvisser** [comment]
lets discuss this one during refinement

**Comment by GerbenBosschieter** [comment]
This issue should be fixed before we can release. this is way to confusing to let them use this on mobile. So if the fix itself is to much work and will result in delaying the release of the new sign up flow, we should do a quick fix so people can use it.
