### ISSUE TITLE
Transaction filter: textual change

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1602]
## Context/goal: 
One ouf client noticed a small textual mistake.
The filter gives an option to filter on a start and end date.
The filter tells the user it is UP TO a certain date. But in reality it is  UP TO AND INCLUDING.

### Task
- [ ] Change text:
    - **From**: Tot
    - **To**: Tot en met

![Screen Shot 2020-06-09 at 10 07 05](https://user-images.githubusercontent.com/38419514/84122966-7fab1e00-aa39-11ea-811e-dd39d3570346.png)

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1195
