### ISSUE TITLE
CSS Me-app information page is broken

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1603]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/84123845-b03f8780-aa3a-11ea-8448-a16abd68af58.png)

**Comment by GerbenBosschieter** [comment]
Only on dev right ?

**Comment by maxvisser** [comment]
Correct not sure why :) https://westerkwartier.forus.io/me

**Comment by maxvisser** [comment]
Let me check this out first; maybe its something on deployment
