### ISSUE TITLE
Textual change: Write numbers in full letters

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1606]
## Context/goal: 
The image below shows the current state of the modal after you want to log in on the Me-app by authorisation/connection code. The text itself has some dutch writing errors.
There are rules to write numbers in sentences in dutch. the following rules are related to the current modal.

- Numbers below twenty should be written in letters.
- Numbers in ten (10, 20, 30 ,40 ,50, up to 100) should also be written in letters.

### Task
1. Change text:
**Description**: Na vijf tot tien seconden wordt de app gekoppeld. Is het gelukt? Klik dan op volgende.
**Subdescription**: Ziet u na dertig seconden nog steeds de zes cijfers in de app? Probeer het dan opnieuw.

2. First letter of the button: "**opnieuw proberen**" should be capital.

<img width="934" alt="Screen Shot 2020-06-18 at 10 00 10" src="https://user-images.githubusercontent.com/38419514/84994366-dd7eea80-b14a-11ea-80a0-550f429efe33.png">

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1195
