### ISSUE TITLE
Webshop configuration page doesn't change webshop after switching organisations

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1617]
# Description
Webshop configuration page doesn't change webshop after switching organisations (see image for example)

**Branch tested on:** Master

**URL tested:** https://staging.forus.io/sponsor/organizations/325/implementation/6

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fsponsor%2Forganizations%2F325%2Fimplementation%2F6&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/sponsor/organizations/325/implementation/6&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8a91db4203a5f3d7e68a3039d63332c48d4b3f92/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/8a91db4203a5f3d7e68a3039d63332c48d4b3f92/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fsponsor%2Forganizations%2F325%2Fimplementation%2F6&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/sponsor/organizations/325/implementation/6&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
If the identity has access to a certain page he will not change page.
this also happens with other pages for example a fund request
![image](https://user-images.githubusercontent.com/10818702/85990408-42abc900-b9f2-11ea-90b3-db9311f26ed8.png)
