### ISSUE TITLE
Break up filling in phonenumber and scanning QR into two steps

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1625]
## Current situation
The steps of downloading the me app (sms) and scanning the QR code are on one step: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=1%3A2652
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/dbdb71bc-6509-43cd-a79b-29f11b2037e9)

## Desired situation
Split up the steps to improve the UX: 
Step 1: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=1%3A4562
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/51aef90b-3589-4fe3-b96c-895a4cce05c6)
Step 2: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=1%3A6482
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/43b977ac-9d07-4c1f-9665-853734a6dac8)

## Improvement IP
https://github.com/teamforus/general/issues/222

**Comment by danrminds** [comment]
https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB-prototype-signupflows?node-id=1434%3A4005

In the original prototype
