### ISSUE TITLE
IE: Backspacing with input fields results in leaving the page.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1626]
IE: Backspacing with input fields results in leaving the page.

**URL tested:** https://staging.forus.io/provider/sign-up

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fprovider%2Fsign-up&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/provider/sign-up&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/88374e1d9fd1bab83fdb51767ca6818b9810153f/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/88374e1d9fd1bab83fdb51767ca6818b9810153f/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fprovider%2Fsign-up&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/provider/sign-up&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
IE's biggest flaw. the backspace of doom

**Comment by danrminds** [comment]
Not sure you can do anything about this. @aghimpu - please check

**Comment by danrminds** [comment]
@aghimpu Do you have an update on this? Is this possible? Please report here and close the issue

**Comment by aghimpu** [comment]
@dev-rminds already fixed this with IPad screen keyboard fix
