### ISSUE TITLE
Sign-up-v2: Brand new exchange token  tells me it is already expired. Stuck on ofrm

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1627]
Sign-up-v2: Brand new exchange token  tells me it is already expired. Stuck on form

**URL tested:** https://staging.api.forus.io/api/v1/identity/proxy/confirmation/redirect/1fc971fff637018e925a78f2bae8faa6f8cfa8d49d2f8a74c88962c280d7f2d52d111d467f4bc38753e89f1300a66262be07a9fc4933bc73f9a986743fa01f3cc12dfc74d5c13b96192be58ba628e1d8f519ddf831619b4eec9af7760bc887ca62583c78/me_app-ios/general

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.api.forus.io%2Fapi%2Fv1%2Fidentity%2Fproxy%2Fconfirmation%2Fredirect%2F1fc971fff637018e925a78f2bae8faa6f8cfa8d49d2f8a74c88962c280d7f2d52d111d467f4bc38753e89f1300a66262be07a9fc4933bc73f9a986743fa01f3cc12dfc74d5c13b96192be58ba628e1d8f519ddf831619b4eec9af7760bc887ca62583c78%2Fme_app-ios%2Fgeneral&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.api.forus.io/api/v1/identity/proxy/confirmation/redirect/1fc971fff637018e925a78f2bae8faa6f8cfa8d49d2f8a74c88962c280d7f2d52d111d467f4bc38753e89f1300a66262be07a9fc4933bc73f9a986743fa01f3cc12dfc74d5c13b96192be58ba628e1d8f519ddf831619b4eec9af7760bc887ca62583c78/me_app-ios/general&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/185f944887841ff05f7171c8baa5644d34441ce7/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/185f944887841ff05f7171c8baa5644d34441ce7/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.api.forus.io%2Fapi%2Fv1%2Fidentity%2Fproxy%2Fconfirmation%2Fredirect%2F1fc971fff637018e925a78f2bae8faa6f8cfa8d49d2f8a74c88962c280d7f2d52d111d467f4bc38753e89f1300a66262be07a9fc4933bc73f9a986743fa01f3cc12dfc74d5c13b96192be58ba628e1d8f519ddf831619b4eec9af7760bc887ca62583c78%2Fme_app-ios%2Fgeneral&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.api.forus.io/api/v1/identity/proxy/confirmation/redirect/1fc971fff637018e925a78f2bae8faa6f8cfa8d49d2f8a74c88962c280d7f2d52d111d467f4bc38753e89f1300a66262be07a9fc4933bc73f9a986743fa01f3cc12dfc74d5c13b96192be58ba628e1d8f519ddf831619b4eec9af7760bc887ca62583c78/me_app-ios/general&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
Don't really understand the issue.

**Comment by maxvisser** [comment]
Test both on staging (release v0.13.1) and production

**Comment by maxvisser** [comment]
Could be a environment specific issue (AWS)

**Comment by GerbenBosschieter** [comment]
Only happens if you create a new profile

**Comment by maxvisser** [comment]
android and iOS (maybe aswell signupflow)
