### ISSUE TITLE
Sign-up v2: Input fields doesn't accept a valid e-mailadres.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1628]
Sign-up v2: Input fields doesn't accept a valid e-mailadres.

**URL tested:** https://staging.forus.io/provider/sign-up

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fprovider%2Fsign-up&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/provider/sign-up&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8399808c38c45dbf8ce4b064b9f637f3c2132328/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/8399808c38c45dbf8ce4b064b9f637f3c2132328/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fprovider%2Fsign-up&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/provider/sign-up&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
Hmm I made multiple organizations with all kinds of email adresses; Is this IE specific?

**Comment by GerbenBosschieter** [comment]
No, it's not IE specific. Just reproduced it again.
How does our backend check if an e-mail is valid? It almost like like it checking if the domain name itself really exist.

**Comment by maxvisser** [comment]
Oh that could be actually; as DNS check

**Comment by GerbenBosschieter** [comment]
If you are sure, than you can close this issue ;)

**Comment by maxvisser** [comment]
Yeah I am sure; this was done after maintaince a new feature in laravel 5.8
