### ISSUE TITLE
Sign-up v2: fund filter missing organizations

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1631]
Sign-up v2: fund filter missing organizations
Not all the organization are displayed on the signup form

**URL tested:** https://staging.forus.io/provider/sign-up

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fprovider%2Fsign-up&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/provider/sign-up&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/a0d8ab4a1848ebe0cdf46e5bdb58bf64928d6733/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/a0d8ab4a1848ebe0cdf46e5bdb58bf64928d6733/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fprovider%2Fsign-up&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/provider/sign-up&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
I guess aswell IE bug?

**Comment by jamalv** [comment]
berkelland and westerkwartier missing

**Comment by GerbenBosschieter** [comment]
@maxvisser no not all the bugs are because of IE.

**Comment by maxvisser** [comment]
Fund filter seems to only show organization within the first page of pagination. If you go to the second page you see the organizations which are missing.
