### ISSUE TITLE
Physical cards: Connecting old cards

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1634]
## Context/goal: 
Overview: https://github.com/teamforus/general/issues/182
Figma: https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK/%F0%9F%8C%8D-%F0%9F%A7%91%E2%80%8D%F0%9F%A6%AF%F0%9F%94%8D%F0%9F%93%9D%E2%9A%99%EF%B8%8FIP182%3A-Reactivate-cards?node-id=1%3A21

We need to allow people to re-connect existing cards to the voucher.
- The old cards contain a QR-code and a 16-digits number. 
    - Format of the 16 digits number is: 1001-xxxx-xxxx-xxxx
    - Pre-fill the 1001 part the same way we do on the phone number in signup-flow. 
 - We need to save this code as an alias to the current voucher. When a provider will scan the QR-code of a physical card - he needs to get same access as to a normal QR-code of the same voucher
    - Apply validation on the 1001 part of the codes like this (to check if this can be a valid 16 digits code)

![Screenshot 2020-07-05 at 17 21 59](https://user-images.githubusercontent.com/33207036/86535935-186f7500-bee4-11ea-8718-c5491d92c8bf.png)

**Comment by danrminds** [comment]
@jamalv If you can attach here an exact QR-code from a physical card - would be perfect.

**Comment by jamalv** [comment]
@danrminds sorry, missed that comment; I don't think its needed anymore, right? :)

**Comment by maxvisser** [comment]
yeah I have already sent a physical card as a photo to dan and yasha :)
