### ISSUE TITLE
When logging in with the Me app on the requester dashboard the me app says I am recovering my account

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#164]
The app gives me the wrong feedback. Should say if I logged in successful or not. If not why not.

**Comment by Jimmy390** [comment]
I can confirm this, the same problem occurs with my demo. When I try to login with the Me App and it is successful the app returns a message with the question if I want to recover my account. 

Only after I have clicked proceed it will display a short text message stating that I have successfully logged in.

Screen capture:
<img src="https://i.imgur.com/B5fHE6j.jpg" alt="Screenshot Me App" width="40%" height="40%">

**Comment by GerbenBosschieter** [comment]
I think I can fix this by adding the proper text.

**Comment by maxvisser** [comment]
Denis can you add a string to strings.xml

**Comment by jknnr** [comment]
fixed

**Comment by maxvisser** [comment]
@jknnr this issue is still in latest build of me-android

**Comment by maxvisser** [comment]
![](https://i.imgur.com/dqm3pZf.jpg)

**Comment by maxvisser** [comment]
@jknnr can you check on iOS what the message is there?
