### ISSUE TITLE
Move final signup flows to dashboard library

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1640]
## Context/goal: 
https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB-prototype-signupflows?node-id=613%3A4595&viewport=1000%2C775%2C0.25

**Comment by jamalv** [comment]
@bodivleij is currently working on https://github.com/teamforus/general/issues/307 and might have time to do this as part of that task, so this can be put on hold.
