### ISSUE TITLE
Alert if application to fund is in progress already

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1643]
## Context/goal: 
When a requester starts the signupflow but already has an active request in progress - we now display a default browser alert.
Replace it with this alert.

https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB-prototype-signupflows?node-id=613%3A4595

![Screenshot 2020-07-08 at 18 03 33](https://user-images.githubusercontent.com/33207036/86942516-81095c80-c145-11ea-9242-f63725886f57.png)

**Comment by maxvisser** [comment]
This needs dutch translations

**Comment by maxvisser** [comment]
U heeft al een aanvraag die in behandeling is.
Bekijk de status:
- x
- x
U kunt niet nogmaals een aanvraag indienen.
