### ISSUE TITLE
Bug: exports of providers gives duplicates (same provider that has applied for other funds)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1649]
## Main asssignee: @

Start from branch: **Master**

## Context/goal: 
If sponsor would export the list of providers it will get duplicates  in the export.

One of our sponsor has mentioned this bug. Their client council is currently critically reviewing the on boarding process of  providers and they need this list. 

### Note
- Would be really nice if we could fix this ASAP, I gave it a priority hotfix because there are some other things not perfect for them yet and fixing this asap will help us with the relationship we have with them

<img width="743" alt="Screen Shot 2020-07-15 at 09 59 22" src="https://user-images.githubusercontent.com/38419514/87520003-abe23c00-c682-11ea-8c2d-12cdde83254b.png">

**Comment by GerbenBosschieter** [comment]
Image is from staging environment

**Comment by maxvisser** [comment]
Filtered on fund;
