### ISSUE TITLE
Change text: footer mail unsubscribe

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1651]
@maartenfv commented on [Mon Jul 20 2020](https://github.com/teamforus/general/issues/293)

![image](https://user-images.githubusercontent.com/10818702/87945200-b47eac00-caa0-11ea-89ed-d48eba978d58.png)

Should be: 

Deze e-mail is verstuurd naar maarten@forus.io. Is deze e-mail aan u gericht, maar wilt u zich afmelden voor dit soort berichten? U kunt dit aangeven in uw e-mailvoorkeuren.

**Comment by linda-90** [comment]
Is deze e-mail aan u gericht, maar wilt u zich afmelden voor dit soort berichten? U kunt dit aangeven in uw e-mailvoorkeuren.

**Comment by maartenfv** [comment]
I have updated the text.

**Comment by maartenfv** [comment]
@maxvisser What is the next step for this issue? When is this expected to be released?

**Comment by maxvisser** [comment]
Its in release/v0.13.0 now planned to be released on monday.

**Comment by maxvisser** [comment]
This task can be closed as it is fixed. CR; can be kept open until its on production :)
