### ISSUE TITLE
Move UID from prevalidation_records to prevalidation table

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1653]
## Context/goal: 
Makes more sense

**Comment by jamalv** [comment]
@maxvisser is this still relevant?

**Comment by jamalv** [comment]
I'm assuming this can be closed, please re-open if still relevant

**Comment by maxvisser** [comment]
This is about moving customer numbers or bsn numbers to the level which groups records instead of being a record it self. Not sure how desirable but from a code perspective these identifier records are a bit special
