### ISSUE TITLE
Unlimited product has -9 stock left

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1655]
## Main asssignee: @
Fix from master

## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/88261205-1f5cfc80-ccc6-11ea-8563-9726b73c4b63.png)

On product list and product details we show 'Products left in stock' this is value is currently broken for unlimited offers.

Should state 'Unlimited' NL -> 'Onbeperkt' or hide it completely

**Comment by maartenfv** [comment]
@maxvisser We should use "onbeperkt". Should this be in this repo?

**Comment by maxvisser** [comment]
Yes as it is a bug. This is an unlimited offer without any stock
