### ISSUE TITLE
Footer link "emailvoorkeuren" is broken

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1658]
## Prerequisites

1. Access to an account on staging environment

## Description

Clicking "e-mailvoorkeuren." in the footer of an email takes me to a white page

## Steps to Reproduce (bug report)

1. Log in using a staging email on the dashboard
2. Click  e-mailvoorkeuren

**Expected behavior:** Go to emailvoorkeuren

**Actual behavior:** Blank page

<img width="1501" alt="Screenshot 2020-07-23 at 13 48 25" src="https://user-images.githubusercontent.com/30194799/88283157-3104cb00-cceb-11ea-9a00-0a4262352e22.png">

**Reproduces how often:** Every time

**Comment by maxvisser** [comment]
should be preferences/email

**Comment by maxvisser** [comment]
Currently aswell broken on production.
