### ISSUE TITLE
Logging time is hardcoded 14.55

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#166]

**Comment by Jimmy390** [comment]
I think this issue correlates with issue #129

**Comment by TomForus** [comment]
![tijd verandert niet issue](https://user-images.githubusercontent.com/36765624/46956199-00fbb300-d095-11e8-9028-7ddeaec55b28.png)

**Comment by GerbenBosschieter** [comment]
@Jimmy390 do you have permission to close issues? if so, just close them if it's a duplicate ;)
And thumbs up for your involvement. Like it :)
