### ISSUE TITLE
Notification preferences need some text

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1668]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/88504353-cbf3f280-cfd4-11ea-98a6-0275e1627d92.png)

**Comment by maxvisser** [comment]
Title: "Samenvatting over uw aanmeldingen bij fondsen"
Description: "Een samenvatting van al uw aanmeldingen bij fondsen"

Title: "Samenvatting van uw gereserveerde aanbiedingen"
Description: "Een samenvatting alle notificaties omtrent aanbiedingen die zijn gereserveerd"

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-frontend/pull/1248

**Comment by GerbenBosschieter** [comment]
Already merged
