### ISSUE TITLE
Product voucher upload CSV: A field in automatically genereated Note is missing

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1671]
## Context/goal: 
When you upload a CSV on product voucher generator and don't fill in a note the system automatically generates one for you:
Aangemaakt op 2020-07-27 door , toegekend aan mail@gmail.com

The email of sponsor is missing in this sentence
should be:
Aangemaakt op 2020-07-27 door {{e-mail of sponsor employee}}, toegekend aan mail.roetman@gmail.com

## code
https://github.com/teamforus/forus-frontend/blob/328ea303b10683c4c5b1b5c74b42711b1e7ebe48/src/sources/forus-platform/js/angular-1/components/Modals/ModalVouchersUploadComponent.js#L141

probably this rootScope variable is empty: $rootScope.auth_user.primary_email

## User flow
`. go to sponsor dashboard
2. go to product voucher generator
3. upload csv with valid product_id and email column (no note)
4. check note field of product voucher its "Aangemaakt op 2020-07-27 door , toegekend aan mail@gmail.com"

bug is uploader_email is empty in default note field

**Comment by maxvisser** [comment]
reproduce @GerbenBosschieter

**Comment by maxvisser** [comment]
Show alex where the issue is :) @maxvisser

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1507
