### ISSUE TITLE
Physical cards: design mobile screens

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1693]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/89168447-2ebd2f00-d57d-11ea-9c3a-6e1a54962f79.png)

![image](https://user-images.githubusercontent.com/10818702/89168477-3977c400-d57d-11ea-86ec-a6f2e0564b1f.png)

![image](https://user-images.githubusercontent.com/10818702/89168507-41cfff00-d57d-11ea-9b11-319e336abd8e.png)

![image](https://user-images.githubusercontent.com/10818702/89168578-58765600-d57d-11ea-87c3-765050854715.png)

**Comment by danrminds** [comment]
https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BBIP182%3A-Reactivate-cards?node-id=676%3A178&viewport=605%2C384%2C0.4151375889778137
