### ISSUE TITLE
Implement mobile view for the activating physical cards

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1700]
## Context/goal: 
https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BBIP182%3A-Reactivate-cards?node-id=676%3A178&viewport=605%2C384%2C0.4151375889778137

![Screenshot 2020-08-11 at 19 09 03](https://user-images.githubusercontent.com/33207036/89927131-2791c300-dc06-11ea-9c1c-024e7de75bcb.png)

**Comment by maxvisser** [comment]
Adding blinking cursor (mobile & desktop)
