### ISSUE TITLE
Physical cards. Block card screens

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1701]
## Context/goal: 
<img width="1179" alt="Screenshot 2020-08-12 at 10 38 35" src="https://user-images.githubusercontent.com/33207036/89994310-4173ea00-dc88-11ea-9bc1-ac7f95c4a5e4.png">
<img width="1363" alt="Screenshot 2020-08-12 at 10 39 15" src="https://user-images.githubusercontent.com/33207036/89994321-45077100-dc88-11ea-95ac-9e1acf69afeb.png">
<img width="1301" alt="Screenshot 2020-08-12 at 10 38 42" src="https://user-images.githubusercontent.com/33207036/89994325-45a00780-dc88-11ea-9a55-92e12e728d82.png">

These screens are missing on desktop and mobile.

Also adjust this mobile screen to make it more compact
<img width="275" alt="Screenshot 2020-08-12 at 10 41 06" src="https://user-images.githubusercontent.com/33207036/89994435-6a947a80-dc88-11ea-96f5-5403d7474889.png">

**Comment by maxvisser** [comment]
@danrminds On desktop the icon is also not nice.

![image](https://user-images.githubusercontent.com/10818702/89995213-82b8c980-dc89-11ea-8e2f-f7e4aeecd87c.png)

This should indicate blocking card / replacing card

**Comment by danrminds** [comment]
@maxvisser Definitely we will revise the icons

**Comment by danrminds** [comment]
https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BBIP182%3A-Reactivate-cards?node-id=1%3A21
