### ISSUE TITLE
Provider bug: after email confirmation the signupflow tells me the acces token is invalid

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1704]
## Main asssignee: @

**Start from branch** Release v0.14.0 

## Context/goal: 
1. Was logged out and opened signup flow
2. created profile and verifef mail
3. Tried to create a organization and confirmed. The signup flow was not redirecting me to the next page. because of an invalid acces token (see image below)

<img width="437" alt="Screen Shot 2020-08-20 at 11 20 44" src="https://user-images.githubusercontent.com/38419514/90752151-56c7c480-e2d7-11ea-94a4-5174c09b993d.png">

**Comment by GerbenBosschieter** [comment]
It looks like this is just a bug overall. Van't add a product to the webshop

**Comment by maxvisser** [comment]
could not replicate it on develop; @maxvisser will replicate it.

**Comment by maxvisser** [comment]
tried this on staging provider signupflow. Could not reproduce
