### ISSUE TITLE
Review mobile menu on webshops (top and bottom)

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1705]
## Context/goal: 
https://www.figma.com/file/Z96JUSqKypvCPOYjWy5UbG/Mobile-webshop-menu?node-id=115%3A180

**Comment by danrminds** [comment]
https://www.figma.com/file/Z96JUSqKypvCPOYjWy5UbG/Mobile-webshop-menu?node-id=147%3A0

@jamalv Can you please check and approve this? I can move it back to master after approved.

**Comment by danrminds** [comment]
https://www.figma.com/file/Z96JUSqKypvCPOYjWy5UbG/Mobile-webshop-menu?node-id=147%3A0

@jamalv Can you please check this and if it is okay I will move it back to master.

**Comment by jamalv** [comment]
@danrminds very nice! master can be replaced!

**Comment by jamalv** [comment]
(please assign me next time :))

**Comment by maxvisser** [comment]
I would only make the 'active' state blue / primary color
