### ISSUE TITLE
Webshop improvements (navigation)

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1706]
## Context/goal: 
In addition to the goal of finalising the webshops we would like to include the new navigation as well.
The new navigation wil influence all of the webshops and we have some desires of how to implements this.
I would like to request to start with this part of finalising the webshops, lot of designs already fit if we fix the improvements on the navigation.

- Good baseline in the common 
- As much variables we can add in the vars.scss
- As little a possible extra css files for navigation per implementation

## Goals
- As much as css handled in the common instead of extra navigation.scss files.
- The code quality @dev-rminds and @aghimpu  you desire
- Easy to change if there is a new implementation (variables, not to much css navigation.scss files)
- No navbar should be be fixed anymore
- On mobile the navbar should be as the mobile footer branch
- Eventually I have the desires to add a litttle css files to a new implmentation as possible. The image below shows the implementation of groningen on my branch where you can already see that I commented otu alot of css files but still have the desires result

**Image:**
<img width="555" alt="Screen Shot 2020-08-24 at 10 31 07" src="https://user-images.githubusercontent.com/38419514/91022190-17f67f00-e5f5-11ea-845f-83d1fa63de49.png">

#### Current state:
I've already started with a branch where I included the the above mentioned desires and goals. Only problem is that I am not sure if @dev-rminds @aghimpu  agree with the way I did it. So Please take a quick look how I did it, continue with it our start over and make it better.

### Proposals / designs
[Baseline for the navigation:](https://www.figma.com/file/FMhzCEMbbTGiPjAmOvnTQn/Update-webshop-menu-bars?node-id=0%3A1) (use the one Will Smith is presenting ;)

This design can be used for every webshop as a baseline. I can imagine that some of the webshop do need an extra css file to make it work for their specific design.
- Common
- Oost Gelre
- Berkelland
- Winterswijk
- Noordoostpolder

Webshops that probably need a additional navigation.scss (click on the link to see a example, it should be visually as close as the links below)

Groningen: https://dev.forus.io/groningen/#!/
Nijmegen: https://dev.forus.io/nijmegen/#!/
Westerkwartier:  https://dev.forus.io/westerkwartier/#!/

#### Problems with my branch
- Probably did some things with buttons on the common that screws up some alignment.
- This branch has some changes that are not included on the dev branch: REMOVE ALL CAPPS issue :https://github.com/teamforus/general/issues/272
- I've commented out old css in all the navigation files
- Mobile footer branch is not merged with dev yet.
- This branch has groningen webshop design in it but develop hasn't

**Branch:** [develop.webshop-improvements-navigation ](https://github.com/teamforus/forus-frontend/tree/develop.webshop-improvements-navigation)

**Comment by maxvisser** [comment]
I did a bit of cleanup on the branch; code has not change much; moved my code to feature.navigation-groningen-webshop
