### ISSUE TITLE
CR: aanvraag of aanvragen. Singular or plural.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1711]
Start from: master

@maartenfv commented on [Tue Sep 01 2020](https://github.com/teamforus/general/issues/394)

The email needs to state singular when there is only one ![image](https://user-images.githubusercontent.com/30211022/91817310-8c54a200-ec35-11ea-8e93-615bee705e2b.png)

**Comment by maxvisser** [comment]
Enhance issue with exact sentence which needs to be changed

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-backend/pull/889
