### ISSUE TITLE
Auto-validation requester signupflow: step indicator gets shorter while going to steps.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1712]
@mmjvdlinden commented on [Wed Sep 02 2020](https://github.com/teamforus/general/issues/395)

### Requested by:
- Martijn van der Linden, gemeente Nijmegen

### Change description
- The steps in the registration flow go wrong, instead of going through steps 1 to 4, the resident gets stuck at step 1 and it becomes: step 1 of 4, step 1 of 3, step 1 of 2
- See above [these screenshots](https://irvn-my.sharepoint.com/:f:/g/personal/m6_van_der_linden_nijmegen_nl/Essttg8ybR5FvdlmmxTRRHcBXKfMhSQBIg1fJYw8R9dDkQ?e=NYy6Ti)
- Can this be adjusted to a regular flow?

---

@maxvisser commented on [Wed Sep 02 2020](https://github.com/teamforus/general/issues/395#issuecomment-685409788)

Reproduced.

When the user has already logged in once with DigiD (leaves form, website closes) after logging in with DigiD and returns to complete the application (of only 4 steps). Of course there are only two more steps to finish. This is crazy for someone who goes through the steps in one go.

Desired situation:
Login step and DigiD step remain part of the steps.

<details>
<summary>Step 3: bevestig uw inkomen</summary>

![image](https://user-images.githubusercontent.com/10818702/91944596-9ee6de00-ecfe-11ea-93ec-257570e846c2.png)

*where currently step 1 is should be step 3
</details>

## Task
- [ ] Auto-validation requester signupflow has 4 steps, when user returns from DigiD to signupflow. Signupflow has only 2 steps. Should be still 4 steps -> "Bevestig uw inkomen" should be step 3 of 4

**Comment by maxvisser** [comment]
Easy fix: remove step text
![image](https://user-images.githubusercontent.com/10818702/91975552-d914a780-ed1f-11ea-9e0a-f8a720d9f88f.png)

**Comment by maxvisser** [comment]
@myshelova could you review this and see if there is a better solution

**Comment by jamalv** [comment]
Figma file for this change: https://www.figma.com/file/buNhwrhiuG23hrxWZRGkrC/Nijmegen?node-id=218%3A928
