### ISSUE TITLE
Clarification request improving texts: missing titles, weird dutch texts

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1718]
### Requested by:
-

### Change description
![image](https://user-images.githubusercontent.com/10818702/91999949-41be4d00-ed3d-11ea-8105-626acec90537.png)

## Task
- [ ] blocktitle: "Aanvulverzoek"
- [ ] Al geantwoord -> "Aanvulverzoek ingediend" 
- [ ] Uw aanvraag is voltooid, u krijgt een email wanneer deze is goedgekeurd -> "Uw aanvulverzoek is ingediend, u krijgt een e-mail als uw aanvraag is afgehandeld."

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/100082179-31070a00-2e48-11eb-966a-0f10e67f4ca9.png)

block_title -> Uw aanvraag voor {{fund_name}} aanvullen
Bevestig uw -> Should be replaced by criteria title

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/101616088-34d18980-3a0f-11eb-9975-223da1dc0c20.png)

**Comment by maxvisser** [comment]
Seems to still be an issue

**Comment by aghimpu** [comment]
Doesn't seem to be an issue anymore, I double checked on both develop and master.
