### ISSUE TITLE
E-mail settings: text fixes

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1720]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/92080474-ebdfb880-edc1-11ea-9820-0f29fece35bc.png)
Email should be E-mail with a dash

Primary should be "Primair"

**Comment by SjoerdHilhorst** [comment]
shouldn't we also do this for the entire platform then?

**Comment by maxvisser** [comment]
If you find more email you can fix those aswell ;) These were found during user testing

**Comment by GerbenBosschieter** [comment]
Would be nice to fix it everywhere indeed. This can make it hard to review if we do everything at once. 

So I propose to do it like this:
- First all email in dashboard
- Second webshops
- Third signup flows.

**Comment by maxvisser** [comment]
@SjoerdHilhorst Is this atleast now fixed on this page?

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1358
