### ISSUE TITLE
Sponsor dashbaord: prevliadations are hidden because of panel type

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1722]
## Main asssignee: @

**Branch: Master**

## Context/goal: 
With the lastes release we added panel type = "validator" to show or hide the prevalidations.
But means that prevalidations are now hidden on sponsor dahsboard, this is really confusing for our current user who have never heard of validator dashboard and and already use workarounds to grant citizen new vouchers for diffferent funds.

**To do**
- show prevalidations on sponsor dashboard

**Comment by GerbenBosschieter** [comment]
This if statement hides the prevalidations
![Uploading mmmmeeee.png…]()

Without the if statement it does show prevalidations
![prevalidaaa](https://user-images.githubusercontent.com/38419514/93066588-75bd3a80-f67a-11ea-98cf-4f3e2009cb2b.png)

File: csv-prevalidations.pug

**Comment by maxvisser** [comment]
fixed this on release branch
