### ISSUE TITLE
Relations. Add record via validator dashboard. Design review

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1727]
## Context/goal: 
https://www.figma.com/file/rW80bGvSS7TKXovctNjjUQ/Relations?node-id=29%3A10563

![Screenshot 2020-09-05 at 16 54 57](https://user-images.githubusercontent.com/33207036/92307708-94477580-ef98-11ea-900a-34e4a882f5c7.png)
![Screenshot 2020-09-05 at 16 55 00](https://user-images.githubusercontent.com/33207036/92307720-a5908200-ef98-11ea-8f2f-237f68e7d8a5.png)
![Screenshot 2020-09-05 at 16 55 05](https://user-images.githubusercontent.com/33207036/92307723-acb79000-ef98-11ea-9cdb-bcff9e4914d6.png)

**Comment by maxvisser** [comment]
Sasha already revised this proposal
