### ISSUE TITLE
NOP: Improve the hover design of links and buttons

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1734]
@linda-90 commented on [Mon Sep 07 2020](https://github.com/teamforus/general/issues/413)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
- Now several hovers are used on the website (staging environment)
<img width="147" alt="Schermafbeelding 2020-09-07 om 15 03 07" src="https://user-images.githubusercontent.com/36952230/92403304-795c3900-f131-11ea-8d3f-a50ff9cfc056.png"><img width="221" alt="Schermafbeelding 2020-09-07 om 14 57 51" src="https://user-images.githubusercontent.com/36952230/92403305-79f4cf80-f131-11ea-9636-618b2b9850ce.png"><img width="179" alt="Schermafbeelding 2020-09-07 om 14 57 46" src="https://user-images.githubusercontent.com/36952230/92403308-7a8d6600-f131-11ea-9b51-f1c4cec66f37.png">

    - Shadow
    - Color change
    - Underlined text

Style guide is in Figma: https://www.figma.com/file/pUWeZwelwsJK8W58ZGip9r/Webshop%3A-Noordoostpolder?node-id=742%3A0&viewport=240%2C662%2C0.8783382773399353

### Tasks
- [ ] Update hovers as shown in the Figma design

**Comment by linda-90** [comment]
Is this ready yet?
