### ISSUE TITLE
NOP Webshop: make buttons similar

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1735]
@linda-90 commented on [Mon Sep 07 2020](https://github.com/teamforus/general/issues/413)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
- Now several hovers are used on the website (staging environment)

![image](https://user-images.githubusercontent.com/10818702/93086703-cbeca680-f697-11ea-84f7-bf821815883e.png)

Two hovers affects are different:
    - remove shadow
    - add nderlined text

### Tasks
- [ ] Align primary buttons

**Comment by GerbenBosschieter** [comment]
This is not a task, this is a CR. Why is this task created while I already asked for a CR and review on current navigation.
