### ISSUE TITLE
NOP Webshop: add dropshadows to navbar and header

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1736]
@linda-90 commented on [Mon Sep 07 2020](https://github.com/teamforus/general/issues/412)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description

<img width="1437" alt="Schermafbeelding 2020-09-07 om 14 38 46" src="https://user-images.githubusercontent.com/36952230/92389715-e5cb3e00-f119-11ea-9049-9df48b11c140.png">
<img width="1437" alt="Schermafbeelding 2020-09-07 om 14 38 29" src="https://user-images.githubusercontent.com/36952230/92389718-e6fc6b00-f119-11ea-8afb-ea524ce20576.png">

Figma design is leidend:
https://www.figma.com/file/pUWeZwelwsJK8W58ZGip9r/Webshop%3A-Noordoostpolder?node-id=658%3A88&viewport=-270%2C685%2C0.36613044142723083

<img width="537" alt="Schermafbeelding 2020-09-07 om 14 54 35" src="https://user-images.githubusercontent.com/36952230/92389826-127f5580-f11a-11ea-8359-7f8cd66d20a0.png">

## Task
- [ ] Add dropshadow

**Comment by GerbenBosschieter** [comment]
@maxvisser Ik heb geen idee wie die dropshadow heeft bedacht. echt onnodig na mijn inziens. Is dit vanuit feedback vanuit NOP. OF heeft iemand dit intern bedacht ?

Daarnaast is er een ander figma bestand die iets anders zegt:
<img width="947" alt="Screen Shot 2020-09-14 at 11 18 53" src="https://user-images.githubusercontent.com/38419514/93068021-3bed3380-f67c-11ea-939c-b063c0351b6a.png">

**Comment by maxvisser** [comment]
@SjoerdHilhorst lets put this one on hold for now.

**Comment by maxvisser** [comment]
Until its clear whats what.

**Comment by linda-90** [comment]
@GerbenBosschieter Wat bedoel je met:

> Daarnaast is er een ander figma bestand die iets anders zegt:

Ik kan geen ander bestand vinden. Master page (zoals in de issue staat) is leidend: https://www.figma.com/file/pUWeZwelwsJK8W58ZGip9r/Webshop%3A-Noordoostpolder?node-id=658%3A88&viewport=113%2C390%2C0.19195933640003204

Verder staat op deze pagina beschreven hoe de buttons er volgens de huisstijl van NOP eruit moeten zien.
https://www.figma.com/file/pUWeZwelwsJK8W58ZGip9r/Webshop%3A-Noordoostpolder?node-id=742%3A0&viewport=294%2C480%2C0.38735729455947876

**Comment by maxvisser** [comment]
This issue about dropshadows on the navbar; if these shadows are really needed I would suggest to add these to the common aswell @GerbenBosschieter 

As I saw you already introduced them on Geertruidenberg; with merge conflicts I removed those shadows.
https://geertruidenberg.staging.forus.io/

**Comment by maxvisser** [comment]
I will close this task as CR as described here https://github.com/teamforus/general/issues/412
