### ISSUE TITLE
NOP Webshop: Change color of labels on product page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1737]
@linda-90 commented on [Mon Sep 07 2020](https://github.com/teamforus/general/issues/414)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
- Change the color of the discount and amount labels on product page

<img width="992" alt="Schermafbeelding 2020-09-07 om 17 57 13" src="https://user-images.githubusercontent.com/36952230/92404400-c7723c00-f133-11ea-9fb9-81b2fd44438b.png">

### Tasks

- [ ] Change the color of the red label (discount) to the green color of NOP (#549104)
- [ ] Change the color of the gray label (amount) to the blue color of NOP (#20b6ea)

<img width="440" alt="Schermafbeelding 2020-09-07 om 18 10 25" src="https://user-images.githubusercontent.com/36952230/92405427-d35efd80-f135-11ea-84c3-805fc90e7421.png">

**Comment by jamalv** [comment]
@maxvisser just checked this on production, it's not there?

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1417
