### ISSUE TITLE
Create figma proposal for assign vouchers to BSN numbers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1751]
## Context/goal: 
CR:
https://github.com/teamforus/general/issues/298

- As a sponsor I would like to be able to assign vouchers to different UID's (e.g., email adres or BSN).
- As a sponsor, I want to be able to add a unique ID number to the CSV upload when generating QR-codes.
- As a sponsor, **I do not** want to use the "note" field to keep track of whom I have given a code or to write down BSN or customer number.
- As a sponsor, I want to be able to search through these new numbers.

*Note* The voucher generators are going to be used to generate thousands of codes. This means that it will not just be a feature for edge cases. The design needs to take into account these demands in terms of search-ability etc.

For the busregeling this is a must-do issue.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/460fd94a-9480-4140-b98e-94201bfa50e3)

As a sponsor I would like to be able to assign vouchers to different UID's (e.g., email adres or BSN).

Some funds use UID, Some BSN. Alot of vouchers are now generated with these UIDs in the note field. It would be better to set these UID as a seperate field on the voucher.

**Comment by jamalv** [comment]
Figma: https://www.figma.com/file/2aop46Q059INcaDiECK8Bs/Voucher-generator-Assign-to-UID-and-add-field?node-id=0%3A1

**Comment by maxvisser** [comment]
Proposal is done
