### ISSUE TITLE
Acties page on webshop should have titles 'Acties' 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1758]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/92572579-ea603580-f284-11ea-9652-b6aad83e4fdf.png)

**Comment by maxvisser** [comment]
Fixed

**Comment by maxvisser** [comment]
@SjoerdHilhorst I see you changed the page subsidies to 'Aanbod' and the navbar item to 'Aanbod'; seems that this was not in the text fix issue as a planned task. Could you revert these changes?

**Comment by SjoerdHilhorst** [comment]
This mentions changing it to "aanbod":
https://docs.google.com/spreadsheets/d/1B1rSQjzejkIMThG2bAIW27Xg6Ol2GLY-hLts7b5vcsI/edit#gid=433994186&range=C26

@jamalv what do you think

**Comment by maxvisser** [comment]
We already reversed the change in release 0.16.3

**Comment by maxvisser** [comment]
Did you implement any other textual fixes from the spreadsheet?

**Comment by maartenfv** [comment]
@jamalv Can we change it to aanbod? As requested by Groningen?

**Comment by maxvisser** [comment]
Please open a new CR instead of opening old forus tasks.
