### ISSUE TITLE
Fund with only a product formula gives a no_formula permission error

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1759]
## Context/goal: 
A fund with only a product formula should be able to be activated. User should get only the product voucher.

![image](https://user-images.githubusercontent.com/10818702/95193984-f7653b80-07d4-11eb-8bee-fc36810b0361.png)

**Comment by maxvisser** [comment]
Not sure if this worked in the past (if this is even a bug or intended)

**Comment by dev-rminds** [comment]
@maxvisser This was intended (in the past as well)

**Comment by maxvisser** [comment]
Lets discuss this one @dev-rminds

**Comment by maxvisser** [comment]
Discussed this. As this is need to give out a fund on 1st nov. We decided to implement this as a feature.

**Comment by maxvisser** [comment]
Workaround:
Connexion will change name and contact details

Another workaround:
hide map when there are no offices


If budget formula hide all products from products page webshop product hidden
- If 0 fixed and no multiply formula

**Comment by maxvisser** [comment]
Still get a €0 euro voucher when formula of 0 euros is set. Not sure how this should work
![image](https://user-images.githubusercontent.com/10818702/96738550-224bb400-13bf-11eb-8377-235e4e20c386.png)
