### ISSUE TITLE
Login - Fail (want het werkte niet)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#1763]
Open login modal/page

Fill in e-mail address

Click on link in mail retrieved

:( Did not work.

**Comment by maartenfv** [comment]
https://forus.testquality.com defect [D3](https://forus.testquality.com/project/11094/result/2106091/defect/7196). Do not remove or edit.

**Comment by maxvisser** [comment]
Seems to be a false positive 👍 Maarten is testing testquality suite.
