### ISSUE TITLE
Alternative text for app-icons on homepage

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1765]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/93761759-a23efc80-fc0e-11ea-8fd8-17c6bcd83f44.png)

https://wcag.nl/quickscan/1xSBEujTbNcHInuePy5T

**Comment by maxvisser** [comment]
@GerbenBosschieter can you close this if its done? or @SjoerdHilhorst
