### ISSUE TITLE
Text review assign voucher by BSN

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1783]
## Context/goal: 

Figma:
https://www.figma.com/file/2aop46Q059INcaDiECK8Bs/?node-id=22%3A38157

On voucher generator sponsor should with this proposal be allowed to assigned vouchers to BSN numbers (retrieved by DigiD)

This needs text review. Voucher generator was never really text reviewed. I added screenshots and play pages to show current state. If needed we can enhance more texts.

**Comment by jamalv** [comment]
@maxvisser as I understand this mail is turned of for the current usecase? Is this still high-priority and relevant?

**Comment by maxvisser** [comment]
Linda has worked on this; already she wrote the mails. THis can be closed
