### ISSUE TITLE
Signupflow: image upload

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#179]
## Description

Gerben want us to disable uploading images or make the UX experience better with a crop functionality.

**Comment by maxvisser** [comment]
whats the status on this issue? @danrminds @GerbenBosschieter

**Comment by maxvisser** [comment]
I put this back into the icebox

**Comment by GerbenBosschieter** [comment]
@maxvisser I've tried to add some instructions into the pug files. But it's really ugly. For Zuidhorn it wasn't really a problem cause we did most of the images our self. But for Nijmegen it would be nice if it's fixed. will write some instructions and send it to @danrminds. Maybe Alex can make something pretty out of it.

**Comment by maxvisser** [comment]
https://github.com/alexk111/ngImgCrop
