### ISSUE TITLE
Requester signupflow: new activation success page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1796]
## Context/goal: 
This page contains funds who user can activate.

Few cases where page is shown:
- Page is shown when voucher is added by login with DigiD (for example bsn number was assigned to a voucher before user existed)
- Page is shown when user has valid record for criteria for funds on the platform. List of funds user can activate is shown.
- Page is show after requester got a mail from validator that his fund request was approved. User is returned by link in mail to this page of signupflow. -> option: page is made as a directive so it can be reused as a seperate page / modal for this instance.

![image](https://user-images.githubusercontent.com/10818702/94523279-3b829a00-0231-11eb-8425-21cb5bce6c27.png)

![image](https://user-images.githubusercontent.com/10818702/94527075-c023e700-0236-11eb-90a4-b2bb948aa4a6.png)

**Comment by jamalv** [comment]
@maxvisser what was the reason to put this on hold?

**Comment by maxvisser** [comment]
Limited time; scope was bigger then expected and design was not ready.
