### ISSUE TITLE
Placeholder for organisation, funds and products

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#180]
**Is your feature request related to a problem? Please describe.**
When a user doesnt upload a image for the organisation or product there should be a nice placeholder image

**Describe the solution you'd like**
- [x] Placeholder for organizations, funds, products @alex

**Comment by maxvisser** [comment]
@danrminds idea: maybe create one for each category using the icons from the filter menu:
![image](https://user-images.githubusercontent.com/10818702/47237094-5bbb4480-d3de-11e8-81fd-be3f5786fad6.png)

**Comment by danrminds** [comment]
What if the organisation has more categories attached?

**Comment by maxvisser** [comment]
randomize?

**Comment by danrminds** [comment]
https://www.dropbox.com/sh/f5en64ktsutigpq/AADwai71L1cT5Af3Vv41CMB1a?dl=0

**Comment by maxvisser** [comment]
do these need to be recolored based on webshop?

**Comment by danrminds** [comment]
Could be. I want to see them in this color first, and then we can decide
