### ISSUE TITLE
Provider: Can't sign-up and/or edit my organization

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1803]
## Main asssignee: @

**Start from**: Master

## Context/goal: 
I'm getting questions of organizations that can't change their name of the organization by dashboard.
They are not getting an error at all but can;t confirm the change.

I logged in as the provider to check what's going on. Console doesn't tell me anything usefull at all to give more context about this bug. 
This probleem is only occurs on production

**Comment by maxvisser** [comment]
Can't reproduce this on staging. Tested this by changed a test accounts organization name and it works. Could be a problem on master only

**Comment by maxvisser** [comment]
I can reproduce it on production aswell. I do get a js error but it is not really descriptive.

**Comment by GerbenBosschieter** [comment]
Looks like the problem isn't there anymore but now all KvK numbers het rejected :(

**Comment by maxvisser** [comment]
this first issue seems to be laravel.log not having the right permissions
