### ISSUE TITLE
Design proposal: Optimization for webshop

### ISSUE THREAD

**Issue by Myshelova** [teamforus/forus#1806]
## Context/goal: 
*currently we have some new webshops for launching without brand customization.*
https://www.figma.com/file/6mW06zt7214LgwZIoY2VVF/Requester-signupflow%3A-Project-%F0%9F%92%AF?node-id=416%3A13630
https://www.figma.com/file/o6niDcOCCRGbrt0GyM2Xfr/Activate-with-DigiD?node-id=0%3A1

**Comment by nikhilbugaliya** [comment]
This Figma named website takes a lot of time to open .. Please fix out this one..

**Comment by Myshelova** [comment]
https://github.com/teamforus/general/blob/master/manuals/design/Customisation_of_new_webshops.md
