### ISSUE TITLE
CR: Add search on provider name as seperate filter on products page webshop

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1809]
@maxvisser commented on [Mon May 04 2020](https://github.com/teamforus/general/issues/181)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal Vleij

### Change description
I had a discussion with Jamal about this CR last week. Currently our search field is able to filter on provider name but this is not really inituitive for the user (he does not know). Making it a seperate search field which auto completes on provider name helps making it more usefull.

**Comment by danrminds** [comment]
- [ ] Current search field - rename to "Zoek en actie" and search it only on action name
- [ ] Add a new field (search with suggestions) that should search specifically for provider names (and suggest providers). Name of the field: `Aanbieders`
