### ISSUE TITLE
How the system works: step-by-step

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#181]
**Is your feature request related to a problem? Please describe.**
Currently the webshop of zuidhorn contains a step by step guid
![image](https://user-images.githubusercontent.com/10818702/47066817-97d88480-d1e7-11e8-9b39-fee76b4dfb9e.png)

**Describe the solution you'd like**
We have to port this content to the new webshop. Can alex make a design @danrminds

**Comment by danrminds** [comment]
<img width="1136" alt="screenshot 2018-10-18 20 07 08" src="https://user-images.githubusercontent.com/33207036/47174660-7d9ac580-d311-11e8-8917-b942ce483890.png">

**Comment by maxvisser** [comment]
Probably need a different picture as now you dont see the laptop and its just weird looking
