### ISSUE TITLE
CR: implementation dashboard icon

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1811]
@maxvisser commented on [Wed Jun 24 2020](https://github.com/teamforus/general/issues/250)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Menu item now uses a location pin which does not really resambles what the page is about.

![image](https://user-images.githubusercontent.com/10818702/85554518-453ea500-b625-11ea-9dd1-214cb72a94e7.png)

I would suggest to change the menu image to something like a shoppingcart with a cog inside.
![image](https://user-images.githubusercontent.com/10818702/85554449-33f59880-b625-11ea-936e-21c5374e0934.png)

storefront would also be a good option (if easier)
![image](https://user-images.githubusercontent.com/10818702/85554618-61dadd00-b625-11ea-982e-45eb919814db.png)

**Comment by maxvisser** [comment]
Should be added to Atoms and Molecules; for frontend we need it in three different colors.

**Comment by danrminds** [comment]
@sashooa 

You have it in an organism, but not in the molecules. Also - the updated organism - should automatically update the library pages, which is not the case now

Also - we might need 3 colours (as in molecules):
<img width="1123" alt="Screenshot 2020-10-16 at 11 48 31" src="https://user-images.githubusercontent.com/33207036/96243793-888e9c00-0fa5-11eb-9e21-b1e7df9be748.png">
