### ISSUE TITLE
Missing screen in Signupflow figma

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1813]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/91999318-8ac1d180-ed3c-11ea-898a-235840975946.png)

**Comment by sashooa** [comment]
https://www.figma.com/file/ArDg3BA8o4uANBLk3ZVzeM/Dashboards?node-id=2148%3A0 this one ? :)

**Comment by maxvisser** [comment]
Yes thanks 👍
