### ISSUE TITLE
FAQ webshop zuidhorn

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#182]
**Is your feature request related to a problem? Please describe.**
The current webshop has a FAQ
![image](https://user-images.githubusercontent.com/10818702/47066888-d1a98b00-d1e7-11e8-96f2-9b0154543cb5.png)

**Describe the solution you'd like**
Port this content to the new system.

@GerbenBosschieter Can you look if any of the questions differ in 2.0

**Comment by danrminds** [comment]
<img width="1205" alt="screenshot 2018-10-18 20 07 16" src="https://user-images.githubusercontent.com/33207036/47174637-71166d00-d311-11e8-8b85-e2d3b7f44006.png">

**Comment by maxvisser** [comment]
Great design!
