### ISSUE TITLE
Align the buttons that are being used to open the list of products/providers.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1831]
@GerbenBosschieter commented on [Mon Oct 12 2020](https://github.com/teamforus/general/issues/523)

Learn more about change requests here: https://bit.ly/39CWeEE

### Change description
On provider and sponsor dashboard we are using different buttons that do exactly the same. We should align this so that's not confusing.

Proposal: 
- Use the button where the icon of the eye is visible and text. 
- Change text fron "Kijk" to "Openen" or "Bekijken"

<img width="48" alt="Screen Shot 2020-10-12 at 10 36 00" src="https://user-images.githubusercontent.com/38419514/95724524-c5d9ed80-0c76-11eb-96c9-8de16898c45e.png">
<img width="95" alt="Screen Shot 2020-10-12 at 10 35 53" src="https://user-images.githubusercontent.com/38419514/95724527-c6728400-0c76-11eb-9149-babe1141164e.png">

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1388
