### ISSUE TITLE
Write mail text proposal for assigning  vouchers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1833]
### Budget voucher
Budget voucher still shows the word 'voucher' probably should be tegoed.
<details>
<summary>Current mail being sent</summary>

![image](https://user-images.githubusercontent.com/10818702/95827371-f03db080-0d33-11eb-9c77-d18734c6c8df.png)
</details>

### Action voucher
For example user activates his stadjerspas and gets the QR-code in their mailbox.
<details>
<summary>Current mail being sent</summary>

![image](https://user-images.githubusercontent.com/10818702/95827371-f03db080-0d33-11eb-9c77-d18734c6c8df.png)
</details>

Should atleast contain name of fund.

### Product voucher
Mail is in context of user just buying a product in webshop. Should contain context of receiving a voucher directly from sponsor.

<details>
<summary>Current mail being sent</summary>

![image](https://user-images.githubusercontent.com/10818702/95827642-46125880-0d34-11eb-8f16-5d67a2ac8d51.png)

</details>

## Task
- [ ] Write a proposal for these three mails; context is sponsor assigning voucher to requester (via bsn or e-mail) or when a requester applies to fund through a form or activation code

**Comment by linda-90** [comment]
@maxvisser Figma proposal with all emails for citizens: https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/Mails?node-id=371%3A160&viewport=388%2C207%2C0.08348924666643143
