### ISSUE TITLE
White page after DigiD login

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1835]
## Prerequisites

1. Staging DigiD account
2. Go to webshop on groningen Staging

*Describe what is needed beforehand to be able to solve this ISSUE*

## Description

After DigiD login (signup flow, without prevalidation (i think) I ended up on a white page with only the footer. 

## Steps to Reproduce (bug report)

1. Go to groningen staging
2. Start application
3. Log in with digid
4. end up on blank page

**Reproduces how often:** Seems to appear only sometimes (few percent of the time)

**Comment by maxvisser** [comment]
Have not seen this anymore; Will close this now until its relevant again
