### ISSUE TITLE
Proposal: No price on webshop

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1842]
## Description

How to show when a product has no price and when it is free.

**Comment by jamalv** [comment]
## Goal
As a provider I would like the "free" label to be removed when I set "no price"

![Screenshot 2020-10-19 at 13.52.48.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/5b5ca753-e5ec-401d-9aeb-e4d7981efa9b)

The "free" label should be shown when:

The original price and the discount by the provider is the same (e.g. both €50) meaning the final price = free
The the original price - the discount by the provider - the subsidised price by the sponsor = free

**Comment by jamalv** [comment]
@maxvisser could you review the proposal above and plan a development task?

**Comment by maxvisser** [comment]
Currently the provider can only tell the system its free or he is limited to the 0.10 cent transactions costs of bunq

**Comment by jamalv** [comment]
Ah okay, well, that's not the most important in this issue :)

Can the other parts be planned in?

**Comment by maxvisser** [comment]
Does the me-app not be changed?

**Comment by maxvisser** [comment]
created a task
