### ISSUE TITLE
Text proposal: Text changes Test transaction Provider signup

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1846]
## Context/goal: 
Figma: https://www.figma.com/file/ZLkMhbL0c3LlHTpNKDmVh0/?node-id=0%3A1

**Comment by maxvisser** [comment]
@jamalv link to relevant figma page

**Comment by jamalv** [comment]
Figma: https://www.figma.com/file/ZLkMhbL0c3LlHTpNKDmVh0/?node-id=0%3A1

**Comment by linda-90** [comment]
Waarom moet de tekst aangepast worden? Wat is de feedback?

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/520

**Comment by linda-90** [comment]
@maxvisser Thanks, text review is done

**Comment by jamalv** [comment]
@maxvisser I see this updated text has not been implemented yet?

Current state on staging: 
<img width="854" alt="Screenshot 2020-11-15 at 12 17 04" src="https://user-images.githubusercontent.com/30194799/99183498-894d5600-273c-11eb-8967-7617c77ae03b.png">

**Comment by jamalv** [comment]
new text in figma: Bijna klaar! Tot slot, oefen alvast hoe een betaling tussen u en een inwoner werkt. Scan onderstaande QR-code met de app en doe een test betaling.

**Comment by linda-90** [comment]
@jamalv Prima tekst, akkoord!

**Comment by linda-90** [comment]
Kan deze issue worden gesloten? @jamalv Ik unassign mezelf.

**Comment by jamalv** [comment]
@maxvisser can/has this been implemented?

**Comment by maxvisser** [comment]
Is in production
