### ISSUE TITLE
Text review: Me page on webshop

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1849]
## Context/goal: 
https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa/Webshop-Me-page?node-id=0%3A1&viewport=958%2C329%2C0.9104166626930237

**Comment by maxvisser** [comment]
@linda-90 did you look at this one? could you close the issue if you have done it?

**Comment by linda-90** [comment]
✅ Yes
