### ISSUE TITLE
Text review: Product page improvements

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1875]
## Context/goal: 
https://www.figma.com/file/VvubQOugtWD50iJ0B955vl/Product-page?node-id=261%3A0&viewport=-265%2C215%2C0.565208375453949

**Comment by linda-90** [comment]
I have posted some comments in Figma @maxvisser

**Comment by linda-90** [comment]
Can you respond to the comments? Text check is not ready yet.

**Comment by maxvisser** [comment]
its already implemented?

**Comment by maxvisser** [comment]
I read the figma comments don't see any issues on staging production with the things you noted. Do you?

**Comment by linda-90** [comment]
Well, to be able to do a good text review, the context has te be clear. 
For example: Is it about an additional payment or a payment 'vanuit een tegoed'?

**Comment by maxvisser** [comment]
both

**Comment by maxvisser** [comment]
just saying this was an issue from almost a month ago. The feature is already live
