### ISSUE TITLE
E-mail about product reservation is not being send to provider

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1877]
## Context/goal: 
Provider doesn't receive an e-mail about product reservation. Only the e-mail digest.
It's about this e-mail: https://github.com/teamforus/forus-backend/blob/master/resources/lang/nl/mails/implementations/general/product_bought.php

## Task
- [ ] add e-mail back, only sent mail when products mannualy were reserved in webshop.

**Comment by GerbenBosschieter** [comment]
Product_bought is not added to:

https://github.com/teamforus/forus-backend/tree/master/app/Mail/Vouchers

**Comment by jamalv** [comment]
@GerbenBosschieter @maxvisser discussed with @dev-rminds this was disabled because of bulk product creation?

**Comment by maxvisser** [comment]
Ah yes, I remember. This was indeed a problem which would resulted in Connexxion/Nienoord being spammed with reserved mails.

**Comment by maxvisser** [comment]
I would implement it only for reserving product via webshop (implement it back)
