### ISSUE TITLE
Design review: Me page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1878]
## Context/goal: 
https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa/Webshop-Me-page?node-id=1%3A104

**Comment by jamalv** [comment]
@danrminds please update colors

@Myshelova 1 screenshot can be updated :)

**Comment by Myshelova** [comment]
@maxvisser @jamalv Updates are done (Look at the "Me app - UPD" page) https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa/Webshop-Me-page?node-id=1%3A104
