### ISSUE TITLE
CR: Logo Noordoostpolder looks distorted in IE

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1889]
@linda-90 commented on [Thu Nov 12 2020](https://github.com/teamforus/general/issues/572)
start from master

### Change description

Logo Noordoostpolder looks distorted in IE:
![nop-logo-ie](https://user-images.githubusercontent.com/36952230/98991165-c1ca1580-252b-11eb-9e37-02969411f706.png)

How it should look like:
<img width="368" alt="Schermafbeelding 2020-11-12 om 21 18 54" src="https://user-images.githubusercontent.com/36952230/98991841-b2979780-252c-11eb-94c8-9f8fff8f6f98.png">

**Comment by GerbenBosschieter** [comment]
Same counts for Groningen. And i will check if there are other ones

**Comment by maxvisser** [comment]
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/8a179efe-e8d3-4f13-84ac-fd82d71b0c54)

**Comment by maxvisser** [comment]
happens on IE 11
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/7d1ec05f-92cc-4184-aa96-61d31a9703e6)
