### ISSUE TITLE
Shouldn't need to scroll to view image rights checkbox

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1890]
@jamalv commented on [Sat Nov 14 2020](https://github.com/teamforus/general/issues/577)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Probably modal should be wider or something.

<img width="830" alt="Screenshot 2020-11-14 at 14 29 09" src="https://user-images.githubusercontent.com/30194799/99148049-e0dcba80-2685-11eb-93b2-e2b537e2a43e.png">

<img width="838" alt="Screenshot 2020-11-14 at 14 29 13" src="https://user-images.githubusercontent.com/30194799/99148053-ea662280-2685-11eb-86d2-9930b7761f7e.png">

https://www.figma.com/file/Cgyc4oG77eT6yH8OQpGktr/?node-id=176%3A137

**Comment by jamalv** [comment]
@maxvisser Why did you assign me? I think this needs a design review?

**Comment by jamalv** [comment]
Or maybe it can be easily fixed in code by making some things wider?

**Comment by jamalv** [comment]
Just checked on staging, no longer seems to be an issue.
