### ISSUE TITLE
Bug: Editing business hours bug in provider dashboard

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1891]
## Main asssignee: @

**Start on branch:** Master

## Context/goal: 
We currently have a problem with editing business hours on provider dashboard. The providers can't do any adjustments.  after filling in the provider sign up flow. I gave this issue a hotfix priority. Our biggest client has invited alot of providers and this is there first experience and we already have some complaints.

Below two images. One what you see visually, the other response of the console.

<img width="653" alt="Screenshot 2020-11-16 at 22 18 48" src="https://user-images.githubusercontent.com/38419514/99309449-ba6f7880-2859-11eb-87c8-4c4534a0c5fd.png">

<img width="821" alt="Screenshot 2020-11-16 at 21 54 55" src="https://user-images.githubusercontent.com/38419514/99308924-f524e100-2858-11eb-8db1-787dcf53e645.png">

**Comment by GerbenBosschieter** [comment]
Could the be a js minify issue?

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/99363263-d05e5700-28b4-11eb-976b-e370e731eef1.png)

**Comment by maxvisser** [comment]
Not sure why I don't see what you see.

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/99363857-8aee5980-28b5-11eb-807e-72619474086b.png)

**Comment by maxvisser** [comment]
shows:
![image](https://user-images.githubusercontent.com/10818702/99363888-9477c180-28b5-11eb-8c69-aa43c8107b3d.png)

**Comment by maxvisser** [comment]
seems to be aswell a bug with previewing the dates, it shows the incorrect labels

**Comment by maxvisser** [comment]
seems to be a bug which when there is no weekday 1 the script for parsing the office data will crash as there is no start date for weekday 1 (as its not existent)

**Comment by danrminds** [comment]
@maxvisser Is this deployed? Can it be closed?

**Comment by maxvisser** [comment]
i

**Comment by maxvisser** [comment]
it is
