### ISSUE TITLE
Design review. Me app page on Webshop

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1893]
## Context/goal: 
CR: https://github.com/teamforus/general/issues/496
Figma: https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa/Webshop-Me-page?node-id=1%3A104

**Comment by danrminds** [comment]
Make the screen in the phone use the original colors, not red.

**Comment by sashooa** [comment]
Me app page https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa/?node-id=85%3A445

**Comment by jamalv** [comment]
@Myshelova the screenshots should be generic; I have added suggestions: https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa?node-id=100:87#50102195
