### ISSUE TITLE
Update styling of provider sign-up flow depending on a parameter in the URL

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1896]
## Context/goal: 
We want to pass a parameter to the signup URL for providers, pointing to a certain implementation. 
**Example:** https://forus.io/provider/sign-up?implementation=groningen

We need to use the branding of that implementation in the sign-up flow. 

**Optional:**
 - [ ] Use of logo
 - [ ] Use of menu and footer from the implementation

**Comment by jamalv** [comment]
To give extra context on this task:

Every municipality gives out a URL for their providers to sign up. They send it on social media, put it in flyers, etc. Therefore they would like the URL as easy (and dutch) as possible.

This URL should give as good and trustworthy as an experience as possible, from start to finish. This leads to more organisations in the platform and happier providers lead to happier municipalities :)

The URL to start signing up providers is needed early in the implementation proces so should be easy to set up. Ideally, in the implementation CMS you can set a slug for this URL forus.io/berkelland-aanbieder for example. This URL should:

- Filter on funds for that implementation, in the fund overview of the signup-flow
- Show custom styling linked to that implementation (optionals described in task)

**Comment by maxvisser** [comment]
- how do want to get the logo (use tags or implementation key)
- where do we get the logo from?
