### ISSUE TITLE
Design login screen page

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1901]
## Context/goal: 
https://forus.io/
We now have this login modal:
![Screenshot 2020-11-18 at 17 37 37](https://user-images.githubusercontent.com/33207036/99559175-c592e780-29c4-11eb-8c56-562020d8bcea.png)

 - We need to make a version as a separate page (with empty white background, centered box with same contents)
 - Add button and text - `If don't have yet an account - Sign up here`
 - After logged in we need a screen to display a success message and the option to choose what environment you want to login into:
    - Als sponsor
    - Als validator
    - Als aanbieder (provider)

**Comment by sashooa** [comment]
https://www.figma.com/file/ubb2ZdHjOYaAc1wGk3mTCt/Login-met-e-mail-Proposal
