### ISSUE TITLE
Update library and migration of pull-requests to library

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1902]

**Comment by jamalv** [comment]
I want to propose a new workflow here as well.

1. The team makes new proposals and ends up with a **review** page. This includes text and a concept design.
2. The designer @sashooa reviews the page and adds the frame **directly in the library** including final design review.
3. The a **master component** is made out of the master page frame, and the instance is added to the original separate figma file in the **"master"** tab.
4. The figma file gets a big "master" checkbox on the cover, and the file is handed of to developement
5. After development is done, the file can be directly moved to the archive, no pull-request needed, it's already in the library.
