### ISSUE TITLE
Proposal: API Backoffice connection

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1905]
## Main asssignee: @maxvisser 

Document: https://docs.google.com/document/d/1CJIzLuhm9Zz_URL4wuT_sed-ddoRZxzYZj7zCQV64MI/edit#

## Context/goal: 
Please finish the proposal together with Valentin. The spec that we use here should be re-usable for other implementations :)

Timeline: we'd like to send it on Monday

**Comment by maxvisser** [comment]
wrote out more specs. send it to review to valentin

**Comment by maxvisser** [comment]
Proposal has been made now up for review by stakeholders.

**Comment by maxvisser** [comment]
moved to next week
