### ISSUE TITLE
Pricing options (no price, free and discount only) in dashboard

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1907]
## Context/goal: 
https://www.figma.com/file/siGNnFJekZbRAlTVQp2rai/?node-id=37%3A1463

<img width="674" alt="Screenshot 2020-11-24 at 10 57 14" src="https://user-images.githubusercontent.com/33207036/100071536-d53a8200-2e43-11eb-8078-e6ddffdce446.png">

**Comment by danrminds** [comment]
https://github.com/teamforus/forus/issues/1853

**Comment by maxvisser** [comment]
I added the figma abit; I think it should work like this:
User fills in or a price or check 'no price'
if he check no price he enables the option 'This product is free' and 'This is a discount'
If he selects 'This is a discount' it will enable the discount field
