### ISSUE TITLE
Text review: No funds applied yet

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1913]
![image](https://user-images.githubusercontent.com/10818702/100103598-653cf380-2e65-11eb-8398-96e2f5c574e3.png)

## Context
A provider adds his product but he did not apply for any funds yets in the signup (he skipped that step).
He goes to his dashboard and creates a product. 

## Task
We need a translation text for this empty block. In this block we normally show all accepted fund requests.

**Comment by linda-90** [comment]
Uw aanbod kan nog niet op een website worden geplaatst omdat u zich eerst voor een fonds moet aanmelden.
Meld u aan voor één of meerdere fondsen.
