### ISSUE TITLE
Text review: Approving multiple funds

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1923]
@GerbenBosschieter commented on [Thu Apr 23 2020](https://github.com/teamforus/general/issues/165)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- One our implementations
- Team members

### Change description
**Current**
- The current layout of the sponsor dashboards allows the sponsor to: 
    -> Click **Providers** -> Select fund -> Get providers list -> accept or reject

**Change**
- Changing the user flow into something similar as the webshop will give a better overview and will allow the sponsor to:
    -> Click **Providers** -> Get provider list -> Select provider -> select which fund or offer should be accepted/rejected 

Using this flow will open options to give the sponsor see more relevant data at once.
I would even suggest that splitting "Providers" & "Offers" like the webshop would be something to consider. We are developing new features that will give the sponsor more options and control. Changing the UX of this part of the dashboard is something we could consider.

**Possible MVP**
- Adding more context at provider cards about which fund they are connected to.

https://www.figma.com/file/FzkMCqhlv7U3zU5evcOnz2/%F0%9F%94%B5Approving-multiple-funds

**Comment by linda-90** [comment]
did a text review, see comments
