### ISSUE TITLE
When selecting unlimited stock while you already filled in a stock amount product adding does not work anymore

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1926]
## Prerequisites

1. account with organization

## Description

creating a product with unlimited stock

## Steps to Reproduce (bug report)

1. create product
2. fill in test data for title, description and price, category, end date
3. fill in 100 stock, and press unlimited stock checkbox right after
4. product can't be submitted, no errors.

*Give a step by step guide to reproduce the bug*

**Expected behavior:** Even if user fills in a stock amount before checking unlimited stock, unlimited stock checkbox should have priority

**Actual behavior:** user can't submit form

**Reproduces how often:** 100% of the time

**Comment by maxvisser** [comment]
@MichaelForus we can't reproduce it anymore could you help us check it?

**Comment by MichaelForus** [comment]
@maxvisser the problem seems to have disappeared. I can no longer reproduce it either.

**Comment by maxvisser** [comment]
Thanks for your help. Will close this one until we can reproduce it.
