### ISSUE TITLE
When creating a product voucher, product id is not valid

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/forus#1931]
## Description
Not able to create a product voucher by bulk or manually. it wrongly says that the product id is not valid

## Steps to Reproduce (bug report)

1. Go to product voucher page
2. upload csv, or click "aanmaken"

*Give a step by step guide to reproduce the bug*

**Expected behavior:** 
Product vouchers are created

**Actual behavior:** 
By csv:
![image](https://user-images.githubusercontent.com/48722300/100618216-d1af6b00-331b-11eb-9a31-97b2741079ac.png)
Manually:
![image](https://user-images.githubusercontent.com/48722300/100618298-ef7cd000-331b-11eb-8098-8328c035e956.png)

**Reproduces how often:** 
Always

**Comment by SjoerdHilhorst** [comment]
could you try to reproduce it max?

**Comment by maxvisser** [comment]
You can't generate product vouchers for subsidy funds

**Comment by maxvisser** [comment]
@dev-rminds not sure why you can't could maybe eleborate?
