### ISSUE TITLE
Design change: Webshop Me page has email in screenshot change this to e-mail

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1932]
@GerbenBosschieter commented on [Wed Dec 02 2020](https://github.com/teamforus/general/issues/612)

Learn more about change requests here: https://bit.ly/39CWeEE

### Figma
https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa

### Change description
- Please stop using email. In dutch in means something else than in english.
Use different screenshot where email is e-mail.
<img width="279" alt="Screenshot 2020-12-02 at 09 44 11" src="https://user-images.githubusercontent.com/38419514/100849948-5ec10400-3483-11eb-83dc-4227cf55b550.png">

**Wrong**
<img width="1360" alt="Screenshot 2020-12-02 at 09 44 05" src="https://user-images.githubusercontent.com/38419514/100849945-5d8fd700-3483-11eb-988e-f1a7a4896c76.png">

**Alternative screenshot**
![IMG_C32AD9C01774-1](https://user-images.githubusercontent.com/38419514/100849985-6f717a00-3483-11eb-8517-fe0b4e1f4590.jpeg)

**Comment by maxvisser** [comment]
@danrminds its about change the screenshot used in the left most phone to a this new screenshot

**Comment by maxvisser** [comment]
https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa

**Comment by sashooa** [comment]
https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa/?node-id=85%3A445
