### ISSUE TITLE
Design proposal: Provider activity

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1934]
## Context/goal: 
Show on providers list the time that a provider was inactive. 

How to display inactivity:
- Calculate average, below average activity, above average activity

![image](https://user-images.githubusercontent.com/10818702/100888502-7bc2fa80-34b6-11eb-8d6a-df3974c8ece1.png)

How to display information
progress bar
text 
dots
blocks which are days/weeks/months/years

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/100888479-74035600-34b6-11eb-8a23-76831cae8c39.png)

**Comment by sashooa** [comment]
https://www.figma.com/file/Xo6zjqJtKYUqTQU57acxmS/Provider-activity?node-id=1%3A4266

**Comment by danrminds** [comment]
@maxvisser Please check the 2 options designed and make a choice.

**Comment by maxvisser** [comment]
I would do the text one and show the time of inactivity in days / weeks / months / years

**Comment by maxvisser** [comment]
I like the blocks aswell. But this is probably better for the details page. Currently you miss too much context on what it is. (how it works)
