### ISSUE TITLE
BUG: Can't edit products that have a price (system says 'no price' field is mandatory)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1939]
## Main asssignee: @
fix from master

## Context/goal: 

```
{message: "The given data was invalid.",…}
errors: {no_price_type: ["Het Geen prijs type veld is verplicht wanneer Geen prijs aanwezig is."]}
message: "The given data was invalid."
```

## Task
How to reproduce: 
create a product with a price;
Try to edit product with a price;

- [ ] fix bug

**Comment by GerbenBosschieter** [comment]
only happens if you want to edit the product. not adding

**Comment by maxvisser** [comment]
{message: "The given data was invalid.",…}
errors: {no_price_type: ["Het Geen prijs type veld is verplicht wanneer Geen prijs aanwezig is."]}
message: "The given data was invalid."
