### ISSUE TITLE
Missing Translation: You have not applied to any fund yet

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1941]
## Context/goal: 
<img width="1002" alt="Screenshot 2020-12-04 at 08 29 51" src="https://user-images.githubusercontent.com/38419514/101134656-03218280-360b-11eb-85a6-e9019118c4ea.png">

**Comment by maxvisser** [comment]
Already a task for to implement it. This is a duplicate

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1935
