### ISSUE TITLE
Product description limit

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1943]
## Context/goal: 
Can we make the limit of product description longer? I've tried to add a lot of products/services from products that are being used at the old Stadjerspas system. Like 80% of these description are too long for our platform. 

Would also be nice for the provider to have more space so they can add any additional information fr times like these (corona). This could visually influence the product card on the webshop because of the image of the product. Maybe split the image from the description?

### Reason
We are currently in the onboarding process of providers for stadjerspas. Hundrerds of products/services will be added and we only have a couple weeks left. The proces of adding these products will probably a lot of copy/paste stuff. But this will not work for them  and they need to rethink all descriptions :(

Example: https://stadjerspas.nl/activiteit/2271

## Task
- [ ] Increase product description character limit to 2500 characters.

Nice to have: show character count and max amount of characters below description box

**Comment by GerbenBosschieter** [comment]
Adding products n behalf providers now. Character limit is set to 1000. This isn't enough for a lot o descirptions. As a mentioned before. Limit of 2500

**Comment by maxvisser** [comment]
its a bug; should already 2500; we only implemented it on Update

**Comment by maxvisser** [comment]
Fixed it on a PR https://github.com/teamforus/forus-backend/pull/1032
