### ISSUE TITLE
As a sponsor I would like to do a contribution to an action that is has no price an is a discount

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1946]
## Context/goal: 
This one sound weird but is really important for a lot of use cases. Please use the following issue as a scenario: https://github.com/teamforus/forus/issues/1944

The scenario mentioned above is not only giving a discount of € 20,-.  The provider doesn't really do the discount of € 20,-. They expect that the € 20,- will be payed by the municipality.

This is not possible in the platform. 

#### Important
the following issue is part of this https://github.com/teamforus/forus/issues/1944

## Task
- [ ] Sponsor should add subsidy amount even if there is no price set by provider

Allow sponsor to subsidize more then price (even if its free) to a maximum of €2.500,-

**Comment by maxvisser** [comment]
Sponsor should add subsidy amount even if there is no price set by provider

**Comment by maartenfv** [comment]
@maxvisser Do you have an update? As it is high prio?

**Comment by maxvisser** [comment]
currently still on the sprint backlog. No progress has been made. I am also not sure if this is still an high priority as there is a fix for this. (i believe) @GerbenBosschieter Could you assess this?

**Comment by maartenfv** [comment]
@jamalv As this is high prio it needs to be solved asap. Can you give a plan and time line?

**Comment by jamalv** [comment]
@maxvisser could you detail what you believe to be the fix?

**Comment by maxvisser** [comment]
Discussed this one last week with gerben. The quick fix is online and this not high priority anymore.

**Comment by maxvisser** [comment]
Allow sponsor to subsidize more then price (even if its free) to a maximum of €2.500,-
