### ISSUE TITLE
Design review: Provider overview page

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1947]
@jamalv commented on [Sat Dec 05 2020](https://github.com/teamforus/general/issues/628)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a provider I would like an overview of what's expected of me after completing the signupflow.

This is a proposed solution to https://github.com/teamforus/general/issues/624

Another important reason: right now provider's have a conceptual "gap" after sign in, it's very unclear that you should start adding some offers in order to start making some profits. This page will hopefully help with that problem as well.

Figma: https://www.figma.com/file/hJS4uLSGgA1cMdyVtqDinG/?node-id=1%3A80

## Proposal:
![image](https://user-images.githubusercontent.com/30194799/101246205-22570780-3712-11eb-808d-4b70f97c3f5e.png)

**Comment by jamalv** [comment]
@danrminds could you please review this design with sashoa? The goal is to keep the scope the same but just make sure the styling and buttons are aligned.

**Comment by danrminds** [comment]
https://www.figma.com/file/hJS4uLSGgA1cMdyVtqDinG/?node-id=9%3A745
