### ISSUE TITLE
Design review: add CMS block for provider page to figma

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1950]
@jamalv commented on [Mon Dec 07 2020](https://github.com/teamforus/general/issues/636)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As an implementation owner I’d like to add my own information to the provider page

Figma: https://www.figma.com/file/00iERh8W6ouVGJV7Khcx91/?node-id=0%3A1

## Add Extra block to CMS:
<img width="996" alt="Screenshot 2020-12-07 at 10 46 06" src="https://user-images.githubusercontent.com/30194799/101335500-93fd9580-3879-11eb-8996-28b3f8d6081b.png">

## Add content to provider page:
<img width="532" alt="Screenshot 2020-12-07 at 10 47 47" src="https://user-images.githubusercontent.com/30194799/101335559-a7106580-3879-11eb-81a9-dc0e6adb3b66.png">

**Comment by danrminds** [comment]
@sashooa - content you can use from here for the design review: https://stadjerspas.nl/pagina/organisaties

**Comment by jamalv** [comment]
@danrminds @sashooa Please pay attention; the page content will be loaded from the CMS so it will be user generated. I don't even know if any design review is needed here?

**Comment by danrminds** [comment]
I got that part, Is more on the styles (design) of how that content will be displayed from markdown. That is why I thought to review that screen as well. But I assume it will be same as the one on top? In that case no need for that to be reviewed.

**Comment by jamalv** [comment]
Lena made some documentation about typography: https://github.com/teamforus/general/blob/master/manuals/design/typography-styleguides.md

The current results (including review) is: https://stadjerspas-acc.gemeente.groningen.nl/explanation

I think if we can use the same styling we'll be good :D

**Comment by jamalv** [comment]
Actually, maybe it's more about aligning the text on top (title and subtitle) with styling from the CMS, to make sure the whole page has the same styling and it doesn't feel too much like two seperate parts.

**Comment by sashooa** [comment]
https://www.figma.com/file/00iERh8W6ouVGJV7Khcx91/?node-id=20%3A0
