### ISSUE TITLE
Text review:  E-mail confirmation follow-up

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1954]
## Context/goal: 
https://www.figma.com/file/1qV7a2t0XTbFnmlXPlduJk/Email-confirmation-followup?node-id=3%3A2&viewport=597%2C547%2C0.6333333253860474

Proposal: show the normal email confirmation page with a link: how to continue? when they click the link we give them a smal f.a.q. about how to continue. (were you just signing in? you can close this page. were you applying trough a form? please continue on the form.)

**Comment by linda-90** [comment]
Check!
