### ISSUE TITLE
Implement E-mail confirmation follow-up

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1955]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/101359562-be147f00-389c-11eb-8b3c-27cf57ec5510.png)

https://www.figma.com/file/1qV7a2t0XTbFnmlXPlduJk/?node-id=131%3A0

**Comment by SjoerdHilhorst** [comment]
I cant find where this would be located

**Comment by maxvisser** [comment]
Hi @SjoerdHilhorst 
This is the 'forus-backend' angular project in forus-fronted repository

**Comment by SjoerdHilhorst** [comment]
I still need a little more context? when does this page show up, is there already a different page that show up?

**Comment by maxvisser** [comment]
How to get to this page:

Install Me-app
Login on Me-app using mailadress
Click on link in e-mail

**Comment by maxvisser** [comment]
Yes this is basically adding a link on an existing page and add a page with extra context.
