### ISSUE TITLE
Validator dashboard: fund request remove functionality to approve/deny single records

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1956]
@maxvisser commented on [Tue Nov 24 2020](https://github.com/teamforus/general/issues/593)

Learn more about change requests here: https://bit.ly/39CWeEE

### Change description
I find that the way we implemented approving and denying single records is incomplete. I propose to add a frontend flag to disable this for now and add it to the list of unreleased features.

![image](https://user-images.githubusercontent.com/10818702/100076722-d074ce80-2e41-11eb-9ccf-19eb72b3aa0f.png)

## Task
- [ ] add a frontend flag to hide denying / approving single records
- [ ] change text for approving all / deny all records.
Alles valideren -> Goedkeuren
Alles weigeren -> Weigeren

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/forus-frontend/pull/1519
