### ISSUE TITLE
Change text: Digest of notification to sponsor about actions which changed price.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1957]
## Description

![image](https://user-images.githubusercontent.com/10818702/101362804-e1d9c400-38a0-11eb-8813-97d72ee6dbee.png)

## Task
- [ ] translate text of notification:
[provider_name] heeft de prijs aangepast van het aanbod "[product_name]"
De prijs voor het aanbod "[product_name]" is aangepast. Hierdoor is het aanbod verwijderd van de website.
Accepteer het aanbod om het opnieuw op de website te plaatsen.

**Comment by SjoerdHilhorst** [comment]
vgm staat dit in de translation database, daar kan ik niet bij

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-backend/blob/f5e2cc0824c3831fcc418ed1a52090075c4eb17c/resources/lang/nl/notifications/notifications_funds.php#L44

**Comment by maxvisser** [comment]
seems to have already a translation (maybe I added it so atleast there would be a dutch text )
