### ISSUE TITLE
Show provider activity per fund (on the list of providers

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1961]
## Context/goal: 
https://www.figma.com/file/Xo6zjqJtKYUqTQU57acxmS/Provider-activity?node-id=1%3A4266

Use the text information option (not the one with dots)
<img width="957" alt="Screenshot 2020-12-08 at 08 52 59" src="https://user-images.githubusercontent.com/33207036/101455407-d3d48380-3932-11eb-9be3-0e87edd9e907.png">

**Show activity based on:**
days / weeks / months / years. 

**Example:**
- Today
- 1 day ago
- 5 days ago
- 1 week ago
- 2 weeks ago
- 1 month ago
- 2 months ago
- more than a year ago

**Comment by danrminds** [comment]
@jamalv @maxvisser Can you please add the translations here in dutch for the available options considering singular / plural?

**Comment by maxvisser** [comment]
Vandaag
1 dag geleden
5 dagen geleden
1 week geleden
2 weken geleden
1 maand geleden
2 maanden geleden
Meer dan een jaar geleden
