### ISSUE TITLE
BUG: Can't see any transactions on webshop on my BUDGET voucher

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1963]
## Context/goal: 
I don't know how. But somehow the transaction overview is gone on the webshop.  My assumption is that we focus so much on Stadjerspas that we did a change that effects another implementation and we released it without checking.

Last two releases where without acceptance testing. So probably something with the last two releases.

This bug in combination with the problem on the android the app that vouchers are not shown, results in problems for our current users. They can't see their budget and their transactions.

**Comment by GerbenBosschieter** [comment]
<img width="738" alt="Screenshot 2020-12-08 at 15 01 33" src="https://user-images.githubusercontent.com/38419514/101495132-73f8cf80-3968-11eb-9488-b63502722764.png">

**Comment by maxvisser** [comment]
Fixed
