### ISSUE TITLE
add CMS block for provider page

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1965]
## Context/goal: 
https://www.figma.com/file/00iERh8W6ouVGJV7Khcx91/?node-id=20%3A0

As an implementation owner I’d like to add my own information to the provider page

Figma: https://www.figma.com/file/00iERh8W6ouVGJV7Khcx91/?node-id=0%3A1

## Add Extra block to CMS:
<img width="996" alt="Screenshot 2020-12-07 at 10 46 06" src="https://user-images.githubusercontent.com/30194799/101335500-93fd9580-3879-11eb-8996-28b3f8d6081b.png">

## Add content to provider page:
<img width="532" alt="Screenshot 2020-12-07 at 10 47 47" src="https://user-images.githubusercontent.com/30194799/101335559-a7106580-3879-11eb-81a9-dc0e6adb3b66.png">

**Comment by maartenfv** [comment]
Should be a separate page? 
1. Add uitleg pagina voor aanbieders (providers)
2. Uitleg needs to be a seperate page
3. Inwoners and aanbieders do not want to be on the same page.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/0cf775b9-4a04-40ce-a400-5c79702b5d7f)

**Comment by maxvisser** [comment]
it is maarten. this is about https://stadjerspas.gemeente.groningen.nl/aanbieder-aanmelden

**Comment by maxvisser** [comment]
Could you add your comments to the CR? as this can maybe be confusing for the team (if you reply somethings which are not in the original CR)

**Comment by maartenfv** [comment]
Where is the CR?
