### ISSUE TITLE
Provider overview page (dashboard)

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1966]
## Context/goal: 
https://www.figma.com/file/hJS4uLSGgA1cMdyVtqDinG/?node-id=9%3A745

<img width="945" alt="Screenshot 2020-12-09 at 09 04 24" src="https://user-images.githubusercontent.com/33207036/101602189-00090680-39fe-11eb-89dc-38ce9180f2e0.png">

You need to display in the boxes the following information:

### Aanbod
The number of offers you have as a provider.
Button -> Create a new product

### Actieve fondsen
How many funds you can apply to.
Button -> For fund application, would it be possible to link directly to “available” funds, instead of “active”? - I will be more logical for providers :)

<img width="612" alt="Screenshot 2020-12-09 at 09 05 41" src="https://user-images.githubusercontent.com/33207036/101602207-0ac39b80-39fe-11eb-84a1-49215b678f87.png">

### Inkomsten
Here display how much income you did via sales in total
Button -> view transactions

### Medewerkers
Show how many employees you have
Button -> Add new one

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-frontend/pull/1527
