### ISSUE TITLE
Link footer of some e-mail goes towards localhost

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1967]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
![image](https://user-images.githubusercontent.com/10818702/101808584-d0015680-3b16-11eb-9cd2-2d7f0fe8d513.png)

**Comment by maxvisser** [comment]
not all emails do get localhost. We only saw this bug on employee invite

**Comment by maxvisser** [comment]
Can't be reproduced locally

**Comment by aghimpu** [comment]
Can't reproduce it either

**Comment by maxvisser** [comment]
Seems to be an issue with worker who sent the mail using local host as app url
