### ISSUE TITLE
No navbar returning from login page

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/forus#1970]
## Context/goal: 
on https://dev.forus.io
Going to previous page (homepage) from here
![image](https://user-images.githubusercontent.com/48722300/102062354-e815f600-3df4-11eb-9f03-29944e788386.png)
The navbar doesn't appear:
![image](https://user-images.githubusercontent.com/48722300/102062497-1f84a280-3df5-11eb-8e73-8194a338c915.png)

**Comment by maxvisser** [comment]
Thanks for pointing this out;
https://github.com/teamforus/forus-frontend/pull/1535#issuecomment-744360848
