### ISSUE TITLE
Reason for denying a fund request is not saved

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1977]
@maxvisser commented on [Tue Nov 24 2020](https://github.com/teamforus/general/issues/594)

### Description
If a validator denies a fund request we do not save what he sents to the citizen; I see a potential issue with not saving this information and showing it to the validator:
1. validator denies citizen on 1 jan, fills in 'U bent geweigerd omdat u een inkomen heeft boven x x"
2. Citizen calls on 7 of jan and asks for the reason
3. Validator can't check anymore why he denied said person.

Proposal 
Must have: save what validator fills in to a 'note' field in the database.

Should have: Show it somewhere on the card after pressing the button

**only applicable for deny all or approve all**

**Comment by maartenfv** [comment]
I agree that this is an important issue. There are probably legal consequences in regards to denying. Paper trail is Must-have.

**Comment by dev-rminds** [comment]
@maartenfv We actually do save the rejection reason in the database, it's just not displayed anywhere yet.
