### ISSUE TITLE
Design review: Show loading progress when uploading files in signupflow

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1980]
## Context/goal: 
As a requester I would like to see loading progress when uploading a file in the signupflow.

FIGMA: https://www.figma.com/file/huSnGMIbPkUvIBJPImkojw/?node-id=0%3A1

![Screenshot 2020-12-17 at 11 12 19](https://user-images.githubusercontent.com/33207036/102474644-2d3a6200-4059-11eb-919d-74a6ed6c824a.png)

**Comment by sashooa** [comment]
https://www.figma.com/file/huSnGMIbPkUvIBJPImkojw/?node-id=0%3A1
