### ISSUE TITLE
Introducing Me: Text and URL on connection modal

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1983]
## Context/goal: 
As an implementation owner I'd like a better introduction to the me app on (probably) the first page where people learn about it (from voucher page)

## Suggestion
Figma: https://www.figma.com/file/UuOGYY6mdunE4lh9MVhN9m/?node-id=1%3A80

<img width="819" alt="Screenshot 2020-12-08 at 13 01 03" src="https://user-images.githubusercontent.com/30194799/101481429-76056300-3955-11eb-9430-bbf5a08cd955.png">

**Comment by maxvisser** [comment]
This is on the webshop (you can go to this modal via voucher details page (use QR-code button)
