### ISSUE TITLE
Some changes to Nijmegen webshop

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1988]
## Main asssignee: @

**Support ticket: #2555**

Nijmegen checked the Meedoen website to see uf there are any changes needed for next year. There two changes needed.

## Context/goal: 
**Footer**
- [x] Change contact e-mail from gemeente@nijmegen.nl to meedoen@nijmegen.nl 

**FAQ**
- [x] Make sure all expiration dates are correct and changed to 01-01-2021 (not sure if this done with variable or not)

**Comment by maxvisser** [comment]
Probably there alot of hardcoded 2020's to be changed. Lets see if we can replace those with some variable so this will not be an issue for next year.

**Comment by maxvisser** [comment]
The e-mailadres change in footer can be directly planned. The expiration date needs a bit of research to see where it is hardcoded.

**Comment by SjoerdHilhorst** [comment]
its done with a variable, probably need to change it in db
https://github.com/teamforus/forus-frontend/blob/ec1a029e23eaa71ac13ce99b7cc767eaea1e49c2/src/sources/forus-webshop/pug/tpl/pages/explanation.pug#L93

**Comment by maxvisser** [comment]
Seems to be hardcoded. Changed the dates in the database but on a step of applying and validity question on FAQ still have 2020

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/103507159-d2797680-4e5e-11eb-8276-d3d8301be977.png)
We should also change this to 2021 or remove the year
