### ISSUE TITLE
Design review: Role switching

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/forus#1993]
## Context/goal: 
CR: https://github.com/teamforus/general/issues/635

Design: https://www.figma.com/file/DqaXCJzRWhLLYFOuhbKPYK/Role-switching-in-dashboards-footer?node-id=1%3A11

![image](https://user-images.githubusercontent.com/48722300/102894581-9e1bb880-4463-11eb-937a-462b4164edcc.png)

**Comment by jamalv** [comment]
@SjoerdHilhorst Sweet 👍 - I think there will be 3 different states? Neutral, hover and active? Could you add those 3 states? and @danrminds / @sashooa please also have a look at the proposal.

**Comment by danrminds** [comment]
Design reviewed

**Comment by jamalv** [comment]
Implementation task: https://github.com/teamforus/forus/issues/2031
