### ISSUE TITLE
Update voucher card: make opening modal links more prominent

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1996]
@jamalv commented on [Mon Dec 07 2020](https://github.com/teamforus/general/issues/631)

### Change description
It is currently unclear (user testing) what is expected of the user. 

MVP is updating the styling to clarify the call to action, we can think about bigger iterations after that.

Figma: https://www.figma.com/file/mWmn4EgY0eh1FDye0dIJWE/?node-id=0%3A1

## Current state:
![image](https://user-images.githubusercontent.com/30194799/101322626-a373e300-3867-11eb-84ac-ed78d29e91cb.png)

@maxvisser commented on [Tue Dec 08 2020](https://github.com/teamforus/general/issues/631#issuecomment-740676362)

Looked at this abit; I think making the links more prominent is maybe not even the fix; I would suggest to maybe even add the actions back direct on the card;

Something like this:
![image](https://user-images.githubusercontent.com/10818702/101501032-84607880-396f-11eb-9201-58b3551cd993.png)

**Comment by jamalv** [comment]
@maxvisser what's the status of this one? Will it be in 18.1?

**Comment by maxvisser** [comment]
its in 18.1
