### ISSUE TITLE
Sponsor requirements

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2]
## Dashboard
Select how much to fund / add funds
 - select total funding
 - set incentives for collaborators: validating and providing

Select who to fund ["criteria" - "value"]
 - select validators for criteria ["criteria" - "validator(addr)"]

Select what to fund
 - the person [just giving money]
 - providers [ability to shop at certain shop]
 - products [product - provider (/shop validated by)]
   - set maximum product value
 - select allocation of funds (%)

Crowdfunding (available to the public, cannot edit fund)
 - select fund
 - select what to fund
 - select amount to fund

**Comment by maxvisser** [comment]
Let's make this issue more concrete. I think it would be a good idea to write up user stories and put every user story in a group. I can think of two groups: forus sponsor 'core' and sponsor 'extensions'.

Something like:
As a < type of user >, I want < some goal > so that < some reason >.
As a sponsor, I want to sponsor an amount of tokens that can be offered when criteria's are met.
As a sponsor, I want to select validators so that a certain criteria can be met.

**Comment by maxvisser** [comment]
![decision_tree_wireframe](https://user-images.githubusercontent.com/10818702/38503943-b5cc6da4-3c13-11e8-8bdf-13f105680cb4.png)

Decision tree wireframe based on Microsoft Flows. A sponsor can set criteria based on conditions and action. A action can be a 'Succes', 'End' or another condition.

**Comment by jamalv** [comment]
https://www.w3.org/TR/verifiable-claims-data-model/#what-is-a-verifiable-claim?

**Comment by jamalv** [comment]
https://docs.google.com/spreadsheets/d/1InhbzK2nPlk53naOPQ6S8Ac578U2YBUocC47--fB2d8/edit#gid=1067907813

**Comment by maxvisser** [comment]
## Categories for Forus 'aanbiedingen'/'products'
Got these category's from Speurders.nl from the main category 'child and baby':
Carseets Maxi Cosi - Autostoeltjes Maxi-Cosi
Autostoeltjes overige merken
Babyfoons
Babykleding maat 38-44
Babykleding maat 50-62
Babykleding maat 68-74
Babykleding maat 80-86
Babykleding overige
Babywiegjes
Diversen en overige
Kinderbadjes en accessoires
Kinderbedjes
Kinderboxen
Kinderkleding jongens maat 116-134
Kinderkleding jongens maat 140-158
Kinderkleding jongens maat 164-176
Kinderkleding jongens maat 92-110
Kinderkleding jongens overige
Kinderkleding meisjes maat 116-134
Kinderkleding meisjes maat 140-158
Kinderkleding meisjes maat 164-176
Kinderkleding meisjes maat 92-110
Kinderkleding meisjes overige
Kindermeubels en kamers
Kinderstoelen
Kindervideo's en DVD's
Kinderwagens en wandelwagens
Kledingpatronen
Knuffeldieren
Oppas gevraagd en aangeboden
Rugdragers en buikdragers
Toys - brand/type
  Speelgoed - Fisher Price
  Speelgoed - Lego
  Speelgoed - Playmobil
  Speelgoed - bordspellen
  Speelgoed - buiten
  Speelgoed - diversen
  Speelgoed - poppen
  Speelgoed - puzzels
  Speelgoed - racebanen
  Speelgoed - radiografisch
  Speelgoed - skelters
Traphekjes
Wipstoeltjes

**Comment by maxvisser** [comment]
New requirements 12-04-2018

validation v1
zuidhorn - forus
leengeld -forus
groningen - forus
digid - forus

sponsorship v1
add to existing fund
(original sponsor pays and allocates new funds from 'stichting leergeld')

**Comment by GerbenBosschieter** [comment]
I already talked with @maxvisser about the appropriate way to document this, I will comment them in this issue for now. Feedback is welcome :)

This list is work in progress.

- [ ] As a sponsor I want to be able to register on the me app so I can let my organisation be validated by certified validators (stichting leergeld -> gemeente) [ How to apply, users ]

- [ ] As a sponsor I want to be able to set an expiring time for the budget I make available so I can have control over the budget. [ How to add budget, sponsor ]

- [ ] As a sponsor I would like to have an overview of the amount of people who actually apply for the budget [ How to search information, sponsor]

- [ ] As a sponsor I would like to have an overview for all the budgets I make available so I it’s clear what budgets I own. [ How to search information, sponsor ]

- [ ] As a sponsor I would like to have an overview where I can see where the budget I make available is spend. [ How to search information, sponsor]

- [ ] As a sponsor I want to have contact information if I have any question regarding the platform So I can ask my questions. [How to search information, users ]

- [ ] As a sponsor I would like to add an budget so people can make use of the budget I make available. [ How to add budget, sponsor]

- [ ] As a sponsor I would like to change the amount of the budget so I can do adjustments if something changes what will influence the available budget. [ How to add budget, sponsor]

- [ ] As a sponsor I would like to be able to set requirements for spending the budget so I am sure that the budget will be spend where it’s meant for. [ How to add budget, sponsor]
