### ISSUE TITLE
kvk validation is not working  in latest commit

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#200]
## Description

```
{message: "The given data was invalid.", errors: {kvk: ["validation.kvk"]}}
errors: {kvk: ["validation.kvk"]}
message: "The given data was invalid."
```

## Steps to Reproduce (bug report)

1. https://dev.forus.link/sponsor/#!/organizations/create
2. fill in sign up form
3. can't create organisation because of kvk validation

**Comment by maxvisser** [comment]
Im at Nijmegen tomorrow

**Comment by maxvisser** [comment]
Maybe the KvK api was down while testing. Will test again today

**Comment by danrminds** [comment]
Will try to look into it with Gerben tomorrow maybe, otherwise Tuesday with you

**Comment by maxvisser** [comment]
It was an issue with laravel caching empty variables. Clearing the cache and restarting fixed the issue.
