### ISSUE TITLE
Sponsor dashboard: Changes to overview of actions

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2008]
## Context/goal: 
Unlimited stock is not unlimited stock but 999999. Change it to: onbeperkt or just remove it. Don't what the use of it is in the context of actions\

## Task 
- [ ] first check everywhere where 99999 is displayed
- [ ] implement unlimited stock on subsidies

**Comment by maxvisser** [comment]
A migration is needed.

**Comment by maxvisser** [comment]
Check everywhere were 999999 is displayed; and show the word 'unlimited'
