### ISSUE TITLE
Proposal: switch from markdown to BBcode

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2009]
@maartenfv commented on [Thu Dec 03 2020](https://github.com/teamforus/general/issues/618)

### Change description
- Update CMS from Markdown to WYSIWYG
- Users do not understand markdown and do not what to have to place an &nbsp as an "enter".
- The CMS now requires separate implementation sessions to explain how to use it.

**Comment by maxvisser** [comment]
Proposal is to somehow check if we can parse new lines to &nbsp; manually;

Another solution would be to switch to BBcode instead of markdown

![image](https://user-images.githubusercontent.com/10818702/103640224-e6e96c00-4f4f-11eb-9516-bf5fef7dd20f.png)

![image](https://user-images.githubusercontent.com/10818702/103640213-e2bd4e80-4f4f-11eb-89fa-038e208ba9d5.png)

**Comment by maxvisser** [comment]
@dev-rminds will look into some dependencies for Angularjs and Laravel to make the switch. As it is a different syntax the pages need to be rewritten.

**Comment by maxvisser** [comment]
@jamalv @dev-rminds we discussed this briefly yesterday during intake. Could you write an update on the approach? Do we go BBcode route or create blocks which sponsors can edit?

**Comment by maxvisser** [comment]
on hold: until @danrminds  and @maartenfv have spoken on strategy of cms

**Comment by maartenfv** [comment]
I have spoken with Dan and shared my thoughts. Can this issue proceed?

**Comment by maxvisser** [comment]
Probably this needs to be closed and a new task needs be created.

**Comment by maxvisser** [comment]
As we will not switch from markdown to BB code I will close this issue
