### ISSUE TITLE
Add to provider page "heeft u al een account? klik dan hier om in te loggen"

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2013]
@maartenfv commented on [Tue Dec 22 2020](https://github.com/teamforus/general/issues/674)

Learn more about change requests here: https://bit.ly/39CWeEE

![image](https://user-images.githubusercontent.com/10818702/102987447-9830e080-4512-11eb-91a2-1454e906d2d8.png)

## Task
- [ ] Add small text below "Heeft u al een account? Log dan in"

**Comment by maartenfv** [comment]
When is this to be released?

**Comment by maxvisser** [comment]
Its not done yet.
