### ISSUE TITLE
Provider signupflow: Add login state

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2015]
@jamalv commented on [Mon Dec 21 2020](https://github.com/teamforus/general/issues/663)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
As a provider that is already logged in, when I want to go to my dashboard using "aanmelden als aanbieder" > aanmelden > I would like to have a clear route to go to my dashboard if I have already signed up.

To reproduce use the groningen webshop

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/710a9fd3-aeda-4dc8-81a7-987571db74c4)

## Task
- [ ] When user is authenticated replace login button with a button which opens the dashboard
text:
'Open beheeromgeving'

**Comment by jamalv** [comment]
I recommend fixing this as follows:

add a carrot to show logged in state on the top right:

![Screenshot 2020-12-28 at 19.20.51.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/ad03081d-ba21-4e75-862e-829edf5b36cf)

Redirect to dashboard (for the role that you are on the sign-up flow for) when you click your profile

**Comment by maxvisser** [comment]
Make a button 'Open beheeromgeving' which opens the dashboard
