### ISSUE TITLE
Implement: details link for transactions

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/forus#2017]
## Context/goal: 
Proposal: https://github.com/teamforus/forus/issues/2016

Design: https://www.figma.com/file/9iNO20D0Z9L1YeED8n5WNv/details-link?node-id=22%3A1248

**Comment by jamalv** [comment]
@SjoerdHilhorst nice! I added some comments in figma. The file is read-only? Could you move it to the forus organisation to allow editing?

**Comment by SjoerdHilhorst** [comment]
done

**Comment by jamalv** [comment]
note from @maxvisser he mentions a kijk button is being used on most pages.

**Comment by sashooa** [comment]
https://www.figma.com/file/9iNO20D0Z9L1YeED8n5WNv/?node-id=22%3A1248
