### ISSUE TITLE
Bug: "Open tegoed" does not work

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2018]
## Prerequisites

1. Need to have a stadjerspas on stadjerspas webshop (where I tested, maybe also other webshops)
2. be logged in
3. go to an action
4. click on "open tegoed"

Nothing happens, should go to the voucher

## Description
<img width="1582" alt="Screenshot 2020-12-28 at 16 10 43" src="https://user-images.githubusercontent.com/30194799/103224057-7cb94180-4927-11eb-8569-0e73c278ba09.png">

**Comment by maxvisser** [comment]
Reproduced it on staging
