### ISSUE TITLE
Shorten activation code

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#202]
**Is your feature request related to a problem? Please describe.**
A user has to type the whole activation code. For the current version it looks like:

```
22b10a-e4b610-5cfcfa-5e1b4c
```

**Describe the solution you'd like**
Last year the activation code looked like:

```
1736-D35E
```

**Describe alternatives you've considered**
I understand the code has to be unique and we're facing a security/usability tradeoff, but 

36^8 is 2.821.109.907.456 combinations. I think that's enough to withstand a brute-force attack if we add some measures, and it will be much nicer for the end user.

**Comment by maxvisser** [comment]
Yes, ladies at Zuidhorn also found these codes too long. 

I told them this code now resembles your bsn number, that you can use to apply for other funds in the future. So personally I am in the camp of more security. :cop:

Next time you can add a QR code in the letter and let people scan it with the scanner, thats probably the most user friendly experience of activating something.

**Comment by maxvisser** [comment]
Btw there are more attacks than only bruteforce attacks. I could imagine a person who helps sending the letter steal the code with memory techniques; any person who sees the could really easily remember a 8 character code.

**Comment by jamalv** [comment]
Agree that the QR way is more user friendly (except that they do need to download an app, but well, it's a great app :))

The people sending and sealing the letters are authorised and vetted employees of the municipality. Outside of that, why then not snap a quick pic when no-one is looking? Should not be too hard. 

I agree, security-wise this is not ideal, but we know that. The only real solution to mitigating this risk is implementing peer-to-peer validation and/or DigiD. And we're working hard on that. In my eyes we are not lowering our security since last year.

It is a classic usability / security trade off. But for this I would err on the side of user experience. Typing the long code is quite a poor experience and I wouldn't want to worsen it from last year.

**Comment by danrminds** [comment]
done
