### ISSUE TITLE
Webshop: product details discounts should not be "free"

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2020]
@jamalv commented on [Tue Dec 29 2020](https://github.com/teamforus/general/issues/695)

Currently discounts are displayed as "free" - this is a showstopper since this can mean that citizens will misinterpret and maybe even try to abuse it, this can cause discomfort to the providers/sponsor

<img width="1340" alt="Screenshot 2020-12-29 at 13 08 48" src="https://user-images.githubusercontent.com/30194799/103282740-0247fa80-49d7-11eb-97d3-ac90040c76dd.png">

Example: 
https://stadjerspas-acc.gemeente.groningen.nl/products/1718

**Comment by jamalv** [comment]
2020!
