### ISSUE TITLE
Bug webshop: can't open expired vouchers to see any transactions

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2026]
## Context/goal: 
Normally you can open expired vouchers to see the transactions and the QR Code will be hidden. I can still see the transaction but the frontend doesn't allow me to open the voucher.

<img width="1544" alt="Screenshot 2021-01-04 at 14 25 42" src="https://user-images.githubusercontent.com/38419514/103620908-a03a4880-4f34-11eb-9d65-024ee8c05929.png">

**Comment by maxvisser** [comment]
fixed
