### ISSUE TITLE
Bug webshop: product cards give wrong information after latest release (removal of "aanbiedingsprijs")

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2027]
## Main asssignee: @

**Start from branch:** Master

## Context/goal: 
We've removed "aanbiedingsprijs" on API level I think. But it looks this resulted in some weird behaviour on the product cards on the webshop. On production we see this:

- Old price label (but it shows us normal price)
- Normal price

In some cases it even gives a from: € 0, and normal price: 15%. See image below.

Weird thing is that it looks it doesn't occur on staging. @maxvisser do you know what's going on?

<img width="761" alt="Screenshot 2021-01-04 at 15 42 03" src="https://user-images.githubusercontent.com/38419514/103621764-fc519c80-4f35-11eb-9279-e63fda01c082.png">

**Comment by maxvisser** [comment]
fixed
