### ISSUE TITLE
Add new email notification to the service

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#203]
New emails implemented in the service. 
Need to be connected to the system

- [x] Login via email
- [x] Send voucher to email
- [x] Provider rejected

**Comment by maxvisser** [comment]
@jknnr the one for login is priority as it is needed to connect providers

**Comment by kremlinwarrior** [comment]
{lang}/sender/login/login_via_email

**Comment by kremlinwarrior** [comment]
{lang}/sender/vouchers/provider_rejected

**Comment by kremlinwarrior** [comment]
{lang}/sender/vouchers/sended_via_email

**Comment by kremlinwarrior** [comment]
{lang}/sender/vouchers/sended_via_email
{lang}/sender/vouchers/provider_rejected
{lang}/sender/login/login_via_email

**Comment by kremlinwarrior** [comment]
Ready for testing

**Comment by jknnr** [comment]
@GerbenBosschieter could you test?
