### ISSUE TITLE
Design review: Euro discounts: new type selection and show discounts on sponsor dashboard

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2033]
## Main asssignee: @sashooa 
CR: https://github.com/teamforus/general/issues/712

## Context/goal: 
https://www.figma.com/file/04lT4mV6Jsl7Ot6SlvqWHz/?node-id=66%3A412

#### Creation of product new type selection
Its an selector

![image](https://user-images.githubusercontent.com/10818702/103531955-9fe57300-4e8a-11eb-9001-1051695f6c09.png)

<details>
<summary>Current state</summary>

![image](https://user-images.githubusercontent.com/10818702/103532084-e509a500-4e8a-11eb-9e75-91bc886b41de.png)

</details>

#### Actions modal on sponsor dashboard

![image](https://user-images.githubusercontent.com/10818702/103545752-4be68880-4ea2-11eb-8083-91edf88201f6.png)

Totaal prijs - Total price (price)
[sponsor organization name] betaalt (subsidy amount)
Prijs voor de klant - price in webshop - (price - subsidy amount)

![image](https://user-images.githubusercontent.com/10818702/103545772-54d75a00-4ea2-11eb-93fd-96ab624fe6b9.png)
![image](https://user-images.githubusercontent.com/10818702/103545793-5bfe6800-4ea2-11eb-9422-b31fa8be66c5.png)
![image](https://user-images.githubusercontent.com/10818702/103545809-61f44900-4ea2-11eb-8aae-26b00f8bdee1.png)

If it has no_price (discount or free) we also show it here:

**Comment by sashooa** [comment]
https://www.figma.com/file/04lT4mV6Jsl7Ot6SlvqWHz/?node-id=388%3A658
