### ISSUE TITLE
Add a modal with a choice between CSV and XLS

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2039]
## Main asssignee: @aghimpu 
CR: https://github.com/teamforus/general/issues/698

## Context/goal: 

We should add a modal after pressing export to the following pages:
- prevalidation
- fund requests
- voucher transactions
- fund provider request list

Example:
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/377aa127-7ee0-4187-8aa7-c74a1c3710fd)

**Comment by maxvisser** [comment]
should check what happens on import;
use case to test:
Export upload example
import upload example.

Does it still work with this new data in the file?

**Comment by maxvisser** [comment]
List all places where this is needed;
check if design is needed for every instance;

**Comment by SjoerdHilhorst** [comment]
- voucher generator, csv
- prevalidation, xls
- fund requests, xls 
- voucher transactions, xls
- fund provider request list, xls

**Comment by jamalv** [comment]
@danrminds this is releated to the issue we discussed before

**Comment by jamalv** [comment]
@dev-rminds @maxvisser @danrminds @aghimpu I see this issue was moved to "in progress" over a month ago? What's the status?

**Comment by maxvisser** [comment]
Its not done yet.

**Comment by maxvisser** [comment]
@aghimpu could you add modals for all the new options. On review I removed the CSV option for most use cases as the UI got pretty cluttered with the new buttons
