### ISSUE TITLE
Front end for the new blocks of the webshop @zuidhorn

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#204]
We have 2 new blocks of the webshop 

FAQ and Step by Step guide. 

https://www.dropbox.com/s/2hcbr8qgy2ip3es/Shop%20%232.tif?dl=0

**Comment by maxvisser** [comment]
Awesome! I already added some feedback to the other issue. That the we should look for a different image for the step-by-step guide as you dont see the computer now because the image is cropped.

**Comment by GerbenBosschieter** [comment]
Very nice!
So, I've written some Frequently Asked Questions for the requesters. @maxvisser and @jamalv can you read them and give feedback if needed. 

Also , I was thinking about an article/blog about the new functionalities. So all the changes are clear for the people who had Kindpakket last year. This way we can also use the Blog functionality. What do you guys think?

FAQ:

1. Hoe kan ik het Kindpakket activeren?
    1. Klik rechtsboven op “Activatiecode”.
    2. Vul je e-mailadres en de activatiecode die je per brief hebt ontvangen in.
    3. Klik vervolgens op “versturen”.
    4. Je profiel is aangemaakt en je kindpakket is geactiveerd! 
2. Hoe kan ik inloggen op de webshop?
    1. Dit kan op meerdere manieren, de makkelijkste manier is per e-mail.
    2. Klik rechtsboven in op “Inloggen”.
    3. Kies voor log in via e-mail.
    4. Vul het e-mailadres in (Het e-mail adres die je hebt gebruikt in combinatie met je activatiecode)
    5. Klik op “Versturen”.
    6. Open je e-mail en klik op de link die naar je toegestuurd is om in te loggen. 
3. Bij welke winkels kan ik het Kindpakket besteden?
    1. Je kan een overzicht van alle winkels en verenigingen terugvinden op de webshop. Ga naar “overzicht van alle leveranciers”. 
4. Ik ben mijn voucher kwijt. Wat moet ik doen?
    1. Je kan je voucher altijd terugvinden door in te loggen op de webshop, de voucher kun je uitprinten, naar je e-mail toesturen of zelfs altijd bij hand hebben door gebruikt te maken van de Me app.
5. Hoe kan ik zien hoeveel budget ik nog over heb?
    1. Na elke betaling wordt en er een e-mail toegestuurd met het huidige budget, daarnaast kan je het budget inzien door in te loggen op de webshop of door gebruik te maken van de Me app. 
6. Kan ik iets wat ik heb gekochten ruilen/retour brengen?
    1. Retour brengen is helaas niet mogelijk. Ruilen misschien wel, vraag de winkelier naar de mogelijkheden. 
7. Moet het budget in een keer besteed worden?
    1. Nee, je hoeft het budget niet in een keer te besteden. 
8. Ik heb meerdere kinderen. Moet ik aan ieder kind perse 300 euro besteden?
    1. Nee, je mag zelf bepalen hoeveel je per kind wilt besteden. 
9. Hoe lang is de voucher geldig?
    1. De voucher is vanaf 1 november 2018 een jaar geldig. 
10. Kan ik de voucher omruilen voor contact geld?
    1. Nee, de waarde van de voucher krijg je niet in contact geld uitbetaald. 
11. Kan ik iets kopen bij een nadere winkelier of vereniging die niet op de webshop staat ?
    1. Nee, het budget kan alleen uitgegeven worden bij winkeliers of verenigingen die op de webshop staan. 
12. Ik heb nog een kind gekregen, kom ik in aanmerking voor een hoger budget?
    1. Ja dat kan. Neem dan even contact op met de gemeente. 
13. Hoe kom ik in aanmerking voor het Kindpakket?
    1. Als je denkt recht te hebben op het Kindpakket, neem dan contact op met de gemeente. De gemeente bekijkt dan of je voldoet aan de voorwaarden. 
14. Kan ik de voucher aan iemand anders geven?
    1. Nee, de voucher is strikt persoonlijk. Je mag de voucher niet aan iemand anders geven. Maakt iemand anders wel gebruik van jouw voucher dan wordt je eigen bedrag lager. 
15. Ik zie producten/diensten op de webshop staan, hoe kan ik het product aanschaffen?
    1. Log in op de webshop
    2. Klik op “producten” bovenaan de pagina.
    3. Kies het product dat je wil aanschaffen en klik op “koop”.
    4. Kies het Kindpakket voucher om het product mee aan te schaffen.
    5. Het bedrag van het product wordt van je Kindpakket budget afgehaald en er wordt een nieuwe (product) voucher voor je aangemaakt.
    6. De nieuwe voucher kan alleen gebruikt worden voor het product wat je hebt aangeschaft. 
16. Ik wil mijn kind zelf het product op laten halen, maar wil hem niet het Kindpakket voucher meegeven. Wat kan ik doen?
    1. Je kan een product aanschaffen via de webshop, er wordt dan een nieuwe voucher aangemaakt die alleen gebruikt kan worden voor dat specifieke product. Deze kun je meegeven aan je kind. 
17. Vorig jaar had ik ook recht op Kindpakket, wat is er veranderd?
    1. Er zijn veranderingen doorgevoerd na aanleiding van de verbeterpunten die we hebben ontvangen. Je kan het Kindpakket net zo gebruiken als vorig jaar, maar je kan ook gebruik maken van veel nieuwe opties zoals:
        1. Het gebruiken van de Me app, hier kan je al jouw vouchers beheren, de QR-code scanner gebruiken om in te loggen op de webshop en alle transacties bijhouden.
        2. Er zijn een aantal nieuwe winkels en verenigingen toegevoegd aan de webshop om het aanbod uit te breiden.
        3. Je kan nu losse producten aanschaffen via de webshop.

	Wil je meer informatie over alle nieuwe opties en hoe je deze kan gebruiken, klik dan hier voor meer informatie (een link naar een artikel/blog over wat nieuw is aan kindpakket)

**Comment by jamalv** [comment]
Looking good! Fixed a couple typo’s, dont forget to let Marleen and Margrieta check it :) they answered most questions last year.

**Comment by maxvisser** [comment]
10 contact geld is contant geld

**Comment by maxvisser** [comment]
Wat wat mis met de vorige FAQ trouwens?

**Comment by maxvisser** [comment]
Consistentie aandachtspunt voor het kiezen van woorden;

 Aanbieders/leveranciers/providers/winkeliers/verenigingen zijn te veel woorden voor hetzelfde. Ook producten/aanbiedingen. Voucher/Kindpakket of QR-code

**Comment by maxvisser** [comment]
Als zou kiezen voor de woorden:

Aanbieders

Aanbiedingen

Voucher waarop een budget staat met een toonbare QR-code. 
- met getallen kies ik voor budget
- de QR-code zou ik niet teveel gebruiken
- voucher is combinatie van de QR-code en het budget.

Aanmelden

Reduceren. De aanschaf van een aanbieding reduceert x bedrag van uw budget.
