### ISSUE TITLE
Expire dates: up to and including consistency

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2057]
@jamalv commented on [Mon Jan 04 2021](https://github.com/teamforus/general/issues/709)

A date is **Always** "tot en met"; meaning if something is until the 15th, this should **include** the 15th

Someone needs to go through the system and look at all the dates and see if these are cosistent:
Me-app
Webshop: budget voucher page, product page, product voucher

Requirements:
All fields we let user set where we ask an expire date it should work as 'Tot en met'/'up to and including'
All fields we show to the user should be shown as 'Tot en met'/'up to and including'

**Comment by maxvisser** [comment]
lets focus now on testing all places where we show dates like:
webshop,
Me-app
dashboard
printables
e-mails

Check each date and see if they are consistent.

**Comment by SjoerdHilhorst** [comment]
Also change them directly or just make a list?

**Comment by maxvisser** [comment]
if you can change them directly you may do that ofcourse.

**Comment by SjoerdHilhorst** [comment]
I've checked the frontend, backend, ios and android repo's and changed them to up to and including. Any other places still?
