### ISSUE TITLE
Design review: Change modal when stopping an action

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2067]
## Main asssignee: @sashooa 
CR: teamforus/general#708

## Context/goal: 
The modal says the change is permanent, but that is not the case.

Proposal:
"U verwijderd het aanbod hiermee uit de webshop"

"Informeer inwoners en aanbieders" <- maybe this line can be removed?

<img width="708" alt="Screenshot 2021-01-04 at 11 37 44" src="https://user-images.githubusercontent.com/30194799/103526537-5cd2d200-4e81-11eb-85f7-cab752c90713.png">

```
Titel: Actie stoppen
Tekst: De actie wordt van de website verwijderd.
Hierna kan er van deze actie geen gebruik meer worden gemaakt.
```

![image](https://user-images.githubusercontent.com/36952230/103945041-db0acf00-5134-11eb-8599-675e2e48b530.png)

**Comment by sashooa** [comment]
https://www.figma.com/file/ArDg3BA8o4uANBLk3ZVzeM/Dashboards?node-id=2327%3A223
