### ISSUE TITLE
Repeat design review. Download me iPad UX

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2072]
## Context/goal: 
https://www.figma.com/file/Jf9evMRyAVEbzy4EDubvTr/Download-Me-UX-iPad?node-id=176%3A137&viewport=1555%2C1390%2C0.472746342420578

Second column should have this view on the top where the dropdown is, and without button "Kies":
![Screenshot 2021-01-13 at 16 34 17](https://user-images.githubusercontent.com/33207036/104473378-36b5dc00-55bd-11eb-802d-686e4647b7aa.png)
![Screenshot 2021-01-13 at 16 34 13](https://user-images.githubusercontent.com/33207036/104473384-374e7280-55bd-11eb-8767-ab0341844f68.png)

**Comment by sashooa** [comment]
https://www.figma.com/file/Jf9evMRyAVEbzy4EDubvTr/?node-id=176%3A137
