### ISSUE TITLE
Text proposal: Aanspreekvorm jij / u 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2076]
## Login modal
![image](https://user-images.githubusercontent.com/10818702/104726922-c4680780-5734-11eb-9875-e200528a93c8.png)

## login mail
![image](https://user-images.githubusercontent.com/10818702/104727111-13ae3800-5735-11eb-9286-f297d4b035d3.png)
https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/Mails?node-id=371%3A791

## task
- [ ] write text in 'Je aanspreekvorm'

**Comment by linda-90** [comment]
**Login met E-mail**
Vul jouw e-mailadres in om een link te ontvangen waarmee je kunt inloggen.

Vergeten welk e-mailadres je hebt gebruikt?

Gebruik de Me app om makkelijk en veilig in te loggen, betalingen te doen en tegoeden te beheren.
