### ISSUE TITLE
CSV upload: fund selection

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#209]
Instead hardcoding kindpakket_eligible in csv upload lets make a fund selector.

I see two solutions

Option 1: a column named fonds_id_recht
- advantages
   - you upload a csv where you have prevalidation for different funds
- its close to what we have now

Option 2: A dropdown menu on top of the csv uploader
- you dont have to have the fonds_id in the csv. Makes the user journey easier for the person that uploads the csv

**Comment by maxvisser** [comment]
Margrieta from Zuidhorn already has some questions why we needed kindpakket eligible (wat is eligible?)

**Comment by danrminds** [comment]
I like the proposal. Will forward this to Valentin to see when we can schedule it to be implemented.

**Comment by jamalv** [comment]
I would put configuration mostly in the user interface, and data in the CSV. I think that makes it easier for less technical people, a user interface is easier to explain then how you have to configure the file.

So that means I prefer option 2. Later we can extend the options you get in the user interface for different use cases.

**Comment by jamalv** [comment]
Out of scope sidenote: When this system gets a bit more complex in the future, we can offer users the option to download a sample CSV based on their prevalidation preferences. 

For now lets keep it on fund selection though.

**Comment by danrminds** [comment]
@dev-rminds Will work this one as follows on the interface, not to invent too much at this stage - before uploading the CSV - show the selector with Funds (similar on how we show the organizations) and at the end an option without selection. 

If you choose a fund - it will use the key of the fund (kindpakket for example) and use it to create the record [key]_eligible with value Ja for all the CSV entries. 
If no fund selected - no such record.
