### ISSUE TITLE
Design review: Toggle component

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2093]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/105338799-3da3a680-5bdc-11eb-813e-f39be303b217.png)

## Task
create a new toggle which include 'AAN' / 'UIT'

We use these toggles for example on these kind of modals:
![image](https://user-images.githubusercontent.com/10818702/105338878-557b2a80-5bdc-11eb-9b97-dcb869ca6d86.png)

**Comment by sashooa** [comment]
https://www.figma.com/file/ArDg3BA8o4uANBLk3ZVzeM/Dashboards?node-id=2407%3A11
