### ISSUE TITLE
Design review: Change e-mail icon

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2095]
@jamalv commented on [Thu Jan 28 2021](https://github.com/teamforus/general/issues/752)

### Change description
Change the icon for login mails to stadjerspas

https://www.figma.com/file/KShPJeCpXEt91EVdrHoybN/Mail-Stadjerpas-Login-SVG?node-id=0%3A1&viewport=-177%2C421%2C0.7111635804176331

**Comment by maxvisser** [comment]
@linda-90 I made a SVG icon for login mail for Stadjerspas could you check it?

**Comment by linda-90** [comment]
Nice! Checked. Just reversed the colors like the other icon. 
Can the color of the button also be red?
