### ISSUE TITLE
Text review: Rewrite e-mail after fund request approved

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2097]
@GerbenBosschieter commented on [Wed Jan 20 2021](https://github.com/teamforus/general/issues/749)

### Change description
The e-mail people get after approval of fund request is to confusing for some users.

1. Title is mentioning the word "tegoed". This results in people expecting a budget. 
**Current:**  Uw aanvraag voor een Stadjerspas-tegoed is goedgekeurd.
**Proposal:** Uw aanvraag voor {fund-name} is goedgekeurd

2. The tip about me-app also confusing. It tells user to download the me-app and show the qr code from their phone. Some users think they have to scan the QR Code with their phone. They don't know they should show it to a provider. Just keep it simple with this sentence and tell them they can manage their {fund-name} in the app.

3. Why use the word: "tegoed"? If we just use the fund name, then everybody is happy.

**Conclusion:** Lets rewrite the complete e-mail

<img width="1149" alt="Screenshot 2021-01-20 at 09 38 11" src="https://user-images.githubusercontent.com/38419514/105148916-38265d80-5b03-11eb-9ea0-5e0c1fe300df.png">

## Task
- [ ] remove words like "tegoed" from mail; its confusing
- [ ]  Keep the tip to the app simple; tell them they can manage their {fund-name} in the app.

**Comment by maxvisser** [comment]
mails can be updated in our figma file:
https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/Mails?node-id=371%3A791&viewport=582%2C360%2C0.08385049551725388

**Comment by linda-90** [comment]
Uw aanvraag voor Stadjerspas is goedgekeurd

Beste inwoner,

Uw aanvraag voor de Stadjerspas is goedgekeurd. Activeer uw digitale tegoed op de website.

Tip: Download de Me-app en neem je Stadjerspas mee op je telefoon.

Activeer tegoed

**Comment by maxvisser** [comment]
je en uw door elkaar? omdat dit de standaard mail betreft kies hiervoor u. Ook fondsnaam heeft niet 'de' of 'het' inzich. Dus 'de Stadjerspas' is niet mogelijk; anders krijg je 'de Kindpakket'.

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-backend/pull/1026
