### ISSUE TITLE
Webshop: Fund details page

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2099]
## Main asssignee: @sashooa 
CR: https://github.com/teamforus/general/issues/511

## Context/goal: 
Currently we have a fund list. During usertesting we saw that the requester does not have a easy way to retrieve information about the fund (what are its criteria and what can I get with said voucher?). A detail page for said fund can help with this information distribution

Design a webshop page to display fund information.

 - Fund logo
 - Fund name
 - Description
 - Type of fund (Budget / Acties)
 - Start date
 - End date
 - Aanbod (products)
 - Criterias

![Screenshot 2021-01-25 at 11.27.19.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/6223ae71-8ef7-43bb-8b8b-39df42266433)

criteria details as filled by the municipality
![Screenshot 2021-01-25 at 11.30.37.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/8f236199-de73-4426-afb8-581cb3874573)

**Comment by sashooa** [comment]
https://www.figma.com/file/7lQX9ZRpJW3ZTCtEosAMzs/?node-id=1220%3A25259
