### ISSUE TITLE
Redesign start action modal

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2101]
## Main asssignee: @sashooa 
CR: https://github.com/teamforus/general/issues/753

## Context/goal: 
<img width="1012" alt="Screenshot 2021-01-28 at 09 24 34" src="https://user-images.githubusercontent.com/30194799/106110444-050b4c00-614b-11eb-9ff2-485e9083a4eb.png">

**Comment by sashooa** [comment]
https://www.figma.com/file/vvAUlqbD1ZyrzjzJldBqn5/Redesign-start-action-modal?node-id=1%3A339
