### ISSUE TITLE
Text fix: Make it clear what the difference is between dashboard / app

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2104]
@maxvisser commented on [Wed Dec 02 2020](https://github.com/teamforus/general/issues/613)

## proposal

<img width="419" alt="Schermafbeelding 2021-02-09 om 12 09 48" src="https://user-images.githubusercontent.com/36952230/107355463-c7ee7480-6acf-11eb-840d-8e21fd5556b2.png">

**Comment by linda-90** [comment]
![image](https://user-images.githubusercontent.com/36952230/107355181-6b8b5500-6acf-11eb-9d2b-37a3135c6962.png)
