### ISSUE TITLE
Text review: CMS needs better tooltips

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2121]
@maartenfv commented on [Fri Jan 22 2021](https://github.com/teamforus/general/issues/751)

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/cfadfe12-d427-49e1-ba56-97488ee08240)

What is aanbieder pagina content?

For example, this feature needs a better explanation.  It is not clear what the "standard" is. So with this text you do not help the user get a better understanding.

## Task
@linda-90 Could you do a text review on staging of all tooltips?

**Comment by maxvisser** [comment]
https://www.figma.com/file/TLxmLE6tw9YvigAPF1SPvp/CMS?viewport=878%2C714%2C1

**Comment by linda-90** [comment]
Done! The footer texts are missing in the figma proposal.
