### ISSUE TITLE
Modal too big: Connect me app on dashboard

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2131]
@maxvisser commented on [Thu Dec 24 2020](https://github.com/teamforus/general/issues/686)

![image](https://user-images.githubusercontent.com/10818702/103079184-ac88e200-45d3-11eb-8e0b-b16f0dc08859.png)

## Problem
Modal is not really usable on small screens.

## Task
- [ ] Minimal scroll needed, decrease font sizes / image sizes.

Note: Another proposal to make image smaller and put them beside the text instead of above it.

**Comment by dev-rminds** [comment]
https://github.com/teamforus/forus-frontend/pull/1901
