### ISSUE TITLE
Product type discount percentage: can never be more than 100%

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2137]
@maartenfv commented on [Wed Feb 24 2021](https://github.com/teamforus/general/issues/771)
fix the issue from master

## Description
![image](https://user-images.githubusercontent.com/30211022/109011319-0b8cd500-76b1-11eb-81f4-5ae0134af05c.png)

Needs an error when higher than 100 and a percentage mark.

![unknown](https://user-images.githubusercontent.com/36765624/109011753-8a820d80-76b1-11eb-9747-50cbc45a1e03.png)

Result is that discount percentage is higher than a 100%.

## Task
- [ ] limit on input on 100%
- [ ] add backend validation to add error when user tries to input higher

**Comment by SjoerdHilhorst** [comment]
Issue is when creating a product, when updating the product an error message does appear, cannot find in the backend where this would be located
