### ISSUE TITLE
E-mail already exist text fix

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2140]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/109321108-12524e00-7851-11eb-9674-0a148151bc2b.png)

## Task
- [x] Change text to "Dit e-mailadres is al ingenomen door een ander account"

**Comment by maxvisser** [comment]
@linda-90 could review this error text?

**Comment by linda-90** [comment]
Het e-mailadres is al in gebruik. Er bestaat een ander account met dit e-mailadres.
