### ISSUE TITLE
Can't create fund criteria from edit page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2148]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/110289928-6647fa00-7fea-11eb-9d66-24693c7d8515.png)

It works from list but not from edit page.

**Comment by aghimpu** [comment]
I can't replicate it, is it still an issue?

**Comment by maxvisser** [comment]
Yes I tested this monday on production (master) could of course already be fixed on develop

**Comment by maxvisser** [comment]
Reopen when its reproduced
