### ISSUE TITLE
Application overview page: Proposal

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2149]
Als aanvrager wil ik aan het eind van mijn aanvraag een overzicht zien van de gegevens die ik heb ingevuld, voordat ik bevestig.

EN: As a requester I would like to see an overview of the data I provided during my application before I click send.

**Comment by maxvisser** [comment]
@jamalv could you link the figma file?

**Comment by jamalv** [comment]
https://www.figma.com/file/0YhjrQUDtJLsiFMSXou0B5/781-Application-overview-page?node-id=0%3A1
