### ISSUE TITLE
Variable missing: accepted fund request

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2153]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/110471894-fbc3b680-80dc-11eb-9ee4-93f70df89f88.png)

**Comment by aghimpu** [comment]
doesn't seem to be an issue, apparently it was fixed in this commit
https://github.com/teamforus/forus-backend/pull/1069/commits/8b65943b1706ae0438b31cba6833cfc90c63faf1
