### ISSUE TITLE
Design review: Add me logo with downloads

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2156]
@jamalv commented on [Mon Mar 08 2021](https://github.com/teamforus/general/issues/785)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As a requester, I want to have a trustworthy experience when downloading the me app.

Figma: https://www.figma.com/file/5mYDgbgFE4Lz2jg6O0tUHl/?node-id=0%3A1

---

@jamalv commented on [Mon Mar 08 2021](https://github.com/teamforus/general/issues/785#issuecomment-792836601)

@linda-90 could you please design review?

---

@maxvisser commented on [Mon Mar 08 2021](https://github.com/teamforus/general/issues/785#issuecomment-792840270)

me logo now looks like something you can click

---

@maxvisser commented on [Wed Mar 10 2021](https://github.com/teamforus/general/issues/785#issuecomment-795162250)

Maybe a good idea to move from black app icons to white ones. As the me logo is white.

**Comment by linda-90** [comment]
Did a design review: https://www.figma.com/file/5mYDgbgFE4Lz2jg6O0tUHl/Show-me-icon-with-downloads?node-id=0%3A1&viewport=164%2C-213%2C0.16627167165279388
