### ISSUE TITLE
Design review: Add me logo with downloads

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2159]
@jamalv commented on [Mon Mar 08 2021](https://github.com/teamforus/general/issues/785)
### Change description
As a requester, I want to have a trustworthy experience when downloading the me app.

Figma: https://www.figma.com/file/5mYDgbgFE4Lz2jg6O0tUHl/?node-id=0%3A1

## Task

@linda-90 could you please design review?

Feedback from @maxvisser 
Maybe a good idea to move from black app icons to white ones. As the me logo is white. 
We checked only iOS has a white one. Only changing this one already looks better.

**Comment by jamalv** [comment]
has been planned in for development, no longer relevant
