### ISSUE TITLE
QR code alt attribute

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2164]
De afbeelding met QR-code heeft geen alt-attribuut.

De voorleessoftware komt deze afbeelding tegen en leest een bestandsnaam van de afbeelding voor. Dit zorgt voor een ontoegankelijke en niet gebruiksvriendelijke ervaring voor een gebruiker van de voorleessoftware.

Geef deze afbeelding een alt-attribuut met tekst die de functie van deze afbeelding beschrijft.

**Comment by SjoerdHilhorst** [comment]
cannot state clear alt text directly as qr codes are a standard modal
