### ISSUE TITLE
WCAG: Email sent image alt text

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2165]
Als het e-mailadres is ingevuld en het formulier is verstuurd, verschijnt een nieuw scherm met afbeelding van een envelop. Deze afbeelding mist een alt-attribuut. Zie screenshot 1.

De voorleessoftware komt deze afbeelding tegen en leest een bestandsnaam van de afbeelding voor. Dit zorgt voor een ontoegankelijke en niet gebruiksvriendelijke ervaring voor een gebruiker van de voorleessoftware.

Deze decoratieve afbeelding moet verborgen worden van de voorleessoftware. Dat kan onder andere door role=’presentation’ toe te voegen. Andere oplossingen zijn mogelijk.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
