### ISSUE TITLE
WCAG DigiD alt attribute

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2166]
De afbeelding van de DigiD heeft geen alt-attribuut. Een logo is een informatieve afbeelding waarbij het alt-attribuut ontbreekt/leeg gelaten is. Voor de logo's geldt dat ze altijd het alt-attribuut moeten hebben waarin de volledige tekst van het logo dient terug te komen.

De voorleessoftware komt deze afbeelding tegen en leest een bestandsnaam van de afbeelding voor. Dit zorgt voor een ontoegankelijke en niet gebruiksvriendelijke ervaring voor een gebruiker van de voorleessoftware.

Deze afbeelding heeft een alt-attribuut nodig. Normaal gesproken heeft een logo een alternatieve tekst nodig waarin de tekst van het logo in terugkomt. Echter op deze pagina kan dit logo worden gezien als decoratief. Uit de content van de pagina, onder andere de knop ernaast is duidelijk waar deze pagina over gaat. Het alt-attribuut kan hier leeggetalen worden.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
