### ISSUE TITLE
WCAG: request pending alt attribute

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2173]
Onder het kopje ‘Aanvraag in behandeling’ staat een afbeelding met een uitroepteken. Deze afbeelding mist het alt-attribuut. Dit is een decoratieve afbeelding.

De voorleessoftware komt deze afbeelding tegen en leest een bestandsnaam van de afbeelding voor. Dit zorgt voor een ontoegankelijke en niet gebruiksvriendelijke ervaring voor een gebruiker van de voorleessoftware.

Voor de decoratieve afbeeldingen geldt dat de alternatieve teksten een leeg alt-attribuut moeten hebben.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
