### ISSUE TITLE
WCAG: alt texts for activation (logged in)

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2174]
page: https://stadjerspas.gemeente.groningen.nl/funds/27/activate

In de rechterbovenhoek van de pagina staat een menu. Als op link ‘Activeren’ wordt geklikt, opent een pop-up scherm waarin in drie stappen wordt uitgelegd hoe men dit proces moet doorlopen. In stap 1 en 2 staan afbeeldingen zonder alt-attributen.

Deze afbeeldingen zijn screenshots van de app schermen die laten zien waar bepaalde knoppen staan die moeten worden aangeklikt. Zonder deze informatie is het lastiger te begrijpen op welke knoppen geklikt moet worden.

"Deze afbeeldingen hebben goede alternatieve teksten nodig. Bijvoorbeeld in stap 2 kan de afbeelding de volgende tekst gebruiken: alt=”Onderaan het scherm ‘Welkom bij Me’ staat een witte knop met blauwe tekst ‘Koppelen’”.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
