### ISSUE TITLE
WCAG: Header ‘Stadjerspas aanvraag’ heading-element

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2178]
page: https://stadjerspas.gemeente.groningen.nl/funds/27/activate

The header on this page 'City pass application' is not formatted with a heading element.

When this header is formatted with a header element, the structural information that the text provides is also transferred to auxiliary software.

This is a title of the page and can be converted to H1.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
