### ISSUE TITLE
WCAG: Select elements on filters on actions page

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2181]
Page: https://stadjerspas.gemeente.groningen.nl/actions

De select-elementen onder ‘Aanbieders’, ‘Categorie’ en ‘Tegoeden’ in de linker kolom hebben geen toegankelijke naam. Het label is niet verbonden met het select-element door middel van een ‘for en id’ constructie. 

De voorleessoftware kan niet aan zijn gebruiker vertellen wat het onderwerp is van dit select-element.

In de code moeten de velden gelinkt worden aan labels via een id, zodat het voor hulpsoftware duidelijk is wat er waar ingevoerd moet worden.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
