### ISSUE TITLE
WCAG: Connect device modal; make step buttons headers

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2183]
In the top right corner of the page is a menu. If you click on the link "Authorize device", a pop-up screen will open that explains in three steps how to go through this process. Each step has a heading "Step 1", "Step 2" and "Step 3". These texts are headings but are not formatted as headers.

When this header is formatted with a header element, the structural information that the text provides is also transferred to auxiliary software.

Convert this header to a heading element.

![Screenshot 2021-03-19 at 11.30.42.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/ddd6d240-426d-4d2e-ab4c-d534a5c9a009)

In de rechterbovenhoek van de pagina staat een menu. Als op link ‘Activeren’ wordt geklikt, opent een pop-up scherm waarin in drie stappen wordt uitgelegd hoe men dit proces moet doorlopen. Elke stap heeft een kop ‘Stap 1’, ‘Stap 2’ en ‘Stap 3’. Deze teksten zijn koppen maar zijn niet als koptekst opgemaakt.

Wanneer deze kop met een kop element wordt opgemaakt, wordt de structurele informatie die de tekst geeft ook overgedragen aan hulpsoftware.

Zet deze koptekst om in een heading-element.

**Comment by GerbenBosschieter** [comment]
Checked and passed
