### ISSUE TITLE
WCAG: Use TH-elements for column buttons

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2184]
The data table on this page is not formatted with the correct elements. The column headers 'Date' and 'Notification' are not formatted with th elements.

This ensures that the utility does not know the relationship between these column headings and the underlying cells.

Use th elements for the column headers.

![Screenshot 2021-03-19 at 11.43.02.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/ffa868e7-5166-4d4f-a1b2-d207199c4da1)

Dutch:
De datatabel op deze pagina is niet met de correcte elementen opgemaakt. De kolomkoppen 'Datum' en 'Notificatie' zijn niet met th-elementen opgemaakt. 

Dit zorgt ervoor dat de hulpsoftware niet weet wat de relatie is tussen deze kolomkoppen en de onderliggende cellen.

Gebruik th-elementen voor de kolomkoppen.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
