### ISSUE TITLE
Webshop: Pagination which page is active should be available with ARIA

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2188]
The page under items only indicates in color which page is active. This information is not available in the HTML and thus not available for the utility software.

The user of auxiliary software does not know on which of the five pages of items he is currently on.

Give the current link in the page an explanatory text in the form of a screen reader-only text or an aria label.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
