### ISSUE TITLE
Requester signupflow: progress bar progress should be available in html

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2189]
There is a progress bar under the heading. In steps 1, 2 and 3, the color of the bar changes to indicate what an active step is. This information is not available in the HTML and thus not available for the utility software.

This element indicates important information about the progress of the process. It must be available to all users.

Make sure that this information can also be determined programmatically so that it becomes available to the utility software.

**Comment by SjoerdHilhorst** [comment]
gefixt https://github.com/teamforus/forus-frontend/pull/1728/files#diff-7051f400d24c4fe06eeddd02089bdeb2d609ffaeadc79cfd29ec106c1e942834
