### ISSUE TITLE
In het witte deel van de footer staan twee links (‘Privacyverklaring’ en ‘Toegankelijkheidsverklaring’). De tekstkleur van deze links is #727d84. Deze kleur geeft het kleurcontrast van 4,2:1. 

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2190]
In het witte deel van de footer staan twee links (‘Privacyverklaring’ en ‘Toegankelijkheidsverklaring’). De tekstkleur van deze links is #727d84. Deze kleur geeft het kleurcontrast van 4,2:1.

Tekst die niet voldoet aan minimale eis is slecht leesbaar voor kleurenblinde en slechtziende bezoekers.

Zorg voor een minimaal contrast van 4,5:1.

**Comment by linda-90** [comment]
![image](https://user-images.githubusercontent.com/36952230/114860159-ee8c9c80-9deb-11eb-9cad-c3f7df201b7c.png)
#515152
