### ISSUE TITLE
Het invoerveld waar het e-mailadres moet worden ingevuld heeft placeholdertekst. E achtergrondkleur is #EFF2F4, de tekstkleur is #A3A3A4. Deze kleuren hebben kleurcontrast van 2,2:1. Het label boven dit invoerveld (‘Vul uw e-mailadres in’) heeft tekstkleur #7e818c. Op de witte achtergrond van de pagina geeft deze tekstkleur contrast van 3,8:1.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2191]
Het invoerveld waar het e-mailadres moet worden ingevuld heeft placeholdertekst. E achtergrondkleur is #EFF2F4, de tekstkleur is #A3A3A4. Deze kleuren hebben kleurcontrast van 2,2:1. Het label boven dit invoerveld (‘Vul uw e-mailadres in’) heeft tekstkleur #7e818c. Op de witte achtergrond van de pagina geeft deze tekstkleur contrast van 3,8:1.

Tekst die niet voldoet aan minimale eis is slecht leesbaar voor kleurenblinde en slechtziende bezoekers.

Zorg voor een minimaal contrast van 4,5:1.

**Comment by linda-90** [comment]
Verander tekst kleur in #515152

<img width="508" alt="Schermafbeelding 2021-04-14 om 12 22 10" src="https://user-images.githubusercontent.com/36952230/114695541-0bf23580-9d1c-11eb-90bc-c27b873a17d8.png">

**Comment by SjoerdHilhorst** [comment]
gefixt
