### ISSUE TITLE
De tekstkleur van de actieve link in het kruimelpad is #bbb. Deze kleur geeft het kleurcontrast van 1,9:1. De placeholdertekst in het invoerveld ‘Zoeken’ of ‘Zoek aanbod’ wordt gerenderd als #9a9a9a. Dit geeft een kleurcontrast van 2,8:1.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2192]
De tekstkleur van de actieve link in het kruimelpad is #bbb. Deze kleur geeft het kleurcontrast van 1,9:1. De placeholdertekst in het invoerveld ‘Zoeken’ of ‘Zoek aanbod’ wordt gerenderd als #9a9a9a. Dit geeft een kleurcontrast van 2,8:1.

Tekst die niet voldoet aan minimale eis is slecht leesbaar voor kleurenblinde en slechtziende bezoekers.

Zorg voor een minimaal contrast van 4,5:1.

**Comment by linda-90** [comment]
![image](https://user-images.githubusercontent.com/36952230/114993853-7e8a1f00-9e9c-11eb-9e09-96a91b7a9c9d.png)
#bbb = #515152
#9a9a9a = #515152

**Comment by SjoerdHilhorst** [comment]
gefixt
