### ISSUE TITLE
Naast de naam van de activiteit staat een groen blokje met ‘Actief’ erop. De groene achtergrond #2DC5AB in combinatie met een witte tekst geeft kleurcontrast van 2,2:1. 

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2193]
Naast de naam van de activiteit staat een groen blokje met ‘Actief’ erop. De groene achtergrond #2DC5AB in combinatie met een witte tekst geeft kleurcontrast van 2,2:1. 

Tekst die niet voldoet aan minimale eis is slecht leesbaar voor kleurenblinde en slechtziende bezoekers.

Zorg voor een minimaal contrast van 4,5:1.

**Comment by linda-90** [comment]
![image](https://user-images.githubusercontent.com/36952230/114995928-9c588380-9e9e-11eb-923e-e6106da50112.png)
#2DC5AB = #1C8271
