### ISSUE TITLE
Naast het e-mailadres van de gebruiker staat een groen blokje met ‘Hoofd e-mailadres’. De groene achtergrond #2DC5AB in combinatie met een witte tekst geeft kleurcontrast van 2,2:1. 

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2194]
Naast het e-mailadres van de gebruiker staat een groen blokje met ‘Hoofd e-mailadres’. De groene achtergrond #2DC5AB in combinatie met een witte tekst geeft kleurcontrast van 2,2:1. 

Tekst die niet voldoet aan minimale eis is slecht leesbaar voor kleurenblinde en slechtziende bezoekers.

Zorg voor een minimaal contrast van 4,5:1.

**Comment by linda-90** [comment]
![image](https://user-images.githubusercontent.com/36952230/114859383-f7c93980-9dea-11eb-8a6b-31c905399bb4.png)

bg color: #1C8271
text color: #FFFFFF
