### ISSUE TITLE
In stap 3 van dit aanvraagproces staat een grijs (#F3F5F7) blok met tekst ‘Document slepen & neer zetten’ en ‘max. grootte 8Mb’. Deze tekst heeft tekstkleur van #9EA6B6. Deze kleurencombinatie heeft kleurcontrast van 2,2:1. Zie screenshot 3.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2197]
In stap 3 van dit aanvraagproces staat een grijs (#F3F5F7) blok met tekst ‘Document slepen & neer zetten’ en ‘max. grootte 8Mb’. Deze tekst heeft tekstkleur van #9EA6B6. Deze kleurencombinatie heeft kleurcontrast van 2,2:1. Zie screenshot 3.

Tekst die niet voldoet aan minimale eis is slecht leesbaar voor kleurenblinde en slechtziende bezoekers.

Zorg voor een minimaal contrast van 4,5:1.

**Comment by linda-90** [comment]
![image](https://user-images.githubusercontent.com/36952230/114995385-0d4b6b80-9e9e-11eb-8a5c-40a416fce89f.png)
https://www.figma.com/file/YQvHyLuGakWmHAJ4GSmZx5/WCAG-elements?node-id=36%3A47&viewport=-1077%2C1333%2C0.7350893616676331
