### ISSUE TITLE
Tegenover ‘Organisatietype’ staat een grijs blokje met ‘Bioscoop’. De achtergrondkleur is #8CA3A6, de tekst is wit. Deze kleurencombinatie geeft het kleurcontrast van 2,7:1.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2198]
Tegenover ‘Organisatietype’ staat een grijs blokje met ‘Bioscoop’. De achtergrondkleur is #8CA3A6, de tekst is wit. Deze kleurencombinatie geeft het kleurcontrast van 2,7:1.

Tekst die niet voldoet aan minimale eis is slecht leesbaar voor kleurenblinde en slechtziende bezoekers.

Zorg voor een minimaal contrast van 4,5:1.

**Comment by linda-90** [comment]
Alle teksten zelfde kleur: #2B333B
Label:
bg color: #2B333B
text color: #FFFFFF

<img width="773" alt="Schermafbeelding 2021-04-14 om 13 08 58" src="https://user-images.githubusercontent.com/36952230/114701043-976ec500-9d22-11eb-86bd-9a7d7763a3ef.png">

**Comment by SjoerdHilhorst** [comment]
gefixt
