### ISSUE TITLE
De kleur van de rand van het invoerveld is #dce0e0. Op de witte achtergrond van de pagina geeft deze kleur kleurcontrast van 1,3:1.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2202]
Page: https://stadjerspas.gemeente.groningen.nl/ (login popup)

De kleur van de rand van het invoerveld is #dce0e0. Op de witte achtergrond van de pagina geeft deze kleur kleurcontrast van 1,3:1.

Slechtzienden kunnen moeite hebben om te bepalen waar ze input kunnen geven.

Zorg voor een minimaal contrast van 3,0:1.

**Comment by linda-90** [comment]
<img width="806" alt="Schermafbeelding 2021-04-14 om 12 49 35" src="https://user-images.githubusercontent.com/36952230/114698915-eb2bdf00-9d1f-11eb-8aa2-2112534b1efe.png">

invoerveld
bg: #EFF2F4
rand: #515152
text: #515152

**Comment by maxvisser** [comment]
@linda-90 could you link the figma file with all the states  (disabled, focus etc)

**Comment by linda-90** [comment]
https://www.figma.com/file/YQvHyLuGakWmHAJ4GSmZx5/WCAG-elements?node-id=1%3A2&viewport=700%2C309%2C0.6352798342704773
