### ISSUE TITLE
Het invoerveld waar het e-mailadres moet worden ingevuld is alleen te onderscheiden van zijn achtergrond met kleur #eff2f4. Deze kleur geeft onvoldoende kleurcontrast, namelijk 1,1:1.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2203]
Page: https://stadjerspas.gemeente.groningen.nl/start

Het invoerveld waar het e-mailadres moet worden ingevuld is alleen te onderscheiden van zijn achtergrond met kleur #eff2f4. Deze kleur geeft onvoldoende kleurcontrast, namelijk 1,1:1.

Slechtzienden kunnen moeite hebben om te bepalen waar ze input kunnen geven.

Zorg voor een minimaal contrast van 3,0:1.

**Comment by linda-90** [comment]
<img width="806" alt="Schermafbeelding 2021-04-14 om 12 49 35" src="https://user-images.githubusercontent.com/36952230/114698915-eb2bdf00-9d1f-11eb-8aa2-2112534b1efe.png">

invoerveld
bg: #EFF2F4
rand: #515152
text: #515152
