### ISSUE TITLE
In de header van de website staat een icoon van een chevron dat aangeeft dat hier een verborgen sectie in zit. Deze knop is gemaakt van een niet-interactief div-element en reageert niet op het toetsenbord.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2208]
In de header van de website staat een icoon van een chevron dat aangeeft dat hier een verborgen sectie in zit. Deze knop is gemaakt van een niet-interactief div-element en reageert niet op het toetsenbord.

Deze knop is niet beschikbaar gebruikers die de website alleen met toetsenbord bezoeken.

Geef deze knop interactieve eigenschappen. Dat kan bijvoorbeeld door deze knop te coderen met native HTML button-element.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
