### ISSUE TITLE
WCAG: Document uploader buttons

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2212]
Make it use an Button HTML tag, not a DIV. 

Dutch: 
In stap 3 van het proces staat een knop met ‘Upload een document’. Deze knop is gemaakt van de niet-interactieve div-element. Als een bestand wordt geüpload, verschijnt de naam van het bestand onder deze ‘Upload een document’ knop met een icoon van een kruis. Dit icoon is bedoeld als een knop om de bestanden te verwijderen. Deze knop is gemaakt van een a-element zonder href-attribuut. Dit zorgt ervoor dat deze knop alle interactieve kenmerken mist. Op het laatste scherm met een kop ‘Verzonden!’ staat een knop ‘Terug’. Deze knop heeft dezelfde problemen. Onder dit succescriterium is deze knop niet toetsenbord toegankelijk.

Deze knoppen zijn niet beschikbaar gebruikers die de website alleen met toetsenbord bezoeken.

Geef deze knop interactieve eigenschappen. Dat kan bijvoorbeeld door deze knop te coderen met native HTML button-element.

**Comment by GerbenBosschieter** [comment]
Checked and passed
