### ISSUE TITLE
Webshop: Add skiplink so menu can be skipped

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2215]
There is no mechanism to skip recurring link blocks. This link helps people who are blind or have motor disabilities to get to the unique content of the page more quickly.

As a result, keyboard users have to go through all the menu links on each page to get to the main content.

Add a so-called "skip link" with which the menu can be skipped.

**Comment by maxvisser** [comment]
PR is based from a wrong branch; can we redo this from develop?
