### ISSUE TITLE
Webshop: Logo link has no accessible name

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2221]
Dit succescriterium is bedoeld om bediening met spraaksoftware mogelijk te maken. Belangrijk hierbij is dat de visueel zichtbare tekstonderdeel is van de toegankelijkheidsnaam van het element. Op alle onderzochte pagina’s komt de tekst van het logo niet voor in de toegankelijke naam van het logo. De link heeft helemaal geen toegankelijke naam. 

Deze link is niet met stemsoftware te bedienen.

De zichtbare tekst (‘Stadjespas’) dient in de linktekst of in het alt-attribuut van de afbeelding terug te komen. In het eerste geval kan de linktekst verborgen worden van het scherm met CSS-clip methode of text-indent. Er zijn andere opties mogelijk om deze link toegankelijke naam te geven.

**Comment by GerbenBosschieter** [comment]
Current ALT text = "Organization name". 

This doesn't tell what the image is or does. I propose this:
ALT text = "Home: {name implemenation}"

**Comment by maxvisser** [comment]
its not the organization name;
https://stadjerspas.gemeente.groningen.nl/ its already the implementation name

**Comment by GerbenBosschieter** [comment]
@maxvisser I see. On the WCG audit fix PR it's not. Still we should describe what the logo does because it's a link to home page and not only decorative

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
