### ISSUE TITLE
Footer links ‘Download Me-app’. 

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2222]
In de footer van de website staan twee links met dezelfde toegankelijke naam ‘Download Me-app’. Deze naam komt van het aria-label op de link. De enige inhoud van de link is een afbeelding met alternatieve tekst ‘Google Play Store’ en ‘Apple App Store’. 

Deze alternatieve teksten worden niet gelezen door een voorleessoftware omdat het aria-label de inhoud van de link overschrijft.

Hier kan het aria-label verwijderd worden. Beide links staan onder het kopje ‘Download Me-app’. Uit de alternatieve tekst van het logo is duidelijk naar welke winkel de link verwijst.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
