### ISSUE TITLE
Webshop input field has no label and needs to be connected with "for and id"

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2223]
Het invoerveld ‘E-mail’ heeft geen toegankelijke naam. Dit invoerveld heeft een placeholdertekst ‘E-mail’. Op deze website komen vele invoervelden voor die zichtbare labels missen en waar alleen een placeholdertekst als een label dient.

Deze tekst verdwijnt zodra een bezoeker begint te typen en kan niet als label worden gezien. 

Geef dit invoerveld een zichtbaar label dat prominent in beeld blijft. De meest robuuste optie is een label-element dat verbonden is met ‘for en id’ constructie met het invoerveld.

**Comment by SjoerdHilhorst** [comment]
gefixt
