### ISSUE TITLE
Webshop header CTA-buttons: 'Inloggen' and 'Start' don't have role and function names

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2225]
In de header van de website staan twee knoppen: ‘Inloggen’ en ‘Start aanvraag’. Deze knoppen hebben geen toegankelijke naam en geen rol. Deze bevinding geldt voor alle zelfgemaakte knoppen op deze website die enkel door middel van JavaScript event tot knoppen zijn gemaakt.

De voorleessoftware kan niet aan zijn gebruiker vertellen dat dit knoppen zijn omdat ze de juiste rol missen. Nu zijn deze knoppen gecodeerd als neutrale (niet-interactieve) div-elementen. Daarnaast weet de voorleessoftware niet wat de functie (naam) van deze knoppen is.

Zet deze div-elementen om in button-elementen. Een andere optie is om aan deze neutrale elementen interactieve kenmerken te geven door role=’button’ te geven.

**Comment by GerbenBosschieter** [comment]
Roles zijn toegewezen, echter biedt dit geen oplossing.
