### ISSUE TITLE
Het invoerveld ‘E-mail’ heeft geen toegankelijke naam. Dit invoerveld heeft een placeholdertekst ‘E-mail’. Een placeholdertekst is geen goed alternatief voor een toegankelijke naam.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2226]
Het invoerveld ‘E-mail’ heeft geen toegankelijke naam. Dit invoerveld heeft een placeholdertekst ‘E-mail’. Een placeholdertekst is geen goed alternatief voor een toegankelijke naam.

De voorleessoftware kan niet vertellen welke data dit invoerveld verwacht.

Geef dit invoerveld een label. De meest robuuste optie is een label-element dat verbonden is met ‘for en id’ constructie met het invoerveld.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
