### ISSUE TITLE
WCAG: Popup modals X: give role button and aria-label

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2227]
Alle pop-up schermen op deze website hebben een kruis icoon in de rechterboven hoek om het scherm af te sluiten. Deze iconen die als knopen fungeren zijn gemaakt van niet-interactieve div-elementen en missen alle kenmerken van een knop. Onder dit succescriterium valt het ontbreken van de juiste rol op dit element en de toegankelijke naam van de knop. Zie screenshot 7. 

De voorleessoftware weet niet dat dit icoon een knop is en wat deze knop doet.

Geef deze knop de interactieve kenmerken. Dat kan door role=’button’ en een aria-label. Andere opties zijn ook mogelijk.

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
