### ISSUE TITLE
Aria-rol ‘main’ is verkeerd gebruikt op het html-element. Het is niet toegestaan om role=”main” op html-element te gebruiken.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2229]
Aria-rol ‘main’ is verkeerd gebruikt op het html-element. Het is niet toegestaan om role=”main” op html-element te gebruiken.

Verkeerd gebruik van aria-rol kan voor verkeerde interpretatie van de pagina zorgen. 

Verwijder deze rol van het HTML.

![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/039b3f36-2eb7-41a2-bb42-9687a6c61428)

**Comment by GerbenBosschieter** [comment]
Checkend and passed
