### ISSUE TITLE
Webshop product page: add for and id elements to select element

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2232]
The select element in the left column under the heading "Organization" has no accessible name.

Without an accessible name, the reading software does not know what this element stands for.

Give this select element a label and associate this label with the select with "for and id". 

![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/febe0123-ee84-46a2-852a-f6ebdb62eb0a)

**Comment by GerbenBosschieter** [comment]
Checked and passed
