### ISSUE TITLE
Webshop mobile menu: text reading software does not know the menu are buttons

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2234]
When the website is viewed on a small screen, four buttons appear at the bottom of the screen: ‘Aanbieders’, ‘Aanbod’, ‘Tegoeden’ and ‘Profiel’. These buttons replace the main menu of the website.

The reading software does not know that these are buttons and what these buttons do.

Give these buttons correct role = ”button” and the name that describes the function. The status ("selected") must also be indicated.

**Comment by SjoerdHilhorst** [comment]
fixed
