### ISSUE TITLE
Login by email

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#224]
**Variables:**

- login_link
- platform

**Dutch**

Onderwerp: Jouw inloggegevens

Beste inwoner,

Je hebt zojuist aangegeven dat je wil inloggen op de [platform].
Klik op onderstaande link om verder te gaan met inloggen.

< link>

**English**

Subject: Your login details

Dear citizen, 

You’ve just requested to login on to the [platform].
Click on the link below to continue logging in.

<link>

**Mention:**
for the _[platform]_ variable -> Valentin will give you one of the following possibilities: 

- meapp
- webshop
- panel

Based on this information the service has to display the translated text. For example for English:

- Me App
- Webshop
- Forus Dashboard 

Most probably will be the same translations for dutch as well

**Comment by kremlinwarrior** [comment]
Done
