### ISSUE TITLE
Webshop preferences emails: Add e-mail button from DIV to native HTML element button

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2242]
This page has a big red button with "add email". For the reading software this is not a button, but a non-interactive div element. See screenshot 8.

The reading software cannot tell its user that these are buttons because they miss the correct role. Now these buttons are coded as neutral (non-interactive) div elements. In addition, the reading software does not know what the function (name) of these buttons is.

The most robust solution is to use the native HTML elements such as button elements. Another possible solution is to use WAI-ARIA. 

![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/253a253e-0332-4868-b7a8-fb6187d9a949)

Page where button is:
http://localhost:5500/preferences/emails

**Comment by GerbenBosschieter** [comment]
Checked and passed
