### ISSUE TITLE
Text review: As I sponsor I would like to see the card number and connect/disconnect cards

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2245]
@jamalv commented on [Mon Mar 08 2021](https://github.com/teamforus/general/issues/783)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As I sponsor I would like to see the card number and connect/disconnect cards

Figma: https://www.figma.com/file/94FYlEOLkCYkkwJKtx5NpJ/Physical-cards-in-dashboard?node-id=0%3A1

**Comment by maxvisser** [comment]
Texts are still written for context of citizens connecting a card. @linda-90 could you rewrite/check these text in the mindset of a sponsor (groningen)

**Comment by linda-90** [comment]
Text review:
https://www.figma.com/file/94FYlEOLkCYkkwJKtx5NpJ/Physical-cards-in-dashboard?node-id=35%3A11996
