### ISSUE TITLE
Jij/je: add to notifications

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2253]
A backend flag was added: https://github.com/teamforus/forus/issues/2075

This backend flag should also work for notifications. Max will need an example to understand how to implement it for all notifications.

@maxvisser could you verify this is the last piece of this puzzle? Or do you need anything else from valentin?

**Comment by maxvisser** [comment]
depends on checking the whole system on informal/formal; I believe this is the biggest thing missing.

**Comment by jamalv** [comment]
this is á piece of the puzzle (max verified)

**Comment by jamalv** [comment]
to be specific, this is for requesters.
