### ISSUE TITLE
When PaymentSuccessMail is disabled by user SubsidyPaymentSuccessMail should also be disabled

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2258]
## Context/goal: 
Currently when user disables PaymentSuccessMail in webshop we still sent SubsidyPaymentSuccessMail; 

User should be able to disable all payment success mails with one toggle

![image](https://user-images.githubusercontent.com/10818702/111767712-56140280-88a7-11eb-802a-c3d77bb32223.png)

**Comment by danrminds** [comment]
@maxvisser 2 options here. These are now as 2 emails. 

1. We unify them as 1 email sent in different situations with different text
2. We make a new item in the list (new toggle)

**Comment by maxvisser** [comment]
I would do the first.

**Comment by maxvisser** [comment]
this is probably the same for push notifications
