### ISSUE TITLE
Responsiveness: Product images and footer

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2262]
start from release/v0.22.0

## Context/goal: 
**Product image**
Just use the width 100%. Should be enough. Using min-width of min-height will result in problems in responsiveness on mobile and will unwanted aspect ratio / stretching of images.

And it also look like all pages that are added with cms functionality are not reviewed on responsiveness. Can't check it myself locally because of local installation. 

Code:
<img width="303" alt="Screenshot 2021-03-24 at 11 18 18" src="https://user-images.githubusercontent.com/38419514/112293649-a669d680-8c92-11eb-8b84-d65f6fabd570.png">

Examples: 
https://drive.google.com/file/d/1l1iEsss2g-X1xQOXINXmwlixscwkxaGg/view?usp=sharing
https://drive.google.com/file/d/180YsA-q1z_RVBG53jlEixIIzcKSvSCs0/view?usp=sharing

**Comment by GerbenBosschieter** [comment]
![IMG_9E6E66ED6034-1](https://user-images.githubusercontent.com/38419514/112296242-01043200-8c95-11eb-8915-8edbe1dfd0f4.jpeg)

**Comment by maxvisser** [comment]
Let's try to fix this still in this release 22

**Comment by GerbenBosschieter** [comment]
this is fixed.
