### ISSUE TITLE
Visual: product information on product details card looks messy. Should redesign

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2266]
## Context/goal: 

<img width="1506" alt="Screenshot 2021-04-08 at 10 10 48" src="https://user-images.githubusercontent.com/38419514/113991732-0a73c980-9853-11eb-96b5-c7f65ce8ebc8.png">

**Comment by maxvisser** [comment]
Proposal:
![image](https://user-images.githubusercontent.com/10818702/114194486-d7fbc680-994f-11eb-976c-24b1d2bcecde.png)

**Comment by maxvisser** [comment]
added to release v0.23.0
