### ISSUE TITLE
Nijmegen connection - design loading, error and dashboard pages

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2270]
## Context/goal: 
For Nijmegen we will built a connection to let citizen apply for Meedoenregeling/Busregeling. There is a need for some new pages:
- a page configure the connection on sponsor dashboard
- Webshop: loading page for the connection before you enter requester signupflow
- Webshop: Error page (texts) for when the connection is down

**Comment by maxvisser** [comment]
@maxvisser will make a figma file with a quick proposal which can be reviewed

**Comment by maxvisser** [comment]
https://www.figma.com/file/O3A1gpSSTJ5xoxavB4zOeG/Nijmegen-koppeling?node-id=1%3A1048

**Comment by jamalv** [comment]
@maxvisser can this be closed?
