### ISSUE TITLE
Forus-backend installation instructions

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#228]
What commands do I need to run to install forus-backend locally or on a server?

**Comment by maxvisser** [comment]
releated to https://github.com/teamforus/forus/issues/231

**Comment by maxvisser** [comment]
deployment I can help with making instructions

**Comment by maxvisser** [comment]
Stephan is  testing Jimmy's instructions.

**Comment by maxvisser** [comment]
Niels is updating Jimmy's instructions as they are already outdated
