### ISSUE TITLE
The filter results are not applied in an export file.

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/forus#2284]
## Prerequisites

1. [INSERT PREREQUISITE 1]
2. [INSERT PREREQUISITE 2]
3. [INSERT PREREQUISITE 3]

*Describe what is needed beforehand to be able to solve this ISSUE*

## Description
The filter results are not included in an export file. This is only the case with Applicants(Aanvragers)

## Steps to Reproduce (bug report)

1. Login on sponsor dashboard
2. Click on **Aanvragers**
3. Setup the filter
4. Click on export and choose a format type.
5. Compare the results of the dashboard and the export.

*Give a step by step guide to reproduce the bug*

**Expected behavior:** 
Export file must be the same as the results in the dashboard after setup the filter.

**Actual behavior:** 
Filters are not applied in export file

**Reproduces how often:**
100%

## Additional Information (optional)

*Any additional information, configuration or data that might be necessary to reproduce the issue.*

**Comment by maxvisser** [comment]
If still an issue lets plan it in. I missed this one.

**Comment by GerbenBosschieter** [comment]
Can't reproduce. 

@MichaelForus can you be more specific about the  filter itself? can you recall what the problem exactly was.
