### ISSUE TITLE
Financial dashboard. Statistics improvements

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2286]
## First part (overview)
1. Tooltips on the table

## Filters
<img width="554" alt="Schermafbeelding 2021-04-30 om 12 22 57" src="https://user-images.githubusercontent.com/36952230/116682656-ce91d700-a9ae-11eb-943a-361f1919cabe.png">

1. Add time filtering by Month and Quarter
<img width="450" alt="Schermafbeelding 2021-04-30 om 12 36 12" src="https://user-images.githubusercontent.com/36952230/116684013-ab682700-a9b0-11eb-900c-a3ff9e8563bc.png">

2. Add category filter
3. Filter options: add search bar to search through results
4. Filter options: numbers (counters) on the right side of the dropdowns)
<img width="381" alt="Schermafbeelding 2021-04-30 om 12 27 35" src="https://user-images.githubusercontent.com/36952230/116683129-75767300-a9af-11eb-8359-4589b40eb46a.png">
<img width="518" alt="Schermafbeelding 2021-04-30 om 12 33 50" src="https://user-images.githubusercontent.com/36952230/116683754-562c1580-a9b0-11eb-8925-65b91be2b27c.png">

## Chart
<img width="446" alt="Schermafbeelding 2021-04-30 om 12 37 41" src="https://user-images.githubusercontent.com/36952230/116684137-de121f80-a9b0-11eb-82a7-51d5d2514cb6.png">

5. Add euro sign to graph 'total spent' (if the plugin allows us to)
<img width="531" alt="Schermafbeelding 2021-04-30 om 12 39 58" src="https://user-images.githubusercontent.com/36952230/116684381-2f221380-a9b1-11eb-80cb-9609c4e35120.png">

## Providers
6. Text change: Totaal uitgegeven bij = Totaal uitgegeven
<img width="462" alt="Schermafbeelding 2021-04-30 om 13 43 52" src="https://user-images.githubusercontent.com/36952230/116690753-23871a80-a9ba-11eb-95ac-31138db3e82e.png">

7. Sort the provider list descending based on the amount
<img width="558" alt="Schermafbeelding 2021-04-30 om 13 45 09" src="https://user-images.githubusercontent.com/36952230/116690852-4b767e00-a9ba-11eb-8d92-ebe06a12419a.png">

8. The transactions (transactions buttons) per provider are missing (just like it works in the current dashboard)

**Comment by linda-90** [comment]
I think it makes most sense if all filters show the same number. The total _number of transactions_ is shown in the graph and the table. Can we show this number for all filters?

And do the results change if you set a filter? Does it work like this?
- **Fund 1** has _100_ transactions,
- **All providers** are selected, including _100_ transactions
- **Sports** category is selected, with _30_ transactions.

The graph shows the _30_ transactions in number and total amount in time.
The table shows the _30_ transactions and the providers

-------------

1. Filter by funds - how many transactions
2. Filter by provider - how many transactions
3. Filter by postcodes - how many transactions
4. Filter by category - how many transactions
