### ISSUE TITLE
Deactivating / activating vouchers from Sponsor Dashboard

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2289]
## Context/goal: 
Figma: https://www.figma.com/file/gqlB1qA3B2EyWf9AXFAOHL/Deactivate-voucher?node-id=15%3A22&viewport=-5003%2C371%2C0.8350463509559631
CR: https://github.com/teamforus/general/issues/806

We need to allow the sponsor to deactivate a voucher if necessary and re-activate it back. Possible usecases for this are: the citizen died, fraud inspection, citizen not eligible anymore etc. 

On the voucher page - show a button `Deactivate` if the voucher is not yet deactivated
![Screenshot 2021-05-03 at 17 05 04](https://user-images.githubusercontent.com/33207036/116893869-bed5f500-ac31-11eb-9592-b6430c7158ae.png)

If it is deactivated, replace this button with a button `Activate`
![Screenshot 2021-05-03 at 17 05 54](https://user-images.githubusercontent.com/33207036/116893969-d614e280-ac31-11eb-8fdc-38ec4ccf6f3b.png)

When deactivating a voucher - you need to fill in a reason (mandatory)
![Screenshot 2021-05-03 at 17 06 15](https://user-images.githubusercontent.com/33207036/116894076-ec22a300-ac31-11eb-8e04-ac100bf2f5cd.png)

Show a confirmation modal after, with a checkbox. This checkbox gives you the possibility to send also an email notification to the user.
![Screenshot 2021-05-03 at 17 08 15](https://user-images.githubusercontent.com/33207036/116894331-386de300-ac32-11eb-8f54-2d678b5000a0.png)

**Comment by maxvisser** [comment]
Figma proposal needs to be enhanced; currently there a few things missing:
- the e-mail which gets sent to the citizen
- a place where the sponsor can see the reason he filled in after he deactivates;
- cases where you can deactivate (on the current pull request; you can even deactivate vouchers from 
- How would a deactivated voucher look inside Me-app / webshop
