### ISSUE TITLE
Bug: Title of assigned budget voucher is not shown

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2290]
## Context/goal: 
Mail that user receives after activation of budget voucher shows the literal variable in the title instead of the name of the fund. We had this problem before on a PR

![Screenshot 2021-05-06 at 09 32 29](https://user-images.githubusercontent.com/38419514/117259059-fcaf6500-ae4d-11eb-97ca-3331c4e87040.png)

**Comment by GerbenBosschieter** [comment]
Would be nice if we could hotfix this

**Comment by dev-rminds** [comment]
@GerbenBosschieter 
https://github.com/teamforus/forus-backend/pull/1155
