### ISSUE TITLE
Expiration date of product voucher shouldn't be later than the expiration date of the budget voucher used to buy the product

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2291]
## Context/goal: 
If a requester uses a budget voucher to do a reservation that has an earlier expiration date than the fund of that budget voucher, the product voucher will have the expiration date of the fund instead of the budget voucher.

**Example**
Expiration date of fund: 31-12-2021
Expiration date of budget voucher: 09-05-2021
Expiration date of product voucher: 31-12-2021
Expiration date of product voucher should be: 09-05-2021

![Screenshot 2021-05-07 at 10 03 18](https://user-images.githubusercontent.com/38419514/117418230-76615480-af1b-11eb-8dc2-b70007932933.png)

**Comment by maxvisser** [comment]
this resulted in a problem during extending the fund last year; we extended it on the last day of the fund where still alot of reservation were made. around 40 people had a product voucher which was valid even after their budget voucher was expired.
