### ISSUE TITLE
Add white space (spacing) between header and title 'Aanbod'

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2319]
## Main asssignee: @aghimpu 
CR: https://github.com/teamforus/general/issues/822

## Context/goal: 
<img width="1133" alt="Schermafbeelding 2021-06-09 om 14 20 43" src="https://user-images.githubusercontent.com/36952230/121353448-29afd580-c92e-11eb-9e2c-c078855079ea.png">

<img width="550" alt="Schermafbeelding 2021-06-09 om 14 26 05" src="https://user-images.githubusercontent.com/36952230/121353923-a9d63b00-c92e-11eb-947a-f3076830d732.png">

<img width="1440" alt="Schermafbeelding 2021-06-09 om 14 29 06" src="https://user-images.githubusercontent.com/36952230/121354343-14877680-c92f-11eb-8d7a-40af2b8ce3c9.png">

**Comment by maartenfv** [comment]
Yeaah!
