### ISSUE TITLE
Product reservations new text

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2321]
## Context/goal: 
We need good dutch texts for the product reservation setting(s) in the webshop.

@maxvisser could you add some more context and the english text and maybe a concept dutch text here so that @linda-90 can do the texts?

**Comment by linda-90** [comment]
@jamalv @maxvisser What can I do? Is there a figma proposal?

**Comment by maxvisser** [comment]
not have time yet to index whats needed. Will make screenshots of the all the english texts :)
