### ISSUE TITLE
Order of funds is suddenly changed? Please redo

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2327]
## Context/goal: 
This is a small thing but can have a big impact for our users if they are used to the order of the fund and they accidently do an action on the wrong one caus they are used to a different fund order.

Stadjerspas was always the first one. Now it is Stajderpas jeugd.

<img width="915" alt="Screenshot 2021-06-29 at 10 46 39" src="https://user-images.githubusercontent.com/38419514/123767026-77818300-d8c7-11eb-9a46-763b60ba8260.png">

<img width="515" alt="Screenshot 2021-06-29 at 10 46 08" src="https://user-images.githubusercontent.com/38419514/123767150-8ff19d80-d8c7-11eb-845e-d1042b8388a6.png">

**Comment by GerbenBosschieter** [comment]
Same counts for meedoenregeling en and busvoordeelabonnement. Justy the whole ordering of funds is now different

**Comment by maxvisser** [comment]
which commit changed the order?
