### ISSUE TITLE
Product categorisation financial dashboard

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#234]
**Problem**
The categorisation of products on the webshop is not functioning properly.

As a Sponsor I've created a fund with the category: "speelgoed".
Look at the image below for example:
<img width="516" alt="screen shot 2018-10-28 at 09 43 16" src="https://user-images.githubusercontent.com/38419514/47613846-66d53b00-da96-11e8-98cf-d58624513b9f.png">

And as a provider I've added a product with the same category.
Look at the image below for example:
<img width="580" alt="screen shot 2018-10-28 at 09 42 24" src="https://user-images.githubusercontent.com/38419514/47613869-c4698780-da96-11e8-925f-6a47c5309091.png">

If I log in as a sponsor and take a look a the financial dashboard I see the wrong categories. Everywhere is the same category , except for the webshop and financial dashboard.
<img width="501" alt="screen shot 2018-10-28 at 09 42 59" src="https://user-images.githubusercontent.com/38419514/47613876-00045180-da97-11e8-8a4f-f13fd1288323.png">

**Comment by maxvisser** [comment]
@GerbenBosschieter can you check if this one is fixed, your account can now only access the financial dashboard :)

**Comment by GerbenBosschieter** [comment]
@maxvisser aa hardcoded xD financial dashboard and webshop are solved now :)
