### ISSUE TITLE
Remove activationcode and euro's if it's a subsidy fund

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2340]
## Context/goal: 
If someone would export a voucher in pdf format he would receive the image of the QR-code and on the bottom of the page there is an activation code and and euro amount. This should be removed if the voucher is from a subsidy fund. It gives the impression that there is a budget.

![Screenshot 2021-07-21 at 10 05 43](https://user-images.githubusercontent.com/38419514/126453988-7f6b4b2e-be5c-472b-89be-50ed1ee66b46.png)

**Comment by maxvisser** [comment]
left button is not the activation code ;)

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-backend/pull/1227

**Comment by maxvisser** [comment]
discuss with @GerbenBosschieter the name; we remove now the amount for subsidy voucher and keep the name on the PDF and in the filename of PNG
