### ISSUE TITLE
Add CaseID to API

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2341]
@jamalv commented on [Wed Jul 21 2021](https://github.com/teamforus/general/issues/834)

Learn more about change requests here: https://bit.ly/39CWeEE

### Change description
The municipality needs a unique 'case' ID for the [API](https://docs.google.com/document/d/1CJIzLuhm9Zz_URL4wuT_sed-ddoRZxzYZj7zCQV64MI/edit#heading=h.2uk6madqfceo) connection. 

- [ ] Add a unique 'ID' to each request on the [API](https://docs.google.com/document/d/1CJIzLuhm9Zz_URL4wuT_sed-ddoRZxzYZj7zCQV64MI/edit#heading=h.2uk6madqfceo) - we can decide how we want to do it (name & number) but the ID needs to stay the same for the fund request

**Comment by jamalv** [comment]
2 options to fix it:

- we make the call to the api and send fund key + BSN > they can send us an ID. (each muncipality can choose their own format) - this is already possible. (we can add that we send this back each time)
- we create some ID and send it to them.

todo: verify with @maxvisser (should we generate the ID, or should they do it?)

**Comment by jamalv** [comment]
maybe we'll need to support both options - and depreciate the option that's not used after some time.

**Comment by maxvisser** [comment]
@maxvisser update issue
