### ISSUE TITLE
Change the aanvullherriningsgrens email

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2346]
## Context/goal: 
The current text of the "aanvullherinnerings" is confusing. 

**The following sentences raises questions to our users:**
_"U ontvangt deze mail omdat het budget van het 'Meedoenregeling' fonds lager is dan €2498.70"._ 

The amount in the e-mail is the limit where the user should get the notification minus the transaction cost.

**In the next sentence the amount is higher than the initial amoung:**
_"Het budget op het 'Meedoenregeling' fonds is momenteel €892.00."_

**Proposal**
- Change the sentence that raises questions and use the variable of the limit that the user set on fund settings
- Add a separate sentence about the transaction costs since it is important: _"Houd er rekening mee dat de  transactiekosten van {amount} buiten beschouwen worden gelaten"_

<img width="579" alt="Screenshot 2021-08-03 at 16 27 45" src="https://user-images.githubusercontent.com/38419514/128034030-e3178c39-ef3a-4667-b585-6bd6909f390f.png">

**Comment by maxvisser** [comment]
currently open as a PR; but PR will be closed as it needs to be changed in the custom email template instead
