### ISSUE TITLE
Custom emails

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2353]
@maartenfv commented on [Tue Feb 23 2021](https://github.com/teamforus/general/issues/768)

Proposal: https://docs.google.com/document/d/1jnFYQ0p9SUCd4jN3YWsnF5_7I37AXp-uY_MgaLhu-vA/edit
Figma: https://www.figma.com/file/E09uZSki0EQM7J7x5IeUiV/Webshop-%3E-System-e-mails

## First part
- [ ] Adding the mails to the database + how to store the fixed parts of the mails (API)
- [ ] Markdown
- [ ] Connecting backend to frontend

**Comment by maxvisser** [comment]
Issue moved to [teamforus/e-mails-adjustable-templates #2](https://github.com/teamforus/e-mails-adjustable-templates/issues/2) via [**ZenHub**](https://www.zenhub.com/)
