### ISSUE TITLE
Bug: no longitude is added to databse when provider creates or edits office

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2354]
## Main asssignee: @aghimpu or @dev-rminds 

**Start from branch:** Master

## Context/goal: 
We currently experience a bug where new created offices are wrongly posotioned on the map. This problems also occurs when an organization edits the office. This happends everywehere on the platform, during signup and on the dashboard.

I noticed that the creating and editing does work but for some reason there is no longtituded to the database, only the altititude.

**Comment by dev-rminds** [comment]
@GerbenBosschieter 
https://github.com/teamforus/forus-backend/pull/1254
