### ISSUE TITLE
Sponsor would like to see applications of provider on the last page. (change order)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2361]
## Context/goal: 
Nijmegen would like to have the applications of the provider on the last page. I can remember that we changed this after one of my requests after I did some testing. But user doesn't like this. Eventually we need an option for the user to change the order themselve. 

Until than, please change order of the applications of provider. Newest applications on last page.

**Comment by maxvisser** [comment]
lets check this first before planning it in.

**Comment by maxvisser** [comment]
Its now sorted on alphabetic order, should be sorted on newest creation date (of last fund_provider_request)

**Comment by maxvisser** [comment]
Add dropdown to choose how to sort it.
