### ISSUE TITLE
Easier local deployment for testing by using docker

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#238]
## Context/goal: 
It's currently very cumbersome to get both the front and backends running locally for testing etc. Using docker for this repository can make that a lot easier. 

**Note:** this repository contains two [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules): the [forus-frontend](https://github.com/teamforus/forus-frontend) and [forus-backend](https://github.com/teamforus/forus-backend). The purpose of this issue is to make it as easy as possible to get both of them running locally on different machines.

**Comment by jastam** [comment]
To make this work, docker images will have to be provided by the developers involved. Since the are familiar with the apps involved the will be best able to build these.

**Comment by jamalv** [comment]
docker-compose edit to 

checkout to docker branch
docker build . 
get image hash and run it with:
docker run -it -p 8080:80 8e549b1a4265

# to shell into container -> hash is container hash -> 'docker ps' to get container hash
docker exec -it 1eb5e384ea53 /bin/bash

**Comment by maxvisser** [comment]
Laradock now works on my device and jamal's and erans
