### ISSUE TITLE
FAQ issues

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#239]
- [x] When not logged in the FAQ works, but after you log in it doesn't expand
- [x] The answers on the FAQ is are Lorem ipsum:

<img width="852" alt="screenshot 2018-10-28 at 14 35 20" src="https://user-images.githubusercontent.com/30194799/47616553-bcbdd900-dabe-11e8-9681-125d5a84de01.png">

**Comment by GerbenBosschieter** [comment]
I will fix the lorem ipsum

**Comment by danrminds** [comment]
Done
