### ISSUE TITLE
Show login button on product page when not logged in

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#240]
When a user is not logged in and goes to the product page, there is no clear call to action.

## Logged out (right now):

<img width="735" alt="screenshot 2018-10-28 at 14 37 12" src="https://user-images.githubusercontent.com/30194799/47616573-1d4d1600-dabf-11e8-856b-865368b44c6a.png">

## Logged in:

<img width="701" alt="screenshot 2018-10-28 at 14 37 01" src="https://user-images.githubusercontent.com/30194799/47616578-2e962280-dabf-11e8-9b2f-c90ef62b5bd8.png">

Where it shows a "koop" button when you are logged in, it should show a login button when you're logged out.

**Comment by danrminds** [comment]
Done
