### ISSUE TITLE
Scroll down when you click "lees meer over hoe het systeem werkt"

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#241]
<img width="645" alt="screenshot 2018-10-28 at 14 40 34" src="https://user-images.githubusercontent.com/30194799/47616601-9187b980-dabf-11e8-8f09-cbf49a1836ef.png">

## should scroll to
<img width="1212" alt="screenshot 2018-10-28 at 14 40 41" src="https://user-images.githubusercontent.com/30194799/47616604-99dff480-dabf-11e8-98dd-d1f1d927f94d.png">

**Comment by maxvisser** [comment]
fixed
