### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#242]
Currently the page title is "Forus platform"

<img width="495" alt="screenshot 2018-10-28 at 14 43 46" src="https://user-images.githubusercontent.com/30194799/47616638-fba05e80-dabf-11e8-9fbb-7974d086f958.png">

It should be "[Municipality] - Forus"

**e.g.:**
Zuidhorn - Forus
Nijmegen - Forus

**Comment by GerbenBosschieter** [comment]
done
