### ISSUE TITLE
Automatically select voucher if only one is available.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#243]
When buying a product, after clicking "KOOP" you are taken to a 'kies voucher' screen.

<img width="1252" alt="screenshot 2018-10-28 at 14 51 35" src="https://user-images.githubusercontent.com/30194799/47616734-13c4ad80-dac1-11e8-9920-1258e67b57f6.png">

When you only have one voucher (currently the case for Zuidhorn) you should **not** get this choice. You should only get it when there are multiple vouchers you can choose from, otherwise selection should be made automatically, as it will otherwise cause confusion.

**Comment by maxvisser** [comment]
Should be some confirmation screen, 'shopping cart' checkout. Otherwise its instant

**Comment by maxvisser** [comment]
I think this can be combined with https://github.com/teamforus/forus/issues/352
