### ISSUE TITLE
Switch activatiecode and mijn vouchers buttons when logged in

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#245]
Vouchers are currently hidden behind a dropdown menu:

<img width="450" alt="screenshot 2018-10-28 at 14 58 04" src="https://user-images.githubusercontent.com/30194799/47616818-f04e3280-dac1-11e8-830b-665ab7a1d8b5.png">

It would be better to switch the activatiecode with the mijn vouchers buttons.

People that already have an account have probably already put in the activatiecode (to make the account) and would like to see their vouchers more often than that they need to activate new vouchers.

**Comment by maxvisser** [comment]
also bonus point: when you click login link in mail open the first voucher you have when logging in.
