### ISSUE TITLE
Email: image gets cut off

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#246]
This would look better if the image doesn't get cut:

<img width="1192" alt="screenshot 2018-10-28 at 15 26 11" src="https://user-images.githubusercontent.com/30194799/47617295-eb8b7d80-dac5-11e8-814d-b821469c02b5.png">

**Comment by danrminds** [comment]
The mail is sent by the forus platform (backend). It does not have to be in implementation colors. Only couple of mails are for the requester. The rest are for the providers / validators / sponsors

**Comment by jamalv** [comment]
I agree branding can be generic. 

But I think it's good to refer to the municipality site they are logging in to. So at least mention Zuidhorn etc. somewhere so that users do understand where the mail is coming from.

**Comment by maartenfv** [comment]
I agree with Jamal that in general it can be generic. However I suggest not to make the Forus logo very prominent as the main intent is to inform and not to advertise.

It is better to replace the logo with a reference to the related municipality so that people understand the connection and trust the message.

**Comment by danrminds** [comment]
@maartenfv @jamalv Let's arrange a 10 minutes meeting tomorrow and discuss this issue. 
It has to do with prioritisation of tasks, about the roadmap of our modularity, and other aspects as well.

**Comment by maxvisser** [comment]
@maartenfv could you make a seperate issue about your point of refencing the forus logo? as it is an important statement and it got a bit lost in an issue about a image cut off.

**Comment by danrminds** [comment]
I think even this issue should be deprecated an a new one created - to implement the new design of emails (team of Yasha did)

**Comment by maxvisser** [comment]
I will close this one. This want to leave the discussion open about branding Forus. I think @maartenfv opinion, as a stakeholder in this issue, is really important. That discussion can continue in #354
