### ISSUE TITLE
forus-platform does not support Internet Explorer

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#247]
**Problem**
So, The complete platform is not displayed on IE.
It has to do with AngularJS. 

Our users at the municipality are still working with IE, so this is a problem. Ofcourse we could ask them to use another browser. But we should support the most used browser.

http://henriquat.re/appendix/angularjs-and-ie8/necessary-changes-for-ie8-compatibility.html

**Comment by GerbenBosschieter** [comment]
I re-open this issue.

The dashboards are not supported by IE. The municipality is using Internet Explorer as their default browser. The only thing they get is an empty white page. 
This issue is also on newer version of IE.

**Comment by martijndoornik** [comment]
Screenshot of the console on loading Sponsor Dashboard in IE11:

![image](https://user-images.githubusercontent.com/3370256/49007023-c2184d00-f16a-11e8-9f30-52c63db3074e.png)
