### ISSUE TITLE
FAQ on provider page doesn't expand

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#251]
https://dev.zuidhorn.forus.link/provider/#!/

the FAQ doesn't expand when clicked

<img width="976" alt="screenshot 2018-10-29 at 20 41 39" src="https://user-images.githubusercontent.com/30194799/47675749-0b509d80-dbbb-11e8-9116-fcef41bf416b.png">

**Comment by GerbenBosschieter** [comment]
done
