### ISSUE TITLE
Update urls to point to me app in stores

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#252]
Me app for iOS is live at: https://itunes.apple.com/nl/app/me-forus/id1422610676
Me app for Android is live at: https://play.google.com/store/apps/details?id=io.forus.me

Pages I could find with links to the apps that should be updated:
- [x] https://dev.zuidhorn.forus.link/provider/#!/ (footer, bottom left)
- [x] https://dev.zuidhorn.forus.link/me/
- [x] https://dev.zuidhorn.forus.link/sponsor/#!/ (footer, bottom left)

**Comment by GerbenBosschieter** [comment]
done
