### ISSUE TITLE
Shopkeeper who isnt approved is now on shopkeeper overview on webshop

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#254]
![image](https://user-images.githubusercontent.com/10818702/47713437-91f88f80-dc3a-11e8-826d-a2d9d8305d07.png)

![image](https://user-images.githubusercontent.com/10818702/47713455-9f157e80-dc3a-11e8-9143-058f81739d93.png)

**Comment by danrminds** [comment]
Done
