### ISSUE TITLE
When filling in the activation code the system should auto add a dash (streepje) and the input amount should be limited

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#255]
**Extra important as this is the first interaction with our system.**

**Is your feature request related to a problem? Please describe.**
Currently filling in the code is not user friendly.

**Describe the solution you'd like**
After adding the first section of the code it should auto add the dash.
Input fields should have a character limit.

**Comment by GerbenBosschieter** [comment]
@maartenfv why should it have a character limit ?
Isn't it easier for people who wanna scam the system to create a script and try randomised activation codes if they know the character limit? 

Maybe I am exaggerating

**Comment by maartenfv** [comment]
@GerbenBosschieter just to make the chance of errors when filling it in as limited as possible. But maybe you are right regarding the security. @maxvisser what do you think?

And other example of a possible improvement was suggested by Margrieta of Zuidhorn. She mentioned she preferred the activation codes not to have any 0 or o or O as they look alike.

I think the more streamlined we can make it the better.

**Comment by jamalv** [comment]
currently we have 36^8 = 
2.821.109.907.456 possible combinations

removing o's and 0's would make 34^8 = 
2.176.782.336 possible combinations

classic security / usability tradeoff, I think the risk is manageable.

The system should be protected against brute-forcing anyway (ip-block after x attempts). I believe in the previous version we were using fail2ban, @maxvisser if not implemented yet, please add it to the security backlog.

**Comment by jamalv** [comment]
Regarding adding a dash, sure, let's try.

**Specs:**
* When you click the input field, a light grey dash appears as the fifth character.
* When you've input the first 4 characters the stripe turns black (like text).
* If you type a dash as the fourth character it gets ignored.

**Comment by maxvisser** [comment]
fail2ban is for a different use case ;)

**Comment by maxvisser** [comment]
@danrminds can you think about this issue a bit? I personally see no real problem against it.

**Comment by danrminds** [comment]
Also see no problem against, is just very not critical in my opinion and natters for when we schedule it

**Comment by GerbenBosschieter** [comment]
I re-open this issue. Got some question from support.
The idea of adding the dash automatically was to make it easier for the users to prevent conufsion. At the current state it causes confusion.

The problem now is that people trying to fill in the dash, but it doesn't work. The dash is only being added if you entering the fifth symbol.

**Solution**
- Only add the dash if the users enters the fifth symbol without adding dash them self.
- Does the user enter the dash themself? don't add the dash.

**Comment by maxvisser** [comment]
Or just show the dash before typing the 5th character.
