### ISSUE TITLE
Expire date product voucher, normal voucher should be on a different place.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#257]
I think for product voucher details we need to use the product page and edit in the voucher

![image](https://user-images.githubusercontent.com/10818702/47728767-4c01f280-dc5f-11e8-9121-99f3943323aa.png)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/47715850-4c8b9080-dc41-11e8-9e82-55641da92d41.png)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/47715930-85c40080-dc41-11e8-80e5-403a0c82005e.png)

**Comment by danrminds** [comment]
We need to show extra:

- Expiration day of the offer / voucher. - can be on the part with the product: Geldig tot: [date]
- Show description of the product (also on the product page)
- Provider name and details

**Comment by danrminds** [comment]
https://www.dropbox.com/s/43siflmnve84ogx/Product%20Voucher.tif?dl=0 - Product voucher
https://www.dropbox.com/s/qzwjz272ljqka5d/Product.tif?dl=0 - Product page

**Comment by jamalv** [comment]
@danrminds to clarify: the voucher on the right now is the Kindpakket fund voucher, but it will be the product voucher?

**Comment by danrminds** [comment]
Yes

**Comment by maxvisser** [comment]
Awesome!
