### ISSUE TITLE
Remove the google maps business locations.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#262]
## Problem:

The current map is showing both the shops that we added and the ones that are in google maps already. This can be confusing for end users.

<img width="565" alt="screenshot 2018-11-01 at 08 50 55" src="https://user-images.githubusercontent.com/30194799/47839550-651bb800-ddb3-11e8-9924-03d2cf4ea532.png">

## Proposed solution:
Remove the google maps business locations.

**Bonus:**
I don't think the user needs to have a choice between "map" and "styled map". I think the normal map looks good (with coloured roads and rivers etc.) but we should just remove the default businesses.

**Comment by maxvisser** [comment]
Also the map is in english localisation. We should add language to the embedding url
