### ISSUE TITLE
me landing page: buttons dont link to app/play store

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#268]
these buttons don't work
![image](https://user-images.githubusercontent.com/10818702/47954080-31dd5280-df86-11e8-9667-b2a8588076c1.png)

**Comment by jamalv** [comment]
Duplicate of: https://github.com/teamforus/forus/issues/252 (which was marked as fixed, but apparently wasn't)

**Comment by GerbenBosschieter** [comment]
I fixed those. Thats’s weird. I Will check it out

**Comment by GerbenBosschieter** [comment]
Every link works on every envirnmenont. I will close this issue. @maxvisser if you still see an page where the links don't work pleas re-open the issue and tell me what enviremont exactly.
