### ISSUE TITLE
Broken link to me: 404

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#270]
When clicking the tab 'me' on https://demo.forus.link/provider/#!/ I get a 404:

<img width="908" alt="screenshot 2018-11-03 at 16 55 38" src="https://user-images.githubusercontent.com/30194799/47954328-6272bb80-df89-11e8-97a7-a6a238b5a6ce.png">

**Comment by maxvisser** [comment]
I forgot to add me landing page to qdt-env on general webshop. Can you check if it works on zuidhorn?

**Comment by maxvisser** [comment]
The generel webshop is also not online yet

**Comment by jamalv** [comment]
@maxvisser, jup, that works (coming from: https://demo.zuidhorn.forus.io/provider/#!/)

**Comment by maxvisser** [comment]
forus.link is deprecated  and is not supported anymore.
