### ISSUE TITLE
Records are turned on

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#271]
## Should I already be able to access "mijn eigenschappen"?
I don't think we should display this already.

<img width="593" alt="screenshot 2018-11-03 at 17 13 11" src="https://user-images.githubusercontent.com/30194799/47954583-d1511400-df8b-11e8-93ce-563591885aba.png">

## If so, the page doesn't display right:

<img width="1792" alt="screenshot 2018-11-03 at 17 13 14" src="https://user-images.githubusercontent.com/30194799/47954591-f34a9680-df8b-11e8-9d5d-4350d63f4442.png">

**Comment by maxvisser** [comment]
Is only 'on' on demo. Also saw this

**Comment by maxvisser** [comment]
Will disable this in next release
