### ISSUE TITLE
Can't close issues

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#282]
**Description**
Currently we can't close some of the Github issues that have an label Error 500.
@jamalv some bird in the office told me you where responsible for this , so assign this to you.

**Workaround**
We can close it by going to the list of all issues, add a checkmark to it and close it by clicking "mark as". I would prefer the older situation

**Example**
<img width="804" alt="screen shot 2018-11-06 at 11 47 31" src="https://user-images.githubusercontent.com/38419514/48059551-c5e33000-e1b9-11e8-8213-1b124ff6e468.png">

**Comment by maxvisser** [comment]
Closed them for you

**Comment by jamalv** [comment]
yea, that bird was right, sorry 'bout that 😅

seems like they are gone though: for example this one had 500: https://github.com/teamforus/me/issues/139
