### ISSUE TITLE
fullscreen shopkeepers overiew for me

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#289]
'voucher info' in Me now links to zuidhorn.forus.io 
I want it to link to the map of shopkeepers.

![image](https://user-images.githubusercontent.com/10818702/48065222-680b1400-e1ca-11e8-8054-3812eb2ad34d.png)

![image](https://user-images.githubusercontent.com/10818702/48065426-fc757680-e1ca-11e8-9267-9956a41d8630.png)

**Comment by jknnr** [comment]
For Lena:
Shop name
Shop address
Working hours

**Comment by jknnr** [comment]
We will try to implement the map into the app where the product voucher has transactions. On the budget voucher the info button will lead to the map on the website.

**Comment by maxvisser** [comment]
I created another issue to make the mobile version of the map better.
