### ISSUE TITLE
pagination products block on webshop and product overview

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#291]
**Is your feature request related to a problem? Please describe.**
Now when all shopkeepers add a products, we will show all products on the home page of the webshop because we have no limit of the amount of products.

**Describe the solution you'd like**
Only show 6 products from six different shopkeepers, enable the 'show more' button to go the the overview of all products. Also disable 'category' dropdown and search on frontpage block.

**Comment by ateamcms** [comment]
@maxvisser so we show only 1 product from one shopkeeper and take first 6 shopkeepers. May be the situation when there are no 6 shopkeepers or not?

**Comment by maxvisser** [comment]
also a product should have an image to be on frontpage
