### ISSUE TITLE
Automatically add yourself as trusted validator

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#293]
The creater of the sponsor organisation should be added automatically as a trusted validator for his own organisation.

**Comment by maxvisser** [comment]
With access levels the owner should be automatically a validator for his own fund.

**Comment by danrminds** [comment]
@dev-rminds how can this be implemented in the new access levels?

**Comment by dev-rminds** [comment]
@danrminds We still keep old validators system alongside new access system.

In old system we have validators as separate entities, which are used for validation requests to dashboard (even thought currently we are no using it, it's still available in api).

We shall migrate the validators to the new access system but it will take some time to make sure that we don't break anything.

For now i would suggest to add the creator of the fund as validator when the fund is being created (same thing we did for the provider dashboard to add the creator as person allowed to scan the vouchers)

**Comment by maxvisser** [comment]
Yes, I was thinking the same. Also agree with the approach of merging this system over time with acces levels
