### ISSUE TITLE
collapse shopkeeper card on sponsor dashboard when accepted

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#299]
**Is your feature request related to a problem? Please describe.**
as there can be alot of shopkeepers connected to a fund

**Describe the solution you'd like**
we should collapse this information when accepted
![image](https://user-images.githubusercontent.com/10818702/48067085-a1924e00-e1cf-11e8-9498-5748daf9892f.png)

something like this: 
![image](https://user-images.githubusercontent.com/10818702/48067585-ea96d200-e1d0-11e8-8784-1254c28365c4.png)

**Comment by ateamcms** [comment]
it must be always collapsed when accepted or must be ability to toggle it?

**Comment by maxvisser** [comment]
I think a  toggle that hides everything but contact information
