### ISSUE TITLE
Validator requirements

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#3]
Respond to validation request
 - view requester identifying credential
    - bsn number / validated by government / digid
    - customer service number / validated by company
    - student number / validated by school
 - enter relevant information
 - validate and sign

Proactively validate information
 - get requester address
  - customer physically reveals address (qr code)
  - target customer from address dictionary [bsn / address]

**Comment by GerbenBosschieter** [comment]
I already talked with @maxvisser about the appropriate way to document this, I will comment them in this issue for now. Feedback is welcome :)

This list is work in progress.

User stories Me-App

Behind the user stories is an 'epic' and a kind of user.
Users = multiple roles

- [ ] As a validator I want to be able to register on the me app so I can make use of the me-app it’s services [ How to apply, users ]
- [ ] As a validator I want to be able to see the open request that need to be validated so I can validate them [How to validate, validator ]
- [ ] As a validator I want to be able to set requirements for validation to so the requester can see the requirements [How to validate, validator ]
- [ ] As a validator I would like to see a realtime status of the validation so I can see if its needs to be validated or not [How to validate, validator ]
- [ ] As a validator I want to be able to receive a reminder if a validation request is  open for longer period of time so I the requester won’t have to wait for so long [ How to search information, validator ]
- [ ] As a validator I want to be able to change the status of validation after its validated so I can for instance reject organisation who IMO are know longer valuable to validate [ How to validate, validator ]
- [ ] As a validator I want to be able to have an overview of all the users and organisations I’ve validated [ How to search information, validator ]
- [ ] As a validator I want to have an option to categorise everything so I can find on name, kvk number, personal number, etc [ How to search information, validator ]
- [ ] As a validator I want to have contact information if I have any question regarding the platform So I can ask my questions [How to search information, users ]
- [ ] As a validator I would like to have an report button so I can report certain people or organisations if I don't trust them  [How to report, validator ]
- [ ] As a validator I want to be able I want to do a validation manually so I can for example validate someone who is a the location of my shop/office [ How to validate, validator]

**Comment by GerbenBosschieter** [comment]
User stories are now handled by @danrminds , went through all the user stories with him. Close this issue
