### ISSUE TITLE
change translation text from 'gepauzeerd' to 'wachtend' on provider page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#300]
![image](https://user-images.githubusercontent.com/10818702/48067688-2893f600-e1d1-11e8-9a99-89b0a8afcba2.png)

In context the provider is 'waiting' to be confirmed to be added to the fund.

![image](https://user-images.githubusercontent.com/10818702/48067728-43666a80-e1d1-11e8-8fa0-fb72ecca4172.png)

**Comment by jamalv** [comment]
maybe 'In afwachting'?
