### ISSUE TITLE
Access levels: ability to change mail adresses

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#301]
**Is your feature request related to a problem? Please describe.**
As zuidhorn will merge into a new municipality called Westerkwartier. A user should be able to change his email. this is important because all employees of zuidhorn probably will get a westerkwartier.nl mailadress pretty soon. **edit 8-10-2019: users of wk.nl created a new account so its not that relevant anymore**

**Describe the solution you'd like**
- user creates account
- record primary_email is added with his mail 

**user wants to change mail**

- add email record (needs to be validated by sending mail and clicking a link in mail)
- after clicking validation link user sets new email record as primary_email

**old primary_email becomes email record (which now can be deleted)**

**note:** primary_email record should not be allowed to be manually changed or deleted as it used in some workflows

**security-wise**
I would like that we have a second way of authorization so people can protect themselves from a bad actor changing their emailadres.

## Edge cases
A user already created an identity with the e-mailadres he want to use to change his current mail address to. This is basically merging identities. I would say we should allow a user to soft delete such account (disabling login) and after this user can change e-mails.

**Comment by jamalv** [comment]
Yes, it would be nice to be able to add multiple email addresses. And to remove the primary email address. I like the way GitHub handles this.
