### ISSUE TITLE
Support: Tooltips at for input field

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#304]
**Is your feature request related to a problem? Please describe.**
Some fields are not really understandable and therefore need explanations

**Describe the solution you'd like**
I would like a tooltip option for input field to help the user what he needs to do when he enters a form.

**Describe alternatives you've considered**
A card that is used for FAQ or link to a knowledge base.

**Comment by danrminds** [comment]
TIF: 
https://www.dropbox.com/s/hy4a9iyy9p0fdlp/categories.tif?dl=0

Preview:
![categories](https://user-images.githubusercontent.com/33207036/48554244-2e2ec180-e8de-11e8-97fe-87d2db907530.jpg)
