### ISSUE TITLE
Screenshot Me landing page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#307]
Screenshot should be nice on landing page. 
![image](https://user-images.githubusercontent.com/10818702/48075369-6e59ba00-e1e3-11e8-938a-1914d9241d34.png)

https://zuidhorn.forus.io/me/

## Solution
Make new screenshots of the pages currently on the landing page in dutch!

**Comment by GerbenBosschieter** [comment]
Sidenote: Don't use my personal name XD! 
@jknnr I can also do it if you want to

**Comment by danrminds** [comment]
@GerbenBosschieter are you shy? )

**Comment by jknnr** [comment]
Will do this by Monday

**Comment by GerbenBosschieter** [comment]
@danrminds No, I've send you multiple screenshots and you choose exaclty the one you shouldt use XD

**Comment by maxvisser** [comment]
Only take the fully translated screenshots with nice demo content

**Comment by maxvisser** [comment]
![me-scan-qr-code](https://user-images.githubusercontent.com/10818702/49452021-b1a64900-f7e0-11e8-9297-d54c0302f2f5.png)

@jknnr what do you need to finish this issue. Do you want me to take over?

**Comment by jknnr** [comment]
I have the screenshots:) its done

**Comment by maxvisser** [comment]
but still needs to be implemented right? as https://dev.nijmegen.forus.io/me
