### ISSUE TITLE
Sign up: providers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#308]
**Is your feature request related to a problem? Please describe.**
As Nijmegen wants to add provider from 15 nov till 1 januari we should look at the signup form. It was now quickly implemented for the shopkeeper event.

**Describe the solution you'd like**
An example experience can be: 
https://www.bol.com/nl/m/zakelijkverkopen/

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/48079178-1b840080-e1eb-11e8-86f8-92856c8a7010.png)

confirming email adres is necassery; also check if they have access to mailbox.

**Comment by maxvisser** [comment]
Navbar should be hidden; when you didn't finish the form
![image](https://user-images.githubusercontent.com/10818702/48079340-74ec2f80-e1eb-11e8-8de4-e9a73a510ec1.png)

**Comment by GerbenBosschieter** [comment]
@maxvisser Is this issue now covered with that sign-up flow what I've send you? So I can close it

**Comment by maxvisser** [comment]
Yes
