### ISSUE TITLE
Research push notification implementation

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#31]
Research on the service for push notifications.

RabbitMQ / Websockets / other implementations

**Comment by jastam** [comment]
@martijndoornik Are we still going to do something with this issue? Like make a hello world with websockets for example? I don't think there is much magic left on this topic, but you never now.

**Comment by martijndoornik** [comment]
Problem is that - as far as I know - the Hello World and the final implementation only uses HTTP-connections. 

Also, https://github.com/teamforus/api.forus.io-ethereum/issues/7

**Comment by jamalv** [comment]
we could use a separate service for push notifications, right?

**Comment by martijndoornik** [comment]
We would probably have to

**Comment by danrminds** [comment]
Yes, think so. We also have to think what type of push notifications we will need besides of when you have to approve a transaction with pincode

**Comment by martijndoornik** [comment]
I think when someone receives a transaction or on a refund?

**Comment by danrminds** [comment]
Will not have refund functionality anymore.

**Comment by martijndoornik** [comment]
@maxvisser Can you make a websocket-repository. I will create one for the hello-world example

**Comment by jamalv** [comment]
@maxvisser that would then be forus.io-websocket, right?

**Comment by jastam** [comment]
Since the central part of de application is based on PHP, websockets will be problematic at best. Any workaround will complicate the workflow a lot. 

If we want to use push notifications i would propose periodically polling the PHP api over HTTP for updates. This way fits best with the short term plans.

**Comment by maxvisser** [comment]
I think jaspers solution for this is implemented.
