### ISSUE TITLE
Reimplementing refunds

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#314]
**Is your feature request related to a problem? Please describe.**
I had a discussion with @danrminds about refunds. We started with pro's and con's on this issue: https://github.com/teamforus/forus/issues/313 Refunding payed out money is a really irritating use case for both sponsors and providers (as we seen in 1.0 and thats why we havent implemented it again). On budget level, spending your QR code in the store, makes it that the provider gets directly payed out. With products on the webshop the shopkeeper does not get payed out, only in the store. Our solution for refunds is witholding the payout even longer on products. A two week period starts after the product is bought in the store. This period is used as waranty period.

**Describe the solution you'd like**
In Me the user can select on the product voucher 'I want a refund' it shows a QR code. This QR-code is used to add the amount on the product voucher back to the parent when the provider scan it.

**On budget level**
On budget level refunds are still not possible as the EURO's were already sent to the provider and its headache for programmers and sponsors to get these euro's back on the voucher.

**Comment by jamalv** [comment]
As commented on: https://github.com/teamforus/forus/issues/313 Let's not add refunding back to the platform and let's let the shops offer users their usual solution. Our experience is that the added complexity is not understood and only leads to confusion, while not being used like it is meant.

If many support issues come in that are about refunding, we can re-prioritize. Until then we can solve them on a case-by case basis. Our recommendation is letting the customer solve it with the shop.
