### ISSUE TITLE
Don't allow Providers without offices to apply for Funds.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#318]

**Comment by ateamcms** [comment]
@danrminds don't show funds if provider doesn't have offices? or show alert if provider go to funds page?

**Comment by danrminds** [comment]
When provider click on apply to fund - give an alert

**Comment by ateamcms** [comment]
We have this popup in any issue?

**Comment by danrminds** [comment]
Don't think so. @GerbenBosschieter can you make some text for it?

**Comment by maxvisser** [comment]
Title: U heeft nog geen vestigingen. aangemaakt
Description:
U hebt tenminste één vestiging nodig om uw organisatie aan te melden voor {{fund_name}}.
