### ISSUE TITLE
Popup - You can not apply for the fund without offices

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#321]
When you as a provider dont have any offices, you will still see funds in the list and the button. 

When clicking the button though - it will give you a popup with a message and instructions.

- You can not apply for this fund
- You need first to add at least 1 office
- You can do it [URL]here

@GerbenBosschieter I will need the text for this, and after - reassign me on this issue.

**Comment by GerbenBosschieter** [comment]
text:
**Dutch:** 
Op dit moment kun je je niet aanmelden voor dit fonds. Om je aan te kunnen melden dien je eerst een vestiging toe te voegen. Wil je dat direct doen? Klik dan op deze [link](url) om verder te gaan.

**English**
Currently you can't apply for this fund. To meet the requirements for this fund you need to add an office first. Click this [link ](url) to add an office immediately.
