### ISSUE TITLE
Research into mailchimp

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#324]
## Context/goal: 
Research integration of Mailchimp in the notification service. 
Problem to be solved: risk to have our IPs blocked because of multiple emails sent out.

**Comment by kremlinwarrior** [comment]
I think we can use this service
 https://aws.amazon.com/ru/ses/

**Comment by maxvisser** [comment]
I have SES configured for forus.link, have to do some research how to do this for forus.io

**Comment by kremlinwarrior** [comment]
Can me close it?
