### ISSUE TITLE
Error messages IBAN and KVK need to be improved

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#328]
![image](https://user-images.githubusercontent.com/30211022/48277098-03f68300-e44a-11e8-8ad6-7cf8819c88da.png)

Now it says validation.iban and validation.kvk. Should be: Het ingevulde IBAN nummer is niet geldig and
Het ingevulde KVK nummer is niet geldig

**Comment by maxvisser** [comment]
@gerbenbosschieter is hiermee bezit op een branch

**Comment by maxvisser** [comment]
Veel error messages zijn niet of half vertaald.
