### ISSUE TITLE
Annuleren button does not work as intended

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#329]
![image](https://user-images.githubusercontent.com/30211022/48277471-14f3c400-e44b-11e8-9074-a1424128640d.png)

Now when I press annuleren button al the errors pop up but it does not take me back to another screen.

**Comment by maxvisser** [comment]
I think with the overhaul this feature https://github.com/teamforus/forus/issues/320 will bring this will be fixed

**Comment by maxvisser** [comment]
This is not intended. Should be fixed.

**Comment by maxvisser** [comment]
@GerbenBosschieter if you have time could you check if this is the case for more forms. I want to know how big of an issue this is.
