### ISSUE TITLE
'Gebruik de activatiecode' opent popup zonder emailadres input

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#330]
## Description
When pressing 'use activationcode' link opens popup without e-mail adres input

---

Wanneer aanbiedingen geactiveerd zijn op de webshop en er nog geen aanbiedingen in het systeem staan kun je op gebruik activatiecode klikken. Dit opent een popup zonder invoerveld voor e-mail. (dit is goed wanneer je ingelogd bent) maar wanneer je uitgelogt bent wil je natuurlijk wel een e-mail kunnen invullen.

**Comment by GerbenBosschieter** [comment]
**Problem**
Can't fix this anymore after the implementation of modals. The popup doesn't work anymore and I don't know how I can open the popup.

**What I've tried**

Before modals:
I did it by adding this into the empty-block.pug: **(ng-click="$root.popups.auth.open('activate-code')")**

After modals:
And now I tried it with adding this: **ng-click="openActivateCodePopup()"**  , but this doesn't work either

@ateamcms can you take a look at this.

**Comment by GerbenBosschieter** [comment]
Nevermind @ateamcms , Max helped me a bit with it and I know how to do it know :)
