### ISSUE TITLE
Add warning. Can't delete product until sold out.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#333]
A warning to be showed on the list of products, adding a product form, editing a product (on the top) with some information

**Comment by danrminds** [comment]
@GerbenBosschieter Here also some text would be welcome )

**Comment by maxvisser** [comment]
NL: Let op! Nadat u een aanbieding heeft toegevoegd kunt u deze niet verwijderen tot dat het totale aanbod dat u hier invult verkocht is. Ga daarom na hoe vaak u dit aanbod kunt verkopen voordat u de aanbieding toevoegt. Daarnaast vult u een verloopdatum in van uw aanbod, dit bepaald mede de laatste datum dat de aanvrager uw aanbod kan ophalen.
