### ISSUE TITLE
screenshots of Me new restore pages.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#336]
## Context/goal: 
New screenshots for the flow
![image](https://user-images.githubusercontent.com/10818702/48364476-cfcccd80-e6a8-11e8-96ef-b88b92702457.png)

**Comment by jknnr** [comment]
![simulator screen shot - iphone x - 2018-11-14 at 16 40 12](https://user-images.githubusercontent.com/32199937/48494457-37f8ec00-e82e-11e8-92c9-9cc718c1d615.png)
![simulator screen shot - iphone x - 2018-11-14 at 16 56 00](https://user-images.githubusercontent.com/32199937/48494478-40512700-e82e-11e8-8e28-df546911f973.png)

**Comment by ateamcms** [comment]
Yes, maybe I don't commit that changes - commited to feature-sign-up-flow branch
