### ISSUE TITLE
e-mail notifications product voucher

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#339]
1. Product bought
This is a notification that the product is bought in webshop but not yet paid. Customer will come by in shop to pickup product or service.
![image](https://user-images.githubusercontent.com/10818702/49947132-c2497400-fef0-11e8-96b5-35f9f7410c00.png)

2. Product is sold out
this a notification for provider. They get notified when product is sold out so they can delete the offer in their dashboard and add a new one.
![image](https://user-images.githubusercontent.com/10818702/49948375-9e3b6200-fef3-11e8-8606-e729ed9b4f11.png)

**Comment by maxvisser** [comment]
could you write content for these?

**Comment by kremlinwarrior** [comment]
ok)

**Comment by GerbenBosschieter** [comment]
@maxvisser question for number 3:
Why should they receive an e-mail? Products that are already sold out are not displayed on the webshop. So in what situation do they need this mail

**Comment by GerbenBosschieter** [comment]
@maxvisser we can only add number 1 of there is an option to turn of e-mail notifications

**Comment by maxvisser** [comment]
these are notification for provider. They get notified when product is sold out so they can delete the offer in their dashboard and add a new one.

**Comment by maxvisser** [comment]
**text for mail 1**
Beste gebruiker,

Zojuist heeft iemand uw aanbieding '{{product_name}}' in de webshop gekocht. De klant kan daarom elk moment deze aanbieding komen ophalen of afnemen. 

De uiterlijke datum dat de klant langs kan komen is {{ expiration_date }}

Hopelijk hebben we u hiermee voldoende geïnformeerd.

**Comment by GerbenBosschieter** [comment]
** Test for mail 2 **

Beste gebruiker,

Uw totale aanbod in de webshop voor '{{ product_name }}' is uitverkocht.
U kunt nu het aanbod aanvullen of verwijderen en een nieuw aanbod plaatsen.

Dit kunt u doen door in te loggen op het dashboard
