### ISSUE TITLE
Change menu links on sponsor dashboard

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#341]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/48365832-533bee00-e6ac-11e8-9aa2-e454c0957b62.png)

Eigenschappen voorinstellen
CSV uploader
Prevalidation
etc.
allemaal termen die niet echt duidelijk zijn....

**Comment by jamalv** [comment]
So I think the tab can be called:
- aanvragers

Leveranciers tab can be renamed:
- aanbieders

On the screenshot above where it states CSV uploader in the content area, it can state:
- aanvragers toevoegen
