### ISSUE TITLE
IBAN edit organisation does not show.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#342]
![image](https://user-images.githubusercontent.com/10818702/48365941-a31ab500-e6ac-11e8-9038-349d8dd6b8d2.png)

Could you check if this is just frontend bug? IBAN could never be empty as it is validated on input.

**Comment by maxvisser** [comment]
This is not fixed yet.

**Comment by ateamcms** [comment]
[Commit](https://github.com/teamforus/forus-backend/commit/cfea6ae0a111e7ab7791a7da4fd8ed63f4b28cb2)
