### ISSUE TITLE
signupflow does not check immediately if email is used

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#343]
![image](https://user-images.githubusercontent.com/10818702/48366581-9e570080-e6ae-11e8-818a-b8eeb3d40823.png)

check if email is used. If used, present popup with QR code to login.

**Comment by danrminds** [comment]
It can not check immediately, as it does not login you after filling in your identity info (to let you go back and edit it in case you need - required part). 
It check this only after completing also adding an organization

**Comment by maxvisser** [comment]
Nah. Ofcourse it can, just check (GET request) and not create (POST) immediately. it really depends on how you implement it.

I agree with that it is maybe hard to implement as e-mail is added as a records and checking if a record exist while not creating an identity is more work. (but maybe worth the time investment).
