### ISSUE TITLE
Set up a fixed payment description when topping up.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#344]
## Context/goal: 
Set up a fixed payment description. So they can save it and re-use it instead of clicking the button and use a different description everytime time.

## Example:
![screen shot 2018-11-13 at 11 28 06](https://user-images.githubusercontent.com/38419514/48407517-47e1d480-e737-11e8-9baa-dd4bab097f58.png)

**Comment by maxvisser** [comment]
This is not UX/UI but a feature request.
