### ISSUE TITLE
Add clarification after voucher activation.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#345]
## Context/goal: 
It's not clear enough for the users what they should do after they activated their voucher.
Add a text what they can do with the QR-Code.

- [ ] Add text about the budget and what they can do with the voucher
- [ ] Add text about HOW they can use the voucher. (e-mail, print, me )

**Comment by maxvisser** [comment]
"Add text about the budget and what they can do with the voucher" should also be in the letter to citizens
"Add text about HOW they can use the voucher. (e-mail, print, me )" should also be in the letter to citizens

lets add the FAQ block under voucher details page?

**Comment by GerbenBosschieter** [comment]
With the feedback we received last time, they specifically said it's not clear if the page pops up and they want more information in the page itself. The page should be clear enough without the letter, is what they said.
