### ISSUE TITLE
Provider categories: which ones to add, and how?

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#346]
## Context/goal: 
We need to add all the categories that a sponsor uses for the provider.
I found this list what our next stakeholder is currently using.

- 1. Cultuur
- 2. Cursussen
- 3. Fitness
- 4. Muziek en Dans
- 5. Spiritueel
- 6. Sport
- 7. Overig

## Extra information:
Pleas don't close this issue until our next stakeholder agrees with the list.

**Comment by maxvisser** [comment]
If we group them it probably would make more sense to do something like this:
- 1. Cultuur, muziek en dans
- 2. Onderwijs en cursussen
- 4. Muziek en Dans
- 5. Spiritueel en welzijnsactiviteiten
- 6. Sport, zwemmen en fitness

**Comment by maxvisser** [comment]
If we go the marktplaats approach:
You ask instead of 'offer categories': 'What do you sell?'
Boeken,
Speelgoed,
Fietsen,
Computer,
Kleding,
Sport accessoires,
Activiteiten (tickets)

If they pick 'activiteiten' we give them seperate categories:
Concerten
Cursussen
Cultuur
Recreatie
Sport en fitness
Muziek en dans

**Comment by danrminds** [comment]
Having them to choose from radio buttons: I sell products / I sell services

If chosen products - show only categories for products. and same for services. 
Categories shown as a list of checkboxes (not dropdown anymore)
Also add info buttons on each checkbox options

**Comment by danrminds** [comment]
Products:

Boeken
Speelgoed
Fietsen
Computer
Kleding
Sport accessoires

Services:
Onderwijs en cursussen
Cultuur
Recreatie
Sport, zwemmen en fitness
Welzijnsactiviteiten

**Comment by GerbenBosschieter** [comment]
Don't leave the municipality out of this decision. Before we implement stuff or add categories that they don't agree with.

**Comment by danrminds** [comment]
TIF:
https://www.dropbox.com/s/hy4a9iyy9p0fdlp/categories.tif?dl=0

Preview:
![categories](https://user-images.githubusercontent.com/33207036/48554290-50c0da80-e8de-11e8-9480-bf596f63287a.jpg)
