### ISSUE TITLE
remove option to select organisation, skip it

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#348]
## Context/goal: 
It's not clear for organisations what they should do after singing in.
The text does tell the user what they should do (choose an organisation) but still it's not clear enough.

**Comment by maxvisser** [comment]
@danrminds I'm thinking to let people skip the choosing an organisation if they only have one.

**Comment by maxvisser** [comment]
@GerbenBosschieter Other than skipping choosing organisation, what would you recommend as a solution?

**Comment by jamalv** [comment]
Absolutely agreed, for now we offer functionality for individuals anyway. (right?) So until we do, we can skip this step. 

When we re-implement it when there's features for individuals we can have another look at this.
