### ISSUE TITLE
Signupflow: Clarify why Providers have to enter their e-mailadres three times

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#349]
## Context/goal: 
If a provider follows the sigh up flow it wil ask for the e-mail address three times.
For us its logic because:
- An e-mailaddress of the profile is individual
- An e-mailaddress of the organisation can be a main department or headquarters.
- An e-mailaddress of the office can be different than other offices within the same organisation.

**Comment by maxvisser** [comment]
@danrminds do we currently even use the second mail adres on organisation level?

**Comment by danrminds** [comment]
I think that is the email used to send notifications to the sponsor / provider (meant for the organization)

**Comment by jamalv** [comment]
If it is optional we should definitely label it as optional and explain the context.

e.g:
office email (optional): [ ]
_used to ..._

maybe at the signup flow we can link all of them together. or add a checkmark 
- [ ] same as ... (office email, organisation email etc.)

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/365

**Comment by danrminds** [comment]
@dev-rminds To which e-mail do we send the mail notifications of providers / sponsors?
To the e-mail of the individual identity, organization email, or office email?

**Comment by danrminds** [comment]
1. Removing e-mail from office completely
2. Sending email notifications to the organisation e-mail
