### ISSUE TITLE
When openingshours are empty display message on webshop

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#351]
## Context/goal: 
Some providers have varying opening times. 

when none are entered the following message:
EN: Openings hours unknown, please check with the provider.
NL: Openingstijden onbekend, raadpleeg de aanbieder.

Place to show message:
![image](https://user-images.githubusercontent.com/10818702/48469197-740c5c80-e7ee-11e8-9375-c4575a1eb3f7.png)

It should also be shown on voucher details an product details, where now these times are also shown

**Comment by maxvisser** [comment]
You can leave it empty right?

**Comment by GerbenBosschieter** [comment]
@maxvisser I like this solution

**Comment by jamalv** [comment]
Related to https://github.com/teamforus/forus/issues/350

During role-play a shopkeeper told us their opening times vary and they would like to redirect them to the website. We can kill two birds with one stone if we make the message say:

EN: Openings hours unknown, please check with the provider.
NL: Openingstijden onbekend, raadpleeg de aanbieder.

We can give shopkeepers the option to make their phone number public: https://github.com/teamforus/forus/issues/356

**Comment by maxvisser** [comment]
I like jamal's suggestion more.
