### ISSUE TITLE
Popup: before buying product voucher; tell non-refundable voucher

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#352]
Related to: https://github.com/teamforus/forus/issues/314

We decided not to implement refunding. This has been discussed with our current main stakeholders as wel on Monday and they have accepted this, but on the condition that we give clear warning when an action is permanent.

Especially, for example, when purchasing on the webshop.

"Are you sure you want to buy [offer] for [amount]? Once confirmed, this cannot be undone. Refunds are not possible. The expiration date is 11-11-19 00:00"

@maxvisser Is this already in the system? Otherwise, let's implement this before activating products.

**Comment by danrminds** [comment]
Noted.

**Comment by maxvisser** [comment]
This is not in. But should of course.

**Comment by maxvisser** [comment]
NL: Weet je zeker dat je deze aanbieding '[name of product]' wil kopen voor [amount]? Wanneer bevestigd kan deze transactie niet ongedaan worden gemaakt. Een terugbetaling is niet mogelijk.
De verloopdatum van het product is: [date], Zorg ervoor dat je tijd hebt om het product voor deze datum op te halen.

**Comment by danrminds** [comment]
TIF:
https://www.dropbox.com/s/dgqenagn0jqfb9t/Product%20-%20PopUp.tif?dl=0

Preview:
![product - popup](https://user-images.githubusercontent.com/33207036/48503623-eeff6280-e842-11e8-908e-8c69181b8cee.png)

**Comment by danrminds** [comment]
this page can be disabled after implementing the popup
https://github.com/teamforus/forus/issues/243
