### ISSUE TITLE
Limit the amount of offers / products a provider can add to 2 per provider.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#357]
As we are currently in a startup phase with allowing offers on our platform and we want to gather feedback first. I think we should limit the amount of offers a provider can set up in the system. This way we can manage all feedback and still help out where is needed.

**Comment by ateamcms** [comment]
To make it work with [commit](https://github.com/teamforus/forus-frontend/commit/5c9acf1bf8f0eac9f5b2fb7acc1fba671f04e08f) you needed to add in qdt-env.js file `max_product_count: 2'` for `"forus-platform.provider"`. So you can change max count, that provider can add

**Comment by maxvisser** [comment]
add this to backend
