### ISSUE TITLE
product voucher expiration date ! >= the expiration date of the fund

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#358]
We need to not allow the product expiration date to be later then the expiration date of the fund.

How I see this implemented:

- Provider adds product x on dashboard with 01-01-2020 as expiration date

- fund y expiration date is 01-11-2019 (set on sponsor dashboard)

- When citizens buys product x with fund y the expiration date of the product voucher is set to the end date of the fund.

**Comment by danrminds** [comment]
A problem here: the product is not assigned to a fund (meaning you can not follow the expiration date of the fund

**Comment by maxvisser** [comment]
you use a fund to buy a product -> when you do this action check expiration date of fund -> if product expiration date is higher -> replace it with expiration date of fund.

**Comment by danrminds** [comment]
Yes. So the expiration date we are talking is related to the expiration date of product vouchers, not products themselves.

**Comment by maxvisser** [comment]
Yes sorry title was wrong

**Comment by maxvisser** [comment]
We should add this new date to popup https://github.com/teamforus/forus/issues/352
