### ISSUE TITLE
Me app download (sms service)

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#361]
## Problem

Currently the onboarding page links to the app stores. Since the user will be on their desktop this is a pretty poor UX. 

<img width="1540" alt="screenshot 2018-11-14 at 19 47 39" src="https://user-images.githubusercontent.com/30194799/48504914-2cb1ba80-e846-11e8-8dbf-e2d16c13b9a8.png">

## Solution
We should offer an easy way send the link to their device. SMS is the best way to do this.

- [x] implement a download url (forus.io/dl) and a splash screen like https://github.com/teamforus/forus/issues/361#issuecomment-438978527
- [ ] research what service we can use to achieve sending it by sms (e.g. https://www.twilio.com/sms)
- [ ] implement

## Specs

1. user fills their phone number in the field
2. user receives sms with a link (e.g forus.link/downloadme)
3. user opens link in browser on their phone
4. page checks if the user is on android or iOS and redirects to the appropriate App Store.

For @kremlinwarrior 
The url with those steps - https://dev.zuidhorn.forus.link/provider/#!/sign-up

**Comment by danrminds** [comment]
I assume this is not for Monday?

**Comment by maxvisser** [comment]
https://www.twilio.com/sms

**Comment by maxvisser** [comment]
goal is to implement this before friday; hackathon style :sunglasses:

**Comment by danrminds** [comment]
Advice:
Put a link similar to whatsapp on the step 1
![screenshot 2018-11-15 10 36 14](https://user-images.githubusercontent.com/33207036/48543673-53add200-e8c2-11e8-9b25-ecfad8bcb3db.png)

**Comment by maxvisser** [comment]
If you go to forus.io/dl you should automatically open the app store or playstore (depends on device)

**Comment by danrminds** [comment]
TIF: 
https://www.dropbox.com/s/geqhxfls550c498/1.%20Step%201.tif?dl=0

Preview:
![1 step 1](https://user-images.githubusercontent.com/33207036/48650910-ae494a00-e9f8-11e8-8086-b8c1231f6246.jpg)

**Comment by jamalv** [comment]
On iOS the user should be sent to: https://testflight.apple.com/join/gWw1lXyB

_this version of the app (beta) is connected to staging, where our stakeholders will test if everyting works_

**Comment by jamalv** [comment]
And we'll also need to host an APK that is connected to the same baseurl that android users can download. It should have another bundleID (io.forus.me.beta) so that it will not replace the production version.

**Comment by maxvisser** [comment]
I have an apk for staging
