### ISSUE TITLE
Sign up flow: explanation information Me profile

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#362]
**Is your feature request related to a problem? Please describe.**
The user is ask to make a profile but does not get an explanation why he needs it.

**Describe the solution you'd like**
Explain why he needs to fill in his email, first name and lastname. The reason is that we allow multiple profile to do a transaction for an organisation. He can add more profiles later to his organisation to scan vouchers. To make it simple: You need a profile to scan vouchers for your organisation. Implement this under a information button.

**Comment by danrminds** [comment]
So, we should implement an info button I assume? We can make also a description of the step on the top. The info buttons can be near each field.
And we will need text from @GerbenBosschieter for it
