### ISSUE TITLE
make error message for old browsers IE 9 and lower

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#364]
## Context/goal: 
As we don't support old browser lets make a error message that people need to download a new one.

**Comment by danrminds** [comment]
TIF:
https://www.dropbox.com/s/xvvghg3jhytj8ol/Older%20IE.tif?dl=0

Preview:
![older ie](https://user-images.githubusercontent.com/33207036/48561053-71456080-e8ef-11e8-9906-7f20e4c2889e.jpg)

@GerbenBosschieter - would be nice to have some text )
