### ISSUE TITLE
Signupflow: popup: ask to open on desktop if user is on mobile

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#366]
**Is your feature request related to a problem? Please describe.**
The signupflow should be fillable on mobile. On mobile the flow is much simpler.

**Describe the solution you'd like**
The step of downloading me is at the end. The user will first make a profile and organisation.
Activating the me app happens through deeplinking after download.

**Describe alternatives you've considered**
Not supporting mobile signup for now but giving an error to do it on desktop.

**Comment by dev-rminds** [comment]
Currently, it's not possible to authenticate devices through deep linking.  
This will require a new authorization method which will require to update both android and ios applications and backend as well.  
  
For now i would suggest to show an message asking user to use a computer.  
Or we could send a restore email and ask the user to open the link from the email.

**Comment by jamalv** [comment]
> For now i would suggest to show an message asking user to use a computer.

I think that will be fine.

**Comment by danrminds** [comment]
TIF: 
https://www.dropbox.com/s/m75hy7774nb43zt/Signup%20flow%20mobile.tif?dl=0

Preview:
![signup flow mobile](https://user-images.githubusercontent.com/33207036/48561172-b2d60b80-e8ef-11e8-9a68-900a267db3dc.jpg)
