### ISSUE TITLE
Add office locations while on boarding

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#367]
**Is your feature request related to a problem? Please describe.**
We want on boarding to be a complete process, users should not have to go to the dashboard afterwards. Part of this is adding an office and opening times. The information that is pulled from the KVK is not always accurate.

**Describe the solution you'd like**
There should be a step to add an office, with opening times and your location on the map. When adding your office, we can pull the address from kvk, but we should show it on the map so that the shopkeeper can validate that this is actually the correct location.

**Comment by danrminds** [comment]
TIF:
https://www.dropbox.com/s/5s2fefgqm29ij3p/Add%20offices.tif?dl=0

Preview:
![add offices](https://user-images.githubusercontent.com/33207036/48553380-b3fd3d80-e8db-11e8-844f-99626e375896.jpg)
