### ISSUE TITLE
Signupflow: give a reason why they need an app

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#368]
**Is your feature request related to a problem? Please describe.**
At step 1 of flow give explanation of why they need the app.

**Describe the solution you'd like**
A graphic that the provider will get the concept of that he will use a app to accept payments. 

<img src="https://i.imgur.com/dVclko4.png" height="200"/>

added this img from freepik to header with position: absolute and right: 20px;

![image](https://user-images.githubusercontent.com/10818702/49139029-0afa0e00-f2f1-11e8-8e8b-e1b1bc6c4777.png)

**Comment by danrminds** [comment]
@Myshelova Lena, can you maybe take a look if you can find such a vector or perhaps draw one? :)

**Comment by maxvisser** [comment]
![](https://i.imgur.com/nl61GI4.jpg)

**Comment by maxvisser** [comment]
"To do payments you need an app, you will scan QR-codes and fill in the amount to do a transaction"

**Comment by maxvisser** [comment]
I will close this for now.

**Comment by danrminds** [comment]
Choose one from here better: https://www.freepik.com/index.php?goto=2&searchform=1&k=phone+scans+qr

**Comment by maxvisser** [comment]
https://www.freepik.com/premium-vector/qr-code-icon-on-smartphone-screen_2011911.htm#term=qr%20scan&page=1&position=38

Maybe look good in our colors

**Comment by maxvisser** [comment]
https://www.freepik.com/premium-vector/qr-code-icon-on-smartphone-screen_2011911.htm#term=qr%20scan&page=1&position=38
Or

 bottom right cutting off the sleeve. As it does not have fingernails probably fits better with design language of forus of less detailed vectors

**Comment by maxvisser** [comment]
https://i.imgur.com/dVclko4.png

added a img to header with position: absolute and right: 20px;
