### ISSUE TITLE
Signupflow: brand identity

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#369]
**Is your feature request related to a problem? Please describe.**
Currently the signupflow is in the brand identity of Forus. Nijmegen would like this to be in their style.

**Describe the solution you'd like**
Step one:
Add colors of Nijmegen and logo

Step two:
Use their bootstrap css for all buttons and layout

Tip! The shopkeeper should not have the feeling he left this website when he presses the green button:
https://www.nijmegen.nl/diensten/uitkering-schulden-en-laag-inkomen/meedoen-regeling-organisatie-aanmelden/

**Describe alternatives you've considered**
White labeling the signup flow. No forus branding at all.

**Comment by jamalv** [comment]
Not sure if we want to do this. When the shopkeeper goes to their dashboard they will still feel like they left their page, and the work on our end and the expectations we create with this are quite high.

Currently the page that shopkeepers end up at looks like this: https://www.nijmegen.nl/gns/no_index/webforms/?inter_meedoenregeling

**Comment by jamalv** [comment]
I do think we need to remove all Forus branding (so no logo).

**Comment by jamalv** [comment]
We can copy this page: https://www.nijmegen.nl/diensten/uitkering-schulden-en-laag-inkomen/meedoen-regeling-organisatie-aanmelden/

and update the texts with the new approach. We should then send our stakeholders a link to our version of that page, with the button linking to our (unbranded) signup flow.

**Comment by danrminds** [comment]
@ateamcms - So here we only remove the logo of Forus from the sign-up flow.
