### ISSUE TITLE
Signup flow: apply for a fund

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#370]
**Is your feature request related to a problem? Please describe.**
The signup flow should be a complete process. Therefore the last step should be to apply for a fund.

**Describe the solution you'd like**
1. At the last step of signup, user sees an overview with funds. 
2. User click apply on the fund(s) that they think fit their organisation. 
3. User gets a message: waiting for response from [sponsor name] you will receive an email on [user email address] when you are approved and can start to accept payments.

**Comment by danrminds** [comment]
Step 3 might make confusions, as you might have more funds there. If you apply to 5 funds, do you want that message to appear 5 times?
