### ISSUE TITLE
Signupflow: Already have a profile and organisation

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#378]
## Prerequisites

1. Create Me profile in app
2. login via step 2
3. You will be send to step 3: fill in organisation information
4. Button for going to the next step does not work. 

## Description

Refreshing brings you to the organisation selection page.

**Comment by maxvisser** [comment]
I'm pretty sure I maybe already had an organisation. I will change this one to an enhancement.

I think if you login to the signup form on step 2 and you already have an organisation. its a bit hard to go via organisation selection back to the signup flow...

I would suggest to go not to step 3 but just to the organisation selection screen and let them add offices in dashboard for now.

**Comment by danrminds** [comment]
Now Valentin already commits a hotfix for the issue.

**Comment by maxvisser** [comment]
Now just works, creates new organisation. maybe we should warn people that they are creating second one but that not for now.
