### ISSUE TITLE
Signupflow: organisational emailaddress

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#379]
## Context/goal: 
As we ask in the signupflow 2 types of email adresses. I want to make sure we collect these also in the mail service.

personal e-mailadres. (owner of organisation; used to authenticate only)

organisational e-mail address (provider notifications should go here)

step 1:
also collect these while creating organisation in mail service, this should be done asap.

 - as we already have 12 shopkeepers in the system, I need a way to add these to the mail service via import

step 2:
changing mail service to send notifications to organisational mail address

**Comment by kremlinwarrior** [comment]
Right now we have only one email per user
