### ISSUE TITLE
Crop widget integration

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#380]
TIF:
https://www.dropbox.com/s/6x2ypwlz542qlx3/Crop%20Image.tif?dl=0

Preview:
![crop image](https://user-images.githubusercontent.com/33207036/48673507-6fbfa680-eb42-11e8-9e5f-5df78ac89ee5.png)

**Comment by maxvisser** [comment]
Title: 'Afbeelding bijsnijden'
Subtitle: 'Upload een afbeelding en gebruik daarna het selectievenster om de afbeelding bij te snijden.

----

Title: 'Kies een afbeelding'
Button: 'Upload'
