### ISSUE TITLE
Placeholder for organisation/office

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#383]
**Is your feature request related to a problem? Please describe.**
When you create a identity and organisation, it will automatically get lat long coordinates to pin the office on the map. Could we use the same to suggest a image from streetview?

**Describe the solution you'd like**
https://developers.google.com/maps/documentation/streetview/intro

```
https://maps.googleapis.com/maps/api/streetview?size=400x400&location=40.720032,-73.988354
&fov=90&heading=235&pitch=10
&key=YOUR_API_KEY&signature=YOUR_SIGNATURE
```
making streetview the placeholder image.

**Describe alternatives you've considered**
getting first image from google images
https://webmasters.stackexchange.com/questions/18704/return-first-image-source-from-google-images

**Comment by jamalv** [comment]
I think that this would probably have a very high error rate. I would prefer to make the image optional. If there's no image don't show a placeholder but just move the content to the left when that's possible.

**Comment by jamalv** [comment]
## Bergman with image
<img width="1004" alt="screenshot 2018-11-19 at 10 38 54" src="https://user-images.githubusercontent.com/30194799/48698596-c501c380-ebe7-11e8-8781-c96ef9aababe.png">

## Bergman without image
<img width="1004" alt="screenshot 2018-11-19 at 10 38 54 copy" src="https://user-images.githubusercontent.com/30194799/48698614-d2b74900-ebe7-11e8-92af-fcaef29f7919.png">

**Comment by maxvisser** [comment]
This has low priority. but needs some investigation. I will move this back to icebox until we have some more providers. I want to see the system with alot of provider in it to judge an approach.

**Comment by maxvisser** [comment]
I think with the current implementation of the crop functionality I will close this issue for now.
