### ISSUE TITLE
Edit organisation: btw number should not be required [provider]

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#384]
Can´t confirm the upload of my new picture when editing my organisation because of not entering btw number.

During the sign-up-flow the btw-number is not mandatory, I also did not upload a picture yet.

After I created my organisation I wanted to add a picture.

I found a nice one but when I press bevestig it states that I should fill in the btw number.

**Comment by maartenfv** [comment]
This is contradicting. It is either optional of mandatory.

![image](https://user-images.githubusercontent.com/30211022/48700037-3e4ee580-ebeb-11e8-874a-90d6483531b1.png)

**Comment by ateamcms** [comment]
[This changes is in backend commit](https://github.com/teamforus/forus-backend/commit/74b05a5f10675ca3963b44443be27dfbe7146761)
