### ISSUE TITLE
Signupflow: if you are already logged in and go to URL of sign-up flow - it will direct you to step 4 (adding offices)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#387]
During the sign-up process for the providers, when reloading the page, it stops the process and sends me to the choose organisation page. I can´t go back to the step I was.

## solution
if you are already logged in and go to URL of sign-up flow - it will direct you to step 4 (adding offices)

**Comment by maxvisser** [comment]
same as #381

**Comment by danrminds** [comment]
Don't consider this is as an issue.

1. Why would you reload in the end?
2. This happens only if you are already logged in (everything is created). All the other steps you can make from inside the dashboard.

**Comment by maxvisser** [comment]
I personally feel this should be changed in the long run. We have to think the whole proces through and make a decision on how approach it.

A quick fix for this is maybe a onbeforeunload, this is a popup that happens when you close of the screen or refresh it.

````
    window.onbeforeunload = function() {
        return "Weet je zeker dat je formulier wilt verlaten? Dit betekent dat je wordt ingelogd op het dashboard.";
    }
````

**Comment by ateamcms** [comment]
What about if provider already has several organisations and go to  sign-up flow URL - for what organisation provider will add offices?
