### ISSUE TITLE
change splash on zuidhorn webshop

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#392]
## Context/goal: 
I still dislike the girl on frontpage of zuidhorn. I think we should change it to some images I got from zuidhorn. Will send these to gerben

**Comment by danrminds** [comment]
Will discuss it tomorrow, but having this type of things on both sides seems weird for me

**Comment by GerbenBosschieter** [comment]
So where are the images ?

**Comment by GerbenBosschieter** [comment]
I would like to start working on the image. I need images max :)
