### ISSUE TITLE
provider count on map/overview webshop

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#393]
## Prerequisites

1. Use dev enviremont (already has providers)

## Description

Google Maps has a hardcoded message. (amount of providers)
Tried to fix it myself by doing this:

block.block-shops_map
            .shop_map-header
                .shop_map-title {{ "popup_offices.header.title" | translate }} ({{ $ctrl.Providers.length }}) {{ "popup_offices.header.titlepart" | translate }}

## Result:
![screen shot 2018-11-20 at 15 18 12](https://user-images.githubusercontent.com/38419514/48779273-89462700-ecd7-11e8-9fe2-fc2ddee8e937.png)

**Comment by ateamcms** [comment]
[pull request](https://github.com/teamforus/forus-frontend/pull/162)

**Comment by maxvisser** [comment]
still needs to be added to zuidhorn and nijmegen webshop

**Comment by maxvisser** [comment]
Does not work anymore after unification

**Comment by dev-rminds** [comment]
All the changes that ware made on "implementations" and were not added to "general" webshop as well, ware lost.  
Also the env data should be as thin as possible and contain only data like urls and api keys. Now all other types of configurations should be stored in configs files inside the codebase.  
[https://github.com/teamforus/forus-frontend/blob/develop/src/sources/forus-webshop/js/angular-1/config/flags.js](https://github.com/teamforus/forus-frontend/blob/develop/src/sources/forus-webshop/js/angular-1/config/flags.jsl)

**Comment by dev-rminds** [comment]
Sorry this is not related to this issue i was referring to `max_product_count` parameter from the pull request but it's not used anymore.
