### ISSUE TITLE
Webshop update: Collapse provider details on maps modal webshop frontpage on smaller screens

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#395]
## Problem
on desktop the map is too small.

## Solution
The map needs to be adjust better to the screen size. Lets collapse it when entering screen sizes smaller than 1280px

![image](https://user-images.githubusercontent.com/10818702/49364057-96a1df00-f6e3-11e8-8b1e-eff9a4fbb045.png)

- [ ] automatically collapse right column
- [ ] Add a button to undo the collapse, maybe some arrow >, or collapse it on bigger screens aswell

**Comment by maxvisser** [comment]
adjusted the issue, this will proposal will be shown also with sprint demo
