### ISSUE TITLE
signupflow: add sms service frontend 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#398]
## Context/goal: 
sms service is implemented in notification service;
![image](https://user-images.githubusercontent.com/10818702/48799754-4486b400-ed08-11e8-9dd1-ffc4051aa099.png)

add some frontend like this:
![image](https://user-images.githubusercontent.com/10818702/48800947-764d4a00-ed0b-11e8-8f35-7b5b496d7720.png)

like @jamalv suggested: https://github.com/teamforus/forus/issues/398#issuecomment-440423243
prefix 06 in input field (cant remove)
hardcode +316 

## add sms service to forus-backend
add a call to above stated api route using NOTIFICATION_URL in .env

## sms content
Download Me makkelijk via de link:
https://www.forus.io/DL

**Comment by maxvisser** [comment]
do you guys think that area code is needed? I tested the service it requires area code of +31 before phonenumber (example: +31612345678)

**Comment by maxvisser** [comment]
@jamalv should we still have a link to the app stores on the first step?

**Comment by maxvisser** [comment]
text for title: U kunt Me makkelijk downloaden via: https://www.forus.io/dl

**Comment by danrminds** [comment]
Areacode can be hardcoded in the frontend

**Comment by jamalv** [comment]
yea maybe we can prefix it with 06 as the first two numbers (so user enters 8 numbers) and then just send +31 6 to the backend as prefix

**Comment by jamalv** [comment]
> @jamalv should we still have a link to the app stores on the first step?

I like the way you implemented it now, showing the download link. It might be good to make it light blue to make it stand out more.

**Comment by jamalv** [comment]
shopkeepers will be added after Tuesday, is it possible to implement this before then?

**Comment by maxvisser** [comment]
Seems like I did not set NOTIFICATION_URL. I changed it in the service and merged it.
