### ISSUE TITLE
Requester requirements

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#4]
Select what to request

Provide necessary personal information (according to fund criteria)
- Popup "do you want to reveal xxx to Forus?"
  -  maybe we can skip this step when everything is securely and 
     privately handled on blockchain

Take steps to get missing information validated
 - request digitally - from validator database or manual entry
 - make appointment: receive validator / go to validator

Funding
 - [ ] add extra funds (iDeal) if budget is inadequate

Confirm request
 - if delivery confirm delivery address
 - if pickup, learn pickup location

Receive requested good
 - rate service
 - rate product (after 1 day and after 3 months)

**Comment by maxvisser** [comment]
https://drive.google.com/file/d/13QyRVl3CiuaiRncpVIJXN-Pc1E0ebPhp/view?usp=sharing

**Comment by maxvisser** [comment]
1. fund -> profile -> kindpakket 200
2. vouchers -> me -> bike

Show fund and vouchers in both web and me ?

**Comment by GerbenBosschieter** [comment]
I already talked with @maxvisser  about the appropriate way the document this, I will comment them in this issue for now. Feedback is welcome :)

This list is work in progress.

**User stories Me-App**

Behind the user stories is an 'epic' and a kind of user.
Users = multiple roles (in this case the requester and provider).

* As a requester I want to be able to register myself on the Me-app so I can create an self sovereign identity. [ How to apply, Users ]
* As a requester I want to be able to restore my identity in case I lose / break my phone so I can use the App again. [ How to secure , Users ]
* As a requester I would like to have acces to my personal records so I can have an overview of my personal information. [ How to search information , Requester ]
* As a requester I would like have a categorisation function so I can have a more structured overview of my personal information. [ How to search information , Requester ]
* As a requester I want to be able to approve delegates who can validate my identity if needed. [ How to secure, Requester ] 
* As a requester I want to be able to ask third parties to validate certain records so I can use them for certain services. [ How to get validated, Requester ]
* As a requester I want to be able to set my own requirements for sharing the information so I have control over what third parties can do. [ How to get validated, Requester ]
* As a requester I want to be able to know which validator validated certain information so other parties can judge the legitimacy. [ How to search information, Requester]
* As a requester I would like the validation process been done at the me-app so I don’t have to go to all the other parties their websites or applications. [ How to get validated, Requester ]
    * As a requester I want to be able to change my personal information so that I can adjust it if I made a mistake. [ How to search information, Requester ]
* As a requester I would like send a validation request to a validator so my information can be validated by a third party. [ How to get validated, Requester ]
* As a requester I would like to receive a notification if the requirements are not met so I can add the missing information. [ How to get validated, Users ]
* As a requester I would like to see a list of third parties that are approved to validate my information.  [ How to get validated, Requester ]
* As a requester I would like to set my own requirements for the delegates I can approve. [How to secure, Users]
* As a requester I would like to have some standard delegates (like the government) who can validate my information so I am not dependent of the settings I did on the beginning if I didn’t do it properly or correct. [How to secure, users]
* As a requester I would like to turn my tokens I received via a QR-Code to my wallet. [ How to pay, Users ]
* As a requester I would like to use the QR-code scanner so I can use certain services within the me-app.  [How to pay, Users ]

* As a requester I want to be able to acces the wallet so I can see what my properties are. [ How to search information, Users]
* As a requester I want to be able to see my assets, value and passes so I have an overview off all my properties.  [ How to search information, Users]
* As a requester I want to be able to switch between my properties so I can have a structured overview of the selection I choose. [ How to search information, Users]
* As a requester I would like a wallet where all kinds of valuta can be stored, so I am not dependent of different apps or parties. [ How to search information, Users]
* As a requester I want to be able to send and receive money, tokens and coins so I can transfer value with other people. [ How to pay, Users ]
* As a requester I would like to block ll the information connected to the me-app if I loose / break my phone. [How to secure, users]
* As a requester I would like to see an overview of all the transfers and validations that have been done over time, so I can use this for instance for my bookkeeping. [How to pay, Users ]
* As a requester I want to be able to buy and sell common valuta instantly for other values like cryptocurrencies so I don’t have to use all kinds of applications. [ How to pay, Users ]
* As a requester I want to be able to secure the Me-app comparable with a phone security so I am sure nobody will use my personal information. [How to secure, users]

**User stories Kindpakket and Me-app**

* As a requester I want to be able to request a kindpakket budget from the municipality so I can make use off kindpakket. [ how to apply, users ]
* As a requester I would like to know where I can find information about the shopkeepers who are connected to the kindpakket program so I can see where I can pay with kindpakket tokens. [ how to search information, requester] 
* As a requester I want be able to to find information about frequently asked questions so I can easily get the missing information. [ how to search information, requester]
* As a requester I want to be able to contact an organisation so I can ask my questions directly to an employee. [ how to search information, user ]
* As a requester I want to be able to find contact information so I can call or send an e-mail. [ how to search information, user ]
* As a requester I want to be able to have an overview of my kindpakket tokens so I know how much I can spend. [ how to search information, requester ]

**Comment by GerbenBosschieter** [comment]
@maxvisser You've moved this issue to done. The user stories are now discussed every sprint start and @danrminds works them out and put them in the backlog. 

This issue is still open and I can't close this issue or delete my assignment. @maxvisser can you close this issue? the same counts for issue : #2, #3, #4.
