### ISSUE TITLE
ENV: make return provider panel nijmegen url

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#401]
## Context/goal: 
The landing page in the style of nijmegen is created. If you login to the dashboard via this landing page. the link in mail opens the url set in:
PANEL_PROVIDER_URL=
https://github.com/teamforus/forus-backend/blob/16f98c22b7bee8c7fff7592e48e3100711be1573/.env.example#L54

We need a PANEL_PROVIDER_URL per implementation but for now we need a quick fix for nijmegen.
PANEL_PROVIDER_NIJMEGEN_URL=

**Comment by ateamcms** [comment]
Made commits in [backend](https://github.com/teamforus/forus-backend/pull/67/commits/799b70e3997f1e8576a669c633fcb401a5cc1a66) and [frontend](https://github.com/teamforus/forus-frontend/pull/102/commits/fef5a838ab97ef6d42f7e4e97da1af12ab674989)

**Comment by maxvisser** [comment]
I tried login on https://staging.nijmegen.forus.io/provider/#!/ via mail. 
When I click on the link in the mail I get returned to the right page but I am not logged in.

**Comment by maxvisser** [comment]
return url was set wrong
