### ISSUE TITLE
Westerkwartier webshop

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#406]
- [x] Logo
- [x] Css
- [x] splashes
- [x] change colors of icons
- [x] new footer pug
- [x] new header pug

**Comment by jamalv** [comment]
don't know about official ones, but you can see the new website here: https://probeer.westerkwartier.nl/home

**Comment by danrminds** [comment]
2 versions of design:
https://www.dropbox.com/sh/p04jm61tmw5xm7y/AADZGs8alpUnNECGB43J6fraa?dl=0 

more pages of version 2: 
https://www.dropbox.com/sh/wugwhenwr69orvu/AACHUPjm2F6OnMtd8dboV3Zka?dl=0

**Comment by maxvisser** [comment]
shop 1 is better. I would change the header photo to another photo. (colors are good)

**Comment by maxvisser** [comment]
I think the content of 2 is ok, if header and footer is changed to shop 1

**Comment by danrminds** [comment]
okay.

**Comment by danrminds** [comment]
https://www.dropbox.com/sh/fhgju4ff1137018/AACp_T4WvvilgH12m4_E9n6ya?dl=0

**Comment by danrminds** [comment]
Here are all the pages for the Westerkwartier webshop. We have to plan when we start doing the front-end implementation @maxvisser

**Comment by maxvisser** [comment]
I think we should do the landing pages aswell (design)

**Comment by maxvisser** [comment]
needs approval from @linda-90 / stakeholders

**Comment by linda-90** [comment]
@maxvisser @danrminds I have sent the designs, still waiting for approval.

**Comment by linda-90** [comment]
@maxvisser 
We have received feedback on the front-ends. Can we close this issue?

**Comment by maxvisser** [comment]
Yes
