### ISSUE TITLE
¨Forus support¨ should become just ¨support¨ or ¨hulp¨ or ¨ondersteuning¨

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#420]
![image](https://user-images.githubusercontent.com/30211022/48940964-db768a80-ef19-11e8-833c-3fd7db062b1f.png)

**Comment by maartenfv** [comment]
If you have any suggestions please add!

**Comment by GerbenBosschieter** [comment]
Vraag en antwoord

**Comment by maxvisser** [comment]
Vraag en antwoord zou ik doen. voor de 'je' haters.

**Comment by GerbenBosschieter** [comment]
Changed it to Vraag en antwoord
