### ISSUE TITLE
Landing: Footer should stick to the bottom of the page.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#421]
Now there is some white space at the bottom.

![image](https://user-images.githubusercontent.com/30211022/48941112-85eead80-ef1a-11e8-9b1a-3844dbe16825.png)

**Comment by maxvisser** [comment]
I started on this but am not such a css god as I thought.
https://github.com/teamforus/forus-frontend/tree/footer-fix

**Comment by ateamcms** [comment]
Ok, but now I can't merge this changes to develop - Valentin works on combining webshops and he asked not to make changes in webshops
