### ISSUE TITLE
Chang login modal text: explain Me-app to user

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#422]
The text in the log-in pop up should inform on where to get the me app.

![image](https://user-images.githubusercontent.com/30211022/48941178-c5b59500-ef1a-11e8-80af-006865fb529d.png)

## solution

**first screen in screenshot example:**
- change Inloggen via QR-code to Inloggen via Me

**after clicking qr-code icon**:
- change title of Qr-code to Inloggen via Me
- add link 'Wat is de Me-app?' below QR-code. / meer info??

**Comment by maxvisser** [comment]
Don't like this approach. Also Me App should be just Me in italic.

**Comment by jamalv** [comment]
Yea, this popup should be updated:

> Inloggen
> 
> Scan de QR-code met de [Me App](https://forus.io/DL) of log in met je email adres.
> 
> Log in via QR-Code | Log in via e-mail

Can be even nicer, but that's like the mvp in my eyes

**Comment by maxvisser** [comment]
This also has a more strategic decision behind it. Do we want to push Me already to citizens?

**Comment by GerbenBosschieter** [comment]
Changing the text, no problem. But how do you want to inform the user about the me-app ?
Link to the landings page? link to the popup to the sms service to instal Me ?

Pleas clarify what you exactly want ?

**Comment by maxvisser** [comment]
Lets redirect them to the landing page

**Comment by GerbenBosschieter** [comment]
I've chnaged the text on the subtitle an made a link to the me page

![Screen Shot 2019-03-19 at 09 04 32](https://user-images.githubusercontent.com/38419514/54589480-0a16f480-4a26-11e9-8117-04995cc570d8.png)
