### ISSUE TITLE
Navbar doesn't look good when logged in.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#423]
<img width="511" alt="screen shot 2018-11-23 at 15 11 12" src="https://user-images.githubusercontent.com/38419514/48947665-2f8d6900-ef32-11e8-9360-812907d22a47.png">
## Context/goal: 
Lets make it more beautiful :)

**Comment by maxvisser** [comment]
me logo should be white, more spacing between mail and my vouchers.
