### ISSUE TITLE
Connection between records repository and service

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#43]
Establish connection between docker containers of the records repository and IPFS records service

**Comment by maxvisser** [comment]
I think this issue is a duplicate of https://github.com/teamforus/forus.io/issues/43

**Comment by jamalv** [comment]
@maxvisser, this is issue #43 :)

**Comment by maxvisser** [comment]
I meant #12

**Comment by danrminds** [comment]
Yes, both issues mean at most the same thing. This is more specific though as it refers to a specific repository and specific service, skipping other parts that are stated in #12

**Comment by jamalv** [comment]
The purpose of a hello world is to show that all parts of the system work together in a very elementary form, this is just about two parts of the system. I think the hello world should be the main priority, now that we have a couple different services, and also already native apps. Closing this issue in favor of #12. We can update that issue to make it more concrete and continue the disscussion there.
