### ISSUE TITLE
User communication Glossary

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#432]
## Context/goal: 
Currently there is a lot of confusion what type of communication we should use to our users.
I have to put everything into the translation files and I notice I do a lot of the work multiple times.

It's really inefficient and hard to align all the text  if it changes every time. Besides this it also causes a lot of confusion to our users if the mobile app has different text than the dashboards, landings pages and webshops.

## Example:

- Do we use "Je" or "U"-
- Do we use: "Me App" "App Me" "Me", etc etc.

## Additional information:

For now I would like to start a glossary in Dutch, because all the users are dutch.
I assign everybody with an opinion and who knows dutch :)

The **markdown** in Github is just an example. If you want to improve it, add words or restructure the document, please do so here (don't do it Github directly, just use the google docs if it's done or if there is an update I will convert it to markdown.: 

https://docs.google.com/document/d/174EiM4NFWWAan0vo0dyi6JO_t1mBZsnVLeWCnAJKGDk/edit?usp=sharing

I've just created this so there is some place where we can store it and start do some improvements to our communication to our users.

<h2>Glossary (user)</h2>

<table>
  <tr>
   <td><strong>Word</strong>
   </td>
   <td><strong>Options</strong>
   </td>
   <td><strong>Dutch</strong>
   </td>
   <td><strong>English</strong>
   </td>
  </tr>
  <tr>
   <td>Je
   </td>
   <td>Je & jouw / u & uw
   </td>
   <td>
   </td>
   <td>you
   </td>
  </tr>
  <tr>
   <td>"Me"
   </td>
   <td>"Me App", "Me", "App Me"
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>login
   </td>
   <td>Inloggen, Aanmelden
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>profiel
   </td>
   <td>Profiel, Identiteit, account
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
</table>

**Comment by maxvisser** [comment]
Sorry Gerben. I think with such a young product: this is an ongoing proces of improving UX and therefore text.

Doing this with multiple people does not make the task simpler or more efficient.
