### ISSUE TITLE
Sponsor: access levels, fund owner can't see statistics on financial dashboard

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#438]
## Description
As this is a screenshot from production, I  removed real information:
![image](https://user-images.githubusercontent.com/10818702/49071349-11738180-f22e-11e8-960d-af8af89a2c9d.png)

total amount and total spend works

spend in this month and activated vouchers does not work. Also the line chart does not work.

Line charts and amounts per provider do work.

![image](https://user-images.githubusercontent.com/10818702/49071478-5ac3d100-f22e-11e8-9562-e4b776006e5f.png)

**Comment by danrminds** [comment]
On staging it seems to work. This is production

**Comment by maxvisser** [comment]
I need some easy way to check in  the database if the user has the right amount of rights.

If I add the owner himself as Finance it also does not work btw

**Comment by dev-rminds** [comment]
@maxvisser fixed on frontend, safe to push to production
