### ISSUE TITLE
webshop: login icons colors red

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#439]
## Context/goal: 
recolor these to red as blue stands to much out on a red colored webshop
![image](https://user-images.githubusercontent.com/10818702/49075183-9a8eb680-f236-11e8-9b91-de8dd1098b8b.png)

maybe recolor them in mutiple colors so we have some choice for other implementations

blue (assen)
red (emmen/nijmegen/amsterdam)
green (rotterdam/groningen)

**Comment by GerbenBosschieter** [comment]
showed @maxvisser we decided to go for red
