### ISSUE TITLE
Fund update: give alert to forus via mail deals@forus.io

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#442]
## Context/goal: 
When fund is created on forus, send alert to deals@forus.io that someone requested a new implementation.
- [x] add new mail notification to forus-notification service
- [x] send mail from backend on fund creation 

**mail service**
![image](https://user-images.githubusercontent.com/10818702/49185174-84314980-f361-11e8-998a-c6e3e26d9436.png)

**Comment by ateamcms** [comment]
@maxvisser  what is the reffer_id here?

**Comment by maxvisser** [comment]
tested this, did not get a mail on demo@forus.io

**Comment by maxvisser** [comment]
Now works
