### ISSUE TITLE
Fund update: send mail to citizen that his voucher is about to expire.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#455]
## Context/goal: 

- [x] 4 weeks before end date of fund send automatic mail to all users that have a voucher that has a larger sum than 0
- [x] add new mail to notification-service 
- [x] add mail to backend

@dev-rminds can you add this to the backend?
<img width="586" alt="screen shot 2018-12-19 at 18 49 34" src="https://user-images.githubusercontent.com/38419514/50238198-06d88200-03bf-11e9-84d1-cee0ea3a2a78.png">

## mail content NL

Beste gebruiker van '[FUND]',

In [START_DATE_FUND: YYYY] heeft u van [SPONSOR_ORG_NAME] een [FUND]-voucher ontvangen. Uw '[FUND_NAME]'-voucher is geldig tot en met [end_date_fund: DD/MM/YY]. Vanaf [end_date_fund: DD/MM/YY] is het budget niet meer geldig.

U kunt uw huidige budget en transacties inzien via: [URL SHOP IMPLEMENTATION]
Log vervolgens in met uw e-mailadres.
Lukt het niet om in te loggen, neem dan contact op met:

[TELEPHONENUMBER SPONSOR]
[E-MAILADRES SPONSOR]

We hopen u hiermee voldoende te hebben geïnformeerd.

Met vriendelijke groet,

 [SPONSOR_ORG_NAME] 

## mail content EN

Dear user of '[FUND_NAME]',

In [START_DATE_FUND: YYYY] you received from [SPONSOR_ORG_NAME] a '[FUND_NAME]'-voucher. Your '[FUND_NAME]'-voucher is valid until [end_date_fund: DD/MM/YY]. After [end_date_fund: DD/MM/YY] your voucher will expire.

You can see your current budget on the webshop: [URL SHOP IMPLEMENTATION]
Login with your e-mailadres.
If you can't login, please contact:

[TELEPHONENUMBER SPONSOR]
[E-MAILADRES SPONSOR]

We hope that we informed you with this message.

Sincerely,

[SPONSOR_ORG_NAME]

**Comment by jknnr** [comment]
I would write something like this, please improve and translate:

Subject: Voucher expires in 30 days!

Dear user!
Your [fond_name] voucher issued by [zuidhorn/nijmegen] will expire on [fond_expiration_date]. You will not be able to use it after this date.
Click **here** to go to your profile and see the details

**Comment by maxvisser** [comment]
Also assigned @linda-90 to this issue as we can probably use some  text from the mail  that we sent to the users from Zuidhorn.

**Comment by linda-90** [comment]
@maxvisser 

**This is the mail that we sent to the users from Zuidhorn:**

Beste gebruiker van het [FUND],

In [MONTH/YEAR] heeft u van [PROVIDER] het [FUND] ontvangen. Hiervan kunt u momenteel bij een aantal [PROVIDERS] [PRODUCTS/SERVICES] kopen. Het [FUND] is geldig tot en met [DD/MM/YY]. Mocht u nog budget beschikbaar hebben, dan heeft u nog tot [DATE] de tijd om dit budget uit te geven. Vanaf [DD/MM/YY] is het budget niet meer geldig.

U kunt uw huidige budget en transacties inzien via: [URL SHOP].
Log vervolgens in met uw e-mailadres.
Lukt het niet om in te loggen, neem dan contact op met:

[CONTACT DETAILS]

We brengen u er graag van op de hoogte dat op [DD/MM/YY] het Kindpakket opnieuw wordt uitgegeven. Mocht u recht hebben op deze regeling dan wordt u hiervan te zijner tijd op de hoogte gebracht. We hopen u hiermee voldoende te hebben geïnformeerd.

Met vriendelijke groet,

[NAME]
[POSITION]
[PROVIDER]

**Comment by maxvisser** [comment]
@gerbenbosschieter can you add this mail to the service?

**Comment by GerbenBosschieter** [comment]
yes

**Comment by maxvisser** [comment]
Add screensho of docs to issue aswell
