### ISSUE TITLE
Fund update: Mail provider when fund is closed

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#457]
## Prerequites

issue #1178 is maybe a must have as some citizens/providers will get multiple mails when multiple funds end on the same date.

## Context/goal: 
The fund will be ended on the end date, its state will be closed. We need to notify the provider that the fund has ended

- [x] mail content needs to be written.
- [ ] send mail from backend when end_date is in past

## Provider mail

subject: [fund_name] is geëindigd.
Title: [fund_name] is geëindigd.
```
Beste gebruiker,

[Fund_name] is per [end_date] niet meer geldig. Dit betekent dat er geen betalingen meer gedaan kunnen worden met QR-codes van [fund_name]. Kijk in uw dashboard of u zich voor een nieuw fonds kunt aanmelden. We hopen u hiermee voldoende te hebben geïnformeerd.

Klik [textlink: hier] of op de knop hieronder om naar de webshop te gaan.
[BUTTON: Ga naar dashboard] 
````

## Citizen mail

Title: Uw [fund_name]-voucher is verlopen

```
Beste gebruiker,
Van [sponsor_name] heeft u een budget toegekend gekregen voor [fund_name].
Uw [fund_name]-voucher is vanaf nu niet meer geldig. Mocht u vragen hebben, dan kunt u contact opnemen met [fund_contact]. We hopen u hiermee voldoende te hebben geïnformeerd.

Klik [textlink: hier] of op de knop hieronder om naar de webshop te gaan.
[BUTTON: Ga naar webshop] 
```

**Comment by jknnr** [comment]
Dear user!
The [fund_name] is no longer active due to reaching the expiration date.

**Google-translate, so check please!!!**
Beste gebruiker!
De [fund_name] is niet langer actief vanwege het bereiken van de vervaldatum.

**Comment by maxvisser** [comment]
Could you make this mail @gerbenbosschieter

**Comment by maxvisser** [comment]
@jamalv think this is maybe still a nice email to have maybe you can refine this abit.

**Comment by linda-90** [comment]
Title: Uw [fund_name]-voucher is verlopen

Beste gebruiker,
Van [sponsor_name] heeft u een budget toegekend gekregen voor [fund_name].
Uw [fund_name]-voucher is vanaf nu niet meer geldig. Mocht u nog budget hebben, dan kunt u dat vanaf nu niet meer gebruiken. Mocht u vragen hebben dan kunt u contact opnemen met [fund_contact]. We hopen u hiermee voldoende te hebben geïnformeerd.

**Comment by linda-90** [comment]
Provider
Title: [fund_name] is geëindigd

Beste gebruiker,

[Fund_name] is per [end_date] niet meer geldig. Dit betekent dat er geen betalingen meer gedaan kunnen worden met QR-codes van [fund_name]. Kijk in uw dashboard of u zich voor een nieuw fonds kunt aanmelden. We hopen u hiermee voldoende te hebben geïnformeerd.

**Comment by jamalv** [comment]
Could we add a button / link?

"Login op het dashboard"
