### ISSUE TITLE
Fund wallet smart contract

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#46]

**Comment by maxvisser** [comment]
I personally feel we should set up a plan which can deliver a smart contract can now be fully tested on a test node and can be deployed to mainnet in the coming year / two years. I personally feel that making now to much smart contracts it will be hard to make it completely secure.

**Comment by maxvisser** [comment]
@danrminds could you add clarification to your OP.

**Comment by maxvisser** [comment]
as of now we created a erc20 like contract with a rest api on top. https://github.com/teamforus/api.forus.io-eth/blob/master/truffle/contracts/KindpakketToken.sol
