### ISSUE TITLE
Activating voucher: First user experience -> popup

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#460]
## Context/goal: 
If a user now activate his voucher by using the activation code it will redirect to the voucher details page.
The feedback from the stakeholder told us to optimise this (first) experience by changing the voucher details page and product voucher pages:

- #466 hide transaction list
- #467 add modal of product voucher to normal voucher details page
- #468 add content to new modal #467
- #470 add prefix for voucher amount
- #471 expand voucher modal on voucher details
- #472 product voucher details

**Comment by maxvisser** [comment]
why does it need to be a popup? I think if we enrich the voucher details page it will help alot.

**Comment by GerbenBosschieter** [comment]
because this is what the stakeholder wants

**Comment by GerbenBosschieter** [comment]
Discussed this with @maxvisser . 

No popup needed, we gonna enrich the voucher details page.
Three things need to be covered. I will create separate issues for these. I will leave this issues open for now until the separate issues are created

**Comment by maxvisser** [comment]
you can add it here. I will help with seperation :)
