### ISSUE TITLE
Fix issues with responsiveness and leave space between sections

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#461]
When account names or mailadresses are getting too long they overlap with other sections.

See the room around Demo@forus.io. With longer adresses problem is bigger.

![image](https://user-images.githubusercontent.com/30211022/49140087-a2f8f700-f2f3-11e8-829a-2bc67466b750.png)

**Comment by maxvisser** [comment]
duplicate of https://github.com/teamforus/forus/issues/423
