### ISSUE TITLE
upload csv on different fund key does not work

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#465]
## Prerequisites
1. make 2 funds 
2. config the funds in funds_config with keys: kindpakket_2018 and meedoen
3. make two implementations connect it to fund in config
4. add a validator to fund
5. upload csv for both funds
6. first one works, second one does not.

## Description
I upload the same csv for both funds, on the second fund I can't upload it.
![image](https://user-images.githubusercontent.com/10818702/49212689-ec644780-f3c2-11e8-9e92-eca927dd6112.png)

it seems as the keys are mixed up. The record type key should be meedoen, I think. ;)
![image](https://user-images.githubusercontent.com/10818702/49212600-ab6c3300-f3c2-11e8-91c0-868bbf89e348.png)

**Comment by dev-rminds** [comment]
The new record_type should be added when the fund being configured (fund_configs). And as long as fund is being configured manually the record_type must be created manually.

**Comment by maxvisser** [comment]
Gerben has tested this and this works
