### ISSUE TITLE
Webshop update: product voucher details

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#472]
## Context/goal: 

Page title: Uw voucher

**voucher QR modal**

Status: used/unused: gebruikt/ongebruikt

Title: Fiets

Subtitle QR: Dit is uw aanbiedingsvoucher in de vorm van een QR-code

Verzilver deze voucher bij aanbieder voor:
31 december 2019

actions: share (share with provider), e-mail (to yourself), print

**provider details**
{{product_name}}
{{categorie}}

Hoe werkt het?
Deze voucher kunt u bij de aanbieder laten zien. De aanbieder kan deze code scannen om uw product of dienst te leveren.

Bekijk details van aanbieding >>

**bottom**
Heeft u vragen over deze aanbieding? Neem dan contact met ons op.
{{ provider_name }}
Telefoonnummer: {{telefoon_nummer}}
E-Mailadres: {{provider_email}}

![image](https://user-images.githubusercontent.com/10818702/49698032-bd1db980-fbbe-11e8-9ec4-68d1f9dad663.png)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/49430281-e5ff1280-f7aa-11e8-9b97-67ef17b1dfbd.png)

**Comment by danrminds** [comment]
https://www.dropbox.com/s/mlxijlbv02wfyjd/Product%20Voucher.psd?dl=0

**Comment by danrminds** [comment]
@maxvisser Check it out

**Comment by maxvisser** [comment]
I think without the hover/mouse over the icons in the right card, it will look really empty at the bottom of that card.

**Comment by maxvisser** [comment]
Also if we do a larger image in the card; we should look at using a smaller font for the title

**Comment by maxvisser** [comment]
Other solution I see is giving the first card 1/3 of the full width and right voucher card 2/3 of the width

**Comment by maxvisser** [comment]
I like adding the status. Content for this should be used/not used, or in dutch: gebruikt / ongebruikt

**Comment by maxvisser** [comment]
@danrminds could you also makea version for nijmegen (without zuidhorn branding) just a png to send them.

use this header . ![image](https://user-images.githubusercontent.com/10818702/49582861-9a896780-f956-11e8-9746-c4545fe011af.png)

**Comment by maxvisser** [comment]
@linda-90 still thinks it better to add buttons with text instead of the icons. If possible lets try that aswell

**Comment by sashooa** [comment]
https://www.dropbox.com/s/jm2nbyzkg3rcyh2/Product%20Voucher%20%28Mod%29.tif?dl=0
Nijmegen: https://www.dropbox.com/sh/4lqwcoe0zffbda9/AABzUIlqsE3oHiib3S7Dir8Ca?dl=0

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/49685640-3cd85500-fae7-11e8-80f6-c76047e427ff.png)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/49685828-3cda5400-faeb-11e8-835c-68a0253904cb.png)
added nijmegen style and some nijmegen based content.

**Comment by maxvisser** [comment]
![product voucher](https://user-images.githubusercontent.com/10818702/49685842-a4909f00-faeb-11e8-997c-6197a82b90e9.png)

**Comment by danrminds** [comment]
https://www.dropbox.com/s/rphrb0zymxm0o2t/Nijmegen.tif?dl=0
