### ISSUE TITLE
Provider application form: already have profile textual change

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#482]
Where it says "heeft u al een profiel" it could say:  
"Heeft u (zojuist) al een profiel aangemaakt in de _me app_?"

Since this functionality is mainly there to assist eager people that already signed up in the app, it might help to clarify this a bit further and make it more explicit in the title.

<img width="605" alt="screenshot 2018-12-01 at 12 49 53" src="https://user-images.githubusercontent.com/30194799/49327908-cdeb8100-f567-11e8-9267-ac6d36cff9f2.png">

**Comment by maxvisser** [comment]
Could also be that someone only filled in the form half way though.

**Comment by maxvisser** [comment]
Also its not ' de me app' but just Me

Heeft u al een profiel aangemaakt in <i>Me</i>?

**Comment by GerbenBosschieter** [comment]
it's an ongoing battle. Me app, app Me or Me. lovely. I will change the sentence :)

**Comment by maxvisser** [comment]
https://github.com/teamforus/me/issues/17 issue is also not closed yet ;)
