### ISSUE TITLE
fund update: fund details page should not show criteria

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#486]
**Is your feature request related to a problem? Please describe.**
criteria are hard coded, this is not intuitive, users might have question about this.

**Describe the solution you'd like**

<img width="1017" alt="screenshot 2018-12-03 at 21 55 48" src="https://user-images.githubusercontent.com/30194799/49401086-722b1e80-f746-11e8-99d4-4cb3be78f547.png">

remove the criteria modal for now, these criteria are not valid for each fund.

**Describe alternatives you've considered**
show the real criteria:
Recht op {{fund_name}}: Ja

**Additional context**

**Comment by jamalv** [comment]
also: clicking the title will only show validators and provider counts extra, maybe add this just to the fund modal instead and don't make the title clickable.

**Comment by maxvisser** [comment]
Made this issue on jamals account:smile:

**Comment by maxvisser** [comment]
State changes should also not happen with those play and pause buttons

**Comment by GerbenBosschieter** [comment]
I tried to hide the criterion by adding two slashes to the card. But the terminal will give me an error message. If I add slashes one line underneath it, it will hide all the criterion and the title. But the card itself will stay.

<img width="870" alt="screen shot 2018-12-04 at 14 54 29" src="https://user-images.githubusercontent.com/38419514/49446505-a2210300-f7d4-11e8-9c1a-c0d650188646.png">
