### ISSUE TITLE
Webshop update: product voucher popup adjustments

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#493]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/49595239-d4b73100-f977-11e8-853e-f4523e63797e.png)

adjustments
- [x] text highlight color to green
- [x] date to DD-MM-YYYY
- [x] add euro prefix to amount
- [x] alert icon to green.

**Comment by GerbenBosschieter** [comment]
One: 
![screen shot 2018-12-11 at 12 12 28](https://user-images.githubusercontent.com/38419514/49796970-60490d00-fd3e-11e8-95a4-57258178d16e.png)
Two:
![screen shot 2018-12-11 at 12 12 20](https://user-images.githubusercontent.com/38419514/49796984-7060ec80-fd3e-11e8-84cc-f7a17661e382.png)

**Comment by GerbenBosschieter** [comment]
So @maxvisser, I've Also tried some things with the colours u said. Personally I like the product voucher pop-up. With the dark blue/greenish buttons on the website itself is ugly in my opinion.

![screen shot 2018-12-11 at 14 33 13](https://user-images.githubusercontent.com/38419514/49804752-b5dbe480-fd53-11e8-9238-37a640c2d87b.png)
![screen shot 2018-12-11 at 14 35 27](https://user-images.githubusercontent.com/38419514/49804753-b5dbe480-fd53-11e8-9907-bf4ccc4068f4.png)
![screen shot 2018-12-11 at 14 43 41](https://user-images.githubusercontent.com/38419514/49804754-b5dbe480-fd53-11e8-8962-c571baf1cd23.png)

**Comment by maxvisser** [comment]
Option one
