### ISSUE TITLE
Set first letter of error message to uppercase

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#494]
![image](https://user-images.githubusercontent.com/10818702/49595824-29a77700-f979-11e8-9905-277be432a5c8.png)

Now error messages first letter is lowercase.

Let's make it uppercase

**Comment by ateamcms** [comment]
@maxvisser where is this errors shown?

**Comment by maxvisser** [comment]
I want it on all errors on dashboard.
these specific are for adding products when you dont fill in a expire_date
