### ISSUE TITLE
Fund update: fund should be able to be deleted in waiting state.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#498]
**Is your feature request related to a problem? Please describe.**
as you can now add but not delete funds.

**Describe the solution you'd like**
 its better to be able to delete a fund while still in waiting state.

**Comment by ateamcms** [comment]
@maxvisser where must be delete button?

**Comment by ateamcms** [comment]
I will put confirmation modal if user click delete button - maybe add some text here? https://prnt.sc/lt6dfv

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/49760390-a95c7b00-fcc4-11e8-8e03-5dba59844980.png)
