### ISSUE TITLE
Fund update: edit fund gives start date error

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#507]
![image](https://user-images.githubusercontent.com/10818702/49756339-33ebad00-fcba-11e8-97b1-ba16691c08b6.png)

when I add more categories to an existing fund while editing it, I get this error.

**Comment by ateamcms** [comment]
when you create this fund? (what is created_at value)

**Comment by ateamcms** [comment]
There is request rule for create and edit - start_date must be after 5 days from now if create or from created_at if update - it seems to me that the created_at date is incorrect or the fund was created before making these edits

**Comment by maxvisser** [comment]
allright
