### ISSUE TITLE
Clean up i18n files and improve translation variables after unification of the webshops.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#516]
## Context/goal: 
There are some texts that are not being used anymore after the unification.
I'll check the translations files and remove all the unnecessary content to make it clean again.

**Edited issue**

- [ ] Clean up unnecessary text in i18n file
- [ ] Shorten the translation variables
- [ ] Use vars for every Implementation

It's good for now to use.

**Comment by maxvisser** [comment]
Make translation files clean again! :us:

**Comment by GerbenBosschieter** [comment]
deprecated
