### ISSUE TITLE
Seperate creating identity and activating voucher

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#519]
## Context/goal: 

Userflow:
- [ ] Press activationcode button
- [ ] fill in e-mailaddress and activationcode
- [ ] User presses next
- [ ] User is created but not activated yet.
- [ ] Create mail to mail service -> url to webshop example: zuidhorn.nl/activate/{{confirm_e-mail_code}} /4545-cf0a #280
- [ ] user clicks on link and is activated
- [ ] user is logged in to webshop and will activate voucher and redirected to voucher details page.

alternative userflow:

- [ ] Press activationcode button
- [ ] fill in e-mailaddress 
- [ ] User presses next
- [ ] User is created but not activated yet.
- [ ] Create mail to mail service -> url to webshop example: zuidhorn.nl/activate/{{confirm_e-mail_code}} #280
- [ ] user clicks on link and is activated
- [ ] user is logged in to webshop, pop up 'activation code' will be opened:
user will fill in his activation code.

**Comment by maxvisser** [comment]
@danrminds @dev-rminds  which do you think is better?

**Comment by maxvisser** [comment]
@danrminds @sashooa we need a design for please confirm e-mail popup

**Comment by danrminds** [comment]
Icon to be used in the popup
[email.svg.zip](https://github.com/teamforus/forus/files/2699244/email.svg.zip)
