### ISSUE TITLE
Product edit: new lines in description 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#531]
## Context/goal: 
Currently when you add an description to a product and you add new lines it will all be merged to one line when saved.

## solution
each new line should be kept and shown on webshop with line breaks (\<br \/>)

## alternative

see @danrminds comment below

**Comment by danrminds** [comment]
<img width="830" alt="screenshot 2018-12-14 14 03 38" src="https://user-images.githubusercontent.com/33207036/50004988-144dd080-ffa9-11e8-9e72-b4b64f6bd833.png">

markdown description edit would be better than WYSIWYG.
already implemented on crm
