### ISSUE TITLE
add link to provider dashboard in e-mail after being accepted for fund.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#541]
- [ ] add field to e-mail service @maxvisser
![image](https://user-images.githubusercontent.com/10818702/50006862-67c31d00-ffaf-11e8-9b2b-058e195d4d4b.png)
add provider_dashboard_link to route
- [ ] add to forus-backend @dev-rminds

**Comment by maxvisser** [comment]
added parameter ' provider_dashboard_link ' required to provider_approved route
