### ISSUE TITLE
Webshop: Remove hardcoded text: "u kunt tot 14:55 inloggen.."

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#557]
<img width="980" alt="screenshot 2018-12-18 at 08 23 10" src="https://user-images.githubusercontent.com/30194799/50138264-52dfd580-029e-11e9-98a0-cd16b1a58142.png">

If being logged in without a voucher on the Nijmegen webshop, and you click "gebruik een activatiecode" the modal displays the hardcoded "U kunt tot 14:55 ... verloopt uw sessie" this should be removed.

<img width="1054" alt="screenshot 2018-12-18 at 08 22 20" src="https://user-images.githubusercontent.com/30194799/50138202-16ac7500-029e-11e9-89ce-42f57ac87be7.png">

**Comment by GerbenBosschieter** [comment]
Yea, Will dit his for like the 100th time
