### ISSUE TITLE
White dashboard background: a bit cleaner

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#560]
Currently the dashboard has a blue/grey-ish background. I personally think it doesn't look as clean as it could. By changing the background to white, all the contrast increases and the elements come forward just a bit more. With a white background, all the accents are more powerful. Look at the page you are on right now (GitHub) as an example. 

Since we are now used to the other background it might look weird at first, but just give it a chance 🙂

Also, it fits the clean white style of "me" a bit more as well. 

## Before:
<img width="1792" alt="Screenshot 2019-09-24 at 12 12 46" src="https://user-images.githubusercontent.com/30194799/65503176-a97cde80-dec4-11e9-8e41-ec2069e5acfc.png">

## After:
<img width="1792" alt="Screenshot 2019-09-24 at 12 12 41" src="https://user-images.githubusercontent.com/30194799/65503193-b0a3ec80-dec4-11e9-8c79-d632bd763512.png">

The box shadow I used:
`box-shadow: 0 0px 25px rgba(0,0,0,0.1)`

**Comment by maxvisser** [comment]
Don't really care about the background color. I only really got used to the light blue background. With a few more additions we could easily change css for each implementation (for dashboard aswell). So we could even make them in the brand identity of the municipality.

**Comment by maxvisser** [comment]
will discuss this in sprint review friday

**Comment by maxvisser** [comment]
I think this can be fixed by merging our template with crm template of rminds.

**Comment by jamalv** [comment]
Agree with comment above
