### ISSUE TITLE
Mobile: my vouchers page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#565]
## Context/goal: 
Lets try to make Vouchers page look more identical to Me experience in native apps (as close as possible)

**Comment by danrminds** [comment]
![screenshot 2018-12-20 08 48 26](https://user-images.githubusercontent.com/33207036/50271113-0d551100-0434-11e9-96d1-3041edc853d5.png)

**Comment by maxvisser** [comment]
@danrminds mobile is the problem (not desktop)
![image](https://user-images.githubusercontent.com/10818702/50271526-480b7900-0435-11e9-9455-4af6223f21fc.png)

**Comment by danrminds** [comment]
ohh yeah )

**Comment by maxvisser** [comment]
Show it more like in Me, smaller cards etc. ![image](https://user-images.githubusercontent.com/10818702/50271604-7be69e80-0435-11e9-9727-a6853815e308.png)
