### ISSUE TITLE
extra activation button intro text webshop

### ISSUE THREAD

**Issue by linda-90** [teamforus/forus#569]
## Context/goal: 
gerben could you change this button to 'Start' and make it upon the activate activation code modal ?

Linda wants to add the How the system works link to some \<a\> in the text above the button

Welkom op de website van de Meedoen-regeling. In Nijmegen krijgt iedereen de kans om mee te doen. Heeft u vragen over werking van het systeem? U vindt uitleg \<a\>hieronder.\</a\>

**Comment by danrminds** [comment]
Did not really understand where, what )

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/50270713-d6323000-0432-11e9-9bce-6e1679a2179d.png)

**Comment by danrminds** [comment]
Now is better ) 
Don't see my relevance here I think. Will unassign myself.

**Comment by maxvisser** [comment]
I think this should be done together with https://github.com/teamforus/forus/issues/595
