### ISSUE TITLE
Provider map: make providers searchable

### ISSUE THREAD

**Issue by linda-90** [teamforus/forus#572]
**Is your feature request related to a problem? Please describe.**
As a funds can have over 150 providers connected the map now shows all providers on a list. If you want to look for a specific provider or brand, its a hard task.

**Describe the solution you'd like**
Add a search bar where you can search for the provider you are looking up the address for.

**Comment by maxvisser** [comment]
@danrminds does this need a design?

**Comment by maxvisser** [comment]
done
