### ISSUE TITLE
products: filter on price

### ISSUE THREAD

**Issue by linda-90** [teamforus/forus#574]
**Is your feature request related to a problem? Please describe.**
With each implementation the list of products will become bigger and bigger. We should add some filters to allow people to search for the cheapest deal.

**Describe the solution you'd like**
Make a filter to select 
Lowest price to highest price,
Highest price to lowest price.
Newest
Oldest

![image](https://user-images.githubusercontent.com/10818702/50245880-f8489580-03d3-11e9-83cd-eb454463cc8d.png)

### text NL
Sorteer:
Prijs (laag naar hoog)
Prijs (hoog naar laag)
Verkrijgbaar sinds (nieuw - oud)
Verkrijgbaar sinds (oud - nieuw)

**Describe alternatives you've considered**
price ranges
0-50, 50-150

**Comment by maxvisser** [comment]
I don't think this really needs design as there is room next to search...

**Comment by danrminds** [comment]
I would put Alex to design the dropdown so it does not differ much from the style. It is a small job

**Comment by maxvisser** [comment]
ok

**Comment by maxvisser** [comment]
will make new issues when map is approved
