### ISSUE TITLE
My vouchers: make budget voucher and product voucher seperate lists

### ISSUE THREAD

**Issue by linda-90** [teamforus/forus#577]
## Context/goal: 
Currently we show product vouchers and normal voucher in the same list on my voucher screen. As these are different vouchers we should show them in a different list from each other.

## alternative
show a small identation or other effect which shows where the product voucher was generated from. Or let the user collapse and uncollapse the parent.

## Proposal

![image](https://user-images.githubusercontent.com/10818702/70429032-16415700-1a78-11ea-9f32-3f3e88a1d63e.png)

**Comment by danrminds** [comment]
@maxvisser Let's discuss on how different and which way to show it. Will need design if not the alternative option

**Comment by danrminds** [comment]
Also - can put Used vouchers / Closed vouchers also in a separate list

**Comment by jamalv** [comment]
## Full page example

![image](https://user-images.githubusercontent.com/30194799/70603891-d4d7b580-1bf7-11ea-9f4c-e676b6ad2af6.png)

**Comment by jamalv** [comment]
## Text (for copy-pasting): 

### Budget vouchers
Met deze budget vouchers kan u naar de aangesloten aanbieders. Open de voucher om te zien bij welke aanbieders u het budget op de voucher kan uitgeven.

### Product vouchers
Verzilver de product voucher bij de bijbehorende aanbieder. Open de voucher om te zien bij welke aanbieder u de voucher kan verzilveren.

### Verlopen vouchers
Deze vouchers zijn verlopen en kunnen niet meer gebruikt worden. Open de voucher om meer details in te zien.
