### ISSUE TITLE
As a sponsor I want to define the criterias for receiving my fund

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#58]

**Comment by maxvisser** [comment]
Key | Expected Type | Criteria | Expected value
-- | -- | -- | --
address | PostalAddress or Text | postal codes within a certain municipality | 9712RG, 45, A
birthDate | Date | older than 21 | 2015-01-30
children | Person | children are younger than 18 (not equal to 18) and live on same address as parent | 0xDc0a52E14953551f4a7Ed379a516B4F2699Ee312, 0x4353452E1495FSDFA516B4F2699Ee312
email | Text | REGEX is valid mail address | john@doe.com
primaryEmail | Text | REGEX is valid mail address | john@doe.com PK
familyName | Text |   | Doe
gender | GenderType or Text |   | Male, Female, Neutral
givenName | Text |   | John
netWorth | MonetaryAmount or PriceSpecification | < 12.040 | 12000
parent | Person |   | 0xDc0a52E14953551f4a7Ed379a516B4F2699Ee312, 0x4353452E1495FSDFA516B4F2699Ee312
spouse | Person | is condition for baseSalery barrier | 0xDc0a52E14953551f4a7Ed379a516B4F2699Ee312
taxID | Text | should be unique | 29450561
telephone | Text |   | 6245412102
baseSalary | MonetaryAmount or Number or PriceSpecification | <1.615 (if spouse) <1.131,65 (if no spouse) | 1200

**Comment by martijndoornik** [comment]
Copy-pasta from #75, in regards of the primaryEmail situation:

I suggest using Schema.org's "identifier" from the Think implementation (https://schema.org/Person, about a third down) and implementing it as an email, and thus treat it as one.
