### ISSUE TITLE
Epic: Fund criteria and prevalidations

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#590]
## Context/goal: 
Currently are system works like this:

You create a fund.
Forus setups a fund_config (key, bunq key, amount, multiplier) and implementation urls
create record_type (key_eligible), when configured fund_criteria is generated:
key_eligible = Ja
children_nth >= 1

You can now assign a validator that can validate bsn numbers and children amounts (create activation codes / prevalidations)

What I want:
Forus setup a fund_config, implementation urls, creates record_types and create fund_criteria.

- When I create a record type I want to specify if it must be unique (if so a validator can not upload a prevalidation for the same record again, if activated to a me identity)

- When I create a fund_criteria for a newly generated record type. I want the csv uploader to pick this up and show this in a column of the csv uploader. If I add:
kindpakket_customer_number as a record type
and set a fund_criteria to kindpakket_customer_numer != empty
it should display kindpakket_customer_number in

**Comment by maxvisser** [comment]
close this for now until I have specified it more
