### ISSUE TITLE
To check: I made a transaction but the confirmation mail does not show my new balance.

### ISSUE THREAD

**Issue by admin-forus** [teamforus/forus#618]
As can be seen in the image below the amount stays 50,-. 

50,- was the initial amount.

I made a Kerstpakket  transaction of 15,- on 21 dec. 2018 19:46

![image](https://user-images.githubusercontent.com/37617551/50476373-32afc500-09c8-11e9-9f72-93d30396ad86.png)

**Comment by maxvisser** [comment]
@dev-rminds could you check if amount is correct, when you work on stock amount
