### ISSUE TITLE
research: Why we get popup message 'Suspicious link'

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#619]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/50489849-53007380-0a0a-11e9-85f9-eb13d806ecca.png)

**Comment by jknnr** [comment]
on it

**Comment by jknnr** [comment]
@maxvisser we should try to send the email from the domain @forus.link and check what will happen. Can you help?

**Comment by jamalv** [comment]
@maxvisser we got this in our admin inbox, does it have anything to do with it?

<img width="1308" alt="screenshot 2019-01-09 at 16 09 49" src="https://user-images.githubusercontent.com/30194799/50907982-0022b500-1429-11e9-8ca0-be66dbc19922.png">

**Comment by maxvisser** [comment]
I fixed that today @jamal also saw it..

**Comment by maxvisser** [comment]
I will check if it is because of .link domain

**Comment by GerbenBosschieter** [comment]
https://www.tinywebhut.com/suspicious-link-message-in-gmail-50
