### ISSUE TITLE
Modal popup styling: center align text

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#625]
It is currently not centered but slightly to the left.

<img width="1240" alt="screenshot 2018-12-31 at 11 58 54" src="https://user-images.githubusercontent.com/30194799/50559067-89ccd700-0cf3-11e9-9ed0-3df1f795640a.png">

**Comment by GerbenBosschieter** [comment]
I hid the footer-text. The activation flow is changed. If you enter an e-mailadres thats allready been used u will get an login link. So no need to inform the user. We already enforce them to log in.
