### ISSUE TITLE
Does our contact form work?

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#627]
I received the following mail:

Geachte heer/mevrouw,

Omdat jullie contactformulier niet lijkt te werken even via de mail: xxxx voert verschillende stadspassen in Nederland uit. Wij zouden graag eens met jullie kennis maken om te kijken wat we voor elkaar kunnen betekenen.

Can you guys check if the form is working?

**Comment by maxvisser** [comment]
Does not seem to work (on mobile). I will check this out soon. We already had somewhat the same problem a few months back. 

Also this issue is part of foundation website.

**Comment by jamalv** [comment]
Can confirm it does not work:

<img width="1680" alt="screenshot 2019-01-04 at 12 51 27" src="https://user-images.githubusercontent.com/30194799/50686910-7c7b5980-101f-11e9-826c-7c94ed9f829e.png">

**Comment by jamalv** [comment]
superseded by: https://github.com/teamforus/foundation.forus.io/issues/103
