### ISSUE TITLE
Share product: add option to also mail to your self share product

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#660]
## Problem
User wants to see what is shared to provider aswell

## solution

Add a check mark box below textarea with label: 'Send e-mail as proof to yourself aswell'
NL: 'Stuur e-mail als bewijs ook naar uzelf'

**Comment by ateamcms** [comment]
@maxvisser so we use api for share voucher (vouchers/share_product) but reffer_id now is user id (not organisation id as in existing functionality) or how we must send mail to user?
