### ISSUE TITLE
What to do with payment reference and payment description

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#669]
**Is your feature request related to a problem? Please describe.**

In the current situation the provider can add a description to the payment.
This description will only show up on the provider dashboard.

Besides the the payment description we also have a payment reference thats added to the bank account payment. This is the name of the fund

**Problem**
I've already had contact with some providers that would like to add the payment reference themselves instead of a default reference. 
But I also had contact with a provider that didn't want this , cause it interferes with their own administration.

**Describe the solution you'd like**
I would like a solution that meets the requirements of both situations described above.

**Describe alternatives you've considered**
Let the provider choose if they want to add their description the the payment reference.So make it optional. (like a checkmark what we currently have for displaying information on the webshop)

**Additional context**
I hope its clear. I am looking for more thinking power for this "problem". What do you guys think?

**Comment by maxvisser** [comment]
I want to make an epic out of this. As I see it this problem will be fixed with wallet functionality for organisations or identities.

**Comment by jamalv** [comment]
I think this has been fixed in: https://github.com/teamforus/forus-backend/pull/206
