### ISSUE TITLE
move roles & permissions to config file

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#676]
## Context/goal: 
as some routes depend heavily on permissions and roles, it takes abit longer to proces, moving these out of the database can make a performance improvement.

## Why performance improvement:
each time page loads; we do an extra call to database to get roles and permissions; this is static data and configuration does not change alot. Therefor you can take some time of each request to put this in PHP config instead of a database table.

**Comment by dev-rminds** [comment]
not relevant
