### ISSUE TITLE
statistics provider dashboard transactions

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#694]
## Description
Currently there is no way to see the profit you made totally on a fund without calculating it yourself. This is basic math sum(transactions amount sold)

## task
- [ ] decide calculate on frontend or backend
- [ ] show amount of total sold in block on transaction page.

**Comment by jamalv** [comment]
if it will not take too long, maybe do it on frontend? an mvp of this on the transactions page would be very useful

**Comment by maxvisser** [comment]
show statistics block below transaction block; count all transactions of selection and do a sum of amount
