### ISSUE TITLE
API endpoints

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#7]
Design API endpoints that implement the functionality as described in https://github.com/teamforus/concept-platform/issues/2, https://github.com/teamforus/concept-platform/issues/3, https://github.com/teamforus/concept-platform/issues/4 and  https://github.com/teamforus/concept-platform/issues/5

The api will be used as the main way to connect to the platform while it is not yet practical for frontends and applications to connect directly to a fully decentralised backend (see https://github.com/teamforus/concept-platform/issues/6 for details). 

The documentation: https://github.com/teamforus/forus.io/blob/dev/docs/api.forus.io.md

**Comment by jamalv** [comment]
https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

**Comment by maxvisser** [comment]
I think this is what @martijndoornik is working on? Or what do you want with this issue?

This needs more specification or smaller issues.

**Comment by jamalv** [comment]
This is about thinking about the endpoints of the API and to make sure they are structured in a way that is clear, understandable and as future-proof as we can make it for now. The first version that Valentin made is here: https://github.com/teamforus/forus.io/blob/dev/docs/api.forus.io.v1.md I also wrote down some thoughts here: https://github.com/teamforus/forus.io/blob/dev/docs/api.forus.io.md 

Please mind that api.forus.io is for the parts of the system we want to decentralise using IPFS and Ethereum, and that services.forus.io (maybe we should create another issue for that) is for the centralised parts.

**Comment by jamalv** [comment]
Work on this moved to documentation/development, iterative process.
