### ISSUE TITLE
Allow people to use "www" when visiting our environments.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#703]
## Context/goal: 
People cannot enter the websites if they use the **"www"** format instead of nothing or **https://.**

**How to reproduce:**
- Go to www.nijmegen.forus.io or www.zuidhorn.forus.io ->**error message**
- Go to nijmegen.forus.io or zuidhorn.forus.io -> **works**
- Go to https://zuidhorn.forus.io or https://zuidhorn.forus.io -> **works**

**Comment by maxvisser** [comment]
done

**Comment by maxvisser** [comment]
could you create these next time in teamforus/server?

**Comment by GerbenBosschieter** [comment]
@maxvisser Sorry, I will
