### ISSUE TITLE
What happens when the municipality does not any funds and transactions are made?

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#711]
Will they reach 0,-?
Can they go into debt?
Can they see their debt?
Will they be notified?

I think we should turn the amount red and show how much they owe. They also need to receive an email.

**Comment by maxvisser** [comment]
a fund does not have a balance. 
It has an amount that was initially added 60k
each transaction will be counted up and show as used budget

you can have 0 euros added to a fund
100 euro used

theere is no debt and currently they will not be notified.

if there is no fund on the budget the transaction will stay in a pending state.
