### ISSUE TITLE
IE + EDGE: Voucher card css problems

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#713]
## Prerequisites

1. IE + EDGE browser
2. Profile with a voucher

## Description
Voucher card gets cut off. see image

## Additional Information (optional)
![unnamed](https://user-images.githubusercontent.com/38419514/51325348-076f4180-1a6d-11e9-926b-4b633b331e59.png)

**Comment by maxvisser** [comment]
this is fixed
