### ISSUE TITLE
Uw tegoed is te laag

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#717]
I have not logged in but my tegoed (budget) is not sufficient. (as seen in image below). Should add ¨or you are not logged in¨/¨of u bent nog niet ingelogged¨
![image](https://user-images.githubusercontent.com/30211022/51461800-5ebc2d00-1d5f-11e9-88a8-ef94ee5ab03f.png)

**Comment by GerbenBosschieter** [comment]
How about this?

- Uw tegoed is te laag is not shown if people are not logged in
- Change the button to "Log in om te kopen"

You already made this issue: Log in om te kopen #720 . So telling the users two times they should log in is overkill in my opinion

**Comment by maxvisser** [comment]
superseded by tooltip #725
