### ISSUE TITLE
Make me-app clickable

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#718]
When you reach the site for the first time, you will have no idea what the me-app is. in the pop-up (image below) the ¨me-app¨ should be clickable and it should lead to the FAQ where it explains what the app does and how you can download it.

![image](https://user-images.githubusercontent.com/30211022/51461950-ac389a00-1d5f-11e9-9a84-7ee8f07f1e35.png)

**Comment by GerbenBosschieter** [comment]
Do you want the word Me-app the be clickable everywhere on the webshop ?

**Comment by maxvisser** [comment]
This needs a Me-app explanation page firs, as we only have this currently in the webshop. I would wait with this.

**Comment by maartenfv** [comment]
I think we can add a text to the FAQ with basic info as a quick fix. (What is de Me-app en hoe gebruik ik het?) Later we can add a separate page. @GerbenBosschieter @maxvisser

**Comment by maartenfv** [comment]
Me app can be clickable everywhere where it makes sense. We need to help people understand its use as it is not self-explanatory.

**Comment by GerbenBosschieter** [comment]
What does "everywhere where it makes sense" exactly mean? Where does it exactly make sense in your opinion ? @maartenfv

**Comment by maartenfv** [comment]
@GerbenBosschieter in relation to logging in makes sense for example.
