### ISSUE TITLE
Heeft u nog geen account?

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#719]
In case users are not logged in or do not have an account they will need to be explained what to do next.
In the pop-up (image below) text should be added (click here if you do not have an account) leading to the faq where we explain what to do if you do not have an account.

![image](https://user-images.githubusercontent.com/30211022/51462110-10f3f480-1d60-11e9-9058-8caa3a509ca6.png)

**Comment by GerbenBosschieter** [comment]
So below the option to log in you want to add a sentence: click here if you don't have an account, the users clicks and what happens than ? Should the modal close and scroll to the FAQ about the activation ?

**Comment by maxvisser** [comment]
I would add the footer (of the modal) to this modal. (where we had the time)
add text/link
"Heeft geen account en wilt u één aanmaken door een activatiecode te gebruiken?"

Clicking this link will change the modal to the first step of the activation proces

**Comment by maxvisser** [comment]
Inloggen via Me

**Comment by maxvisser** [comment]
Oh really? I will look into this issue

**Comment by maxvisser** [comment]
Don't really had time to figure this one out.
