### ISSUE TITLE
Add hover change of mouse indicator

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#721]
![image](https://user-images.githubusercontent.com/30211022/51462509-14d44680-1d61-11e9-976d-0add1cec7427.png)

When hovering ¨start¨ the mouse should change from arrow to the clickable hand indicator.

**Comment by maxvisser** [comment]
@gerben I added this link as an div ng-click maybe change it to a <a ng-click> instead

**Comment by GerbenBosschieter** [comment]
Could just keep it this way. Was a small css solution
