### ISSUE TITLE
Add links when mentioning Me and download options

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#723]
![image](https://user-images.githubusercontent.com/30211022/51462794-d428fd00-1d61-11e9-9abd-51f258abeacc.png)

As in the image above links need to be added in the text.

**Comment by maxvisser** [comment]
I like these additions but the user flow of sending people to play store / app store is horrible as they can't really download the app on desktop

**Comment by GerbenBosschieter** [comment]
I think maarten means a link to the me-landingspage.
But don't you guys think its a little bit to much to make every reference to the me app clickable .

**Comment by jamalv** [comment]
Yea, I think to a landing page. There we could explain (/show) how the user will be able to download the me app once they have a voucher (using the sms function). That's probably the best ux / way to create awareness.

Maybe not every link has to be clickable, but in every location where the user might see the term "me-app" for the first time it would be good.

**Comment by jamalv** [comment]
@maartenfv duplicate of https://github.com/teamforus/forus/issues/718 ?

**Comment by maartenfv** [comment]
@jamalv The conclusion makes it a duplicate. I like linking to a information page on Me when the concept is first mentioned.
