### ISSUE TITLE
Update faq

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#724]
![image](https://user-images.githubusercontent.com/30211022/51463315-32a2ab00-1d63-11e9-90ce-f6db676234df.png)

Some of the texts are outdated

**Comment by linda-90** [comment]
@GerbenBosschieter Hadden we deze tekst nog niet aangepast?

New text:
Stap 1: Klik op de _start_ knop om uw activatiecode in te vullen. Stap 2: Vul uw e-mailadres. U ontvangt een bevestigingsmail. Bevestiging dat u toegang heeft tot dit e-mailadres door op de knop in de mail te klikken. Stap 3: Vul uw activatiecode in om de Meedoen-regeling te activeren en klik vervolgens op 'Volgende'. Uw profiel is aangemaakt en uw Meedoen-regeling is geactiveerd.

**Comment by GerbenBosschieter** [comment]
I know it's not correct, as I understand of the feedback we got we where asked not to change it. But I will just change it's.

Just like this one:
<img width="789" alt="screen shot 2019-01-21 at 10 36 04" src="https://user-images.githubusercontent.com/38419514/51465590-7c41c480-1d68-11e9-810b-c5dad519d228.png">
And this one:
<img width="448" alt="screen shot 2019-01-21 at 10 36 23" src="https://user-images.githubusercontent.com/38419514/51465604-84016900-1d68-11e9-9ebe-cef8442cc000.png">
