### ISSUE TITLE
Add tooltip directive to webshop

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#725]
## Context/goal: 
I've added a little warning message into the product.pug

<img width="689" alt="screen shot 2019-01-21 at 13 07 04" src="https://user-images.githubusercontent.com/38419514/51473743-828e6b80-1d7d-11e9-8bbe-f87912134623.png">

I want to have a tooltip added to the **.product-price-insufficient** part so I can give the user some content.

**Comment by maxvisser** [comment]
I requested changed to your pr until this is fixed
