### ISSUE TITLE
Financial dashboard: card needs text changes

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#726]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/51482948-0c4b3280-1d98-11e9-97de-cc1eb02c2bf4.png)

Title: Huidige saldo

Saldo: €193,-

add spacing

Label: Startbudget
initially added budget: € 200,-

**Comment by GerbenBosschieter** [comment]
It's not completely clear for me. Do you mean like this:
<img width="233" alt="screen shot 2019-01-22 at 17 03 03" src="https://user-images.githubusercontent.com/38419514/51547994-a4641d00-1e67-11e9-9063-101766b14ee0.png">

**Comment by maxvisser** [comment]
Yes
