### ISSUE TITLE
enable rejection mail again and change content mail

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#732]
## Context/goal: 

Beste [PROVIDER],

Onlangs heeft u zich aangemeld voor [FUND].
[SPONSOR] heeft uw aanmelding beoordeeld en heeft besloten dat u voor [FUND] bent afgewezen.
Mocht u hierover meer willen weten, dan kunt u contact opnemen met [SPONSOR].

[SPONSOR CONTACT DETAILS]

We hopen u hiermee voldoende te hebben geïnformeerd.

Vriendelijke groet,
Team [FUND]

**Comment by GerbenBosschieter** [comment]
@eran does the backend part.
I will do the mail
