### ISSUE TITLE
Fedra Sans - Paid font for Westerkwartier

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#750]
## Context/goal: 
On the new website of Westerkwartier they use the font Fedra Sans. We used it also in design, but we either need access to their license or Forus should purchase a license as well. Or switch to another font.

For now we gonna use only Lato (the second font of their website) until decided otherwise.

**Comment by maxvisser** [comment]
Let's use Lato for now.

maybe @linda-90 can ask about this when projectgroup is established.

**Comment by linda-90** [comment]
Waiting for response :)

**Comment by linda-90** [comment]
**Fonts**
Response Westerkwartier:
We can use the following Google fonts instead of the fonts with a license.

Fedra (licentie)
Ubuntu (google font)

Corbel
Cantarell (google font)
