### ISSUE TITLE
Top up modal: add more details

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#768]
I was working on a screen capture of the platform for the new website and noticed something about top up: when you send funds somewhere, you need to fill the recipient as well. I looked at the info Coinbase provides, and it's quite a bit more than we currently do, let's look into this.

## Forus
<img width="1026" alt="screenshot 2019-02-11 at 14 06 09" src="https://user-images.githubusercontent.com/30194799/52565146-4abb9680-2e06-11e9-83b9-07b59ba1654a.png">

## Coinbase
<img width="510" alt="screenshot 2019-02-11 at 14 01 25" src="https://user-images.githubusercontent.com/30194799/52565156-527b3b00-2e06-11e9-902f-4eb460a0149e.png">

**Comment by jamalv** [comment]
Striped out some info we don't need:
<img width="510" alt="screenshot 2019-02-11 at 14 01 25" src="https://user-images.githubusercontent.com/30194799/52565254-a0903e80-2e06-11e9-9b20-fe48b88ebd17.png">

**Comment by GerbenBosschieter** [comment]
And what's the purpose of asking this information ?

**Comment by maxvisser** [comment]
No not asking but giving

**Comment by jamalv** [comment]
Yea, you give the info to the sponsor, in case they need to fill these details to perform the top up.

**Comment by TomForus** [comment]
Closed due to inactivity
