### ISSUE TITLE
if on validator dashboard, validator can upload csv without fund_id / _eligble key

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#771]
## Context/goal: 
This task is about researching the posibility to prevalidate records without it being directly used for a fund. This will help make the platform more generic.

**Comment by jamalv** [comment]
@maxvisser how urgent is this issue still for project-37?

**Comment by maxvisser** [comment]
if you want to prevalidate without _eligible keys or fund_id you currently can't; for project-37 its not really needed but maybe for project-60 (multiple funds one activation code)
