### ISSUE TITLE
Add € before all input fields where a price is asked

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#773]
**Is your feature request related to a problem? Please describe.**
Current field does not have localization:
![image](https://user-images.githubusercontent.com/10818702/52957609-596bf580-3392-11e9-80d4-75887a0ad35b.png)
https://stackoverflow.com/questions/2913236/html-text-input-field-with-currency-symbol

**Describe the solution you'd like**
- [x] Add euro symbol before input field
- [ ] Add filter to show a dot on the right location example 10000 should be 10.000

**Gerben**
- [x] Add euro symbol to input field (provider / add offers)

**Comment by GerbenBosschieter** [comment]
Closed this issue. Added the € signs to the translation files.
Created issue #781 for the issue with the dot
