### ISSUE TITLE
You can't edit fund because start date error

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#785]
## Context/goal: 
If you edit a fund after start date you get an error because a validation says that the start date is in the past.

For example:
user want to set a new image for a fund
uploads image
presses submit
-> get an error that the start date cant be in the past.

**Comment by GerbenBosschieter** [comment]
Isn't more logic to make only certain things changeable (like the image, adding categories). Cause changing the date or the name of the fund is a but strange to me.
