### ISSUE TITLE
Validation requests - primary key of fund instead of BSN

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#792]
## Context/goal: 
*explain why this issue was opened*

**Comment by maxvisser** [comment]
there is no link between validation and fund

**Comment by jamalv** [comment]
@maxvisser, is this relevant for this sprint?

**Comment by maxvisser** [comment]
yes this needs to be discussed; if we have funds that are not municipalites; Currently BSN or UID is necessary
