### ISSUE TITLE
Can't add picture to product on Mozzila Firefox

### ISSUE THREAD

**Issue by NelisVanWijk** [teamforus/forus#820]
Can't add a picture as a provider to a new product in Firefox on the demo platform. Also tested it on Microsoft Edge which works fine. 

edit from @emachiels :
Looks like the Javascript works differently in Firefox, making the to be uploaded image too big. The API indicates that the image is too big. 
Max upload filesize in the API is 2MB, Firefox makes the image 2.7MB, Chromium 1.8MB when using an image with the size of 5,87MB.
## Task:

- [ ] There should be some feedback for the user indicating the image blob is too big.

**Comment by maxvisser** [comment]
@GerbenBosschieter if you have time could you try and reproduce this issue?

**Comment by GerbenBosschieter** [comment]
@NelisVanWijk I've tried to reproduce this. But it it works fine with my mozilla.
When does this happen exactly? After the moment you clicked  confirm ? or when you open the image cropper ?

Can you maybe check in the console what happends if you upload an image? What I do see is that uploading an image can take a while and if you do something else in between it wil cancel the image uploading.

**Comment by NelisVanWijk** [comment]
![afbeelding](https://user-images.githubusercontent.com/25053173/54342059-c8f49e00-463b-11e9-9433-d7e7738665d7.png)

**Comment by NelisVanWijk** [comment]
![afbeelding](https://user-images.githubusercontent.com/25053173/54342077-d6118d00-463b-11e9-99e3-f08c3c63f24d.png)

**Comment by NelisVanWijk** [comment]
These are the errors i'm getting while uploading some pictures, while other pictures work fine

**Comment by danrminds** [comment]
Can you share some files that do not work?

**Comment by NelisVanWijk** [comment]
![photo-1524594152303-9fd13543fe6e](https://user-images.githubusercontent.com/25053173/54342743-8d5ad380-463d-11e9-894a-470787219241.jpg)

**Comment by NelisVanWijk** [comment]
![academy-of-music-727074_1920](https://user-images.githubusercontent.com/25053173/54342999-0f4afc80-463e-11e9-8502-5a5383f4353e.jpg)

**Comment by emachiels** [comment]
Looks like the Javascript works differently in Firefox, making the to be uploaded image too big. The API indicates that the image is too big. 
Max upload filesize in the API is 2MB, Firefox makes the image 2.7MB, Chromium 1.8MB when using an image with the size of 5,87MB.

There should be some feedback for the user indicating the image blob is too big.
