### ISSUE TITLE
Optimize voucher list route

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#821]
## Context/goal: 
In Me app we currently only show fund image, voucher name, price and status.

We can optimize the voucher list route on api more by excluding certain data from the GET route.

**Comment by emachiels** [comment]
We probably can't at the moment. The voucher list and specific vouchers use the same resource, meaning that the data returned is the same for both the list and the specific voucher view. The whole structure of retrieving vouchers should then be rewritten to make a distinction between all or just one voucher, as far as I can see.

**Comment by maxvisser** [comment]
Will rewrite this issue later
