### ISSUE TITLE
Sign-up flow: moving step 5 and 6 before creating organisation

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#824]
## Context/goal: 
*explain why this issue was opened*

**Comment by jamalv** [comment]
From brainstorm:
![54699692-cb6e6080-4b31-11e9-9e05-1a47f07236a4](https://user-images.githubusercontent.com/30194799/54699923-3ddf4080-4b32-11e9-8da8-6ba9265aa576.jpg)
