### ISSUE TITLE
Enhance transaction history if product is bought.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#829]
# Description

If someone "buys" a product, the transaction history is being added to the voucher where it's bought from. The budget voucher.

After the product voucher itself being used the user is not provided with any information about the transaction itself. This is inconvenient for the user if there is a problem between the user and the provider. The user can't "prove" what day and time the transaction is done. And also for me as support guy it makes it more difficult if there is no @maxvisser to check the database for this information.

# Proposal

Add the date and time to the product voucher card in the same place as the expiration date and the creation date . I would like to do it myself but I have no clue what variable i should use on the front end to get this information.

![Screen Shot 2019-03-28 at 10 26 42](https://user-images.githubusercontent.com/38419514/55146023-20b6fd00-5144-11e9-8366-8da0e8b96b49.png)

**Comment by GerbenBosschieter** [comment]
@maxvisser can you tell me what variable I should use to add this to the frontend ?

**Comment by maxvisser** [comment]
Good issue. We removed the transaction overview on the product voucher. your probably can still get this variable but its an array
