### ISSUE TITLE
Webshop should have text to speech

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#839]
## Description

Depends on licensing, this issue needs abit of research on how to implement.

## Additional information
tool:
https://www.readspeaker.com/nl/

**Comment by GerbenBosschieter** [comment]
Is this something we should implement into the webshops ? This is normally done by text to speech tools / plugins and not within the website itself.

**Comment by maxvisser** [comment]
needs abit of research of what someone uses with hearing aids.
