### ISSUE TITLE
Pincode usage [to discuss]

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#84]
Process pincode only locally on clientside or not [to discuss]

**Comment by maxvisser** [comment]
pincodes are stored locally as a fall-back when face-id or fingerprint doesnt work.

**Comment by maxvisser** [comment]
the only reason to store the pincode in backend would be to use it when buying a voucher / sending a validation request. Option would be to have QR-code in screen to let people 'sign' these actions with their me app.
