### ISSUE TITLE
Oracle validation in name of Forus

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#85]
Oracle on the Forus infrastructure. It will validate records in the name of Forus (with the public key of Forus, in name of KVK, BUNQ, DigiD)

**Comment by maxvisser** [comment]
How does Valentin thinks he can do this? I would do this after we investigated IRMA attributes

**Comment by danrminds** [comment]
This still has to be discussed. It is partly related to the issue: #90 and #91

**Comment by maxvisser** [comment]
As I see it, this currently has no priority as we first need to restructure backend to this to happen.

**Comment by jamalv** [comment]
I think in a similar way jasper implemented his DigiD oracle. Indeed, can be done after backend restructuring.
