### ISSUE TITLE
Webshop: Organization profile page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#850]
## Description

- [ ] shows contact details if public
- [ ] shows all offices
- [ ] shows all products

**Comment by maxvisser** [comment]
![Organization description](https://user-images.githubusercontent.com/10818702/55546337-5cffd580-56cf-11e9-9595-4a5fe88f53ea.png)

**Comment by NelisVanWijk** [comment]
Maybe you can add a link to all the products the organization is offering or just have a small list of products underneath the information

**Comment by jamalv** [comment]
released this morning :D
