### ISSUE TITLE
User method of contact with provider/sponsor

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#853]
## Description

- Gewenste contactvorm met de gemeente 
 - Gewenste contactvorm met de leverancier
 - Gewenste contactvorm vanuit de webshop (meldingen etc.)
 - Zijn interessegebieden 
 - Hoe vaak de klant een update wil krijgen van wijzigingen in de webshop die voor hem relevant zijn ten aanzien van het productaanbod.

**Comment by jamalv** [comment]
@maxvisser Can this issue be closed?
