### ISSUE TITLE
add help site to menu of dashboard and make it generic

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#854]
## Description

If help.forus.io is ready; lets add it to dashboards.

**Comment by maartenfv** [comment]
Relevant for Kerstpakket as well. This Issue needs a look regarding its priority.

**Comment by maartenfv** [comment]
https://github.com/teamforus/projects/issues/34

**Comment by GerbenBosschieter** [comment]
WE gaan een helpcentrum opzetten. er zal niet meer worden gewerkt aan help.forus.io.
