### ISSUE TITLE
Mobile: move hamburger menu to left and logo center

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#857]
## Main asssignee: @GerbenBosschieter 

Switch around navbar content.
Currently:
![IMG_8F17FD4237F8-1](https://user-images.githubusercontent.com/38419514/55809648-9331c080-5ae6-11e9-9054-1e8fbcf021ca.jpeg)

How it should be, not because their website does it. But I just like it more:
- logo centered
- login button to the right
- hamburger menu to the left (why left? because we also have a login button and its more common to have the login button to the right and nav items left)

![Screen Shot 2019-04-09 at 16 38 25](https://user-images.githubusercontent.com/38419514/55809552-68476c80-5ae6-11e9-98fe-233ee953b0c2.png)

## Context/goal: 
*explain why this issue was opened*

**Comment by NelisVanWijk** [comment]
**Just an idea is to do the following:**
Maybe just add the login option to the hamburger menu (this is also pretty common). then you can add the search button (like you did on the picture). this makes it easier to search the platform.

**Comment by GerbenBosschieter** [comment]
@NelisVanWijk I like it, but we don't have a search functionality on the webshops yet.

**Comment by NelisVanWijk** [comment]
No i know, for the time being you can put the login button on the right side and my idea can be added whenever a search feature will be added

**Comment by NelisVanWijk** [comment]
![afbeelding](https://user-images.githubusercontent.com/25053173/56639922-1704b480-6672-11e9-9c13-3489d070cd9b.png)
![afbeelding](https://user-images.githubusercontent.com/25053173/56639992-40bddb80-6672-11e9-8bdb-3acc82a3b076.png)

I think there should be a smaller log in button for the mobile site and when logged in the email of the user should be changed bacause as it is now it blocks the logo

**Comment by jamalv** [comment]
Depends on new design
