### ISSUE TITLE
Feature: reservation instead of purchase.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#859]
- [x] change 'koop' to 'reserve'
- [x] add 'annuleer reservering' button when reservation has been made
- [x] edit mail to say reserve instead of bought

**Comment by maxvisser** [comment]
when do we want to send a mail to provider that a reservation has been made?

**Comment by jamalv** [comment]
when a user clicks on reserve?

**Comment by jamalv** [comment]
I would prioritise this issue pretty high btw

**Comment by maxvisser** [comment]
Yes this is a priority high enhancement. Need some mails to be edited aswell

**Comment by maxvisser** [comment]
I thinn we also need a reservation cancelation mail

**Comment by maxvisser** [comment]
added a check on destroy if voucher = productvoucher and if voucher has transactions (should be null)
