### ISSUE TITLE
Feature: sponsor being able to create vouchers 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#862]
## Problem
Currently we implement a quick fix: validator uploads csv, this adds prevalidation records and creates activation codes that can be used to apply for a fund. In the current state of Forus this is a really weird interaction: validators can't see each others validation records; users can get only one voucher via activation code, sponsor can't see the state of these generated activation codes.

## Context/goal: 
Sponsor should be able to create vouchers for his fund; On his dashboard there should be a page 'Vouchers' this page shows all vouchers genereted for a specific fund. He can create new vouchers on this page.
Sponsor can upload a CSV with e-mail adresses; this will result in creating identities and sending action mails directly to these users; and also creating vouchers for these e-mailadresses. (user does not need to fill in activation code).
If no e-mail is known, sponsor creates voucher manually and a activation code is generated, this activation code can be send via postal. 

how do we link these vouchers to unique identifiers like BSN or Customer numbers I still don't know

**Comment by jamalv** [comment]
It should probably also be possible to export a QR code from the voucher dashboard directly. (if somebody does not have acces to a computer to activate the code). This is to support the use case where we want to enable to sponsor to send a "hot" voucher to a customer, avoiding the need to activate.
