### ISSUE TITLE
Epic: Make dashboards mobile ready

### ISSUE THREAD

**Issue by NelisVanWijk** [teamforus/forus#863]
**Is your feature request related to a problem? Please describe.**
The Dashboards are at this moment not really optimal for mobile use.

**Describe the solution you'd like**
If it's possible to create a special mobile dashboard which allows the user to do all the tasks you can do on the desktop that would a nice solution

**Describe alternatives you've considered**
- Change the layout on the current dashboard to make it fitting and easy to use on a mobile device
- Leave the dashboards as they are if you say: 'The dashboard was never meant to be used on a mobile phone'

**Additional context**
This is the dashboard now on a mobile phone
![Screenshot_20190417-121610](https://user-images.githubusercontent.com/25053173/56281180-449aac80-610c-11e9-9c0d-eb85dd871c83.png)
![Screenshot_20190417-121602](https://user-images.githubusercontent.com/25053173/56281181-449aac80-610c-11e9-8564-81f4c70e1bb5.png)
![Screenshot_20190417-121527](https://user-images.githubusercontent.com/25053173/56281182-45334300-610c-11e9-9a33-672161eb0011.png)
![Screenshot_20190417-121517](https://user-images.githubusercontent.com/25053173/56281183-45334300-610c-11e9-95c7-44c4298748cf.png)

**Comment by maxvisser** [comment]
Dashboards were never made responsive; a mobile design would be needed for each page. In practice we see that user don't use the dashboards on mobile. (as you need your e-mail configured on your phone to even get into the dashboard)

**Comment by NelisVanWijk** [comment]
Yes that was my though also if you did not wanted people to use this on mobile devices

**Comment by maxvisser** [comment]
Well its somewhat usable; Its just not really user friendly yet; still needs alot of work.

**Comment by NelisVanWijk** [comment]
Yes i think the ability to use the dashboard on a tablet should not be made impossible though

**Comment by jamalv** [comment]
As part of the redesign I think we should consider mobile friendliness from the start.

Good issue, will close it for now as it is too big, and we'll pick it up during our next design cycle.
