### ISSUE TITLE
QR-code of voucher doesn't scale on mobile phone

### ISSUE THREAD

**Issue by NelisVanWijk** [teamforus/forus#864]
When going to 'Mijn vouchers' and click on a voucher on a phone the QR code 
does not scale with all the other attributes. When you use Chrome it's responsiveness tester it does scale.  

In Chrome:
![afbeelding](https://user-images.githubusercontent.com/25053173/56282063-7e6cb280-610e-11e9-820d-6d005b7f7074.png)

On my phone and my test phone:
![afbeelding](https://user-images.githubusercontent.com/25053173/56282179-cf7ca680-610e-11e9-8643-b9e38aec4bab.png)

**Comment by maxvisser** [comment]
_Me_-app should be able to scan the small QR-code.

**Comment by GerbenBosschieter** [comment]
I can't reproduce this @NelisVanWijk 

I've used safari and chrome to test on an iPhone and Android phone.
![voucheres](https://user-images.githubusercontent.com/38419514/56298418-627b0800-6132-11e9-8a3a-f15d3352c974.png)

![screenboucherres](https://user-images.githubusercontent.com/38419514/56298549-9ce4a500-6132-11e9-8e6c-47e93710af6a.jpeg)

**Comment by NelisVanWijk** [comment]
I'm checking if i can reproduce this issue

**Comment by NelisVanWijk** [comment]
I have also reproduced this issue with the general and Nijmegen client key on the last updates of the forus-frontend Repo on my phones no idea why it happens.

**Comment by NelisVanWijk** [comment]
i've used chrome and the standard browser

**Comment by maxvisser** [comment]
which phone do you use and can you check your dimensions? on something like gsmarena

**Comment by NelisVanWijk** [comment]
Yes that's a Samsung Galaxy s8
![afbeelding](https://user-images.githubusercontent.com/25053173/56354983-73c92080-61d5-11e9-9879-d9291b903739.png)

 and a Xiaomi Redmi Note 5  
![afbeelding](https://user-images.githubusercontent.com/25053173/56355048-9e1ade00-61d5-11e9-8551-17f971b0189c.png)

**Comment by maxvisser** [comment]
You have the problem on both?

**Comment by NelisVanWijk** [comment]
yes

**Comment by maxvisser** [comment]
Reproduced in on my device aswell.

**Comment by maxvisser** [comment]
Looks like width is not capped in css but on desktop it somehow magically works without..
