### ISSUE TITLE
Printables: give context around voucher

### ISSUE THREAD

**Issue by NelisVanWijk** [teamforus/forus#865]
Task: update printables using this design:

Figma: https://www.figma.com/file/JrGErwC6dU10L44ylwnCxU/Printable-Vouchers?node-id=1%3A146

## Budget voucher: 
![image](https://user-images.githubusercontent.com/30194799/69789021-faa89780-11bf-11ea-8487-0f209ea6251f.png)

## Product voucher:
![image](https://user-images.githubusercontent.com/30194799/69789029-0300d280-11c0-11ea-9482-7010c43ffb70.png)

**Comment by maxvisser** [comment]
we are in the proces of rethinking the implementation of multiple QR-codes; as we already get some support calls about confused users. Adding more context to the print is one solution but does not fix the bigger problem.

we are also looking into how to add images into the center of the QR-code so the provider can see the use case of the QR before scanning.

**Comment by maxvisser** [comment]
@dev-rminds could you demonstrate in a PR on how we can add more context in print of voucher?
things we like to add are
fund name
organisation name

**Comment by maxvisser** [comment]
![printable-budget voucher](https://user-images.githubusercontent.com/10818702/61528452-1be1c600-aa1f-11e9-9018-79d5de57cd57.png)

**Comment by maxvisser** [comment]
![printable-product voucher](https://user-images.githubusercontent.com/10818702/61528487-387dfe00-aa1f-11e9-9713-3560b7c6e45f.png)

**Comment by jamalv** [comment]
@danrminds designs are done: https://www.figma.com/file/JrGErwC6dU10L44ylwnCxU/Printable-Vouchers?node-id=0%3A1

Could you pick this one up with @aghimpu?

**Comment by maxvisser** [comment]
Figma needs to be cleaned up a bit

**Comment by jamalv** [comment]
Done :) what do you think now?

**Comment by GerbenBosschieter** [comment]
I would like to see a sentence added about refunding.

**Comment by maxvisser** [comment]
@GerbenBosschieter Could you leave this feedback in figma? Alex already implemented Figma but we could still add this to the PR; just comment what you want and where.

**Comment by aghimpu** [comment]
@GerbenBosschieter is it just about adding this sentence "Aankopen met deze voucher kunnen niet worden geretourneerd" to both printables?

**Comment by maxvisser** [comment]
Yes
