### ISSUE TITLE
No background image webshop

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#866]
## Context/goal: 
The background image of the webshop has disappeared. I have no idea how this happend. In the css I can see that on rule is overwritten by **background: none**
<img width="1139" alt="Screen Shot 2019-04-23 at 12 37 09" src="https://user-images.githubusercontent.com/38419514/56574977-df8bfe80-65c4-11e9-8719-cbd98b31f38a.png">

**Comment by maxvisser** [comment]
Oh really? thats stange also only nijmegen as it seems.

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-frontend/commit/a2e95a8cd0f681289cd551eb5e173e348adbe03c#diff-b6eebe0fc4a15100b3451dd72298754d it seems we have overwriitten header-sprite css in this commit
