### ISSUE TITLE
Login on Me via desktop (me app checks if device token is valid)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#868]
## Context/goal: 
This issue about deeplinking via e-mail:
current implementation makes it impossible to login via desktop on Me-app.

Current userflow:
User fills in e-mail in Me-app to login (recover account)
User opens e-mail on desktop, clicks on link and page opens with button 'open in me'
user clicks button and nothing happens.

Happy userflow:
User fills in e-mail in Me-app to login
User opens e-mail get option to deeplink to app or login via desktop
User clicks link and user gets automatically logged in on mobile phone.

**Comment by maxvisser** [comment]
open me -> opens QR-code

**Comment by jamalv** [comment]
proposal: https://github.com/teamforus/me/issues/380
issue for approval: https://github.com/teamforus/development/issues/284

**Comment by maxvisser** [comment]
two types of QR-codes
one for unauthenticated -> not sensitive
one for authenticated devices -> sensitive
