### ISSUE TITLE
Confirming transactions by PIN

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#87]
-- offline voucher (printed), webshop
dont need confirmation

-- used by Me
needs confirmation

Confirm voucher transactions / other transactions with Pincode is only in Me app not saved on backend. If no pincode, just ask yes / no question ' Do you want to do a payment of 2 euros? ' 
touch id/face id

- [ ] push notification
- [ ] client communication

#### regular transaction with approval
- [ ] send notification to accept payment and let user accept transaction first

EN: Do you want to accept the payment request of € {amount} ?
NL: Wilt u de betalingsverzoek van € {{amount}} accepteren?

#### product voucher transaction with approval
- [ ] Send notification to me app to first accept product voucher transaction before payment

to requester
EN: Do you want to accept the request for using your voucher for '{product_name}'?
NL: Wilt u het verzoek accepteren om uw aanbieding voucher te gebruiken voor {product_name}?

- [ ] to provider

EN: Your request has been declined.
NL: Uw verzoek is afgewezen.

EN: Your request has been accepted.
NL: Uw verzoek is geaccepteerd.

**Comment by maxvisser** [comment]
As I explained in #84, pincodes should only be used in front-end. Therefore the backend doenst have to check if pincode has been entered correctly. The apps should just check for the right pincode, therefor if your identity is authorized to do the transaction, the user should be able to do this directly against the api. If he uses a front-end, he is asked to enter a pincode that is saved locally.

**Comment by danrminds** [comment]
I think we can keep the pin-code locally. But still - this issue is valid -> as it concerns other implementations regarding the pincode approval of transactions

**Comment by maxvisser** [comment]
This for Me backlog right? @jknnr how do you see this issue?

**Comment by maxvisser** [comment]
@jknnr @danrminds whats the status update on this issue? lets update it with some context of what still needs to happen to make it work.

**Comment by danrminds** [comment]
Status is as usual - postponed because of all the other issues that appeared meanwhile with higher priority. 
This need work on implementation of push notifications
And backend development 

For now it has to be done by Valentin.

**Comment by jamalv** [comment]
I don't feel we need to rush this. Since doing this well has some tricky questions;

* it implies that there will be a different qr code if you use the app? since with the normal qr code you can just subtract the budget
* what will happen then with the old normal qr code? will it become invalid? if so, we need very clear communication with the user about this

This is iceboxed until we have time to pick it up properly, or it gets priority some other way.

**Comment by danrminds** [comment]
@jamalv We already have 2 types of QR-code implemented. (one that needs manual validation - for the app and one that does not need - for printing and webshop)

**Comment by maxvisser** [comment]
Could you specify a bit how much work it is still though? As I see it, @dev-rminds only needs to implement the service in the backend to make these requests on certain actions and send these actions to @kremlinwarrior's notifications service. maybe 2 days of work?

**Comment by danrminds** [comment]
Yes, not more then 2 days of work

**Comment by maxvisser** [comment]
I think is more an issue which should be created in Me; will close this for now
