### ISSUE TITLE
SCSS Refactoring 7-1 Pattern

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#872]
## Context/goal: 
There where some moments of time pressure, this has resulted in some quick and dirty work  regarding the frontend of the webshops. This can quickly cause minor bugs, it takes a lot of time to make all frontends equal and it is not scalable for future implementations.

To improve the SCSS I propose to use the 7-1 pattern. This means that the architecture of the SCSS and folders will change. (I've discussed this with @jamalv and @maxvisser)

For more info read: https://medium.com/insider-inc-engineering/how-to-style-different-sites-with-one-css-collection-6f33126d4cdb

How the folder structure will look like:
![example7-1](https://user-images.githubusercontent.com/38419514/57075069-05608400-6ce6-11e9-861c-3f2111dfd7cf.png)

The result will ensure that:
- It becomes easier and faster to implement different styles of web shops.
- Preparing the demo environment can become smoother.
- It is easier to build a CMS around it for the future.
- The complete SCSS wil be much more robust.

**Comment by maxvisser** [comment]
@dev-rminds likes the idea: 
he has some suggestions: 

remove vendor, pages

add folder blocks

resetter and typography are merged

**Comment by GerbenBosschieter** [comment]
Nice! the image was just an example ofcourse. We can give our own twist on it :)

**Comment by maxvisser** [comment]
Valentin says you will still need overwrite css with themes. So it will not be alot different than our current implementation functionality wise

**Comment by GerbenBosschieter** [comment]
True, but it will be much easier to change stuff, clearer overview and I assume less repetitive code. Especially because multiple people are contributing to the css. If we are going to have more and more implementations the css will be bigger and bigger. And working by a contribution guide with this pattern will hopefully result in a faster tempo of contributing.
