### ISSUE TITLE
Update and add footer

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#888]
## Design @Myshelova:

<details><summary>Current design (click to expand):</summary>

<img width="816" alt="Screenshot 2019-05-25 at 08 33 53" src="https://user-images.githubusercontent.com/30194799/58365658-de056d00-7ec7-11e9-9e84-bb58fbd77b57.png">

</details>

<details><summary>Updated design wireframe (click to expand):</summary>

<img width="1088" alt="Screenshot 2019-05-25 at 08 30 28" src="https://user-images.githubusercontent.com/30194799/58365634-7d763000-7ec7-11e9-81b6-bdc6474a6585.png">
</details>

## Develop @GerbenBosschieter @maxvisser 
- [x] set up the footer
- [x] add and enable contact form

**Comment by jamalv** [comment]
Footer has been updated in Zeplin. @GerbenBosschieter could you develop it?

<img width="830" alt="Screenshot 2019-05-29 at 06 47 39" src="https://user-images.githubusercontent.com/30194799/58530091-a820fb00-81dd-11e9-9701-de711232d9d1.png">

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-frontend/pull/564
