### ISSUE TITLE
new cta's are not centered on homepage 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#891]
![image](https://user-images.githubusercontent.com/10818702/58273751-a7c5d180-7d91-11e9-9446-10640a77f2b8.png)

**Comment by GerbenBosschieter** [comment]
This happend after you switched around a lot of stuff and influenced other pages.
I would rather not change this because it will probably change other elements and it was allready okay before switching this

**Comment by maxvisser** [comment]
I agree and know the origin of the problem. Let's leave it open as it is still an issue
