### ISSUE TITLE
Header text: explore alternatives

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#900]
Current text: 

**Veilige waarde-uitkering**
_Efficiënt en eerlijk met fondsen omgaan. Inzicht en overzicht houden._

**Comment by jamalv** [comment]
Possible improvement:

**Optimale waarde-uitkering**
Efficiënt en eerlijk met fondsen omgaan. Inzicht en overzicht houden.

**Comment by maxvisser** [comment]
Currently planning sprint with gerben. this can be added as a suggestion the google doc
