### ISSUE TITLE
Add call to action to homepage

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#905]
Below "het platform" I would like to add a call to action:

``` Lees meer over de implementatie van het kindpakket in de Gemeente Zuidhorn > ```

The funnel I am aiming for is:
Homepage > Customer story Zuidhorn > Kindpakket product page > Contact

<img width="658" alt="Screenshot 2019-05-25 at 12 43 35" src="https://user-images.githubusercontent.com/30194799/58368279-03f03900-7eeb-11e9-8e8e-3610cb6c1bc1.png">

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/58373250-36218b00-7f2b-11e9-843c-7f6354ca221e.png)

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-frontend/pull/541
