### ISSUE TITLE
Provider: refine signup flow categories step

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#913]
## Context:
Within the signup flow we currently have two lists that providers can pick categories from. This issue is about creating a more generic system, that will work better for longer into the future.

## Proposal:
t.b.d.

**Comment by maartenfv** [comment]
This issue is relevant for Issue: https://github.com/teamforus/forus/issues/979
Will we do the quick fix and add the category or will we do an complete change and prepare for multiple implementations?

**Comment by maxvisser** [comment]
deprecated by #917
