### ISSUE TITLE
Refinement: Product categorie

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#915]
## Context/goal: 

We would like to change the way in which categories are used.
The categories are currently used for business types and / or the products / services that they offer.

- The sponsor indicates which categories may be accepted on behalf of the fund.
- The registration form for the retailer is adjusted based on what the sponsor has indicated. The shopkeeper only has the option to sign up for the fund that belongs to these categories

### Our current situation
![Untitled Diagram](https://user-images.githubusercontent.com/38419514/58561010-839d4100-8226-11e9-8377-15a2c380ed9f.png)

## Proposal

The connection between the categories and funds will be removed.
The application form for the providers will be adjusted based on a Fund and or Sponsor ID.
This is a solution for the sponsor who want to share the URL for the application form but only wants to display their fund and no other funds. A generic application form can still be used to display every fund.

### Requirements
- [ ] Generate an application form (url) based on the Fund_id and / or Sponsor_id.
- [ ] The form will only show the funds that are based on the Fund_Id and / or Sponsor_id.

**Comment by maxvisser** [comment]
I removed check for categories of fund for provider to apply for a fund from api

**Comment by maxvisser** [comment]
Can be tested on develop

**Comment by maxvisser** [comment]
superseded by https://github.com/teamforus/forus/issues/960
