### ISSUE TITLE
Define: what is a local motion project in Forus?

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#918]
## Context
For local motion we have been discussing what a project will be in Forus. The options we have discussed is that it will either be a fund or that it will be a voucher. Both don’t seem to completely fit.

## Proposal
I think the cleanest way to do this is to enable parent-child relationships between funds. This will open up possibilities around abstraction in the future. It will also make “beslisboom - like” possibilities. E.g. the top-level fund has certain criteria, and then there are also child-funds that have more specific criteria. You could be eligible for (some of the child) funds and for the top level fund, eligibility for any fund is either true or false, but it could be required that you need to be eligible for all the higher level funds to be eligible for a child fund.

## Localmotion example
For local motion it could work as follows: to be eligible to spend money on any fund, you need to be validated to be trustworthy by any lungfund validator. But to be able to spend money for a specific playground, your address needs to be validated with IDIN, and should be closer then x km to the project location.

**Comment by maxvisser** [comment]
Problem you did not fix. An identity needs an voucher, token or valuta to send pay for a product. The sponsor buying product directly from his fund is currently not possible. Therefor Dan proposed to give each project a voucher so it works with the current workflow

**Comment by maxvisser** [comment]
Some option I see to fix this:
Make a budget voucher on the fund owners account that has unlimited funds (balance of fund) same solution different take:
Add a normal voucher and make a sync between voucher balance and fund balance.

**Comment by maxvisser** [comment]
We can also build a voucher generator for the sponsor. He can generate any voucher of any amount for his fund and alocate it to an address/mail

**Comment by jamalv** [comment]
> Problem you did not fix. An identity needs an voucher, token or valuta to send payment for a product. The sponsor buying product directly from his fund is currently not possible. Therefor Dan proposed to give each project a voucher so it works with the current workflow

> Some option I see to fix this:
> Make a budget voucher on the fund owners account that has unlimited funds (balance of fund) same solution different take:
> Add a normal voucher and make a sync between voucher balance and fund balance.

Sure, that seems quite quick-fix-y though. It can work for an MVP but is not too nice for later. This issue is more about thinking what would be the cleanest way to do it, and then make an mvp with that in mind.

> We can also build a voucher generator for the sponsor. He can generate any voucher of any amount for his fund and alocate it to an address/mail

I really like this idea connected with fund abstraction. So; 
* A sponsor "Longfonds" has a fund: "rookvrijspelen", Longfonds is also provider for this fund. 
* The fund has a child for each workspace: "speeltuin Groningen", "speeltuin Hardewijk" etc. 
* When a purchase is made from a fund, the sponsor generates a voucher, this voucher is then used to make the payment to the provider.

For one playground (mvp) this also works without fund abstraction:
* A sponsor "Longfonds" has a fund: "rookvrijspelen", Longfonds is also provider for this fund. 
* When a purchase is made from a fund, the sponsor generates a voucher, this voucher is then used to make the payment to the provider.

**Comment by jamalv** [comment]
Made a separate issue for voucher generator: https://github.com/teamforus/forus/issues/919

**Comment by maxvisser** [comment]
workflow:
localmotion user donates 100 euro's to a project
100€ are allocated to rookvrijspelen fund
user orders flyers of 30 euro's
Localmotion smokefree service will use sponsor (fund creator) access token to generate voucher of 30 euro's
Localmotion smokefree service will use same access token to do transaction on newly generated voucher of 30 euro's

**Comment by jamalv** [comment]
So, to summarise:

* When a donation is made; it is added to the (child) fund.
* When a purchase is done, the sponsor generates a voucher using the voucher generator
* This voucher is used to send the funds to the provider.

**Comment by jamalv** [comment]
Lol, seems like we're on the same page 😛

**Comment by jamalv** [comment]
So to conclude; it is a fund. And we use a voucher generator for the payments.
