### ISSUE TITLE
Epic: Voucher generator for sponsor

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#919]
## Context

When a sponsor generates a fund, the only way to allocate the funds right now, is by creating activation codes for prevalidation records that an identity uses to apply for a fund. We also want to make it possible for a requester to apply to a fund using different records later, but for certain use cases both these options are not fitting. For example when someone has absolutely no acces to a computer whatsoever (for example elderly people). For this type of user, it would be better to get a voucher (qr-code) directly without any application

## Proposal

We add a "voucher generator" to the sponsor dashboard. 

## Wireframe
![Voucher generator-Scope MVP](https://user-images.githubusercontent.com/30194799/58865744-66012900-86b7-11e9-9a8d-268044d00ff3.png)

If e-mail adres doet not exist to UPDATE vouchers identity_address, identity will be created by sponsor and identity address wil be used to UPDATE voucher

## Technical Specifications:

Voucher generator for sponsor needs a new endpoint on the api

### GET list

Endpoint: 
/platform/organizations/1/funds/1/vouchers?

Description:
Get all vouchers of fund 1

Access level: 
organisation creator, admin and finance officer can GET on this route.

Data structure:
**vouchers**

Column | Type | Comment
-- | -- | --
id | int(10) unsigned |  join with voucher_tokens on this id
fund_id | int(10) unsigned |  
amount | decimal(10,2) unsigned |  
product_id | int(10) unsigned NULL |  
parent_id | int(10) unsigned NULL |  
expire_at | timestamp NULL |

**voucher_tokens**

Column | Type | Comment
-- | -- | --
voucher_id | int(10) unsigned |  join with vouchers based on this id
address | varchar(191) | 

### POST store

Endpoint: 
/platform/organizations/1/funds/1/vouchers?

Description:
route will create new entry on vouchers table

Access level:
organisation creator, admin and finace officer can post on this route.

Data structure:

**vouchers**

Column | Type | Comment
-- | -- | --
id | int(10) unsigned Auto Increment |  
fund_id | int(10) unsigned |  
identity_address | varchar(200) |  
amount | decimal(10,2) unsigned |  
product_id | int(10) unsigned NULL |  
parent_id | int(10) unsigned NULL |  

### GET show

Endpoint: 
/platform/organizations/1/funds/1/vouchers/0xd178209b4943e33d969e565e6d65e0a984b7abaa?
get voucher entry based on voucher_token

Notification (if identity address is filled):
Should send mail to identity mail address with QR-code

Description: 
Token address of GET list will be used to show voucher details

Access level: 
organisation creator, admin and finance officer can GET on this route.

### UPDATE send

/platform/organizations/1/funds/1/vouchers/0xd178209b4943e33d969e565e6d65e0a984b7abaa?
update voucher entry based on voucher_token

Data structure:

**vouchers**

Column | Type | Comment
-- | -- | --
id | int(10) unsigned Auto Increment |  
fund_id | int(10) unsigned |  
identity_address | varchar(200) |  will be filled by identity_address of identity that receives voucher
amount | decimal(10,2) unsigned |  
product_id | int(10) unsigned NULL |  
parent_id | int(10) unsigned NULL |  

Access level: 
organisation creator, admin can UPDATE on this route.

Notification:
Should send mail to identity mail address with QR-code

**Comment by maxvisser** [comment]
# API route adjustments

this will create a new endpoint on the api

## POST store

Endpoint: 
/platform/organizations/1/funds/vouchers?

Description:
route will create new entry on vouchers table

Access level:
organisation creator, admin and finace officer can post on this route.

Data structure:
Column | Type | Comment
-- | -- | --
id | int(10) unsigned Auto Increment |  
fund_id | int(10) unsigned |  
identity_address | varchar(200) |  can be left empty
amount | decimal(10,2) unsigned |  
product_id | int(10) unsigned NULL |  
parent_id | int(10) unsigned NULL |  

## GET list

Endpoint: 
/platform/organizations/1/funds/1/vouchers?

Description:
Get all unallocated vouchers of fund 1 (identity_address is empty)

Access level: 
organisation creator, admin and finance officer can GET on this route.

Data structure:

vouchers
Column | Type | Comment
-- | -- | --
id | int(10) unsigned |  join with voucher_tokens on this id
fund_id | int(10) unsigned |  
amount | decimal(10,2) unsigned |  
product_id | int(10) unsigned NULL |  
parent_id | int(10) unsigned NULL |  

voucher_tokens
Column | Type | Comment
-- | -- | --
voucher_id | int(10) unsigned |  join with vouchers based on this id
address | varchar(191) | 

## GET show

Endpoint: 
/platform/organizations/1/funds/1/vouchers/0xd178209b4943e33d969e565e6d65e0a984b7abaa?
get voucher entry based on voucher_token

Description: 
Token address of GET list will be used to show voucher details

Access level: 
organisation creator, admin and finance officer can GET on this route.

## UPDATE send

/platform/organizations/1/funds/vouchers/0xd178209b4943e33d969e565e6d65e0a984b7abaa?
update voucher entry based on voucher_token

Column | Type | Comment
-- | -- | --
id | int(10) unsigned Auto Increment |  
fund_id | int(10) unsigned |  
identity_address | varchar(200) |  will be filled by identity_address of identity that receives voucher
amount | decimal(10,2) unsigned |  
product_id | int(10) unsigned NULL |  
parent_id | int(10) unsigned NULL |  

Access level: 
organisation creator, admin can UPDATE on this route.

**Comment by maxvisser** [comment]
should look after these adjustments if any statistics on financial dashboard are getting messed up when creating voucher with no identity_address allocated

**Comment by sashooa** [comment]
https://www.dropbox.com/sh/7j2n32yzi5i0eij/AACM1lxNgqbn7f5cZI4pVQ9Da?dl=0 design sources 🙈
