### ISSUE TITLE
Websitetest: nijmegen.forus.io

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#925]
We zijn geattendeerd op het volgende: https://internet.nl/site/nijmegen.forus.io/543151/

Kunnen we deze dingen fixen?

Bereikbaar via moderne internetadres (IPv6)
Gezakt : Domeinnaam niet ondertekend (DNSSEC)
Gezakt : Verbinding niet of onvoldoende beveiligd (HTTPS)
Suggestie : Een of meer aanbevolen applicatie-beveiligingsopties niet ingesteld (Beveiligingsopties)

**Comment by maxvisser** [comment]
allemaal infrastructuur zaken; zal ik oppakken in interne repo
