### ISSUE TITLE
Epic: Set fund criteria

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#932]
- User creates fund
- _If_ they want an application procedure:
  - They add a "persona" that has the criteria
    - The persona has a list of criteria, posed as statements
    - The value of your house is between €... and €...
      - First we will configure the statements ourselves, then we'll develop tools that make it possible for anybody to "build" and configure these statements.

**Comment by maxvisser** [comment]
Deprecated; replaced by https://github.com/teamforus/forus/issues/959
