### ISSUE TITLE
Product: Kerstpakket

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#933]
**Context:** deze pagina is bedoeld om het kerstpakket aan organisaties aan te bieden (uiteraard uitgegeven via ons platform). We kunnen hier het pakket presenteren en wat er voor nodig is om deze te implementeren. Dit sluit aan op waar @maartenfv en @linda-90 mee bezig zijn, ondersteuning bij implementatie op afstand. Eerste focus is om het pakket en de voordelen ervan goed en helder te presenteren, het volgende onderdeel van de funnel is implementatie ondersteuning.

Voorbeeld pagina: https://www.forus.io/kindpakket

- [ ] duidelijke uitleg over het pakket
- [ ] voordelen voor inwoner
- [ ] voordelen voor organisatie
- [ ] politieke context etc
- [ ] voorbeeld brieven

**Comment by jamalv** [comment]
Deze pagina zal wellicht wat afwijken van #903 en de huidige kindpakket pagina, omdat de doelgroep en het product afwijkt. Het is mooi als hij zover mogelijk alligned kan blijven met de andere product pagina’s. Maar als het nodig is om af te wijken, om een betere pagina te maken, kan dat ook.

**Comment by maartenfv** [comment]
Dit is het voorstel dat de basis vormt voor het kerstpakket. Ik pas het aan aan de organisatie waar we het naar toesturen. Zo is het voorstel voor de Gemeente Emmen anders dan dat voor ICTU. https://docs.google.com/document/d/1BPEBnObWzz9wphxLBRyAkgO1ujdi2bY6H_Jtu_c9Kl0/edit

**Comment by maartenfv** [comment]
Ik heb een document aangemaakt waar de tekst voor de pagina in kunnen uitschrijven. Deze staat in Media & Communication > Website > Products > Kerstpakket: https://docs.google.com/document/d/1sWtsHu3FCWJJzLP9JVLsJm1uIS0GC3NGDx_89t4x37I/edit
