### ISSUE TITLE
change text on me page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#936]
## Context/goal: 

“ Me wordt gebruikt om vouchers in te bewaren of een betaling te verrichten. Ook wordt Me gebruikt om zonder wachtwoord in te loggen op Forus ”

![image](https://user-images.githubusercontent.com/10818702/60245988-05cc6400-98be-11e9-87b2-a50974c57696.png)

**Comment by GerbenBosschieter** [comment]
@jamalv you created the original text. I am not going to overwrite this and wait for a new issue from you to overwrite it again. So do you agree with @maxvisser here ?
