### ISSUE TITLE
Make a generic Kerstpakket front-end

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#945]
This front-end needs to be generic and re-usable for any Kerstpakket implementation.

We need a design.
And turn this into code

- [x] Create generic design
- [ ] Development

**Comment by GerbenBosschieter** [comment]
I've created a design for Kerstpakket.
Four of our really liked it, so it started the development, I will present this at the sprint demo of august 9.

* I didn't finished the design for other pages and the details like icons, fonts, text, etc etc
It's clear what it should like and will add all the other stuff during development.

**Desgin**
![common_christmas](https://user-images.githubusercontent.com/38419514/62370391-3f823180-b532-11e9-961b-664f3e6a9ccd.png)

**Comment by jamalv** [comment]
Only needs: https://github.com/teamforus/forus/issues/1139

Closing this issue, it is live: https://kerstpakket.forus.io
