### ISSUE TITLE
Change stats to bar chart instead of line.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#948]
As can be seen in the image below currently we use a line chart. This does not make sense as the numbers are not continuous but discreet. Example: we can have 10,55 euros but not 10,55334234 euros. We therefor need a bar chart. This Issue can be closed when the graph is a bar chart.

We could use something like https://www.chartjs.org/. 
Bar chart: https://www.chartjs.org/samples/latest/charts/bar/vertical.html

![image](https://user-images.githubusercontent.com/30211022/60867875-14a30700-a22c-11e9-9426-c4beaa950da5.png)

**Comment by maxvisser** [comment]
we already use chartjs for the line chart so no need for a new library :)

**Comment by maxvisser** [comment]
good suggestion

**Comment by GerbenBosschieter** [comment]
@maartenfv I've already looked into this a while ago. I don't think I am able to do this. The angular plugin (from what I understand) needs to be changed.

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-frontend/pull/580

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/60877123-7ae45580-a23d-11e9-875b-725ac0851327.png)
