### ISSUE TITLE
adapting AWS image storing

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#96]

**Comment by maxvisser** [comment]
I createad an S3 bucket storage on AWS for this called media.forus.link

**Comment by maxvisser** [comment]
Do we need redis or sqs on amazon?

**Comment by maxvisser** [comment]
https://deliciousbrains.com/scaling-laravel-aws-elastic-beanstalk-part-1-setting-up-laravel/ 

External file system

**Comment by maxvisser** [comment]
tested it
