### ISSUE TITLE
Criterias / formulas [SPONSOR]

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#97]
Improving of the criterias system
Implementing formula for allowing budgets to people. Might consider including records in the formula (for example number of kids in the case of Zuidhorn)

**Comment by maxvisser** [comment]
We should discuss how to make this generic and more flexible.

**Comment by danrminds** [comment]
Schedule a meeting for today or tomorrow for this?

**Comment by maxvisser** [comment]
lets plan a meeting for this coming week; after 3 okt

**Comment by danrminds** [comment]
@dev-rminds What do you think?

**Comment by maxvisser** [comment]
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-ssm-2014-11-06.html maybe we can use the parameter store in AWS for storing the formula etc
