### ISSUE TITLE
Bug: Cross-Origin Resource Sharing not allowed ? (providers cant create profile by sign up form)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#975]
## Context/goal: 

Providers cant create a Me profile while signing up.
Clicking **Volgende** results in an error. See Image

<img width="1437" alt="Screen Shot 2019-08-07 at 18 32 29" src="https://user-images.githubusercontent.com/38419514/62640724-81e8ab80-b942-11e9-95d7-cc03a3f63a44.png">

**Comment by maxvisser** [comment]
Cross origin heeft er niks mee te maken

**Comment by GerbenBosschieter** [comment]
En wat dan wel he.

**Comment by SpesFides** [comment]
Problem:
Due to a unexpected reboot to the APM system was offline. This preventate the customer registration system to function properly.

Problem solved:
Boot the APM.
