### ISSUE TITLE
Feature: Donate to provider (charity)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#980]
For the issuance of Kerstpakketten requester need to be able to spend their budget by donating to providers (charities). 

- [ ] Consider the different options in regards to donating
  - We could have the providers simply add a couple offers in the website with different amounts and this could be the donation. The requester purchases the offer and donates.
  - Allowing the requester to chose a provider and typ in a specific amount. This feature can be used to allow the spending of smaller amounts and is useful if someone still has a budget but insufficient funds to purchase an offer.

**Comment by maxvisser** [comment]
I think your first consideration is indeed the MVP, which already works. Maybe we should just first implement this approach try it out and ask for feedback and implement the feedback after.

**Comment by jamalv** [comment]
Decided as an mvp: it will be done live at the Christmas market:

Sponsor will add an organisation for each charity. They will collect the payments using the organisation switcher in the me app, they will stay pending since it is their account. The money gets manually sent to the charities.
