### ISSUE TITLE
Check (and add or alter if needed) all system notifications for the issuance of Kerstpakketten

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#981]
Check if the system is ready for issuing Kerstpakketten.

Consider amongst others:

- Donations Issue: #980
- Invitations of providers: #978

**Comment by maxvisser** [comment]
Eran is current working on seperating emails based on implementation key. This will help customize kerstpakket mails

**Comment by maxvisser** [comment]
#984 new issue
