### ISSUE TITLE
Design Kerstpakket mails

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#984]
## Login mail
Onderwerp e-mail: Log in op het dashboard geldig tot [tijd]

Log in op het dashboard

Beste medewerker,
U heeft zojuist aangegeven dat u wilt inloggen op het Kerstpakket dashboard.
Klik hier of op de knop hieronder om in te loggen.    
Deze link is geldig tot [tijd]. 
Heeft u zich niet aangemeld? Neem dan contact op met de klantenservice van Forus 06-36261231, applicatiebeheerder.
Button: Inloggen

Onderwerp e-mail: Log in op Me geldig tot [tijd]

Log in op Me

Beste medewerker,
U heeft zojuist aangegeven dat u wilt inloggen op Me.
Klik hier of op de knop hieronder om in te loggen. 
Deze link is geldig tot [tijd].    
Button: Inloggen

## New Voucher mail

Onderwerp e-mail: Uw Kerstpakket Emmen voucher in de vorm van een QR-code

Uw Kerstpakket Emmen voucher in de vorm van een QR-code

Beste medewerker,
U heeft gevraagd uw Kerstpakket Emmen voucher per e-mail te ontvangen.
Onderstaande QR-code laat u bij de aanbieder zien. De aanbieder scant deze code en de betaling gebeurt automatisch, daar hoeft u niks voor te doen.

## Provider accepted mail
Onderwerp e-mail: Aanmelding als aanbieder is goedgekeurd

Aanmelding als aanbieder is goedgekeurd
Uw aanmelding is geaccepteerd!

Beste [Naam leverancier],
Kort geleden heeft u zich aangemeld voor [Fonds naam]. [Naam gemeente] heeft uw aanmelding geaccepteerd. Dit betekent dat u vanaf nu uw aanbiedingen kan leveren aan klanten die recht hebben op [Fonds naam].

Team [Fonds naam]

Log in op uw gebruikersomgeving om aanbiedingen toe te voegen, door hier of op de onderstaande knop te klikken.

## New product for sponsor

Onderwerp e-mail: Er is een nieuw aanbod toegevoegd aan de webshop

Er is een nieuw aanbod toegevoegd aan de webshop

Beste [Naam gemeente],
Er is een nieuw aanbod geplaatst op de webshop. Bekijk de webshop om te controleren of het voldoet aan de voorwaarden om vanuit [Fonds naam] aangeboden te worden.

## Tasks
- [ ] template mail for kerstpakket

**Comment by jamalv** [comment]
Plan is to add these to figma so that it is easy to view, edit and communicate the contents of the mails

**Comment by maxvisser** [comment]
needs to added to figma. Who is doing this?

**Comment by maxvisser** [comment]
No priority right now; will close this issue when it will be worked again we can reopen
