### ISSUE TITLE
Settings page [SPONSOR]

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#99]
- [ ] Allow products / Don't allow products
- [ ] Automatic / manual approving of products
- [ ] Allow regular vouchers (spending freely at shopkeepers)
- [ ] Allow pre-validations

**Comment by maxvisser** [comment]
I think that if you trust a validator, you don't need to manually accept pre-validations.

**Comment by maxvisser** [comment]
As we meet with the providers 13 september, I think feature has a priority.

**Comment by danrminds** [comment]
About pre-validations: this is a feature concerning implementation process (for each implementation - the client could want pre validations via CSV, or via database, or with different fields - we just have to turn this on or off in the settings.

**Comment by danrminds** [comment]
Will split this one up
