### ISSUE TITLE
Applying: MVP

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#995]
## Context:

This is part of epic: #793, this issue defines the MVP of the required functionality. The goal is to reach a feature complete application flow that can be demonstrated and is usable by end users.

### Sponsor
The update to the sponsor dashboard, is adding criteria to the fund creator / editor:

- [x] Design by @sashooa 
- [x] Development by @HardCoderNET

<details><summary>View wireframe</summary> 

![forus-platform-sponsor (7)](https://user-images.githubusercontent.com/30194799/64124447-57eea180-cda7-11e9-9e74-0e13010a58fa.png)
</details>

### Requester
For the requester some updates to the webshop will be made.

For the MVP we are doing, the fund has only one product and one provider. The goal is for the user to directly apply to the product (so he will not get a budget voucher, and we don't have to show prices). If the user is logged in, we can show if they are eligible in the product overview:

- [x] Design by @Myshelova  
- [x] Development by @HardCoderNET

<details><summary>View wireframe</summary>

![forus-webshop (4)](https://user-images.githubusercontent.com/30194799/64153157-85caf900-ce2e-11e9-8caf-f9fdd4a15840.png)
</details> 

If the user is directly eligible for the fund, we can immediately give them the voucher when they apply for a product. If they don't have all the info, they will need to fill in a form:

- [x] Design by @Myshelova   
- [x] Development by @HardCoderNET 

<details><summary>View wireframe</summary>

![forus-webshop (2)](https://user-images.githubusercontent.com/30194799/64118405-e0fddc80-cd97-11e9-8e7c-c85ed09af9a3.png)
</details>

After the user finishes filling in the form, the validation requests are sent to the validator dashboard, and we show the user a confirmation. They will get an email when the records are validated.

- [x] Design by @Myshelova    
- [x] Development by @HardCoderNET 

<details><summary>View wireframe</summary>

![forus-webshop (3)](https://user-images.githubusercontent.com/30194799/64118690-6a151380-cd98-11e9-841d-07254b1d5136.png)
</details>

### Validator
The validator will use the (existing) validation dashboard to validate the records.

- [x] Design by @sashooa   
- [x] Development by @HardCoderNET 

<details><summary>View wireframe</summary>

![forus-platform-validator (1)](https://user-images.githubusercontent.com/30194799/64118916-ef002d00-cd98-11e9-8b86-ad144732effb.png)
</details>

## Confirmation mail
If the records match the criteria of the sponsor, the requester will get an email:

> You are eligible for the "Zomer zwem regeling", this is your voucher:
> 
> [qr-code]
> 
> [info about where to spend it etc]
> 
> log in to the webshop to see your budget and transactions
> 
> [link to the webshop]
>

**Comment by jamalv** [comment]
@maartenfv could you ask if our client wants the designs to be generic or if he wants it to be in the style of the municipality?

Also, do we want mobile designs as wel or if is enough to show the mvp only on desktop?

**Comment by maartenfv** [comment]
@jamalv Will do. We need mobile as well.

**Comment by maxvisser** [comment]
lets make a new issue 433 is pretty old; I closed it.

**Comment by jamalv** [comment]
mobile designs are part of this issue and the associated estimates

**Comment by danrminds** [comment]
### Validator dashboard:
https://www.dropbox.com/s/9bdtviu3q8wt3av/Validator%20%28New%29.PSD?dl=0

Sponsor dashboard:
https://www.dropbox.com/s/x4zem617ab2undo/Add%20fonds%20%28New%29.PSD?dl=0

**Comment by jamalv** [comment]
> ### Validator dashboard:
> https://www.dropbox.com/s/9bdtviu3q8wt3av/Validator%20%28New%29.PSD?dl=0
> 
> Sponsor dashboard:
> https://www.dropbox.com/s/x4zem617ab2undo/Add%20fonds%20%28New%29.PSD?dl=0

@danrminds, nice, I've added some comments to the validator dashboard

**Comment by danrminds** [comment]
@jamalv Okay, will make the adjustments.

**Comment by danrminds** [comment]
Updated validator dashboard:

https://www.dropbox.com/s/nz4nepqjxnrngeo/Validator%20%28New%29%20%28v2.1%29.PSD?dl=0

Also left comments under your feedback.

**Comment by jamalv** [comment]
The mvp is done; superseded by this epic: https://github.com/teamforus/development/issues/118
