### ISSUE TITLE
Applying: Form components

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#996]
## Context:
For the application form, we need to design generic input fields components. Since the target audience is not digitally fluent, we should aim for the best possible UX.

## Tasks

- [x] List the elements
- [x] Wireframes
- [ ] Designs @Myshelova 

I've made a start here: https://www.figma.com/file/nyH6OawYjZonHEFocQ4q4o/Webshop-Dashboard-Alpha-Version?node-id=150%3A394

## Elements

* Text field
* Text box
* Number field
* Stepper (1, 2, 3, 4, etc.)
* Valuta (euro)
* Date picker
* Checkmark
* List (radio)
* List selector (dropdown)
* List search (dropdown)

Did I miss any?

**Comment by GerbenBosschieter** [comment]
Would be nice if the design could be conform the accessibility law/guidelines (WCAG -> Toegankelijkheid). 

This website offers a lot of these guidelines. (most of it it is obvious)
https://www.digitoegankelijk.nl/onderwerpen/formulieren

Succescriterium 1.1.1 - Niet-tekstuele content
Succescriterium 1.3.3 - Zintuiglijke eigenschappen
Succescriterium 1.4.1 - Gebruik van kleur
Succescriterium 2.2.1 - Timing aanpasbaar
Succescriterium 2.4.6 - Koppen en labels
Succescriterium 2.4.7 - Focus zichtbaar
Succescriterium 3.2.1 - Bij focus
Succescriterium 3.2.2 - Bij input
Succescriterium 3.3.1 - Fout identificatie
Succescriterium 3.3.2 - Labels of instructies
Succescriterium 3.3.3 - Foutsuggestie
Succescriterium 3.3.4 - Foutpreventie (wettelijk, financieel, gegevens)

**Comment by maxvisser** [comment]
Would be nice to use same angular plugin for dates, this is the current design:
![Screenshot from 2019-09-13 10-14-16](https://user-images.githubusercontent.com/10818702/64847442-52971f80-d60f-11e9-81f8-2d98c7dc00a7.png)

![Screenshot from 2019-09-13 10-15-03](https://user-images.githubusercontent.com/10818702/64847481-66428600-d60f-11e9-9592-54fcd493fadc.png)

![Screenshot from 2019-09-13 10-15-40](https://user-images.githubusercontent.com/10818702/64847511-778b9280-d60f-11e9-99b2-9a4ebb019db0.png)

**Comment by maxvisser** [comment]
image upload modal + crop:
![Screenshot from 2019-09-13 10-16-48](https://user-images.githubusercontent.com/10818702/64847598-a275e680-d60f-11e9-9da6-ae81e929a39c.png)

**Comment by maxvisser** [comment]
Upload box:
![Screenshot from 2019-09-13 10-17-33](https://user-images.githubusercontent.com/10818702/64847625-b7527a00-d60f-11e9-8886-30df46b9ece7.png)

**Comment by maxvisser** [comment]
![Screenshot from 2019-09-13 10-25-01](https://user-images.githubusercontent.com/10818702/64848095-c1c14380-d610-11e9-9450-ed4cc85c01bf.png)

**Comment by maxvisser** [comment]
![Screenshot from 2019-09-13 10-26-13](https://user-images.githubusercontent.com/10818702/64848164-ecab9780-d610-11e9-9521-c91513ddd26f.png)
